### PR TITLE
alternator: avoid assertion failure when configured with a busy port

### LINKED ISSUE #16720: Alternator SIGABRT if requested TCP port is already in-use
**Installation details**
Scylla version (or git commit hash): 5.4.0-0.20231205.58a89e7a4231 with build-id `7486a70ced30f7c89053f5c5a230c20ad31ffc1f`

Seen by a user:

When Alternator is configured to listen on an already bound port (eg: 9042 CQL), ScyllaDB aborts. We should print a more meaningful message explaining the problem, perhaps even prior to start opening any TCP socket:

```shell
INFO  2024-01-10 12:38:28,429 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.7:9042 (unencrypted, non-shard-aware)
INFO  2024-01-10 12:38:28,429 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 172.17.0.7:19042 (unencrypted, shard-aware)
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
scylla: seastar/src/net/posix-stack.cc:553: virtual future<accept_result> seastar::net::posix_ap_server_socket_impl::accept(): Assertion `i.second' failed.
Aborting on shard 1.
Backtrace:
  0x35a19db
  0x35d1a1f
  linux-vdso.so.1+0x78f
  /opt/scylladb/libreloc/libc.so.6+0x90a6f
  /opt/scylladb/libreloc/libc.so.6+0x44b3f
  /opt/scylladb/libreloc/libc.so.6+0x30287
  /opt/scylladb/libreloc/libc.so.6+0x3db93
  /opt/scylladb/libreloc/libc.so.6+0x3dc0f
  0x369304b
  0x3629333
  0x3629c5f
  0x3628adb
  0x3628973
  0x362920f
  0x2cb590f
  0x361150f
2024-01-10 12:38:28,518 INFO exited: scylla (terminated by SIGABRT; not expected)
```

### PR DESCRIPTION
**Pull request by nyh**
If Alternator is configured to use a port which is already busy (e.g., port 9042 which is used by CQL), we expect a clean error message like:

  ERROR 2024-01-10 18:32:44,948 [shard 0:main] init - Startup failed:
  std::system_error (error system:98, posix_listen failed for address
  127.0.0.1:9042: Address already in use)

This indeed happens when running Scylla on a *single core*. But when we have multiple cores, we encounter a Seastar bug scylladb/seastar#2036: Core 0 fails its listen cleanly as expected (with an exception as shown above), but all other cores fail on a nasty assertion failure:

  seastar/src/net/posix-stack.cc:553: virtual future<accept_result>
  seastar::net::posix_ap_server_socket_impl::accept():
  Assertion `i.second' failed.

This causes Scylla to crash in an ugly way, and the user doesn't understand what really went wrong.

The solution in this patch works around the Seastar bug by first running the server initialization function on core 0, and only then running it on all other cores. The port already in use is detected on shard 0 and we never try to do it on the other shards and don't reach the assertion failure.

This solution is also better that if in the future the http server initialization will have other configuration checks: It's better to get these errors once from shard 0 - and not in parallel from all shards.

Fixes #16720.

### CODE REVIEW

**Review by fee-mendes — APPROVED** [review]

**Comment by xemul** [comment]
But is alternator the only port that suffers from this problem? E.g. there's API port that start very early, so binding pretty much anything else (e.g. messaging service or CQL itself) to this port will step on the same ugliness, no?

**Comment by nyh** [comment]
> But is alternator the only port that suffers from this problem? E.g. there's API port that start very early, so binding pretty much anything else (e.g. messaging service or CQL itself) to this port will step on the same ugliness, no?

I don't know. The specific details of this problem rely on Seastar's HTTP server (for which I opened https://github.com/scylladb/seastar/issues/2036), that the other services in Scylla don't use, but it's quite possible and perhaps even likely that we suffer from the same problem also for other services. I didn't check.

Maybe it's indeed a good idea to check, and if the problem exists in other places, I can make a function `sharded::invoke_on_this_shard_and_then_other_shards()` that everyone can use.

**Comment by xemul** [comment]
> Maybe it's indeed a good idea to check, and if the problem exists in other places, I can make a function sharded::invoke_on_this_shard_and_then_other_shards() that everyone can use.

I hate to say that, but this invoke_on_this_shard_and_then_other_shards() will find its first user in database starting

from main.cc:
```c++
            // We need to init commitlog on shard0 before it is inited on other shards
            // because it obtains the list of pre-existing segments for replay, which must
            // not include reserve segments created by active commitlogs. 
            db.local().init_commitlog().get();
            db.invoke_on_all(&replica::database::start).get();
```
:nauseated_face:

**Comment by nyh** [comment]
> ```c++
>             // We need to init commitlog on shard0 before it is inited on other shards
>             // because it obtains the list of pre-existing segments for replay, which must
>             // not include reserve segments created by active commitlogs. 
>             db.local().init_commitlog().get();
>             db.invoke_on_all(&replica::database::start).get();
> ```

I wouldn't know how to change this code - why does this look the way it looks, and not more like
```
db.local().start().get();
db.invoke_on_others(&replica::database::start).get();
```
Would this latter code also work?

**Comment by nyh** [comment]
@xemul you were right - if I use "--native-shard-aware-transport-port=9042" I get exactly the same assertion failure.

So I'll probably need to fix this in additional places. I'll change this PR to be a draft and work on improving it.

**Comment by nyh** [comment]
> Maybe it's indeed a good idea to check, and if the problem exists in other places, I can make a function `sharded::invoke_on_this_shard_and_then_other_shards()` that everyone can use.

I'm adding a utility function `utils::invoke_on_all_local_first` and using it for both Alternator and CQL. Doing this correctly is **ridiculously complicated**. C++ syntax has become an absolute disaster, sorry to say so. I'm almost - but not completely - done with this patch and will push it when I'm done.

**Comment by xemul** [comment]
> @xemul you were right - if I use "--native-shard-aware-transport-port=9042" I get exactly the same assertion failure.
> 
> So I'll probably need to fix this in additional places. I'll change this PR to be a draft and work on improving it.

@nyh , I think that the right way to go is to fix scylladb/seastar#2036 , not workaround it in scylla

**Comment by xemul** [comment]
> > ```c++
> >             // We need to init commitlog on shard0 before it is inited on other shards
> >             // because it obtains the list of pre-existing segments for replay, which must
> >             // not include reserve segments created by active commitlogs. 
> >             db.local().init_commitlog().get();
> >             db.invoke_on_all(&replica::database::start).get();
> > ```
> 
> I wouldn't know how to change this code - why does this look the way it looks, and not more like
> 
> ```
> db.local().start().get();
> db.invoke_on_others(&replica::database::start).get();
> ```
> 
> Would this latter code also work?

It should. The database::start() is
* l.d.h. start
* compaction manager enabling
* co_await init_commitlog()

and steps 1 and 2 are OK to be done on local shard first

**Comment by nyh** [comment]
I'm re-proposing this PR (taking it out of draft mode). I've considered, and with instructions from @eliransin, ruled out the following ideas for improvement:
1. We could fix the Seastar issue https://github.com/scylladb/seastar/issues/2036 instead. Eliran and I sat on this on this for a couple of hours (!) and couldn't figure out how the relevant Seastar code works. Eliran said that it shouldn't be I that fixes the Seastar code - so I won't.
2. I created a function invoke_on_all_local_first() that could be used in multiple places, not just Alternator. But this was very hard to get right (C++) and still a workaround that might miss some use cases (e.g., did we remember to change the redis server? the metrics server? etc.).

So not wishing to continue fighting whether this is a high priority issue or not, I give up and propose **this** PR. Take it or leave it. It improves Alternator configuration friendliness, and nothing else. It's better than nothing, and I already did it. So please take it - don't leave it.

**Comment by nyh** [comment]
> > @xemul you were right - if I use "--native-shard-aware-transport-port=9042" I get exactly the same assertion failure.
> > So I'll probably need to fix this in additional places. I'll change this PR to be a draft and work on improving it.
> 
> @nyh , I think that the right way to go is to fix [scylladb/seastar#2036](https://github.com/scylladb/seastar/issues/2036) , not workaround it in scylla

Feel free to fight your own managers for the right work on this issue. I've given up and don't intend to work on it beyond what I already did.

We need Seastar experts in the company which:
1. Can quickly solve Seastar bugs because they're already familiar with the code.
2. *Want* to solve Seastar bugs because they love it.
3. Their managers don't tell them every day they are supposed to work on MV, not spend hours learning a Seastar problem and fixing it.
So unfortunately, it can't be me, but it doesn't mean someone else can't fix that issue. I opened the issue.

**Pull request closed without merging**
