### PR TITLE
test/boost/multishard_mutation_query: use random schema

### PR DESCRIPTION
**Pull request by denesb**
This test currently uses `test/lib/test_table.hh` to generate data for its test cases. This data generation facility is used by no other tests. Worse, it is redundant as we already have a random data generator with fixed schema, in `test/lib/mutation_source_test.hh`. So in this series, we migrate the test cases in said test file to random schema and its random data generation facilities. These are used by several other test cases and using random schema allows us to cover a wider (quasi-infinite) number of possibilities.
After migrating all tests away from it, `test/lib/test_table.hh` is removed.
This series also reduces the runtime of `fuzzy_test` drastically. It should now run in a few minutes or even in seconds (depending on the machine).

Fixes: #12944

### CODE REVIEW

**Comment by denesb** [comment]
The first two commits of this series are fixes for bugs found by using random schema in the tests. These will be extracted out into separate PRs.

**Comment by denesb** [comment]
Depends on:
* https://github.com/scylladb/scylladb/pull/12578
* https://github.com/scylladb/scylladb/pull/12579

**Comment by denesb** [comment]
Dequeued, test failed in promotion: https://jenkins.scylladb.com/job/scylla-master/job/next/5646/testReport/

**Comment by denesb** [comment]
v2:
* Rebased.
* Fixed flaky tests, turns out there were more bugs waiting to be discovered:
    - https://github.com/scylladb/scylladb/pull/12824
    - https://github.com/scylladb/scylladb/pull/12932

**Comment by denesb** [comment]
Ping.

**Comment by DoronArazii** [comment]
Ping @tgrabiec

**Pull request merged**
