### PR TITLE
Prevent queries from running after storage_proxy and batchlog_manager shutdown

### LINKED ISSUE #8995: storage_proxy::drain_on_shutdown does not synchronize with ongoing queries.
As seen in #8933, there's a race between query readers and database shutdown.
6d79da1 solved the terminate() issue by allowing the gate_closed exception to propagate,
but as seen in e.g. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1148, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1202, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node4', ['ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)', 'ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)'])]
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/864/artifact/logs-all.release.2/1625453021390_update_cluster_layout_tests.TestUpdateClusterLayout.simple_add_new_node_while_adding_info_1_test/node4.log
```
INFO  2021-07-05 02:43:33,373 [shard 0] init - Shutting down drain storage proxy
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,373 [shard 0] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Asked to stop
INFO  2021-07-05 02:43:33,374 [shard 1] hints_manager - Stopped
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down drain storage proxy was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down streaming service was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down Raft RPC was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down storage proxy RPC verbs was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down sstables format selector was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager
INFO  2021-07-05 02:43:33,374 [shard 0] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 1] migration_manager - stopping migration service
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down migration manager was successful
INFO  2021-07-05 02:43:33,374 [shard 0] init - Shutting down database
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down database was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down service_memory_limiter was successful
INFO  2021-07-05 02:43:39,078 [shard 0] init - Shutting down sst_dir_semaphore
ERROR 2021-07-05 02:43:39,078 [shard 0] storage_proxy - Exception when communicating with 127.0.53.4, to read from system.batchlog: seastar::gate_closed_exception (gate closed)
ERROR 2021-07-05 02:43:39,079 [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sst_dir_semaphore was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down Raft was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down messaging service was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down tracing instance was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down migration manager notifier was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down prometheus API server was successful
INFO  2021-07-05 02:43:39,079 [shard 0] init - Shutting down sighup
INFO  2021-07-05 02:43:39,080 [shard 0] init - Shutting down sighup was successful
ERROR 2021-07-05 02:43:39,080 [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

There are still on-going queries after storage_proxy::drain_on_shutdown completed.

### PR DESCRIPTION
**Pull request by bhalevy**
This series hardnes both `storage_proxy::drain_on_shutdown()`
and `db::batchlog_manager::stop()` to make sure no queries run after they complete.

For the storage_proxy, a `_query_gate` is added, and is held by queries using a newly introduced `gate::holder` that was added to the `service_permit`.

db::batchlog_manager::stop() and its timer rearming logic were hardened to prevent `do_batch_log_replay` from running after the batchlog_manager was stopped.

Fixes #8995

Test: unit(dev)
DTest: compact_storage_tests.py:TestCompactStorage.wide_row_test,
           update_cluster_layout_tests:TestUpdateClusterLayout.simple_add_new_node_while_adding_info_{1,2}_test (dev)

### CODE REVIEW

**Review by denesb — COMMENTED** [review]
Doesn't this just moves the gate closed exception from one place to the other?

**Comment by bhalevy** [comment]
> Doesn't this just moves the gate closed exception from one place to the other?

No, it prevents it by closing the gate in drain_on_shutdown

**Comment by avikivity** [comment]
Do we really have to add a new gate? Is there no existing facility we can use?

For example, storage_proxy is an async_sharded_service. Adding more and more control methods slows down the code and makes it more complicated.

**Comment by bhalevy** [comment]
> Do we really have to add a new gate? Is there no existing facility we can use?
> 
> For example, storage_proxy is an async_sharded_service. Adding more and more control methods slows down the code and makes it more complicated.

@avikivity it looks like for #8995 we can do without an additional gate. I realized that the batchlog controller was not stopped in the scenario at hand (scylla stopping during startup, while waiting for gossip to settle). I'll push a new version shortly that deals only with the batchlog manager.

That said, I think that we should harden storage_proxy::drain_on_shutdown to wait on all in-flight queries.  It is really insufficient the way it is done today.  But let's postpone that 'till after fixing the shutdown order problem(s) so that service that might issue queries will be stopped before the storage proxy is drained on shutdown.

**Comment by mykaul** [comment]
@bhalevy - is this still relevant?

**Comment by bhalevy** [comment]
> @bhalevy - is this still relevant?

Given the discussion in #8995
We can abandon this PR.

**Pull request closed without merging**
