### PR TITLE
[Backport 5.4] Update tools/cqlsh submodule to v6.0.17

### PR DESCRIPTION
**Pull request by fruch**
Mostly a set of fixes in the area of ssl handling

* tools/cqlsh 99b2b777...9d49b385 (21):
  > cqlshlib/sslhandling: fix logic of `ssl_check_hostname`
  > cqlshlib/sslhandling.py: don't use empty userkey/usercert
  > Dockerfile: noninteractive isn't enough for answering yet on apt-get
  > fix cqlsh version print
  > cqlshlib/sslhandling: change `check_hostname` deafult to False
  > Introduce new ssl configuration for disableing check_hostname
  > set the hostname in ssl_options.server_hostname when SSL is used
  > issue-73 Fixed a bug where username and password from the credentials file were ignored.
  > issue-73 Fixed a bug where username and password from the credentials file were ignored.
  > issue-73
  > github actions: update `cibuildwheel==v2.16.5`
  > dist/debian: fix the trailer line format
  > `COPY TO STDOUT` shouldn't put None where a function is expected
  > Make cqlsh work with unix domain sockets
  > Bump python-driver version
  > dist/debian: add trailer line
  > dist/debian: wrap long line
  > Draft: explicit build-time packge dependencies
  > stop retruning status_code=2 on schema disagreement
  > Fix minor typos in the code
  > Dockerfile: apt-get update and apt-get upgrade to get latest OS packages

Ref: #18590

### CODE REVIEW

**Comment by fruch** [comment]
@scylladb/scylla-maint can we have this merged ?

**Comment by fruch** [comment]
> @scylladb/scylla-maint can we have this merged ?

this is the same set of fixes as in:
https://github.com/scylladb/scylladb/pull/18591

we need to get them into 5.4/2024.1

**Comment by denesb** [comment]
This PR was queued two days ago. Closed by https://github.com/scylladb/scylladb/commit/393880f355cce7283a67928f3e98728339a8d247.

**Comment by fruch** [comment]
@denesb  "Closes" doesn't work with things not targeted for the default branch, so backport PR can't close issue, right ?

**Comment by mykaul** [comment]
> @denesb "Closes" doesn't work with things not targeted for the default branch, so backport PR can't close issue, right ?

I believe it needs to be done manually.

**Pull request closed without merging**
