### PR TITLE
Remove DateTieredCompactionStrategy

### PR DESCRIPTION
**Pull request by raphaelsc**
This is the last step of deprecation dance of DTCS.

In Scylla 5.1, users were warned that DTCS was deprecated.

In 5.2, altering or creation of tables with DTCS was forbidden.

5.3 branch was already created, so this is targetting 5.4.

Users that refused to move away from DTCS will have Scylla falling back to the default strategy, either STCS or ICS.

See:
`WARN  2023-07-14 09:49:11,857 [shard 0] schema_tables - Falling back to size-tiered compaction strategy after the problem: Unable to find compaction strategy class 'DateTieredCompactionStrategy`
    
Then user can later switch to a supported strategy with alter table.

### CODE REVIEW

**Comment by tchaikov** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2311/
```
06:19:27  test/raft/replication_test.cc(238): Entering test case "conf_changes_2"
...
06:19:27  random-seed=695285690
06:19:27  ==44177==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
06:19:27  Electing first leader 0
06:19:27  Processing updates
06:19:27  Appending remaining values
06:19:27  === TEST.PY SUMMARY START ===
06:19:27  Test exited with code -4
```

per https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.subprocess.Process.returncode. 

> A negative value -N indicates that the child was terminated by signal N (POSIX only).

and per https://man7.org/linux/man-pages/man7/signal.7.html

4 is SIGILL .. not sure the cpu was trying to execute an illegal instruction. but i don't think it's related to this change.

**Comment by raphaelsc** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2311/
> 
> ```
> 06:19:27  test/raft/replication_test.cc(238): Entering test case "conf_changes_2"
> ...
> 06:19:27  random-seed=695285690
> 06:19:27  ==44177==WARNING: ASan doesn't fully support makecontext/swapcontext functions and may produce false positives in some cases!
> 06:19:27  Electing first leader 0
> 06:19:27  Processing updates
> 06:19:27  Appending remaining values
> 06:19:27  === TEST.PY SUMMARY START ===
> 06:19:27  Test exited with code -4
> ```
> 
> per https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.subprocess.Process.returncode.
> 
> > A negative value -N indicates that the child was terminated by signal N (POSIX only).
> 
> and per https://man7.org/linux/man-pages/man7/signal.7.html
> 
> 4 is SIGILL .. not sure why the cpu was trying to execute an illegal instruction. but i don't think it's related to this change.

yes, unrelated. replayed and CI returned success

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint ping

**Review by denesb — COMMENTED** [review]
What happens exactly to users who still have DTCS tables after upgrading to 5.4? Won't parsing the compaction-strategy name fail when loading the schema from disk? Do we gracefully handle that by silently falling back to another CS, like you mention in the commitlog?

**Comment by raphaelsc** [comment]
> What happens exactly to users who still have DTCS tables after upgrading to 5.4? Won't parsing the compaction-strategy name fail when loading the schema from disk? Do we gracefully handle that by silently falling back to another CS, like you mention in the commitlog?

@denesb Yes, 

`WARN  2023-07-14 09:49:11,857 [shard 0] schema_tables - Falling back to size-tiered compaction strategy after the problem: Unable to find compaction strategy class 'DateTieredCompactionStrategy`

And we can later safely perform the switch to a supported strategy

**Comment by raphaelsc** [comment]
Update commit message to show the fallback message dumped in the log

**Pull request closed without merging**
