### PR TITLE
utils/large_bitset: replace reserve_partial with utils::reserve_gently

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Replace the reserve_partial loop in large_bitset constructor with a new function - reserve_gently() that can reserve memory without stalling by repeatedly calling reserve_partial() method of the passed container.

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
Followup to https://github.com/scylladb/scylladb/pull/19279 based on this [suggestion](https://github.com/scylladb/scylladb/pull/19279#discussion_r1638070311).

**Review by avikivity — APPROVED** [review]

**Comment by lkshminarayanan** [comment]
V2 changelog :
 - updated the comments of `reserve_partial()` to mention `reserve_gently()`

**Comment by lkshminarayanan** [comment]
V3 Changelog:
 - fixed failing test in debug mode.

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
This is an improvement, don't think it is a backport candidate.

**Pull request merged**
