### PR TITLE
test/topology: pytest log level and format

### PR DESCRIPTION
**Pull request by alecco**
Fix log level and format for topology tests.

Signed-off-by: Alejo Sanchez <alejo.sanchez@scylladb.com>

### CODE REVIEW

**Review by denesb — APPROVED** [review]

**Comment by kbr-scylla** [comment]
1. Please provide a motivation for this change. What exactly was the problem? What is this fixing?
2. Please provide an example of "before" and "after" so we can understand how the change affects log output in practice.

**Comment by kostja** [comment]
Please don't queue this, this leads to duplicate messages in the log.

**Review by kostja — CHANGES_REQUESTED** [review]
The driver config is set in pytest.ini, no need to set it here.

**Comment by alecco** [comment]
Changed to `print()`.

**Pull request closed without merging**
