### PR TITLE
Update tools/cqlsh submodule to v6.0.20

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh c8158555...0d58e5ce (6):
  > cqlsh.py: fix server side describe after login command
  > cqlsh: try server-side DESCRIBE, then client-side
  > Refactor tests to accept both client and server side describe
  > github actions: support testing with enterprise release
  > Add the tab-completion support of SERVICE_LEVEL statements
  > reloc/build_reloc.sh: don't use `--no-build-isolation`

Fixes: #18989

This is needed the updated back/restore procedure which is built on a new "DESC SCHEMA WITH INTERNALS"
so for doing the procedure manually this version is needed

### CODE REVIEW

**Comment by mykaul** [comment]
test_mc_sstables_case_sensitive_insert (and others) are failing on Exception: Create test schema failure: <stdin>:23:SyntaxException: Unknown property 'tombstone_gc'

1. Do we still need to test mc sstables?
2. What happened to tombstone_gc?

**Comment by fruch** [comment]
> test_mc_sstables_case_sensitive_insert (and others) are failing on Exception: Create test schema failure: :23:SyntaxException: Unknown property 'tombstone_gc'
> 
> 1. Do we still need to test mc sstables?
> 2. What happened to tombstone_gc?

those test are probably taking output of cqlsh describe, and pass it back to cassandra to create the KS/Tables

I have https://github.com/scylladb/scylla-dtest/pull/3831/commits/ffc5bf6949a5bbaba7a55fd2f631eb79b8bfa8e4

the stop using cqlsh for this, but still we'll need to filter scylla specific variables out

@sylwiaszunejko can you look into the test_login ? seems like one test is missed from getting adapted to the server side describe

**Comment by fruch** [comment]
One issue identified in cqlsh
https://github.com/scylladb/scylla-cqlsh/pull/89

thanks for the CI for surfacing it up....

the 2nd issue is clearer, not to filter unsupported parameter before giving it to cassandra, it a small fix to dtest.

**Comment by fruch** [comment]
and here's the missing part in dtest:
https://github.com/scylladb/scylla-dtest/pull/4375

**Comment by fruch** [comment]
waiting for a new build of cqlsh
https://github.com/scylladb/scylla-cqlsh/actions/runs/9369117847

and then we can try this one again

**Comment by fruch** [comment]
damn it, one test popped up, not clear why it didn't before.

fixing the test in:
https://github.com/scylladb/scylla-dtest/pull/4401

**Comment by fruch** [comment]
@scylla-maint now all issue we fixed, and CI is green.

**Comment by fruch** [comment]
thanks @denesb

**Pull request closed without merging**
