### PR TITLE
Fix version numbers in upgrade page title

### PR DESCRIPTION
**Pull request by kbr-**

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM

**Review by annastuchlik — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to 5.1

Doesn't apply to 5.1.

**Comment by annastuchlik** [comment]
This change has already been applied to 5.1; no need to backport now:
https://github.com/scylladb/scylladb/blob/branch-5.1/docs/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/index.rst

**Pull request closed without merging**
