### PR TITLE
service/storage_service: bypass coordinator-side for range scans on local tables

### PR DESCRIPTION
**Pull request by denesb**
Range scans have an involved coordinator-side machiner, with concurrent scanning of vnodes, with exponentially increasing concurrency. This is completely unnecessary for local tables, furthermore it has poor performance characteristics for sparse tables (and most local tables are sparse). Add a bypass for local tables, directly calling into the replica to serve the range scan locally. This should make range scans over local tables much faster and lighter.

Fixes: #20563

Performance improvement, no backport needed.

### CODE REVIEW

**Comment by denesb** [comment]
I will think of a way to measure the effect of the improvement, but first let's get a passing CI proving that there is no fundamental flaw in the improvement.

**Review by bhalevy — APPROVED** [review]

**Comment by denesb** [comment]
I started working on measuring the improvement, but so far with a modified `perf_simple_query`, but so far it looks like it is worse in every possible way. Maybe we already had the best possible range scan implementation? More likely the test is wrong somehow, but I don't yet know how.

**Comment by tgrabiec** [comment]
We should already handle local reads with a single request, range splitting is disabled for local tables. See query_ranges_to_vnodes.cc:

```
    if (_local) { // if the range is local no need to divide to vnodes
        add_range(get_remainder());
        return;
    }
```

**Comment by tgrabiec** [comment]
It would also be better to hide this at the erm level, so that its splitter returns a single range. This way all algorithms will benefit.

**Comment by denesb** [comment]
Closing this, the range scans are already optimized for local tables.

**Pull request closed without merging**
