### PR TITLE
Typo - then -> than

### PR DESCRIPTION
**Pull request by mykaul**
Fix a typo.

Signed-off-by: Yaniv Kaul <yaniv.kaul@scylladb.com>

### CODE REVIEW

**Review by annastuchlik — APPROVED** [review]
LGTM, thanks!

**Review by nyh — APPROVED** [review]
Thanks. Next time please prepend the commit message of documentation patches by "doc:" so they can be more easily recognized in "git log". I'll edit the commit message myself now and commit this patch.

**Comment by mykaul** [comment]
> Thanks. Next time please prepend the commit message of documentation patches by "doc:" so they can be more easily recognized in "git log". I'll edit the commit message myself now and commit this patch.

Do we have a list of 'known prefixes' somewhere?

**Comment by denesb** [comment]
> > Thanks. Next time please prepend the commit message of documentation patches by "doc:" so they can be more easily recognized in "git log". I'll edit the commit message myself now and commit this patch.
> 
> Do we have a list of 'known prefixes' somewhere?

Not really, choosing a prefix is more ad-hoc. A good guide is the name of the directory you touched most files in. This doesn't always work though, either because you modify files in the root directory or because you modify multiple directories. In this case you can use the logical subsystem, or even multiple prefixes, separated by comma. For patches touching everything, we use "treewide" prefix.

**Pull request closed without merging**
