### PR TITLE
docs/README.md: expand prerequisites list

### PR DESCRIPTION
**Pull request by denesb**
poetry and make was missing from the list.

### CODE REVIEW

**Comment by tzach** [comment]
@dgarcia360 please review

**Comment by denesb** [comment]
Ping.

**Comment by tzach** [comment]
LGTM
Theme do explicitly require [Poetry 1.12](https://python-poetry.org/docs/master/) or later.
https://sphinx-theme.scylladb.com/stable/getting-started/installation.html#prerequisites

**Review by tzach — APPROVED** [review]

**Comment by denesb** [comment]
New in v2:
* Added version to poetry line.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Pull request closed without merging**
