### PR TITLE
Update tools/jmx submodule 

### PR DESCRIPTION
**Pull request by denesb**
Contains:
* https://github.com/scylladb/scylla-jmx/pull/202.
* https://github.com/scylladb/scylla-jmx/pull/203.
* https://github.com/scylladb/scylla-jmx/pull/204.

For CI.

### CODE REVIEW

**Comment by denesb** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/594/

Dtest job failed: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/599/consoleFull
@tchaikov please look into it.

**Comment by mykaul** [comment]
Does it contain the fix to https://github.com/scylladb/scylla-jmx/pull/200 as well?

**Comment by tchaikov** [comment]
should be fixed by https://github.com/scylladb/scylla-jmx/pull/204

**Comment by denesb** [comment]
> should be fixed by [scylladb/scylla-jmx#204](https://github.com/scylladb/scylla-jmx/pull/204)

Updated the branch to contain scylladb/scylla-jmx#204 too.

**Comment by denesb** [comment]
JMX submodule updates as 7586491e1ea93d4296946e66926ba098506cf977. Closing this PR.

**Pull request closed without merging**
