### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by nyh**
update seastar module (see commit message)

### CODE REVIEW

**Comment by nyh** [comment]
I wanted to update Seastar for @xemul's https://github.com/scylladb/seastar/pull/1718. I'm doing it as a PR to get the CI.
I don't know what the "conflicting files" above complains about... Maybe I need to redo this patch even though I just did it 10 minutes ago?

**Comment by tchaikov** [comment]
> * seastar 0784da87...576ee47d (67):

@nyh you local submodule is very likely not updated for a while. to be more specific, you might need to rebase your local branch against a change including #15218, and update the `seastar` submodule, then rerun the `refresh-submodules.sh` script. as quite a few commits in seastar submodule have been included by #15218 already, and that PR has been merged. hence the conflict.

**Comment by fruch** [comment]
Can we still update seastar regardless of the intention?

So we can get @bhalevy fix:
semaphore: initialize wait_list in move ctor

**Comment by tchaikov** [comment]
> Can we still update seastar regardless of the intention?
> 
> So we can get @bhalevy fix: semaphore: initialize wait_list in move ctor

we can, why not? i think once @nyh updates his pull request. we will have Benny's change as well. as it is actually an ancestor of Pavel's commit.

**Comment by nyh** [comment]
> > * seastar 0784da87...576ee47d (67):
> 
> @nyh you local submodule is very likely not updated for ~a while~ 3 days. to be more specific, you might need to rebase your local branch against a change including #15218, and update the `seastar` submodule, then rerun the `refresh-submodules.sh` script. as quite a few commits in seastar submodule have been included by #15218 already, and that PR has been merged. hence the conflict.

Yes, I don't know how it happened to me on the first try, on the second one I didn't forget to update and got a more sensible change set, but it still didn't work. Strange. I'll try again.

**Comment by nyh** [comment]
Hoping that third time's the charm. Now at least github doesn't complain.

**Comment by tchaikov** [comment]
probably could add `Fixes #15253` in the commit message right under the line of 

```
> semaphore: initialize wait_list in move ctor
```

**Comment by nyh** [comment]
> probably could add `Fixes #15253` in the commit message right under the line of

Right. Also #15263, right?

**Comment by nyh** [comment]
Pushed new version with two "Fixes" lines

**Comment by tchaikov** [comment]
> > probably could add `Fixes #15253` in the commit message right under the line of
> 
> Right. Also #15263, right?

actually, i hope so. i didn't spend lot of time verifying my theory, despite that it sounds very plausible. if we are less optimistic (or more pessimistic), `Refs` would be more appropriate. but personally, i'd go with `Fixes` -- we can always reopen it once it surfaces again.

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please merge

**Comment by denesb** [comment]
Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.

**Comment by mykaul** [comment]
> Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.

So if someone needs a Seastar update to go along with a fix in Scylla core, you expect it to be in the same PR?

**Comment by tchaikov** [comment]
> Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.

neither do i understand this. so, if i wanted to bump up seastar submodule, the commit will end up in master as long as:

1. a PR is created to bump up seastar. the PR targets `master`
2. all checks are green
3. and it gets an approval from a random reviewer (is this still necessary?)
4. this commit will be cherry-picked into `next` automatically?

**Comment by nyh** [comment]
> Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.

Sure, but:
1. The pull request (instead of immediately updating and pushing) was necessary to get the CI.
2. Anybody could have done this pull request, not just a maintainer.
3. When the CI finishes, any maintainer that notices this happens can merge it - not just the original person who sent the pull request. In this case, @denesb was faster than me. I could have done it too if he wouldn't have.

**Comment by nyh** [comment]
> So if someone needs a Seastar update to go along with a fix in Scylla core, you expect it to be in the same PR?

Not always:
1. If you need a new Seastar feature for your commit, we can update Seastar in one PR, and in some later PR will add code that needs the new feature.
2. Sometimes, updating Seastar exposes some existing bug or incorrect dependency or something in Scylla, so we need to commit one PR that includes both the Seastar update **and** some small change to Scylla to make it work with the new Seastar. Luckily, this doesn't happen often (it shouldn't, because Seastar is supposed to be backward-compatible, and usually is).

**Comment by nyh** [comment]
> neither do i understand this. so, if i wanted to bump up seastar submodule, the commit will end up in master as long as:
> 
>     1. a PR is created to bump up seastar. the PR targets `master`
>     2. all checks are green

This is the important part, and why I created the CI. There is always a risk that a new Seastar change will break Scylla (even subtly, in one of the tests), so I don't want to update Seastar without the CI.

>     3. and it gets an approval from a random reviewer (is this still necessary?)

A review is not absolutely necessary - it is presumed that Seastar itself was reviewed independently, so that any Seastar version can be considered reviewed and usable if CI passes. However, it's always better if someone does find the time to review - in this case I forgot to mention the right "Fixes", for example, so it's good a reviewer (you) reminded me.

>     4. this commit will be cherry-picked into `next` automatically?

No, not automatically - a maintainer does it. Like all other merges.

**Comment by denesb** [comment]
> > Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.
> 
> 
> 
> So if someone needs a Seastar update to go along with a fix in Scylla core, you expect it to be in the same PR?

No, that is not what I meant.

**Comment by tchaikov** [comment]
> Queued. Note that seastar updates do not need to go through the usual queuing process. One can "queue" their own seastar update PR once CI approves. Just like one can just update some submodule and push the update to next, without having to go through another maintainer.

ahh, all of a sudden, i realized that, in this context, "one" actually implies "one maintainer" not a regular contributor.

**Comment by denesb** [comment]
What I meant is that the first rule of the maintainers: "don't commit your own PR" doesn't apply to submodule updates. Nadav explained it well above.

**Comment by tchaikov** [comment]
thank you Nadav, for your explanation.

**Pull request closed without merging**
