### PR TITLE
[Backport 5.4] mv: adjust memory tracking of single view updates within a batch

### PR DESCRIPTION
**Pull request by wmitros**
Currently, when dividing memory tracked for a batch of updates we do not take into account the overhead that we have for processing every update. This patch adds the overhead for single updates and joins the memory calculation path for batches and their parts so that both use the same overhead.

Fixes https://github.com/scylladb/scylladb/issues/17854

(cherry picked from commit https://github.com/scylladb/scylladb/commit/efcb718e0aad43d67f84e30475fa75c44a872653)

### CODE REVIEW

**Comment by wmitros** [comment]
This PR should wait for https://github.com/scylladb/scylladb/pull/18105 before getting merged.
It resolves the conflicts from https://github.com/scylladb/scylladb/pull/17877 and fixes the cherry-pick hash in the commit message.

**Comment by wmitros** [comment]
https://github.com/scylladb/scylladb/pull/18105 got merged so this is ready for merging as well

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued

**Comment by wmitros** [comment]
Merged in c4515a9b99450184f2da08180ccd930d412119f9

**Pull request closed without merging**
