### PR TITLE
Docs: add comment on collection vs UDT perfromance in CQL Types

### PR DESCRIPTION
**Pull request by tzach**
Fix https://github.com/scylladb/scylla-docs/issues/3706

### CODE REVIEW

**Review by nyh — CHANGES_REQUESTED** [review]
I think this statement you add is too vague and its "proof" in the blog post is questionably related. The blog post wasn't about collections, it was about replacing multiple columns which you always read and write together with a UDT. 
Here you are suggesting to replace a **collection** by a UDT. But wouldn't it make more sense to replace a collection by a **frozen collection**? Does replacing one frozen collection by a UDT add any more performance? Does it even make sense to replace a collection with a UDT, given they have completely different semantics?

**Comment by nyh** [comment]
Looking at the original issue, I think the intention was to recommend replacing regular (unfrozen) collections by frozen collections, not by UDTs.

**Comment by denesb** [comment]
UDT is actually stored as a collection in low-level code. So I agree with @nyh, I don't see why this statement would be true, unless we are talking about frozen vs. non-frozen collection/UDT (in cassandra UDT is always frozen AFAIK).

**Comment by tomer-sandler** [comment]
See my latest comment in the original issue: https://github.com/scylladb/scylla-docs/issues/3706#issuecomment-1385781286

**Comment by annastuchlik** [comment]
I think we could address this issue in the following way:
In the _[Noteworthy characteristics](https://docs.scylladb.com/stable/cql/types.html#noteworthy-characteristics)_ of collections, we should add another bullet to the list that starts with "_Non-frozen collections have the following noteworthy characteristics and limitations_":
- Non-frozen collections impose a significant performance penalty. To ensure better performance, use frozen collections or frozen UDTs. See [this blog post](https://www.scylladb.com/2017/12/07/performance-udt) for more information about improving performance.

@tomer-sandler What do you think?

**Review by tomer-sandler — COMMENTED** [review]
I don't see the [last suggestion](https://github.com/scylladb/scylladb/pull/11638#issuecomment-1386818698) from @annastuchlik in this commit...

**Comment by annastuchlik** [comment]
@tomer-sandler I can't edit Tzach's PR. I've opened a V2 PR and I'll close this one.
Could you review the changes in https://github.com/scylladb/scylladb/pull/12583?

**Comment by annastuchlik** [comment]
Closing. See V2 for final updates: https://github.com/scylladb/scylladb/pull/12583.

**Pull request closed without merging**
