### PR TITLE
Update manager-monitoring-integration.rst

### PR DESCRIPTION
**Pull request by guy9**
Changing default manager from 56090 to 5090
@amnonh please review
@annastuchlik please change if other locations in Docs require this change

### CODE REVIEW

**Comment by annastuchlik** [comment]
The PR looks technically good, but the change must be reviewed by @amnonh.

@guy9 Thanks for letting me know. There are no other occurrences in the docs.

**Comment by amnonh** [comment]
It looks ok, but I would be happy if someone from the Manager team can have a look

**Comment by annastuchlik** [comment]
@karol-kokoszka Could you have a look or assign somebody as a reviewer?

**Comment by annastuchlik** [comment]
@karol-kokoszka Ping

**Review by karol-kokoszka — APPROVED** [review]
+1

**Comment by annastuchlik** [comment]
@karol-kokoszka Thanks!

@scylladb/scylla-maint Please merge.

**Pull request closed without merging**
