### PR TITLE
replica: Fix race between split compaction and migration

### PR DESCRIPTION
**Pull request by raphaelsc**
After removal of rwlock (53a6ec05ed311d), the race was introduced because the order that compaction groups of a tablet are closed, is no longer deterministic (since they're now closed in parallel).

Some background first:
Split compaction runs in main (unsplit) group, and adds sstable to left and right groups on completion.

The race works as follow:
1) split compaction starts on main group of tablet X
2) tablet X reaches cleanup stage, so its compaction groups are closed in parallel
3) left or right group are closed before main (more likely when only main has flush work to do)
4) split compaction completes, and adds sstable to left and right
5) if e.g left is closed, adjusting backlog tracker will trigger an exception, and since that happens in row cache update's execute(), node crashes.

The problem manifested as follow:
```
[shard 0: gms] raft_topology - Initiating tablet cleanup of 5739b9b0-49d4-11ef-828f-770894013415:15 on 102a904a-0b15-4661-ba3f-f9085a5ad03c:0 ...
...
[shard 0:strm] compaction - [Split keyspace1.standard1 009e2f80-49e5-11ef-85e3-7161200fb137] Splitting [/var/lib/scylla/data/keyspace1/...] ...
...
[shard 0:strm] cache - Fatal error during cache update: std::out_of_range (Compaction state for table [0x600007772740] not found), at: ...
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, row_cache::do_update(...
   --------
   seastar::internal::do_with_state<std::tuple<row_cache::external_updater, std::function<seastar::future<void> ()> >, seastar::future<void> >
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::(anonymous namespace)::thread_wake_task
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(...
   seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_resu...
```

From the log above, it can be seen cache update failure happens under streaming sched group and during compaction completion, which was good evidence to the cause.
Problem was reproduced locally with the help of tablet shuffling.

Fixes: #19873.

Backport: 6.1 contains 53a6ec05ed311d so it's vulnerable. 6.0 isn't vulnerable yet, but it will be after 53a6ec05ed311d, so this will be backported to 6.0 too.

### CODE REVIEW

**Review by Deexie — APPROVED** [review]
LGTM

**Comment by Deexie** [comment]
> After removal of rwlock ([53a6ec0](https://github.com/scylladb/scylladb/commit/53a6ec05ed311dfbdf04903e3bd5321c9261de59)), the race was introduced because the order that compaction groups of a tablet are closed, is no longer deterministic (since they're now closed in parallel).
> 
> Some background first: Split compaction runs in main (unsplit) group, and adds sstable to left and right groups on completion.
> 
> The race works as follow:
> 
>     1. split compaction starts on main group of tablet X
> 
>     2. tablet X reaches cleanup stage, so its compaction groups are closed in parallel
> 
>     3. left or right group are closed before main (more likely when only main has flush work to do)
> 
>     4. split compaction completes, and adds sstable to left and right
> 
>     5. if e.g left is closed, adjusting backlog tracker will trigger an exception, and since that happens in row cache update's execute(), node crashes.
> 
> 
> The problem manifested as follow:
> 
> ```
> [shard 0: gms] raft_topology - Initiating tablet cleanup of 5739b9b0-49d4-11ef-828f-770894013415:15 on 102a904a-0b15-4661-ba3f-f9085a5ad03c:0 ...
> ...
> [shard 0:strm] compaction - [Split keyspace1.standard1 009e2f80-49e5-11ef-85e3-7161200fb137] Splitting [/var/lib/scylla/data/keyspace1/...] ...
> ...
> [shard 0:strm] cache - Fatal error during cache update: std::out_of_range (Compaction state for table [0x600007772740] not found), at: ...
>    --------
>    seastar::continuation<seastar::internal::promise_base_with_type<void>, row_cache::do_update(...
>    --------
>    seastar::internal::do_with_state<std::tuple<row_cache::external_updater, std::function<seastar::future<void> ()> >, seastar::future<void> >
>    --------
>    seastar::internal::coroutine_traits_base<void>::promise_type
>    --------
>    seastar::internal::coroutine_traits_base<void>::promise_type
>    --------
>    seastar::(anonymous namespace)::thread_wake_task
>    --------
>    seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(...
>    seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_resu...
> ```
> 
> From the log above, it can be seen cache update failure happens under streaming sched group 

Nit: the log you pasted doesn't mention streaming scheduling group

>and during compaction completion, which was good evidence to the cause. Problem was reproduced locally with the help of tablet shuffling.
> 
> Fixes: #19873.
> 
> **Please replace this line with justification for the backport/* labels added to this PR**

**Comment by raphaelsc** [comment]
> > After removal of rwlock ([53a6ec0](https://github.com/scylladb/scylladb/commit/53a6ec05ed311dfbdf04903e3bd5321c9261de59)), the race was introduced because the order that compaction groups of a tablet are closed, is no longer deterministic (since they're now closed in parallel).
> > 
> > Some background first: Split compaction runs in main (unsplit) group, and adds sstable to left and right groups on completion.
> > 
> > The race works as follow:
> > 
> >     1. split compaction starts on main group of tablet X
> > 
> >     2. tablet X reaches cleanup stage, so its compaction groups are closed in parallel
> > 
> >     3. left or right group are closed before main (more likely when only main has flush work to do)
> > 
> >     4. split compaction completes, and adds sstable to left and right
> > 
> >     5. if e.g left is closed, adjusting backlog tracker will trigger an exception, and since that happens in row cache update's execute(), node crashes.
> > 
> > 
> > The problem manifested as follow:
> > 
> > ```
> > [shard 0: gms] raft_topology - Initiating tablet cleanup of 5739b9b0-49d4-11ef-828f-770894013415:15 on 102a904a-0b15-4661-ba3f-f9085a5ad03c:0 ...
> > ...
> > [shard 0:strm] compaction - [Split keyspace1.standard1 009e2f80-49e5-11ef-85e3-7161200fb137] Splitting [/var/lib/scylla/data/keyspace1/...] ...
> > ...
> > [shard 0:strm] cache - Fatal error during cache update: std::out_of_range (Compaction state for table [0x600007772740] not found), at: ...
> >    --------
> >    seastar::continuation<seastar::internal::promise_base_with_type<void>, row_cache::do_update(...
> >    --------
> >    seastar::internal::do_with_state<std::tuple<row_cache::external_updater, std::function<seastar::future<void> ()> >, seastar::future<void> >
> >    --------
> >    seastar::internal::coroutine_traits_base<void>::promise_type
> >    --------
> >    seastar::internal::coroutine_traits_base<void>::promise_type
> >    --------
> >    seastar::(anonymous namespace)::thread_wake_task
> >    --------
> >    seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::async<sstables::compaction::run(...
> >    seastar::continuation<seastar::internal::promise_base_with_type<sstables::compaction_result>, seastar::future<sstables::compaction_resu...
> > ```
> > 
> > From the log above, it can be seen cache update failure happens under streaming sched group 
> 
> Nit: the log you pasted doesn't mention streaming scheduling group

It's the strm, right after the shard number. We have an abbreviation for every sched group name to fit 4 char limit.

> 
> >and during compaction completion, which was good evidence to the cause. Problem was reproduced locally with the help of tablet shuffling.
> > 
> > Fixes: #19873.
> > 
> > **Please replace this line with justification for the backport/* labels added to this PR**
> 
>

**Comment by Deexie** [comment]
> It's the strm, right after the shard number. We have an abbreviation for every sched group name to fit 4 char limit.


Oh, I see

**Comment by raphaelsc** [comment]
@denesb please consider merging

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint ping

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
> **Please replace this line with justification for the backport/* labels added to this PR**

@raphaelsc we need to backport this everywhere, we backport(ed) https://github.com/scylladb/scylladb/commit/53a6ec05ed311dfbdf04903e3bd5321c9261de59, no? If so, please update the description and the labels.

**Comment by raphaelsc** [comment]
> > __Please replace this line with justification for the backport/_ labels added to this PR_*
> 
> @raphaelsc we need to backport this everywhere, we backport(ed) [53a6ec0](https://github.com/scylladb/scylladb/commit/53a6ec05ed311dfbdf04903e3bd5321c9261de59), no? If so, please update the description and the labels.

only 6.1, 6.0 is not vulnerable yet, so I am planning to add this patch to https://github.com/scylladb/scylladb/pull/19808 after it lands on master.

**Comment by raphaelsc** [comment]
I'll add 6.0 label so we don't forget to do it.

**Pull request closed without merging**
