### PR TITLE
write out the generated UUID for sending to support

### PR DESCRIPTION
**Pull request by tarzanek**
@tzach can you approve?

### CODE REVIEW

**Comment by avikivity** [comment]
We don't merge patches into branches (causes an immediate regression in master).

**Comment by tarzanek** [comment]
how can this be merged then (sorry for my ignorance, I only pressed "edit this page" on the docs page and this came out of it 😉 )?

can someone retarget it?
or what to do now?

**Comment by avikivity** [comment]
> how can this be merged then (sorry for my ignorance, I only pressed "edit this page" on the docs page and this came out of it wink )?
> 
> can someone retarget it? or what to do now?

Start over without "edit this page".

**Comment by mykaul** [comment]
> > how can this be merged then (sorry for my ignorance, I only pressed "edit this page" on the docs page and this came out of it wink )?
> > can someone retarget it? or what to do now?
> 
> Start over without "edit this page".

@annastuchlik @tzach we should remove that useless button from our docs. The flow doesn't work, as it doesn't allow commit to your own fork and from there create a proper PR.

**Comment by tzach** [comment]
The Edit button does use a fork and allows you to set the branch you want to merge to, including master.
The default is the branch you are currently reading  (see capture below).

We just moved *latest* from [master to 5.1](https://github.com/scylladb/scylladb/pull/12105) ,  which explains why we have not seen this mistake before.

@dgarcia360, let's look for a solution.
We can keep the Edit just in master pages, but it will reduce contributions.

@tarzanek you can try Edit from the master version of the page
[docs/troubleshooting/report-scylla-problem.rst](https://docs.scylladb.com/master/troubleshooting/report-scylla-problem.html)


image

**Comment by tzach** [comment]
> We can keep the Edit just in master pages, but it will reduce contributions.

Or, we can have the Edit to *always* send you to edit the *master* version of the page
(might be a problem if the page was renamed)

**Comment by tarzanek** [comment]
oh wow, retargeting to master caused a balagan! :-D

**Comment by tarzanek** [comment]
ok, it's a mess, confirming this flow creates more problems than it solves

BUT I loved how quickly I edited the doc page ...

**Comment by tarzanek** [comment]
tried again cleanly:
https://github.com/scylladb/scylladb/pull/12176

so yes, against master it works

**Comment by annastuchlik** [comment]
@tarzanek I'm sorry this problem emerged when you were contributing. 5.1 is the first release when the documentation is versioned, and the "latest stable version" is not master, so we weren't aware of it.

Still, I think we should try to find a solution to that problem to make editing pages very easy.

**Pull request closed without merging**
