### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by avikivity**
* seastar 8889cbc198...d41af8b592 (14):
  > Merge 'Perf stall detector related improvements' from Travis Downs
Ref #8828, #7882, #11582 (may help make progress)
  > build: pass HEAPPROF definition to src/core/reactor.cc too
  > Limit memory address space per core to 64GB when hwloc is not available
  > build: revert use pkg_search_module(.. IMPORTED_TARGET ..) changes
  > Fix missing newlines in seastar-addr2line
  > Use an integral type for uniform_int_distribution
  > Merge 'tls_test: use a dedicated https server for testing' from Kefu Chai
  > build: use ${CMAKE_BINARY_DIR} when running 'cmake --build ..'
  > build: do not set c-ares_FOUND with PARENT_SCOPE
  > reactor: drop unused member function declaration
  > sstring: refactor to_sstring() using fmt::format_to()
  > http: delay input stream close until responses sent
  > build: enable non-library targets using default option value
  > Merge 'sstring: specialize uninitialize_string() and use resize_and_overwrite if available' from Kefu Chai

### CODE REVIEW

**Comment by avikivity** [comment]
This fails since the JSON formatting of floating point values has changed:

```
RuntimeError: Doctest failed! Captured output:
**********************************************************************
Line 32, in test_basic_data_types
Failed example:
    cqlsh_print('''
    SELECT toJson(col1), toJson(col2), toJson(col3), toJson(col4), toJson(col5),
           toJson(col6), toJson(col7), toJson(col8), toJson(col9), toJson(col10),
           toJson(col11),toJson(col12),toJson(col13),toJson(col14),toJson(col15)
     FROM primitive_type_test WHERE key1 = 'foo'
    ''')
Expected:
    <BLANKLINE>
     system.tojson(col1) | system.tojson(col2) | system.tojson(col3) | system.tojson(col4) | system.tojson(col5)   | system.tojson(col6)                    | system.tojson(col7)                    | system.tojson(col8) | system.tojson(col9)  | system.tojson(col10) | system.tojson(col11) | system.tojson(col12) | system.tojson(col13) | system.tojson(col14) | system.tojson(col15)
    ---------------------+---------------------+---------------------+---------------------+-----------------------+----------------------------------------+----------------------------------------+---------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------
                   "bar" |            "0x0011" |         "127.0.0.1" |             "blarg" | "2011-02-03T04:05:00" | "0ad6dfb6-7a6e-11e4-bc39-b4b6763e9d6f" | "bdf5e8ac-a75e-4321-9ac8-938fc9576c4a" |              "bleh" | -9223372036854775808 |           1234.45678 |          9.87123e+07 |          9.87123e+07 |          -2147483648 |           2147483648 |                 true
    <BLANKLINE>
    (1 rows)
    <BLANKLINE>
Got:
    <BLANKLINE>
     system.tojson(col1) | system.tojson(col2) | system.tojson(col3) | system.tojson(col4) | system.tojson(col5)   | system.tojson(col6)                    | system.tojson(col7)                    | system.tojson(col8) | system.tojson(col9)  | system.tojson(col10) | system.tojson(col11) | system.tojson(col12) | system.tojson(col13) | system.tojson(col14) | system.tojson(col15)
    ---------------------+---------------------+---------------------+---------------------+-----------------------+----------------------------------------+----------------------------------------+---------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------
                   "bar" |            "0x0011" |         "127.0.0.1" |             "blarg" | "2011-02-03T04:05:00" | "0ad6dfb6-7a6e-11e4-bc39-b4b6763e9d6f" | "bdf5e8ac-a75e-4321-9ac8-938fc9576c4a" |              "bleh" | -9223372036854775808 |           1234.45678 |        98712312.1222 |             98712310 |          -2147483648 |           2147483648 |                 true
    <BLANKLINE>
    (1 rows)
    <BLANKLINE>
```

Note the new output is more accurate than the old output.

@fruch how do you recommend we proceed here? Ideally we'd relax the test to accept both old and new forms, but this is difficult due to how the test is written.

**Comment by fruch** [comment]
> This fails since the JSON formatting of floating point values has changed:
> 
> ```
> RuntimeError: Doctest failed! Captured output:
> **********************************************************************
> Line 32, in test_basic_data_types
> Failed example:
>     cqlsh_print('''
>     SELECT toJson(col1), toJson(col2), toJson(col3), toJson(col4), toJson(col5),
>            toJson(col6), toJson(col7), toJson(col8), toJson(col9), toJson(col10),
>            toJson(col11),toJson(col12),toJson(col13),toJson(col14),toJson(col15)
>      FROM primitive_type_test WHERE key1 = 'foo'
>     ''')
> Expected:
>     <BLANKLINE>
>      system.tojson(col1) | system.tojson(col2) | system.tojson(col3) | system.tojson(col4) | system.tojson(col5)   | system.tojson(col6)                    | system.tojson(col7)                    | system.tojson(col8) | system.tojson(col9)  | system.tojson(col10) | system.tojson(col11) | system.tojson(col12) | system.tojson(col13) | system.tojson(col14) | system.tojson(col15)
>     ---------------------+---------------------+---------------------+---------------------+-----------------------+----------------------------------------+----------------------------------------+---------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------
>                    "bar" |            "0x0011" |         "127.0.0.1" |             "blarg" | "2011-02-03T04:05:00" | "0ad6dfb6-7a6e-11e4-bc39-b4b6763e9d6f" | "bdf5e8ac-a75e-4321-9ac8-938fc9576c4a" |              "bleh" | -9223372036854775808 |           1234.45678 |          9.87123e+07 |          9.87123e+07 |          -2147483648 |           2147483648 |                 true
>     <BLANKLINE>
>     (1 rows)
>     <BLANKLINE>
> Got:
>     <BLANKLINE>
>      system.tojson(col1) | system.tojson(col2) | system.tojson(col3) | system.tojson(col4) | system.tojson(col5)   | system.tojson(col6)                    | system.tojson(col7)                    | system.tojson(col8) | system.tojson(col9)  | system.tojson(col10) | system.tojson(col11) | system.tojson(col12) | system.tojson(col13) | system.tojson(col14) | system.tojson(col15)
>     ---------------------+---------------------+---------------------+---------------------+-----------------------+----------------------------------------+----------------------------------------+---------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------+----------------------
>                    "bar" |            "0x0011" |         "127.0.0.1" |             "blarg" | "2011-02-03T04:05:00" | "0ad6dfb6-7a6e-11e4-bc39-b4b6763e9d6f" | "bdf5e8ac-a75e-4321-9ac8-938fc9576c4a" |              "bleh" | -9223372036854775808 |           1234.45678 |        98712312.1222 |             98712310 |          -2147483648 |           2147483648 |                 true
>     <BLANKLINE>
>     (1 rows)
>     <BLANKLINE>
> ```
> 
> Note the new output is more accurate than the old output.
> 
> @fruch how do you recommend we proceed here? Ideally we'd relax the test to accept both old and new forms, but this is difficult due to how the test is written.

I'll take a look at the tests, but I think we can have 2 variations for each, a bit annoying.

Other option is to remove it from gating and putting them back fixed after merging this one

**Comment by tchaikov** [comment]
@avikivity and @fruch the change in the formatting of float point values was introduced in https://github.com/scylladb/seastar/commit/4f4e84bb2cec5f11b4742396da7fc40dbb3f162f . if `98712312.1222` is preferred over `9.87123e+07` for better readability, i will create a PR in Seastar to address this.

**Comment by tchaikov** [comment]
ahh, sorry, I misinterpreted the output. Indeed, I like the new output as well.

**Comment by fruch** [comment]
@avikivity I've look at the tests, and yes those doctest based test are a bit problematic to adapt to both cases.

So I think we first need to remove them from gating, and then introduce them back after refactoring them to support both cases

**Comment by avikivity** [comment]
OK. Will you manage the process?

**Comment by fruch** [comment]
> OK. Will you manage the process?

Yes, also I would like to see which more tests might be affected by this

@bhalevy heads up

**Comment by fruch** [comment]
> OK. Will you manage the process?

Yes, also I would like to see which more tests might be affected by this

@bhalevy heads up

**Comment by fruch** [comment]
@avikivity @tchaikov 

please see:
https://github.com/scylladb/scylla-dtest/pull/2982

I've took this PR and refactor those test to stop using doctest, and also to accept the non scientific notation

I've checked if there are any more test that might be affect, I didn't found any.

**Comment by avikivity** [comment]
> 

Many thanks!

**Comment by avikivity** [comment]
Rebased to check with updated dtest.

**Pull request closed without merging**
