### PR TITLE
doc: add OS support for version 2023.1

### PR DESCRIPTION
**Pull request by annastuchlik**
Fixes https://github.com/scylladb/scylladb/issues/13857

This commit adds the OS support for ScyllaDB Enterprise 2023.1. The support is the same as for ScyllaDB Open Source 5.2, on which 2023.1 is based.

After this commit is merged, it must be backported to branch-5.2. In this way, it will be merged to branch-2023.1 and available in the docs for Enterprise 2023.1

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge.

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to branch-5.2.
The information added with this PR is critical in version 2023.1.

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to branch-5.2. The information added with this PR is critical in version 2023.1.

Done, as 9c99dc36b5d44fdd960acc8451e29cae8cefcaff.

**Pull request closed without merging**
