### PR TITLE
test: make use of concurrent bootstrap

### LINKED ISSUE #15423: raft topology: test concurrent bootstrap
In the Raft-based topology concurrent bootstraps are supported. We should test it and make use of it in the testing framework. In particular, in every test in the `broadcast_tables` and `topology` suits all starting nodes should bootstrap concurrently. We can also add a new function to `ManagerClient` that adds multiple servers concurrently.

### PR DESCRIPTION
**Pull request by patjed41**
In #16102, we added a test for concurrent bootstrap in the raft-based
topology. This test was running in CI for some time and
never failed. Now, we can believe that concurrent bootstrap is not
bugged or at least the probability of a failure is very low. Therefore,
we can safely make use of it in all tests using the raft-based topology.

This PR:
- makes all initial servers start concurrently in topology tests,
- replaces all multiple `server_add` calls with a single `servers_add`
  call in tests using the raft-based topology,
- removes no longer needed `test_concurrent_bootstrap`.

The changes listed above:
- make running tests a bit faster due to concurrent bootstraps,
- make multiple tests test concurrent bootstrap previously tested by
  a single test.

Fixes scylladb/scylladb#15423

### CODE REVIEW

**Comment by patjed41** [comment]
The last commit is unrelated, but since it's just a comment fix, I've decided that there is no need to submit a separate PR.

**Review by kostja — APPROVED** [review]

**Comment by kostja** [comment]
Wonderful.

**Review by piodul — APPROVED** [review]

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Had to dequeue, looks like some nodes are hanging in concurrent boot
https://jenkins.scylladb.com/job/scylla-master/job/next/6939/testReport/junit/(root)/non-boost%20tests/Build___aarch64___Unit_Tests_aarch64___topology_experimental_raft_test_mv_tablets_dev_1/

**Comment by kbr-scylla** [comment]
```
11:58:07.127 ERROR> [dev/topology_experimental_raft.test_mv_tablets.1] last line of /scylladir/testlog/aarch64/dev/scylla-400.log:
ERROR 2023-12-14 11:58:07,127 [shard 0: gms] storage_service - raft topology: raft_topology_cmd failed with: raft::stopped_error (Raft instance is stopped, reason: "background error, exceptions::mutation_write_failure_exception (stale topology exception, caller version 4, callee fence version 5)")
```

**Comment by patjed41** [comment]
I opened #16423.

I'll clarify what's happening here. I don't think this PR caused this failure. However, this PR should still wait until it's investigated and fixed. It looks like there is a bug in the Raft-based topology that reveals itself during concurrent bootstrap. If this PR was merged, we would increase the frequency of failures in CI caused by this bug. It's because this PR increases usage of concurrent bootstrap in tests.

**Comment by patjed41** [comment]
rebased

**Comment by patjed41** [comment]
Replaced new multiple calls to `server_add` with one call to `servers_add`.

**Comment by patjed41** [comment]
> Replaced new multiple calls to `server_add` with one call to `servers_add`.

I made a small mistake. It should work now.

**Comment by patjed41** [comment]
@kbr-scylla I think it can be requeued now. #16423 is fixed.

**Comment by kbr-scylla** [comment]
Qd

**Pull request merged**
