### PR TITLE
test: test_tablet_cleanup: wait for servers to see each other before multi-node queries

### LINKED ISSUE #17029: [x86_64, release]: topology_experimental_raft.test_tablets is flaky
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/7145/ 

```
=================================== FAILURES ===================================
_____________________________ test_tablet_cleanup ______________________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7f84aa2c8dd0>

    @pytest.mark.asyncio
    async def test_tablet_cleanup(manager: ManagerClient):
        cmdline = ['--smp=2', '--commitlog-sync=batch']
    
        logger.info("Start first node")
        servers = [await manager.server_add(cmdline=cmdline)]
        await manager.api.disable_tablet_balancing(servers[0].ip_addr)
    
        logger.info("Populate table")
        cql = manager.get_cql()
        n_tablets = 32
        n_partitions = 1000
        await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
        await cql.run_async("CREATE KEYSPACE test WITH replication = {{'class': 'NetworkTopologyStrategy', 'replication_factor': 1}} AND tablets = {{'initial': {}}};".format(n_tablets))
        await cql.run_async("CREATE TABLE test.test (pk int PRIMARY KEY);")
        await asyncio.gather(*[cql.run_async(f"INSERT INTO test.test (pk) VALUES ({k});") for k in range(1000)])
    
        logger.info("Start second node")
        servers.append(await manager.server_add())
    
        s0_host_id = await manager.get_host_id(servers[0].server_id)
        s1_host_id = await manager.get_host_id(servers[1].server_id)
    
        logger.info("Read system.tablets")
        tablet_replicas = await get_all_tablet_replicas(manager, servers[0], 'test', 'test')
        assert len(tablet_replicas) == n_tablets
    
        # Randomly select half of all tablets.
        sample = random.sample(tablet_replicas, n_tablets // 2)
        moved_tokens = [x.last_token for x in sample]
        moved_src = [x.replicas[0] for x in sample]
        moved_dst = [(s1_host_id, random.choice([0, 1])) for _ in sample]
    
        # Migrate the selected tablets to second node.
        logger.info("Migrate half of all tablets to second node")
        for t, s, d in zip(moved_tokens, moved_src, moved_dst):
            await manager.api.move_tablet(servers[0].ip_addr, "test", "test", *s, *d, t)
    
        # Sanity check. All data we inserted should be still there.
        assert n_partitions == (await cql.run_async("SELECT COUNT(*) FROM test.test"))[0].count
    
        # Wipe data on second node.
        logger.info("Wipe data on second node")
        await manager.server_stop_gracefully(servers[1].server_id, timeout=120)
        await manager.server_wipe_sstables(servers[1].server_id, "test", "test")
        await manager.server_start(servers[1].server_id)
        await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
>       partitions_after_loss = (await cql.run_async("SELECT COUNT(*) FROM test.test"))[0].count
E       cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.180.122.19:9042 datacenter1>: <Error from server: code=0000 [Server error] message="No live endpoint available">, <Host: 127.180.122.49:9042 datacenter1>: <Error from server: code=0000 [Server error] message="No live endpoint available">})

test/topology_experimental_raft/test_tablets.py:534: NoHostAvailable

```

### PR DESCRIPTION
**Pull request by michoecho**
Waiting for CQL connections is not enough. For the queries to succeed, nodes must see each other. We have to wait for this, otherwise the test will be flaky.

Fixes #17029

### CODE REVIEW

**Comment by mykaul** [comment]
Why wouldn't this be folded into wait_for_cql_and_get_hosts()? When do we not need it?

**Comment by mykaul** [comment]
CC @gleb-cloudius (we were discussing similar issue - where just CQL open is not enough)

**Comment by gleb-cloudius** [comment]
> CC @gleb-cloudius (we were discussing similar issue - where just CQL open is not enough)

Yes, we also discussed that both dtest and test.py have functions to check exactly that. And indeed that patch here calls such function.

**Comment by michoecho** [comment]
> Why wouldn't this be folded into wait_for_cql_and_get_hosts()? When do we not need it?

IIUC they are doing different things. You might want to have a test where you query nodes which don't see each other, and you might also want to have a test where you wait for nodes to see each other, even if the CQL connection isn't (or can't be) ready.

So you can't just fold one into another. But we could have a helper which does both.

Anyway, don't let this discussion hold the patch, it's a fix for a flaky test.

**Review by denesb — APPROVED** [review]

**Review by kbr-scylla — APPROVED** [review]

**Pull request closed without merging**
