### PR TITLE
treewide: rename flat_mutation_reader_v2 to mutation_reader

### PR DESCRIPTION
**Pull request by avikivity**
flat_mutation_reader_v2 was introduced in a pair of commits in 2021:

  https://github.com/scylladb/scylladb/commit/e3309322c3480a91bcd1e1e4072bba75fb31b777 "Clone flat_mutation_reader related classes into v2 variants"
  https://github.com/scylladb/scylladb/commit/08b5773c1252422c5403d01f761784baefed0e63 "Adapt flat_mutation_reader_v2 to the new version of the API"

as a replacement for flat_mutation_reader, using range_tombstone_change
instead of range_tombstone to represent represent range tombstones. See
those commits for more information.

The transition was incremental; the last use of the original
flat_mutation_reader was removed in 2022 in commit

  https://github.com/scylladb/scylladb/commit/026f8cc1e7e9e3218b3ceb0726cab88bd2d96541 "db: Use mutation_partition_v2 in mvcc"

In turn, flat_mutation_reader was introduced in 2017 in commit

  https://github.com/scylladb/scylladb/commit/748205ca75b3eebb8276aa8762d64c78694698c7 "Introduce flat_mutation_reader"

To transition from a mutation_reader that nested rows within
a partition in a separate stream, to a flat reader that streamed
partitions and rows in the same stream.

Here, we reclaim the original name and rename the awkward
flat_mutation_reader_v2 to mutation_reader.

Note that mutation_fragment_v2 remains since we still use the original
for compatibilty, sometimes.

Some notes about the transition:

 - files were also renamed. In one case (flat_mutation_reader_test.cc), the
   rename target already existed, so we rename to
    mutation_reader_another_test.cc.

 - a namespace 'mutation_reader' with two definitions existed (in
   mutation_reader_fwd.hh). Its contents was folded into the mutation_reader
   class. As a result, a few #includes had to be adjusted.

No backport required, cosmetic change.

### CODE REVIEW

**Comment by mykaul** [comment]
Hmpf. There's a reason IPv6 is not IPv5.

**Comment by tgrabiec** [comment]
> Should we go further and remove flat_?

Yes.

**Review by tgrabiec — APPROVED** [review]

**Comment by avikivity** [comment]
> > Should we go further and remove flat_?
> 
> Yes.

In this commit or a later one? I don't mind another sed pass.

**Comment by avikivity** [comment]
> > > Should we go further and remove flat_?
> > 
> > 
> > Yes.
> 
> In this commit or a later one? I don't mind another sed pass.

pull request, I don't propose two sequential patches renaming a single thing incrementally.

**Comment by avikivity** [comment]
> > > > Should we go further and remove flat_?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > In this commit or a later one? I don't mind another sed pass.
> 
> pull request, I don't propose two sequential patches renaming a single thing incrementally.

I'll just change it.

**Comment by avikivity** [comment]
> > > > > Should we go further and remove flat_?
> > > > 
> > > > 
> > > > Yes.
> > > 
> > > 
> > > In this commit or a later one? I don't mind another sed pass.
> > 
> > 
> > pull request, I don't propose two sequential patches renaming a single thing incrementally.
> 
> I'll just change it.

It's actually more difficult, since mutation_reader still exists.

**Comment by avikivity** [comment]
v2: rename to mutation_reader

**Review by denesb — APPROVED** [review]

**Pull request closed without merging**
