### PR TITLE
doc: add a cloud instance recommendations page

### PR DESCRIPTION
**Pull request by annastuchlik**
Fixes https://github.com/scylladb/scylladb/issues/13808

This commit moves cloud instance recommendations from the Requirements page to a new dedicated page.

The content of subsections is simply copy-pasted, but I added the introduction and metadata for better
searchability.

### CODE REVIEW

**Comment by annastuchlik** [comment]
image

**Comment by annastuchlik** [comment]
@tzach Please review this PR. I decided to move the recommendations to the same page (the sections are on the menu), modify the page title, and add metadata - altogether, it will result in better accessibility.
Also, I didn't add the snitch information to that page, as it's a simple reference page for cloud instances. The snitch information should and will be added together with installation and configuration.

**Comment by tzach** [comment]
I would add a link to the new page from the rop of the old page (docs/getting-started/system-requirements.rst) in the Supported Platforms section.

**Review by tzach — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge.

**Pull request merged**
