### PR TITLE
utils/tagged_integer: remove conversion to underlying integer

### PR DESCRIPTION
**Pull request by lersek**
~~~
utils/tagged_integer: remove conversion to underlying integer

Silently converting a tagged (i.e., "dimension-ful") integer to a naked
("dimensionless") integer defeats the purpose of having tagged integers,
and is a source of practical bugs, such as
<https://github.com/scylladb/scylladb/issues/20080>.

We could make the conversion operator explicit, for enforcing

  static_cast<TAGGED_INTEGER_TYPE::value_type>(TAGGED_INTEGER_VALUE)

in every conversion location -- but that's a mouthful to write. Instead,
remove the conversion operator, and let clients call the (identically
behaving) value() member function.
~~~

No backport needed (refactoring).

The series is supposed to solve #20081.

Two patches in the series touch up code that is known to be (orthogonally) buggy; see
- `service/raft_sys_table_storage: tweak dead code` (#20080)
- `test/raft/replication: untag index_t in test_case::get_first_val()` (#20151)

Fixes for those (independent) issues will have to be rebased on this series, or this series will have to be rebased on those (due to context conflicts).

The series builds at every stage. The debug and release unit test suites pass at the end.

### CODE REVIEW

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
```
10:43:16  Traceback (most recent call last):
10:43:16    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 2078, in workaround_python26789
10:43:16      code = await main()
10:43:16             ^^^^^^^^^^^^
10:43:16    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1805, in main
10:43:16      boost_to_junit(xunit_file, junit_file)
10:43:16    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1710, in boost_to_junit
10:43:16      test_suites = boost_root.find('TestSuite').findall('TestSuite')
10:43:16                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10:43:16  AttributeError: 'NoneType' object has no attribute 'findall'
```

`test.py` failed .

**Comment by lersek** [comment]
> #### Failed Tests (1/31922):
> 
>     * [test_topology_changes.dev.5](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/10920/testReport/junit/%28root%29/test_tablets/Tests___Unit_Tests___test_topology_changes_dev_5) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.5)

I've made an attempt to analyze the test artifacts, against the test itself.

The test `test_topology_changes` is in `test/topology_experimental_raft/test_tablets.py`. If first creates a cluster with three nodes, a keyspace called `test`, and creates & populates a table called `test.test`.

Then two more servers are added (one by one), with the table being re-checked repeatedly meanwhile. Finally the very first server (from the original three) is removed from the cluster, and then the keyspace is dropped.

In the logs, I can see these actions reflected. The first three servers are 3863, 3864, 3865. The last two are 3875, 3879. Server#0 (3863) shuts down fine. Afterwards, the `DROP KEYSPACE test` command reaches the remaining four servers -- the last two from the original three (3864, 3865), and the two extra (3875, 3879).

For dropping the keyspace, each of the remaining four nodes start dropping and truncating the table `test.test` (`database - Truncating test.test without snapshot`). The last three servers (3865, 3875, 3879; i.e., the last one of the original three, and the two extra) seem to complete this fine. However, the second server of the original three (3864) fails like this:

~~~
INFO  2024-08-15 10:16:56,628 [shard 0: gms] database - Truncating test.test without snapshot
ERROR 2024-08-15 10:16:56,645 [shard 1: gms] on_internal_error - compaction not disabled on table test.test during TRUNCATE, at: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x554d8e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5553b0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x5556b8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a0767 0x1636bd0 0x13b21dd 0x130e35e 0x1329d31 0x106c6e0 0x106ca0c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3eb8bf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ecc8a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3edd17 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x409be8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a184a /lib64/libc.so.6+0x97506 /lib64/libc.so.6+0x11b40b
   --------
   seastar::smp_message_queue::async_work_item<seastar::sharded<replica::database>::invoke_on_all(seastar::smp_submit_to_options, std::function<seastar::future<void> (replica::database&)>)::{lambda(unsigned int)#1}::operator()(unsigned int) const::{lambda()#1}>
Aborting on shard 1, in scheduling group gossip.
Backtrace:
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4153b4
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3de565
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x4095c6
  /lib64/libc.so.6+0x40cff
  /lib64/libc.so.6+0x994a3
  /lib64/libc.so.6+0x40c4d
  /lib64/libc.so.6+0x28901
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a07ea
  0x1636bd0
  0x13b21dd
  0x130e35e
  0x1329d31
  0x106c6e0
  0x106ca0c
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3eb8bf
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3ecc8a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3edd17
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x409be8
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/dev/seastar/libseastar.so+0x3a184a
  /lib64/libc.so.6+0x97506
  /lib64/libc.so.6+0x11b40b
~~~

This comes from `replica/table.cc`.

~~~
future<db::replay_position> table::discard_sstables(db_clock::time_point truncated_at) {
    // truncate_table_on_all_shards() disables compaction for the truncated
    // tables and views, so we normally expect compaction to be disabled on
    // this table. But as shown in issue #17543, it is possible that a new
    // materialized view was created right after truncation started, and it
    // would not have compaction disabled when this function is called on it.
    if (!schema()->is_view()) {
        auto compaction_disabled = std::ranges::all_of(storage_groups() | boost::adaptors::map_values,
                                                       std::mem_fn(&storage_group::compaction_disabled));
        if (!compaction_disabled) {
            utils::on_internal_error(fmt::format("compaction not disabled on table {}.{} during TRUNCATE",
                schema()->ks_name(), schema()->cf_name()));
        }
    }
~~~

The expectation that compaction be first disabled on a table (= not MV) when initiating truncation is violated. That's probably what's truly worth investigating -- AFAICT, the python code never modifies (updates / deletes etc) data in the `test.test` table after its initial population (which inserts all distinct partitions, so no overwrites); therefore, there should not be anything to "compact" (no data in the table is stale). Perhaps when table truncation is initiated through dropping a keyspace, then a code path different from truncate_table_on_all_shards() is taken, and compaction is not disabled (i.e., breaking the assumption of `table::discard_sstables()`).

Either way, this exception is then somehow *misreported* (or mis-propagated) as `Cannot drop non existing keyspace` by `prepare_keyspace_drop_announcement()` in `service/migration_manager.cc`. That's the exception we get from `await cql.run_async("DROP KEYSPACE test;")` in the python test source (last line of `test_topology_changes` is in `test/topology_experimental_raft/test_tablets.py`).

Now, I've searched the github tickets for the actual error message (`compaction not disabled on table test.test during TRUNCATE`), rather than for the "red herring" `Cannot drop non existing keyspace`. This search yields #20091, which was originally filed on Aug 9th (i.e., about a week ago).

**Comment by lersek** [comment]
FWIW, I'm going to relaunch the CI run now. --> https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10928/

**Comment by mykaul** [comment]
The CI failure is then a dup of https://github.com/scylladb/scylladb/issues/19707

**Comment by lersek** [comment]
@mykaul 

> The CI failure is then a dup of #19707

upon skimming that, I agree!

**Review by bhalevy — APPROVED** [review]

**Comment by lersek** [comment]
> 🔴 CI State: FAILURE

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10928/console

~~~
14:20:43  Traceback (most recent call last):
14:20:43    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 2078, in workaround_python26789
14:20:43      code = await main()
14:20:43             ^^^^^^^^^^^^
14:20:43    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1805, in main
14:20:43      boost_to_junit(xunit_file, junit_file)
14:20:43    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1710, in boost_to_junit
14:20:43      test_suites = boost_root.find('TestSuite').findall('TestSuite')
14:20:43                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:20:43  AttributeError: 'NoneType' object has no attribute 'findall'
~~~

Same CI issue as noted by @tchaikov [here](https://github.com/scylladb/scylladb/pull/20159#issuecomment-2290639957)

**Comment by lersek** [comment]
@tgrabiec can you please review this? (Or else, can this series be merged?) Thank you!

**Pull request merged**
