### PR TITLE
Cherry-pick Seastar patch

### PR DESCRIPTION
**Pull request by nyh**
Backported Seastar commit 4f4e84bb2cec5f11b4742396da7fc40dbb3f162f:

* seastar 04a39f448...06bb98796 (1):
  > sstring: refactor to_sstring() using fmt::format_to()

Refs https://github.com/scylladb/scylladb/issues/15127

### CODE REVIEW

**Comment by tchaikov** [comment]
```
 pytest failurea pytest failed:  json_test.py::TestsToJsonSelect::test_basic_data_types
```

the test failure is expected. but we need to address it on the dtest's end. the change which originally brought the alternative representation of float formatting was https://github.com/scylladb/scylla-dtest/pull/2982. but it involves a lot of unrelated change. so we need to backport it manually to the `branch-5.1` branch, so that the test in question can pass before and after this change. yeah, we will drop the old one after this PR lands.

**Comment by nyh** [comment]
Reached branch-5.1, so closing the issue.

@fruch - dtest now fails - see https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/, can you please take a look?

[dtest / json_test.TestsFromJsonInsert.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsFromJsonInsert/dtest___test_basic_data_types/)
    [dtest / json_test.TestsToJsonSelect.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsToJsonSelect/dtest___test_basic_data_types/)

**Comment by tchaikov** [comment]
> Reached branch-5.1. @fruch - dtest now fails - see https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/, can you please take a look?
> 
> [dtest / json_test.TestsFromJsonInsert.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsFromJsonInsert/dtest___test_basic_data_types/) [dtest / json_test.TestsToJsonSelect.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsToJsonSelect/dtest___test_basic_data_types/)

seems we were using next-5.1 for testing, while the backport went straight into branch-5.1: next-5.1 does not in include the backport.

**Comment by nyh** [comment]
> > Reached branch-5.1. @fruch - dtest now fails - see https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/, can you please take a look?
> > [dtest / json_test.TestsFromJsonInsert.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsFromJsonInsert/dtest___test_basic_data_types/) [dtest / json_test.TestsToJsonSelect.test_basic_data_types](https://jenkins.scylladb.com/job/scylla-5.1/job/next/325/testReport/junit/json_test/TestsToJsonSelect/dtest___test_basic_data_types/)
> 
> seems we were using next-5.1 for testing, while the backport went straight into branch-5.1: next-5.1 does not in include the backport.

Which repository are you referring when you are giving these branch names? This backport in this did *not* PR go "straight to branch-5.1. It went into scylla.git next-5.1, it wasn't yet promoted to scylla.git's branch-5.1. This is tested against some branch of scylla-dtest.git, I'm not sure which and I want @fruch to take a look at it. It's possible that @fruch's fix didn't make it to scylla-dtest.git's branch-5.1 and this is what Jenkins is using. He may need to do his change in two steps - one that will be able to reach scylla-dtest.git's branch-5.1 (because it passes also on the older version of Scylla, by disabling the test). And only when all the dust settles, a second PR to restore the test.

**Comment by tchaikov** [comment]
i am referring scylla-dtest repo.

**Comment by fruch** [comment]
> i am referring scylla-dtest repo.

@nyh, @tchaikov is correct I've failed to notice that https://github.com/scylladb/scylla-dtest/pull/3620 is pointed straight at branch-5.1, and not on next-5.1

the code that supposed to warn/block me about those, isn't in 5.1 😩

I'll fix is shortly

**Comment by nyh** [comment]
This PR reached branch-5.1, and will not be closed automatically, so I'm doing it manually.

**Pull request closed without merging**
