### PR TITLE
locator: token_metadata: replace boost range with std range

### PR DESCRIPTION
**Pull request by avikivity**
Reduce dependency load by standardizing on std::ranges. This is a little
involved since a we use a custom iterator.

Code cleanup; no backport.

### CODE REVIEW

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12937/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/66/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1507/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4580/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12605/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12937/)
> #### Failed Tests (1/35595):
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12937/testReport/junit/boost.view_schema_test.test_all_types.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)

#20772

**Comment by avikivity** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12948/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/74/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1517/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4590/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12615/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12948/)
> 
> #### Failed Tests (1/35618):
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12948/testReport/junit/boost.secondary_index_test.test_secondary_index_create_custom_index.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
> #### Build Details:
> * Duration: 7 hr 39 min
> * Builder: i-098f46de45564d543 (m5ad.8xlarge)

https://github.com/scylladb/scylladb/issues/20772

**Comment by nyh** [comment]
"Docker test" failed, I have no idea what this is and clicking on the link https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/104/ doesn't work (tells me the page does not exist or I don't have permissions to see it). @scylladb/releng any idea what's wrong?

**Comment by yaronkaikov** [comment]
> "Docker test" failed, I have no idea what this is and clicking on the link https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/104/ doesn't work (tells me the page does not exist or I don't have permissions to see it). @scylladb/releng any idea what's wrong?

@nyh it's a bug in pkg - https://github.com/scylladb/scylla-pkg/issues/4554 - will send a patch to fix it soon

**Comment by yaronkaikov** [comment]
> > "Docker test" failed, I have no idea what this is and clicking on the link https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/104/ doesn't work (tells me the page does not exist or I don't have permissions to see it). @scylladb/releng any idea what's wrong?
> 
> @nyh it's a bug in pkg - [scylladb/scylla-pkg#4554](https://github.com/scylladb/scylla-pkg/issues/4554) - will send a patch to fix it soon

patch was merged

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13017/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/123/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4650/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12677/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1575/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13017/)
> #### Failed Tests (1/35601):
> 
>     * [test_mv_tablets_empty_ip.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13017/testReport/junit/%28root%29/test_mv_tablets_empty_ip/Tests___Unit_Tests___test_mv_tablets_empty_ip_debug_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_mv_tablets_empty_ip.debug.1)
> 

#20316

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13043/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/142/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12699/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4671/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1597/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13043/)
> #### Failed Tests (2/35612):
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13043/testReport/junit/boost.secondary_index_test.test_secondary_index_contains_virtual_columns.3.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13043/testReport/junit/boost.secondary_index_test.test_secondary_index_case_sensitive.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 

#20772

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by avikivity** [comment]
@nyh review ping

**Review by nyh — APPROVED** [review]

**Pull request merged**
