### PR TITLE
mv: adjust memory tracking of single view updates within a batch

### LINKED ISSUE #17854: mv: memory used by a view updates batch is incorrectly divided
Since https://github.com/scylladb/scylladb/pull/17420, we're correctly tracking the overhead for a view updates batch. However, even before that we had some overhead which was not taken into account when dividing the memory tracked for singular view updates:
https://github.com/scylladb/scylladb/blob/88119006022d52b03824efb756ebc01734444a5a/db/view/view.cc#L1719
As a result, the view update batch keeps freeing up less memory than it should at the beginning, frees a large chunk of memory when all singular view updates have been started (remote updates in progress), and evens out when all updates finish.
Because of that, we can use more memory than we're supposed because we're tracking less memory than we're actually using when all (remote) updates of a batch have been started.

### PR DESCRIPTION
**Pull request by wmitros**
Currently, when dividing memory tracked for a batch of updates we do not take into account the overhead that we have for processing every update. This patch adds the overhead for single updates and joins the memory calculation path for batches and their parts so that both use the same overhead.

Fixes #17854

### CODE REVIEW

**Review by nyh — APPROVED** [review]
Looks good. The "generic" function name "memory_usage_of()" is bound to confuse someone in the future, as it is specifically the memory used for sending a mutation in the context of MV, not just the memory usage of the mutation, so I would have used a more specific name, eg., memory_to_send_view_update(), but I guess it's not that bad because the comment you wrote explains it well enough.

**Comment by nyh** [comment]
Regarding backports: since this is a small fix over a fix we already plan to backport, we should backport this one too,

**Comment by mykaul** [comment]
What's the status of backporting this to 5.4.x and 5.2.x?

**Comment by piodul** [comment]
> What's the status of backporting this to 5.4.x and 5.2.x?

I queued the backport for 5.4 (https://github.com/scylladb/scylladb/pull/18107) today (https://github.com/scylladb/scylladb/commit/c4515a9b99450184f2da08180ccd930d412119f9).
Backport for 5.2 (https://github.com/scylladb/scylladb/pull/17999) was queued and merged about three weeks ago (https://github.com/scylladb/scylladb/commit/44bcaca929f49ac9fd1a9a81b6d472f885daf6bd).

**Pull request closed without merging**
