### PR TITLE
docs: fix typo in getting-started/install-scylla/launch-on-gcp.rst

### PR DESCRIPTION
**Pull request by Sh4d1**

### CODE REVIEW

**Comment by tzach** [comment]
LGTM
The website page use "nvme" as well
https://www.scylladb.com/download/?platform=gcp#open-source

**Comment by avikivity** [comment]
We require a signed contributor agreement to accept pull requests. See https://www.scylladb.com/open-source-nosql-database/contributor-agreement/.

**Comment by Sh4d1** [comment]
@avikivity just sent the CLA!

**Comment by denesb** [comment]
Queued.

>  It would be great to have it backported to branch-5.4, too, but I don't know what's your stane on that. The updated page does not exist in versions prior to 5.4,

I don't see why not. All you need to do is add the appropriate label and the bot will open the PRs.

**Pull request closed without merging**
