### PR TITLE
configure: generate SCYLLA-VERSION-FILE and SCYLLA-RELEASE-FILE in build/$mode

### LINKED ISSUE #8254: SCYLLA-RELEASE-FILE and SCYLLA-VERSION-FILE should be generated under build/$mode
It is wrong to generate these files under the root of the build tree since they should describe the built artifacts, and those can be built and packaged separately per mode.

### PR DESCRIPTION
**Pull request by bhalevy**
As they reflect only the selected modes when configure.py runs.

Fixes #8254

Test: rm -rf build; ./configure.py && ninja
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

### CODE REVIEW

**Comment by avikivity** [comment]
What does this fix?

**Comment by bhalevy** [comment]
It allows building different versions in different modes.

**Comment by avikivity** [comment]
You can do this today:

```console
git checkout v1
./configure.py --mode x
ninja
git checkout v2
./configure.py --mode y
ninja
```

**Comment by bhalevy** [comment]
`dist/debian/debian_files_gen.py` relies on the state configure.py leaves in build/SCYLLA-{VERSION,RELEASE}-FILE
so I think that building the debian package for `v1` in your example will get confused.

Alternatively, I don't mind getting rid of these artifacts, and maybe generating them temporarily just during configure, but leave nothing under `build/`

**Comment by avikivity** [comment]
> `dist/debian/debian_files_gen.py` relies on the state configure.py leaves in build/SCYLLA-{VERSION,RELEASE}-FILE
> so I think that building the debian package for `v1` in your example will get confused.

Why? v1 is built before v2 is checked out.

> 
> Alternatively, I don't mind getting rid of these artifacts, and maybe generating them temporarily just during configure, but leave nothing under `build/`

I still need to understand the problem we're trying to solve.

**Comment by bhalevy** [comment]
> Why? v1 is built before v2 is checked out.

Yes, if you do a full build before checking out a new version you're good.
The scenario I meant to describe is building the debian package at a later time after you've built another version in a different mode, and later checked out the original version and you want to package your previously built artifacts that are already present in the build directory.  So artifacts that may be reused should be stored in build/$mode by convention.

**Comment by avikivity** [comment]
> > Why? v1 is built before v2 is checked out.
> 
> Yes, if you do a full build before checking out a new version you're good.
> The scenario I meant to describe is building the debian package at a later time after you've built another version in a different mode, and later checked out the original version and you want to package your previously built artifacts that are already present in the build directory. So artifacts that may be reused should be stored in build/$mode by convention.

Well, there are many other failure modes in that model where you switch between versions and don't build in between.

**Comment by bhalevy** [comment]
Closing as this PR aged out and there was no proven need

**Pull request closed without merging**
