### PR TITLE
test/topology: split tablets tests

### PR DESCRIPTION
**Pull request by alecco**
Split tablets test cases to own test file as the total running time is too long (14 minutes).

Refs #13905

### CODE REVIEW

**Comment by tgrabiec** [comment]
Another way to solve this would be at the framework level, where each test case is run concurrently with others, even in the same file. Is there any reason not to do that, for example, do test cases in a single file assume they don't run concurrently?

**Comment by kostja** [comment]
There is value in not running each tiny test case concurrently. There is nothing wrong with establishing a protocol between developers asnd the testing framework when developers inform the testing framework about their intent related to concurrent execution by putting tests into independent files, and by grouping files with similar resource requirements into suites. I don't think expecting clairvoyance from the testing framework is the right strategy, given our resources of extending it are limited.

**Comment by tgrabiec** [comment]
> There is value in not running each tiny test case concurrently. There is nothing wrong with establishing a protocol between developers asnd the testing framework when developers inform the testing framework about their intent related to concurrent execution by putting tests into independent files, and by grouping files with similar resource requirements into suites. I don't think expecting clairvoyance from the testing framework is the right strategy, given our resources of extending it are limited.

Grouping tests with different characteristics makes sense, but it doesn't mean we want to prevent parallelism within the group. For example, tablet test cases have different characteristics (time-bound) than boost tests (cpu-bound), but we still want to parallelize them, this is what this PR does. If we want to prevent CPU starvation, we should dedicate concurrency for different groups. 

I'm trying to understand what should be the guidelines for splitting vs not splitting. Do you have an example of test file which we don't want to parallelize? With boost tests we take a different philosophy approach, and parallelize everything.

**Comment by kostja** [comment]
> > There is value in not running each tiny test case concurrently. There is nothing wrong with establishing a protocol between developers asnd the testing framework when developers inform the testing framework about their intent related to concurrent execution by putting tests into independent files, and by grouping files with similar resource requirements into suites. I don't think expecting clairvoyance from the testing framework is the right strategy, given our resources of extending it are limited.
> 
> Grouping tests with different characteristics makes sense, but it doesn't mean we want to prevent parallelism within the group. For example, tablet test cases have different characteristics (time-bound) than boost tests (cpu-bound), but we still want to parallelize them, this is what this PR does. If we want to prevent CPU starvation, we should dedicate concurrency for different groups.
> 
> I'm trying to understand what should be the guidelines for splitting vs not splitting. Do you have an example of test file which we don't want to parallelize? With boost tests we take a different philosophy approach, and parallelize everything.

Not all tests are so heavyweight as tablets. E.g. cql-pytest has a lot of small test cases which share the cluster/server instance. The second thing is shared pytest fixtures. Some fixtures can have heavyweight setup phase. So it makes sense to not run these in parallel.

I'd say any group of tests that is CPU bound, has shared state, shared code that's not worth putting into a library, and is running under 100ms is not worth splitting. Splitting each such test would create a lot of tiny files, and a lot of subprocess start/stop overhead.

**Pull request closed without merging**
