### PR TITLE
sstables: Reduce cost for loading sstables with tablets

### PR DESCRIPTION
**Pull request by raphaelsc**
Loader was changed to quickly determine ownership after consuming sharding metadata only. If it's not available, it falls back to reading first and last keys from summary. The fallback is only there for backward compatibility and it costs a lot more as we don't skip to the end where keys are located in summary.

With tablets, sharding metadata is only first and last keys so we can do it without sharder. So loader will be able to use it instead of looking up keys in summary.

### CODE REVIEW

**Review by avikivity — APPROVED** [review]
very nice

**Review by denesb — APPROVED** [review]
What is the relation of this PR with https://github.com/scylladb/scylladb/pull/17552?
Are the two orthogonal? Or do they overlap?

**Comment by raphaelsc** [comment]
> What is the relation of this PR with https://github.com/scylladb/scylladb/pull/17552?
> Are the two orthogonal? Or do they overlap?

The issue it fixes becomes invalid after this pr.

**Comment by lkshminarayanan** [comment]
> > > What is the relation of this PR with #17552?
> > > Are the two orthogonal? Or do they overlap?
> > 
> > 
> > The issue it fixes becomes invalid after this pr.
> 
> So #17552 can be closed? @lkshminarayanan

Yes. I have closed it now.

**Pull request closed without merging**
