### PR TITLE
raft: Fix race condition on override_snapshot_thresholds.

### PR DESCRIPTION
**Pull request by bitpathfinder**
When the server_impl::applier_fiber is paused by a co_await at line raft/server.cc:1375:
```
co_await override_snapshot_thresholds();
```
a new snapshot may be applied, which updates the actual values of the log's last applied and snapshot indexes. As a result, the new snapshot index could become higher than the old value stored in `_applied_idx` at line raft/server.cc:1365, leading to an assertion failure in `log::last_conf_for()`.
Since error injection is disabled in release builds, this issue does not affect production releases, therefore backporting is not needed.

This issue was introduced in [this commit](https://github.com/scylladb/scylladb/pull/20095/commits/9dfa041fe16340d5d067bbec299872be65308612), when error injection was added to override the log snapshot configuration parameters.

How to reproduce: 
1)  Build *debug* version of randomized_nemesis_test
 ```# ninja-build build/debug/test/raft/randomized_nemesis_test```
2) run 
``` #parallel --halt now,fail=1 -j20 'build/debug/test/raft/randomized_nemesis_test --run_test=test_frequent_snapshotting  -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000   --default-log-level trace > tmp/logs/eraseme_{}.log  2>&1 && rm tmp/logs/eraseme_{}.log' ::: {1..1000}```

Fixes scylladb/scylladb#20363

Backport not required -- the commit which introduced the regression didn't end up in any release branches yet.

### CODE REVIEW

**Comment by kbr-scylla** [comment]
> _applied_idx at line raft/server.cc:1365 could become less than the new snapshot index

This is formulated as if `_applied_idx` was decreasing ("`_applied_idx" becomes less ..."), when the problem is not that `_applied_idx` changes (it doesn't), but the snapshot index changes (increases).

**Comment by bitpathfinder** [comment]
New version: fixed typo.

**Comment by kbr-scylla** [comment]
The PR description covers many interesting details that will be lost during merge, because for single-commit PRs, only the commit message is preserved.

I think the full story should be included in the commit message. Basically the commit message and the PR description should be mostly in sync (maybe except some details that are not important for `git log` but important for review, e.g. reason of backporting / not backporting *which BTW is missing from your PR for some reason*)

**Comment by bitpathfinder** [comment]
> > _applied_idx at line raft/server.cc:1365 could become less than the new snapshot index
> 
> This is formulated as if `_applied_idx` was decreasing ("`_applied_idx` becomes less ..."), when the problem is not that `_applied_idx` changes (it doesn't), but the snapshot index changes (increases).

PR description has been updated to make it more clear that it's the snapshot index that could be changed. Also added the reasoning for not backporting .

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Queued.

Added "Backport not required -- the commit which introduced the regression didn't end up in any release branches yet." to the PR description

**Pull request closed without merging**
