### PR TITLE
sstables: avoid a possible case of unclosed readers

### LINKED ISSUE #13406: make sure readers are closed around their use in a seastar thread
As seen in https://github.com/scylladb/scylla-enterprise/issues/2786#issuecomment-1490046781
we have a pattern of using flat mutation readers in a seastar thread where the reader is moved to a lambda capture
and then the lambda function has uses a deferred_close to close the reader, like in https://github.com/scylladb/scylladb/blob/207dcbb8fa6bc679298c424366f89f0f226c3abb/sstables/sstables.cc#L1832-L1833

The problem here is that `seastar::async` may throw, destroying the reader without closing it first.

We can wrap the seastar::async call with `with_closeable(std::move(reader)` to deal with that.

### PR DESCRIPTION
**Pull request by michoecho**
There are some cases of readers being moved into seastar::async, where they are
closed by deferred_close. However, seastar::async may fail with a bad_alloc, and
the deferred_close inside will never run, leaving the reader unclosed and
resulting in an assert violation.

This is not really a stability problem, because if bad_alloc is happening in a
seastar::async, a database failure is imminent anyway. But the assert violation
obscures the bad_alloc and causes confusion.

Fixes #13406

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]
lgtm

**Comment by bhalevy** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/512/

@michoecho needs rebase?

**Comment by michoecho** [comment]
@bhalevy No, scylla-sstable relied on the reader being destroyed in a thread in one place, because it was calling a `close()` in a destructor. But the patch broke this assumption.

v2: Fixed.

**Comment by bhalevy** [comment]
@denesb I presume that scylla-sstable code is in your realm.  please review

**Comment by michoecho** [comment]
CI failed due to https://github.com/scylladb/scylladb/issues/13211, restarting

**Review by denesb — CHANGES_REQUESTED** [review]
Have we seen this cause problems in practice? IIRC we made readers not require a close before they are first used. So creating the reader outside of a thread, then destroying them while attempting to move them to a thread should not cause any problems.

https://github.com/scylladb/scylladb/blob/fd817e199c81f391d95c601f09d6be1918ce506e/readers/mutation_reader.cc#L377-L386

I think this PR is not needed at all.

**Comment by mykaul** [comment]
> I concur, [9ada63a](https://github.com/scylladb/scylladb/commit/9ada63a9cbdbe75eeb55eb6298f26b666ab93707) deals with this condition and it is not present in 2022.1.1 where the assert failure in [scylladb/scylla-enterprise#2786](https://github.com/scylladb/scylla-enterprise/issues/2786) was hit.

Do we need a backport?

**Pull request closed without merging**
