### PR TITLE
build_docker.sh: Upgrade package during creation and remove sshd service

### PR DESCRIPTION
**Pull request by yaronkaikov**
When scanning our latest docker image using `trivy` (command: `trivy image docker.io/scylladb/scylla-nightly:latest`), it shows we have OS packages which are out of date.

Also removing `openssh-server` and `openssh-client` since we don't use it for our docker images

Fixes: https://github.com/scylladb/scylladb/issues/16222

### CODE REVIEW

**Comment by avikivity** [comment]
We use Fixes not Closes so it gets the backport candidate label.

**Comment by avikivity** [comment]
Also don't refer to scylla-pkg which is a private repository.

**Comment by yaronkaikov** [comment]
Changed

**Comment by avikivity** [comment]
> Changed

The commit is unchanged.

**Comment by yaronkaikov** [comment]
> > Changed
> 
> The commit is unchanged.

Now it is :-)

**Comment by yaronkaikov** [comment]
@avikivity can you please merge?

**Comment by mykaul** [comment]
I think it should be easily backportable to earlier releases.

**Pull request closed without merging**
