### PR TITLE
Update tools/cqlsh submodule

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh 8769c4c2...6e1000f1 (5):
  > build: erase uid/gid information from tar archives
  > Add github action to update the dockerhub description
  > cqlsh: Add extension handler for "scylla_encryption_options"
  > requirements.txt: update python-driver==3.26.0
  > Add support for arm64 docker image

### CODE REVIEW

**Comment by fruch** [comment]
there are few dtest that are missing this cqlsh feature

**Comment by tchaikov** [comment]
> Please use `git submodule summary` to generate changelogs for submodules. See the log for seastar for example.
> 
> Also see https://github.com/scylladb/scylladb/blob/master/docs/dev/maintainer.md#updating-submodule-references

FWIW, `git submodule summary` was unable to include all commits if there were merge commits in it, so the script mentioned in above link was rewritten.

**Comment by tchaikov** [comment]
> there are few dtest that are missing this cqlsh feature

@fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?

**Comment by fruch** [comment]
> There are four commits in cqlsh-master, but only one listed here

fix that

**Comment by fruch** [comment]
> > there are few dtest that are missing this cqlsh feature
> 
> @fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?



> > there are few dtest that are missing this cqlsh feature
> 
> @fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?

encryption at rest test are doing so, they are looking for some of the encryption properties :
https://github.com/scylladb/scylla-dtest/blob/0d8f5ad68ccf69fde0807ba4f04300e46b7df5c1/encryption_at_rest_test.py#LL409C17-L409C27

**Comment by avikivity** [comment]
If I run git submodule summary, I see different commit hashes:

```
* tools/cqlsh 8769c4c...960343a (4):
```

why is that?

**Comment by fruch** [comment]
> If I run git submodule summary, I see different commit hashes:
> 
> ```
> * tools/cqlsh 8769c4c...960343a (4):
> ```
> 
> why is that?

I don't know

I've used:

https://github.com/scylladb/scylladb/blob/master/scripts/refresh-submodules.sh

**Comment by tchaikov** [comment]
> If I run git submodule summary, I see different commit hashes:
> 
> ```
> * tools/cqlsh 8769c4c...960343a (4):
> ```
> 
> why is that?

it's a regression. should be fixed by #13974

**Comment by tchaikov** [comment]
> > > there are few dtest that are missing this cqlsh feature
> > 
> > 
> > @fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?
> 
> > > there are few dtest that are missing this cqlsh feature
> > 
> > 
> > @fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?
> 
> encryption at rest test are doing so, they are looking for some of the encryption properties : https://github.com/scylladb/scylla-dtest/blob/0d8f5ad68ccf69fde0807ba4f04300e46b7df5c1/encryption_at_rest_test.py#LL409C17-L409C27

the test is checking "key_provider" in the table description not "encryption". probably i am missing something obvious?

**Comment by fruch** [comment]
> > > > there are few dtest that are missing this cqlsh feature
> > > 
> > > 
> > > @fruch could you point me to the dtest(s) which require this feature? i searched in https://github.com/scylladb/scylla-dtest/ but no luck. BTW, shall we add something like https://github.com/scylladb/scylla-cqlsh/blob/960343aedc4d36fe9308784af758964c24765fed/pylib/cqlshlib/test/test_cqlsh_output.py#L990 in scylla-cqlsh ?
> > 
> > encryption at rest test are doing so, they are looking for some of the encryption properties : https://github.com/scylladb/scylla-dtest/blob/0d8f5ad68ccf69fde0807ba4f04300e46b7df5c1/encryption_at_rest_test.py#LL409C17-L409C27
> 
> the test is checking "key_provider" in the table description not "encryption". probably i am missing something obvious? 

It's one of the parameters inside that structure

**Comment by fruch** [comment]
@avikivity description/commit fixed

@tchaikov any more comments/questions ?

**Comment by avikivity** [comment]
Description says:

```
* tools/cqlsh 8769c4c2...5c62c72e (5):
```

diff says:

```
diff --git a/tools/cqlsh b/tools/cqlsh
index 8769c4c25b..6e1000f17f 160000
--- a/tools/cqlsh
+++ b/tools/cqlsh
@@ -1 +1 @@
-Subproject commit 8769c4c25b979858829fc0e49c6af7c9fc6720ae
+Subproject commit 6e1000f17ffaeb1a956455d35585e46abd5719f7
```

**Comment by fruch** [comment]
> Description says:
> 
> ```
> * tools/cqlsh 8769c4c2...5c62c72e (5):
> ```
> 
> diff says:
> 
> ```
> diff --git a/tools/cqlsh b/tools/cqlsh
> index 8769c4c25b..6e1000f17f 160000
> --- a/tools/cqlsh
> +++ b/tools/cqlsh
> @@ -1 +1 @@
> -Subproject commit 8769c4c25b979858829fc0e49c6af7c9fc6720ae
> +Subproject commit 6e1000f17ffaeb1a956455d35585e46abd5719f7
> ```


found the reason this script take the hash from local `master` branch, while bumping from `origin/master`
```
bash -x ./scripts/refresh-submodules.sh tools/cqlsh
+ set -euo pipefail
+ submodules=(seastar tools/jmx tools/java tools/python3)
+ for ent in "${@:-${submodules[@]}}"
+ submodule=tools/cqlsh
+ '[' tools/cqlsh == tools/cqlsh ']'
+ branch=master
+ bump_to=origin/master
+ pushd .
~/projects/scylla ~/projects/scylla
+ cd tools/cqlsh
+ git fetch origin master
From github.com:scylladb/scylla-cqlsh
 * branch            master     -> FETCH_HEAD
+ git merge-base --is-ancestor HEAD origin/master
++ git rev-parse --short=8 HEAD
+ head_ref=8769c4c2
++ git rev-parse --short=8 master
+ branch_ref=5c62c72e
```

**Comment by avikivity** [comment]
I recommend using `git submodule summary`.

**Comment by tchaikov** [comment]
> > Description says:
> > ```
> > * tools/cqlsh 8769c4c2...5c62c72e (5):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > diff says:
> > ```
> > diff --git a/tools/cqlsh b/tools/cqlsh
> > index 8769c4c25b..6e1000f17f 160000
> > --- a/tools/cqlsh
> > +++ b/tools/cqlsh
> > @@ -1 +1 @@
> > -Subproject commit 8769c4c25b979858829fc0e49c6af7c9fc6720ae
> > +Subproject commit 6e1000f17ffaeb1a956455d35585e46abd5719f7
> > ```
> 
> found the reason this script take the hash from local `master` branch, while bumping from `origin/master`
> 
> ```
> bash -x ./scripts/refresh-submodules.sh tools/cqlsh
> + set -euo pipefail
> + submodules=(seastar tools/jmx tools/java tools/python3)
> + for ent in "${@:-${submodules[@]}}"
> + submodule=tools/cqlsh
> + '[' tools/cqlsh == tools/cqlsh ']'
> + branch=master
> + bump_to=origin/master
> + pushd .
> ~/projects/scylla ~/projects/scylla
> + cd tools/cqlsh
> + git fetch origin master
> From github.com:scylladb/scylla-cqlsh
>  * branch            master     -> FETCH_HEAD
> + git merge-base --is-ancestor HEAD origin/master
> ++ git rev-parse --short=8 HEAD
> + head_ref=8769c4c2
> ++ git rev-parse --short=8 master
> + branch_ref=5c62c72e
> ```

you were still using the version before 8d79811c6a1e32a1619ba360af4d8d8bf99fc2c2

**Review by tchaikov — APPROVED** [review]

**Comment by fruch** [comment]
@scylladb/scylla-maint can this be merged ?

**Pull request closed without merging**
