### PR TITLE
mv: avoid stalls when calculating affected clustering ranges

### PR DESCRIPTION
**Pull request by wmitros**
Currently, when finishing db::view::calculate_affected_clustering_ranges we deoverlap, transform and copy all ranges prepared before. This is all done within a single continuation and can cause stalls.

We fix this by adding yields after each transform and moving elements to the final vector one by one instead of copying them all at the end.

After this change, the longest continuation in this code will be deoverlapping the initial ranges (and one transform). While it has a relatively high computational complexity (we sort all ranges), it should execute quickly because we're operating on views there and we don't need to copy the actual bytes. If we encounter a stall there, we'll need to implement an asynchronous `deoverlap` method.

Fixes https://github.com/scylladb/scylladb/issues/21843

This is a performance fix so no need to backport

### CODE REVIEW

**Comment by wmitros** [comment]
@piodul please take a look

**Review by piodul — APPROVED** [review]
Looks good.

I'm not 100% sure that the root cause of the stall mentioned in the issue is the fact that we don't preempt here - the stall points to the LSA code which is known to stall in low-memory situations. However, adding preempts to the loop definitely should not hurt, especially that in the code that precedes the new code we already take care to yield for each clustering row range added.

**Comment by piodul** [comment]
Queued

**Comment by avikivity** [comment]
I'm pretty sure the reserve() and deoverlap() are both more heavyweight (for different reasons) than the accumulation into the container.

How was this tested?

**Comment by mykaul** [comment]
@piodul , @wmitros ^^^ ?

**Comment by wmitros** [comment]
Sorry, I forgot to answer.


> I'm pretty sure the reserve() and deoverlap() are both more heavyweight (for different reasons) than the accumulation into the container.

Right, if we want to improve this even more we'll have to implement an asynchronous `deoverlap`. I don't think we can do much about the `reserve`, like using a chunked_vector, as we want to return `clustering_row_ranges` (an std::vector) which we later store in a `partition_slice`. I see that I should have at least added an extra yield between them

As @piodul mentioned, it looks like the issue was actually with allocating while having little free memory, but the patch should still help a bit with that slightly - in the backtrace we can see
```
 (inlined by) void std::vector<...>::_M_realloc_insert<...>(...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/vector.tcc:459
```
So it looks like because of `boost::copy_range`, instead of a single `reserve` we were adding elements one by one to the vector and incurring resizes and possible copies along the way (the backtrace comes from enterprise where we had boost instead of the std equivalent)

> How was this tested?

This didn't have any specific tests (do we have any tests for detecting stalls?). This is something encountered in the field, so we don't have a reproducer, but adding extra yields in a synchronous block always shorten the stalls, at least slightly

**Pull request closed without merging**
