### PR TITLE
materialized views: fix rare failure caused by empty update

### LINKED ISSUE #15228: std::logic_error "Empty materialized view updated"
In db/view/view.cc, the function `view_update_builder::generate_update()` starts with:
```c++
    // If we have no update at all, we shouldn't get there.
    if (update.empty()) {
        throw std::logic_error("Empty materialized view updated");
    }
```

We have seen this message appearing in a user's log:
```
[shard 7] view - Failed to push replica updates for table ks.tbl: std::logicerror (Empty materialized view updated)
```

The comments suggest that this message should never have been printed, and the fact that it was indicates a bug.

I have two questions:
1. Does this message indicate a real bug? If so, what could cause it?
2. Or alternatively, maybe there are legimate reasons why this function can be called with empty updates (e.g., all updates have old timestamps) and the check is wrong? If the check is wrong, what is the implication in throwing in that function - could we be interrupting a longer process and losing view updates, or something?

### LINKED ISSUE #17549: [dtest] test_table_alter_delete fails
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/7297/

https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/7296/

### PR DESCRIPTION
**Pull request by nyh**
This one-line patch fixes a failure in the dtest

        lwt_schema_modification_test.py::TestLWTSchemaModification
        ::test_table_alter_delete

Where an update sometimes failed due to an internal server error, and the log had the mysterious warning message:

        "std::logic_error (Empty materialized view updated)"

We've also seen this log-message in the past in another user's log, and never understood what it meant.

It turns out that the error message was generated (and warning printed) while building view updates for a base-table mutation, and noticing that the base mutation contains an *empty* row - a row with no cells or tombstone or anything whatsoever. This case was deemed (8 years ago, in d5a61a8c48261a3478527871927ae6ed01c22ed2) unexpected and nonsensical, and we threw an exception. But this case actually *can* happen - here is how it happened in test_table_alter_delete - which is a test involving a strange combination of materialized views, LWT and schema changes:

 1. A table has a materialized view, and also a regular column "int_col".
 2. A background thread repeatedly drops and re-creates this column int_col.
 3. Another thread deletes rows with LWT ("IF EXISTS").
 4. These LWT operations each reads the existing row, and because of repeated drop-and-recreate of the "int_col" column, sometimes this read notices that one node has a value for int_col and the other doesn't, and creates a read-repair mutation setting int_col (the difference between the two reads includes just in this column).
 5. The node missing "int_col" receives this mutation which sets only int_col. It upgrade()s this mutation to its most recent schema, which doesn't have int_col, so it removes this column from the mutation row - and is left with a completely empty mutation row. This completely empty row is not useful, but upgrade() doesn't remove it.
 6. The view-update generation code sees this empty base-mutation row and fails it with this std::logic_error.
 7. The node which sent the read-repair mutation sees that the read repair failed, so it fails the read and therefore fails the LWT delete operation. It is this LWT operation which failed in the test, and caused the whole test to fail.

The fix is trivial: an empty base-table row mutation should simply be *ignored* when generating view updates - it shouldn't cause any error.

Before this patch, test_table_alter_delete used to fail in roughly 20% of the runs on my laptop. After this patch, I ran it 100 times without a single failure.

Fixes #15228
Fixes #17549

### CODE REVIEW

**Comment by nyh** [comment]
This patch is a trivial fix for a very old bug (the code is 8 years old) which was only discovered half a year ago, and rediscovered in a failing CI test last week which moved it to P1.

@fruch has since reverted the test enablement (dtest commit 3815457f2bd2c40f1205ed9af8be91f7a589e373) - but now, @fruch, you will be able to un-revert the patch. Please do unrevert it (when this patch goes in) because the post-revert code became nonsense - it has syntax errors but nobody cares because the test is skipped ;-) With my patch, I ran the unreverted test 100 times without a single failure - without my patch I saw about 20% failure rate.

**Comment by mykaul** [comment]
> 5\. The node missing "int_col" receives this mutation which sets only int_col. It upgrade()s this mutation to its most recent schema, which doesn't have int_col, so it removes this column from the mutation row - and is left with a completely empty mutation row. This completely empty row is not useful, but upgrade() doesn't remove it.

Is there are reason upgrade() shouldn't remove that empty row?

**Comment by nyh** [comment]
> > 5. The node missing "int_col" receives this mutation which sets only int_col. It upgrade()s this mutation to its most recent schema, which doesn't have int_col, so it removes this column from the mutation row - and is left with a completely empty mutation row. This completely empty row is not useful, but upgrade() doesn't remove it.
> 
> Is there are reason upgrade() shouldn't remove that empty row?

I also thought about this. I don't know if there is a reason why upgrade() should keep an empty row - as far as I know when a clustering row remains "empty" - i.e., doesn't have a row marker, cells or tombstone, it is the same as non-existent and has no useful function and could have been removed completely from the mutation. But,

1. I wasn't sure we don't have other code which relies on upgrade() not removing rows that have no cells left.
2. I wasn't sure that even if I fix upgrade(), there aren't other rare cases where a base-table mutation might not be empty - maybe if upgrade() no longer produce one, something else can still produce one?

Also, since the MV code already had an "if()" for this empty-row case, I thought the safest thing is to fix this if() and not fix some other code so that miraculously this broken if() will not to be reached. And since I realized now that there's nothing "wrong" or "bad" about an empty base-table update row - it's just "nothing" - I think the correct fix is to treat it like nothing and not make a big fuss about it (warn in the log and fail a request).

**Comment by nyh** [comment]
@scylladb/scylla-maint the merge freeze is over, please consider merging this.

**Pull request closed without merging**
