### PR TITLE
Update scylla-tools-java submodule (CI; don't merge)

### PR DESCRIPTION
**Pull request by avelanarius**
Don't merge this PR. Created for purposes of running CI.

Updates scylla-tools-java submodule to avelanarius/pr-351-and-353 (changes from https://github.com/scylladb/scylla-tools-java/pull/351 and https://github.com/scylladb/scylla-tools-java/pull/353)

### CODE REVIEW

**Comment by mykaul** [comment]
The first 4 failures in CI are unrelated. The last one needs to be looked at - or we should just re-run CI, now that the offending commit for the first failures was dequeued.

**Comment by avelanarius** [comment]
Yes, the last test (test_connectivity_with_cassandra_stress) shows there is an actual problem with updated Snakeyaml dependency. I will investigate and fix it in https://github.com/scylladb/scylla-tools-java/pull/351.

**Comment by mykaul** [comment]
> Yes, the last test (test_connectivity_with_cassandra_stress) shows there is an actual problem with updated Snakeyaml dependency. I will investigate and fix it in [scylladb/scylla-tools-java#351](https://github.com/scylladb/scylla-tools-java/pull/351).

Thanks @tzach - do we 'support' cassandra-stress that comes as part of Scylla? Or we can break it freely?

**Comment by avelanarius** [comment]
> > Yes, the last test (test_connectivity_with_cassandra_stress) shows there is an actual problem with updated Snakeyaml dependency. I will investigate and fix it in [scylladb/scylla-tools-java#351](https://github.com/scylladb/scylla-tools-java/pull/351).
> 
> Thanks @tzach - do we 'support' cassandra-stress that comes as part of Scylla? Or we can break it freely?

Isn't it a problem that our CI will use that cassandra-stress and if it's buggy (currently it looks like user profile YAMLs don't work) it will seriously hurt our releng process that expects test to run correctly before pushing out next release.

**Comment by avelanarius** [comment]
> Yes, the last test (test_connectivity_with_cassandra_stress) shows there is an actual problem with updated Snakeyaml dependency. I will investigate and fix it in [scylladb/scylla-tools-java#351](https://github.com/scylladb/scylla-tools-java/pull/351).

That failed test is a serverless test, so it's not a problem with parsing cassandra-stress user profiles, but parsing serverless configuration YAMLs.

**Comment by avelanarius** [comment]
Rerunning CI with v2 changes of https://github.com/scylladb/scylla-tools-java/pull/351 (+ v1 of https://github.com/scylladb/scylla-tools-java/pull/353)

**Pull request closed without merging**
