### PR TITLE
Add Elixir driver

### PR DESCRIPTION
**Pull request by whatyouhide**

### CODE REVIEW

**Comment by bhalevy** [comment]
@whatyouhide can you please add motivation for including the Elixir driver?
(this should go in the patch git commit log)

**Comment by bhalevy** [comment]
cc @tzach

**Comment by whatyouhide** [comment]
@bhalevy done!

**Comment by tzach** [comment]
@whatyouhide can you please follow https://github.com/scylladb/scylladb/blob/master/CONTRIBUTING.md#contributing-code-to-scylla ? This is just for the first PR.

**Comment by whatyouhide** [comment]
I really don't think my phone number or mailing address are necessary to sign a CLA, so I’m gonna close this out, no worries. I've see other projects use https://cla-assistant.io successfully, which makes for a nicer contributor experience IMO.

Anyways, thanks for the great work!

**Comment by tzach** [comment]
Thanks for the input! https://cla-assistant.io/ looks like a great tool

**Comment by annastuchlik** [comment]
@whatyouhide Thanks for your contribution! I've opened a new PR as a V2 of this one so that it can be merged.

**Pull request closed without merging**
