### PR TITLE
raft topology: join_node_request_handler: wait until first node becomes normal

### PR DESCRIPTION
**Pull request by patjed41**
We need to wait until the first node becomes normal in
`join_node_request_handler` to ensure that joining nodes are not
handled as the first node in the cluster.

If we placed a join request before the first node becomes normal,
the topology coordinator would incorrectly skip the join node
handshake in `handle_node_transition` (`case node_state::none`).
It would happen because the topology coordinator decides whether
a node is the first in the cluster by checking if there are no
normal nodes. Therefore, we must ensure at least one normal node
when the topology coordinator handles a join request for a
non-first node.

We change the previous check because it can return true if there
are no normal nodes. `topology::is_empty` would also return false
if the first node was still new or in transition.

Additionally, calling `join_node_request_handler` before the first
node sets itself as normal is frequent during concurrent bootstrap,
so we remove "unlikely" from the comment.

Fixes: #15807

### CODE REVIEW

**Review by piodul — APPROVED** [review]

**Comment by patjed41** [comment]
v2:
- improved the commit message -- it should be more clear now why this change is needed
- made a small change to the comment above the change

**Comment by mykaul** [comment]
What issue does it fix? Will we backporting this to 5.2 and/or 5.4?

**Comment by mykaul** [comment]
> @patjed41 please create a corresponding issue and add `Fixes:` to the commit message.
> 
> > Will we backporting this to 5.2 and/or 5.4?
> 
> No, this is for experimental raft-topology.

It's not experimental in 5.4?

**Comment by kbr-scylla** [comment]
> It's not experimental in 5.4?

Raft-based topology is still experimental in 5.4 and in `master`.

**Comment by patjed41** [comment]
I opened a corresponding issue -- #15807, and added "Fixes:" to the commit message.

**Pull request closed without merging**
