### PR TITLE
repair: fix task_manager_module::abort_all_repairs

### PR DESCRIPTION
**Pull request by Deexie**
Currently, task_manager_module::abort_all_repairs marks top-level repairs as aborted (but does not abort them) and aborts all existing shard tasks.

A running repair checks whether its id isn't contained in _aborted_pending_repairs and then proceeds to create shard tasks. If abort_all_repairs is executed after _aborted_pending_repairs is checked but before shard tasks are created, then those new tasks won't be aborted. The issue is the most severe for tablet_repair_task_impl that checks the _aborted_pending_repairs content from different shards, that do not see the top-level task. Hence the repair isn't stopped but it creates shard repair tasks on all shards but the one that initialized repair.

Abort top-level tasks in abort_all_repairs. Fix the shard on which the task abort is checked.

Fixes: #21612.

Needs backport to 6.1 and 6.2 as they contain the bug.

### CODE REVIEW

**Comment by Deexie** [comment]
- extend the fix by new commits

**Review by denesb — COMMENTED** [review]
Do we have a test which reproduced the broken abort?

**Comment by Deexie** [comment]
> Do we have a test which reproduced the broken abort?

It was reproduced by SCT

**Comment by Deexie** [comment]
- add test

**Comment by yaronkaikov** [comment]
:warning:  @Deexie you have been added as collaborator to scylladbbot fork Please check your inbox and approve the invitation, once it is done, please add the backport labels again- backport/6.1
- backport/6.2

**Pull request merged**
