### PR TITLE
test.py: add --tablets and --experimenta-features options

### PR DESCRIPTION
**Pull request by tchaikov**
so that we can enable tablets globally when testing using `test.py`

Fixes https://github.com/scylladb/scylladb/issues/17406

### CODE REVIEW

**Review by nyh — COMMENTED** [review]
I'm not against this patch, but don't understand its motivation. In many pieces of test.py - such as cql-pytest, alternator and topology, we already enabled tablets experimental mode unconditionally, by default. Why don't we do this for all subdirectories of test.py now - why do we want this to be a user option instead of the default? I see Benny opened https://github.com/scylladb/scylladb/issues/17406 and this PR fixes it. So in this sense this PR is well-motivated, and I should write my "complaints" in the issue.

By the way, in cql-pytest and alternator's run script, I even added an option "--vnodes" to disable the automatically-added tablets experimental feature. It sounds like perhaps in the medium term, that's the option we will need to add to test.py, not "--tablets".

**Comment by nyh** [comment]
Another thing that bothered me: The new "--tablets" option will actually applies only to some of the test suites, e.g., it won't apply to the "alternator", "boost", or "cql" suites. I understand why this happened, but I also don't like it very much.

**Comment by tchaikov** [comment]
> Another thing that bothered me: The new "--tablets" option will actually applies only to some of the test suites, e.g., it won't apply to the "alternator", "boost", or "cql" suites. I understand why this happened, but I also don't like it very much.

i agree with you, this option does not apply to "alternator" or "boost". but it applies to `cql` suite, as it connects to the scylla instance created using cluster manager. i will apply it to "alternator" once i gets more inputs. regarding, "boost", i need to think about it. as boost tests are mostly unit tests -- they are exercising a certain part of the system. so i guess they prefer to have better control of their settings.

**Comment by tchaikov** [comment]
@bhalevy what do you think?

**Comment by tchaikov** [comment]
not relevant anymore. closing.

**Pull request closed without merging**
