### PR TITLE
Don't pollute index caching during sstable compaction

### LINKED ISSUE #14317: Compactions that filter partitions may pollute index caching
Index caching is not scan resistant yet, so compactions that use index for forwarding to the next partition (e.g. cleanup), may end up polluting the index caching. Once the caching is scan resistant, MFU entries will remain cached, whereas LRU entries which aren't frequent will have lower priority over the most frequently used ones. We can easily fix the problem today by bypassing the cache with the help of partition slice's option set.

### PR DESCRIPTION
**Pull request by raphaelsc**
Compaction that uses index reader, e.g. cleanup, for forwarding into the next partition once the current one is filtered out, can pollute the index caching, potentially disrupting index caching for serving the user workload.

A similar fix, employed by view building to avoid interfering with user workload, is used here, which is about bypassing the cache. The flag in partition_slice will tell index_reader to use local cache, which is evicted when the reader is destroyed.

Fixes #14317.

### CODE REVIEW

**Comment by raphaelsc** [comment]
> Is this the same index cache we've switched to off by default, and could that be a possible reason why it wasn't effective?

Yes the same index cache, disabled by default but still explicitly enabled by a subset of users. I think the problem being fixed here may contribute to making the problem worst, but I don't think it's the main reason. /CC @michoecho.

> 
> Ia this a regression?

Not a regression.

> 
> Do we have a test or tests for this? And overall index cache functionality?

@tgrabiec wrote a good set of tests, but I am not sure how QA tested this functionality. /CC @roydahan
I'd recommend writing a longevity test to catch the problem described in https://github.com/scylladb/scylladb/issues/11202, then we can expand it to run sstable cleanup and verify it doesn't interfere with the index hit ratio (exposed as metrics) of user queries.

**Comment by michoecho** [comment]
> and could that be a possible reason why it wasn't effective?

No.

> possible reason

We aren't looking for reasons. We know exactly what the problem was and it's described in #11202.

**Comment by michoecho** [comment]
> can pollute the index caching, potentially disrupting index caching for serving the user workload.

Note 1: index cache and row cache use the same memory pool. So polluting the cache doesn't only disrupt "index caching", but all caching.

> The flag in partition_slice will tell index_reader to use local cache, which is evicted when the reader is destroyed.

Note 2: since the index entries are only evicted when the reader is destroyed (if they weren't evicted by LRU), using bypass_cache doesn't prevent cache pollution during long scans. It only means that entries which survived the flood get additional lifetime in the cache. But it doesn't change what's happening during the flood. So it solves pollution by point reads or short scans (where "short" means: the volume of index stuff loaded into cache is smaller than RAM), but has limited usefulness for long scans.

**Comment by tgrabiec** [comment]
Refs https://github.com/scylladb/scylladb/issues/12378

**Comment by raphaelsc** [comment]
> We shouldn't use next_partition() for skipping partitions in cleanup in the first place, but rather skip to the start of the next range directly.

That's a possible solution, but isn't it extremely inefficient to read an entire partition that's going to be discarded? Think of multi-GB partitions being filtered out.

**Comment by raphaelsc** [comment]
> Refs #12378

That came to mind exactly when reading the index caching implementation. Why local cache is keeping older entries cached when keys are being read in monotonically increasing order.

**Comment by raphaelsc** [comment]
> > can pollute the index caching, potentially disrupting index caching for serving the user workload.
> 
> Note 1: index cache and row cache use the same memory pool. So polluting the cache doesn't only disrupt "index caching", but all caching.
> 
> > The flag in partition_slice will tell index_reader to use local cache, which is evicted when the reader is destroyed.
> 
> Note 2: since the index entries are only evicted when the reader is destroyed (if they weren't evicted by LRU), using bypass_cache doesn't prevent cache pollution during long scans. It only means that entries which survived the flood get additional lifetime in the cache. But it doesn't change what's happening during the flood. So it solves pollution by point reads or short scans (where "short" means: the volume of index stuff loaded into cache is smaller than RAM), but has limited usefulness for long scans.

Agreed. We need to limit local cache size for sstables being fully scanned, like in compaction. It makes no sense to keep older entries cached, which aren't going to be used afterwards. So this patch only partially fixes the problem. https://github.com/scylladb/scylladb/issues/12378 must be fixed for the problem to be fully solved.

**Comment by raphaelsc** [comment]
> > We shouldn't use next_partition() for skipping partitions in cleanup in the first place, but rather skip to the start of the next range directly.
> 
> That's a possible solution, but isn't it extremely inefficient to read an entire partition that's going to be discarded? Think of multi-GB partitions being filtered out.

Reading the issue you referenced here, it seems you're suggesting to skip to the next owned range, rather than skipping partitions one at a time. But for the context of this issue, it's irrelevant it seems because the index reader would still be in use. Probably you just raised it as an off topic suggestion.

**Comment by michoecho** [comment]
> But for the context of this issue, it's irrelevant it seems because the index reader would still be in use.

It would be in use, but it would read the index only once (twice?) per vnode. So it would pollute the cache with 256 index pages, not with the entire index.

**Comment by raphaelsc** [comment]
> > But for the context of this issue, it's irrelevant it seems because the index reader would still be in use.
> 
> It would be in use, but it would read the index only once (twice?) per vnode. So it would pollute the cache with 256 index pages, not with the entire index.

Right, one of the nice advantages of skipping to the next owned range.

**Comment by raphaelsc** [comment]
@tgrabiec it seems to me that the index caching was unconditionally enabled even for full scans, but it was a mistake, right? It seems to me that the solution is about ditching the index cache as a concept, when the index reader is opened for a full scan (and with bypass cache), so only the index page being used is kept alive, which is referenced by the reader's _lower_bound. So view building and cleanup both benefit from the change.

**Comment by raphaelsc** [comment]
> @tgrabiec it seems to me that the index caching was unconditionally enabled even for full scans, but it was a mistake, right? It seems to me that the solution is about ditching the index cache as a concept, when the index reader is opened for a full scan (and with bypass cache), so only the index page being used is kept alive, which is referenced by the reader's _lower_bound. So view building and cleanup both benefit from the change.

local or not, it's still index caching as unused entries are placed into LRU till the reader is destroyed. so to fix the pollution issue, the cache entries would be freed as soon as they become unused. index reader keeps in use the index page it's currently operating on.

**Comment by roydahan** [comment]
> > Is this the same index cache we've switched to off by default, and could that be a possible reason why it wasn't effective?
> 
> Yes the same index cache, disabled by default but still explicitly enabled by a subset of users. I think the problem being fixed here may contribute to making the problem worse, but I don't think it's the main reason. /CC @michoecho.
> 
> > Ia this a regression?
> 
> Not a regression.
> 
> > Do we have a test or tests for this? And overall index cache functionality?
> 
> @tgrabiec wrote a good set of tests, but I am not sure how QA tested this functionality. /CC @roydahan I'd recommend writing a longevity test to catch the problem described in #11202, then we can expand it to run sstable cleanup and verify it doesn't interfere with the index hit ratio (exposed as metrics) of user queries.

@raphaelsc sounds like a good opportunity for you to practice SCT and add such a longevity. we can help if needed.

**Comment by raphaelsc** [comment]
> > > Is this the same index cache we've switched to off by default, and could that be a possible reason why it wasn't effective?
> > 
> > 
> > Yes the same index cache, disabled by default but still explicitly enabled by a subset of users. I think the problem being fixed here may contribute to making the problem worse, but I don't think it's the main reason. /CC @michoecho.
> > > Ia this a regression?
> > 
> > 
> > Not a regression.
> > > Do we have a test or tests for this? And overall index cache functionality?
> > 
> > 
> > @tgrabiec wrote a good set of tests, but I am not sure how QA tested this functionality. /CC @roydahan I'd recommend writing a longevity test to catch the problem described in #11202, then we can expand it to run sstable cleanup and verify it doesn't interfere with the index hit ratio (exposed as metrics) of user queries.
> 
> @raphaelsc sounds like a good opportunity for you to practice SCT and add such a longevity. we can help if needed.

To be really honest, I have more than enough on my plate :-)

**Comment by bhalevy** [comment]
@raphaelsc given https://github.com/scylladb/scylladb/pull/14318#issuecomment-1599560944, does this PR depend on https://github.com/scylladb/scylladb/pull/14469 now?

**Comment by mykaul** [comment]
Can we resolve conflicts and move this forward?

**Comment by raphaelsc** [comment]
> Can we resolve conflicts and move this forward?

I took a different approach and went for https://github.com/scylladb/scylladb/commit/1545ae2d3be23d9ae8e9e5b900bca4c3aefefe7b after discussions I had with Michal and Tomek. The usage of bypass cache has very limited effectiveness during range scans. However, the patch introduces high risk for backporting. The patch mentioned even closes the issue this PR was trying to solve. Perhaps the idea from https://github.com/scylladb/scylladb/issues/12378 has more potential for backporting.

**Comment by mykaul** [comment]
CC @DoronArazii - let's understand where we are with this.

**Comment by DoronArazii** [comment]
> CC @DoronArazii - let's understand where we are with this.

@mykaul - IIUC, this PR can be closed as "not planned".
The issue it's referencing (https://github.com/scylladb/scylladb/issues/14317) was already fixed by a different PR (https://github.com/scylladb/scylladb/pull/14469), and per @raphaelsc it's because they took a different approach.
Raphael - please confirm & close it.

**Comment by mykaul** [comment]
@raphaelsc ? shall we close this one?

**Comment by DoronArazii** [comment]
@raphaelsc ping ^^

**Comment by raphaelsc** [comment]
> @raphaelsc ping ^^

yes, we can close it after https://github.com/scylladb/scylladb/pull/14469. thanks

**Pull request closed without merging**
