### PR TITLE
configure.py: build and use libseastar.so in debug and dev modes

### PR DESCRIPTION
**Pull request by tchaikov**
now that Seastar can be built as shared libraries, we can use it for faster development iteration with less disk usage.

in this change

* configure.py:
  - 'build_seastar_shared_libs' is added as yet another mode value,
     so different modes have its own setting. 'debug' and 'dev' have
     this enabled, while other modes disable it.
  - link scylla with rpath specified, so it can find `libseastar.so`
    in build directory.
* install.sh: remove the rpath as the rpath in the elf image will
  not be available after the relocatable package is installed, also
  rpmbuild will error out when it uses check-rpaths to verify
  the elf images (executables and shared libraries), as the rpath
  encoded in them are not known ones. patchelf() will take care of
  the shared libraries linked by the executables. so we don't need
  to worry about libseastar.so or libseastar_testing.so.

before this change
```console
$ du -sh build/dev
11G     build/dev
$ du -sh build/debug
69G     build/debug

$ time ./tools/toolchain/dbuild test/alternator/run 2>&1 | tee run.log
Scylla is: /home/kefu/dev/scylladb/build/dev/scylla.
Booting Scylla on 127.1.0.2 in /tmp/scylla-test-2...
Boot successful (0.9 seconds).
...
Alternator tests pass

real    0m41.643s
user    0m0.470s
sys     0m0.262s
```

after this change:

```console
$ du -sh build/dev
9.8G    build/dev
$ du -sh build/debug
59G     build/debug

$ time ./tools/toolchain/dbuild test/alternator/run 2>&1 | tee run.log
Scylla is: /home/kefu/dev/scylladb/build/dev/scylla.
Booting Scylla on 127.1.0.2 in /tmp/scylla-test-2...
Boot successful (1.0 seconds).
...
Alternator tests pass

real    0m46.172s
user    0m0.480s
sys     0m0.297s
```
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
please note, this change is marked as a draft for two reasons

- the seastar submodule is not bumped up yet
- the "debug" build of scylla has assertion failure like

```console
$ SCYLLA_HOME=$HOME/scylla build/dev/scylla --overprovisioned --developer-mode=yes --smp 4
Scylla version 5.3.0~dev-0.20230210.fc93edef556e with build-id eb879cb3a5eb1fabe3c4d09b73c94c956e554f43 starting ...
command used: "build/dev/scylla --overprovisioned --developer-mode=yes --smp 4"
parsed command line options: [overprovisioned, developer-mode: yes, smp, (positional) 4]
INFO  2023-02-10 18:45:58,266 seastar - Reactor backend: linux-aio
INFO  2023-02-10 18:45:58,292 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-10 18:45:58,292 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-10 18:45:58,292 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-10 18:45:58,292 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
INFO  2023-02-10 18:45:58,347 [shard 2] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-10 18:45:58,347 [shard 2] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-10 18:45:58,347 [shard 2] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-10 18:45:58,354 [shard 0] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-02-10 18:45:58,354 [shard 2] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-02-10 18:45:58,354 [shard 1] seastar - updated: blocked-reactor-notify-ms=1000000
INFO  2023-02-10 18:45:58,354 [shard 3] seastar - updated: blocked-reactor-notify-ms=1000000
scylla: seastar/include/seastar/core/future.hh:650: void seastar::future_state<seastar::internal::monostate>::set(A &&...) [T = seastar::internal::monostate, A = <>]: Assertion `_u.st == state::future' failed.
scylla: seastar/include/seastar/core/future.hh:650: void seastar::future_state<seastar::internal::monostate>::set(A &&...) [T = seastar::internal::monostate, A = <>]: Assertion `_u.st == state::future' failed.
scylla: seastar/include/seastar/core/future.hh:650: void seastar::future_state<seastar::internal::monostate>::set(A &&...) [T = seastar::internal::monostate, A = <>]: Assertion `_u.st == state::future' failed.
Aborting on shard 3.
Backtrace:
  0x28abfc47bd0c
  0x28abfc4a5032
  /lib64/libc.so.6+0x54d8f
  /lib64/libc.so.6+0xa154b
  /lib64/libc.so.6+0x54ce5
  /lib64/libc.so.6+0x287f2
  /lib64/libc.so.6+0x2871a
  /lib64/libc.so.6+0x4dc65
  0xeecea5
  0xeecacc
  0x28abfc489caf
  0x28abfc48ad77
  0x28abfc4a5522
  0x28abfc44303a
  /lib64/libc.so.6+0x9f801
  /lib64/libc.so.6+0x3f44f
Aborted (core dumped)
```

i am still looking into this failure. no clues so far.

**Comment by tchaikov** [comment]
should be fixed by https://github.com/scylladb/seastar/pull/1494

**Comment by avikivity** [comment]
There are plenty of thread_local in .hh, for example get_scheduling_group_specific_thread_local_data_ptr(). We need to fix them all up, or move to tls-model=global-dynamic (which will slow down tls in the main executable).

**Comment by tchaikov** [comment]
> There are plenty of thread_local in .hh, for example get_scheduling_group_specific_thread_local_data_ptr(). We need to fix them all up, or move to tls-model=global-dynamic (which will slow down tls in the main executable).

Avi, it seems i still have this failure after applying https://github.com/scylladb/seastar/pull/1496 .

**Comment by tchaikov** [comment]
@avikivity https://github.com/scylladb/seastar/pull/1497 is created to address this issue.

**Comment by tchaikov** [comment]
will bump Seastar, once https://github.com/scylladb/seastar/pull/1480 gets merged, and include it in this PR .

**Comment by tchaikov** [comment]
@avikivity hi Avi, should work now. could you please help review this change?

**Comment by avikivity** [comment]
Looks good. Did you test that rpm/deb install works? It's enough to check that /usr/bin/scylla --version works after installation.

**Comment by avikivity** [comment]
Also: please add before/after disk usage for build/dev and build/debug to the cover letter.

I guess the changes won't be dramatic, since we build debug mode tests with debug information off, but after this change we can build tests with debug information on.

**Comment by nyh** [comment]
> Also: please add before/after disk usage for build/dev and build/debug to the cover letter.

I'd also like to see some reassurance that the run speed of the dev executable wasn't dramatically increased (a small increase is acceptable, a large increase less so). I personally like to look at the boot time reported in `test/alternator/run` or the time to run the entire `test/alternator/run` test suite (don't worry, it's less than 30 seconds!), but if you have another favorite "benchmark", that's also fine.

**Comment by tchaikov** [comment]
@avikivity it's already tested by our CI, see https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4620/consoleText

```
[2023-02-27T10:40:39.215Z] + buildah run ubuntu-working-container bash -ec 'echo LANG=C.UTF-8 > /etc/default/locale'
[2023-02-27T10:40:39.947Z] + run bash -ec 'dpkg -i packages/*.deb'
[2023-02-27T10:40:39.947Z] + buildah run ubuntu-working-container bash -ec 'dpkg -i packages/*.deb'
[2023-02-27T10:40:39.947Z] Selecting previously unselected package scylla-conf.
[2023-02-27T10:40:39.947Z] (Reading database ... 12951 files and directories currently installed.)
[2023-02-27T10:40:39.947Z] Preparing to unpack .../scylla-conf_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:39.947Z] Unpacking scylla-conf (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:39.947Z] Selecting previously unselected package scylla-jmx.
[2023-02-27T10:40:39.947Z] Preparing to unpack .../scylla-jmx_5.3.0~dev-0.20230227.c9df23031769-1_all.deb ...
[2023-02-27T10:40:39.947Z] Unpacking scylla-jmx (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:40.620Z] Selecting previously unselected package scylla-kernel-conf.
[2023-02-27T10:40:40.620Z] Preparing to unpack .../scylla-kernel-conf_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:40.620Z] Unpacking scylla-kernel-conf (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:40.620Z] Selecting previously unselected package scylla-node-exporter.
[2023-02-27T10:40:40.620Z] Preparing to unpack .../scylla-node-exporter_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:40.620Z] Unpacking scylla-node-exporter (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:41.297Z] Selecting previously unselected package scylla-python3.
[2023-02-27T10:40:41.297Z] Preparing to unpack .../scylla-python3_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:41.297Z] Unpacking scylla-python3 (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:43.501Z] Selecting previously unselected package scylla-server.
[2023-02-27T10:40:43.501Z] Preparing to unpack .../scylla-server_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:43.501Z] Unpacking scylla-server (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:48.534Z] Selecting previously unselected package scylla-tools-core.
[2023-02-27T10:40:48.534Z] Preparing to unpack .../scylla-tools-core_5.3.0~dev-0.20230227.c9df23031769-1_all.deb ...
[2023-02-27T10:40:48.534Z] Unpacking scylla-tools-core (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.134Z] Selecting previously unselected package scylla-tools.
[2023-02-27T10:40:52.134Z] Preparing to unpack .../scylla-tools_5.3.0~dev-0.20230227.c9df23031769-1_all.deb ...
[2023-02-27T10:40:52.134Z] Unpacking scylla-tools (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.134Z] Selecting previously unselected package scylla.
[2023-02-27T10:40:52.134Z] Preparing to unpack .../scylla_5.3.0~dev-0.20230227.c9df23031769-1_amd64.deb ...
[2023-02-27T10:40:52.134Z] Unpacking scylla (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.134Z] Setting up scylla-conf (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.134Z] Setting up scylla-kernel-conf (5.3.0~dev-0.20230227.c9df23031769-1) ...
...
[2023-02-27T10:40:52.810Z] Setting up scylla-node-exporter (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla-python3 (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla-server (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla-tools-core (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla-tools (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla-jmx (5.3.0~dev-0.20230227.c9df23031769-1) ...
[2023-02-27T10:40:52.810Z] Setting up scylla (5.3.0~dev-0.20230227.c9df23031769-1) ...
...
[2023-02-27T12:02:34.922Z] gw0 I / gw1 I / gw2 I / gw3 I / gw4 I
[2023-02-27T12:02:34.922Z] 
[gw0] linux Python 3.11.1 cwd: /jenkins/workspace/releng/Scylla-CI/scylla-dtest
[2023-02-27T12:02:34.922Z] 
[gw1] linux Python 3.11.1 cwd: /jenkins/workspace/releng/Scylla-CI/scylla-dtest
[2023-02-27T12:02:34.922Z] 
[gw2] linux Python 3.11.1 cwd: /jenkins/workspace/releng/Scylla-CI/scylla-dtest
[2023-02-27T12:02:34.922Z] 
[gw3] linux Python 3.11.1 cwd: /jenkins/workspace/releng/Scylla-CI/scylla-dtest
[2023-02-27T12:02:34.922Z] 
[gw4] linux Python 3.11.1 cwd: /jenkins/workspace/releng/Scylla-CI/scylla-dtest
[2023-02-27T12:02:36.321Z] 
[gw0] Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[2023-02-27T12:02:36.321Z] 
[gw1] Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[2023-02-27T12:02:36.321Z] 
[gw2] Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[2023-02-27T12:02:36.321Z] 
[gw3] Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[2023-02-27T12:02:36.321Z] 
[gw4] Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[2023-02-27T12:02:57.026Z] gw0 [229] / gw1 [229] / gw2 [229] / gw3 [229] / gw4 [229]
[2023-02-27T12:02:57.026Z] 
[2023-02-27T12:02:57.026Z] scheduling tests via LoadScheduling
[2023-02-27T12:02:57.026Z] 
[2023-02-27T12:02:57.026Z] auth_test.py::TestAuth::test_permissions_caching 
[2023-02-27T12:02:57.026Z] listsnapshots_test.py::TestNodetoolListSnapshots::test_snapshot_for_several_kses 
[2023-02-27T12:02:57.026Z] limits_test.py::TestLimits::test_max_batch_size 
[2023-02-27T12:02:57.026Z] secondary_indexes_test.py::TestLocalIndexes::test_stop_node_during_local_index_build 
[2023-02-27T12:02:58.428Z] auth_test.py::TestAuth::test_grant_revoke_auth 
[2023-02-27T12:02:58.428Z] [gw4] PASSED auth_test.py::TestAuth::test_grant_revoke_auth 
[2023-02-27T12:03:01.032Z] [gw1] PASSED limits_test.py::TestLimits::test_max_batch_size 
[2023-02-27T12:03:01.707Z] [gw3] PASSED auth_test.py::TestAuth::test_permissions_caching 
[2023-02-27T12:03:01.707Z] simple_driver_test.py::TestSimpleDriver::test_simple_compound_primary_key_create_insert_select[SMP=2] 
[2023-02-27T12:03:02.384Z] simple_driver_test.py::TestSimpleDriver::test_simple_composite_partition_key_create_insert_select[SMP=2] 
[2023-02-27T12:03:03.781Z] [gw0] PASSED listsnapshots_test.py::TestNodetoolListSnapshots::test_snapshot_for_several_kses 
[2023-02-27T12:03:04.456Z] simple_driver_test.py::TestSimpleDriver::test_simple_compound_primary_key_create_insert_select[SMP=1] 
[2023-02-27T12:03:04.456Z] [gw4] PASSED simple_driver_test.py::TestSimpleDriver::test_simple_compound_primary_key_create_insert_select[SMP=2] 
[2023-02-27T12:03:05.129Z] [gw1] PASSED simple_driver_test.py::TestSimpleDriver::test_simple_composite_partition_key_create_insert_select[SMP=2] 
[2023-02-27T12:03:06.523Z] auth_test.py::TestAuth::test_all_authorization_operations 
[2023-02-27T12:03:07.198Z] [gw3] PASSED simple_driver_test.py::TestSimpleDriver::test_simple_compound_primary_key_create_insert_select[SMP=1] 
[2023-02-27T12:03:07.874Z] migration_test.py::TestMigrationUpgradeSSTables::test_migrate_sstable_with_counter[2_1_x] 
[2023-02-27T12:03:07.874Z] simple_driver_test.py::TestSimpleDriver::test_simple_create_insert_select[SMP=2] 
[2023-02-27T12:03:09.276Z] [gw0] PASSED auth_test.py::TestAuth::test_all_authorization_operations 
[2023-02-27T12:03:11.467Z] migration_test.py::TestMigrationUpgradeSSTables::test_migrate_sstable_with_counter[2_2_x] 
[2023-02-27T12:03:17.680Z] simple_driver_test.py::TestSimpleDriver::test_simple_create_insert_select[SMP=1] 
[2023-02-27T12:03:19.080Z] [gw4] PASSED migration_test.py::TestMigrationUpgradeSSTables::test_migrate_sstable_with_counter[2_1_x] 
[2023-02-27T12:03:20.482Z] [gw1] PASSED simple_driver_test.py::TestSimpleDriver::test_simple_create_insert_select[SMP=2] 
[2023-02-27T12:03:21.158Z] [gw3] PASSED migration_test.py::TestMigrationUpgradeSSTables::test_migrate_sstable_with_counter[2_2_x] 
[2023-02-27T12:03:22.559Z] migration_test.py::TestMigration::test_migrate_sstable_with_counter[3_0_mc] 
```

**Comment by avikivity** [comment]
Ah, didn't know that.

**Comment by tchaikov** [comment]
> Also: please add before/after disk usage for build/dev and build/debug to the cover letter.
> 
> I guess the changes won't be dramatic, since we build debug mode tests with debug information off, but after this change we can build tests with debug information on.

done.

**Comment by tchaikov** [comment]
> > Also: please add before/after disk usage for build/dev and build/debug to the cover letter.
> 
> I'd also like to see some reassurance that the run speed of the dev executable wasn't dramatically increased (a small increase is acceptable, a large increase less so). I personally like to look at the boot time reported in `test/alternator/run` or the time to run the entire `test/alternator/run` test suite (don't worry, it's less than 30 seconds!), but if you have another favorite "benchmark", that's also fine.

done.

**Comment by tchaikov** [comment]
@avikivity @nyh mind taking another look?

**Comment by avikivity** [comment]
My request for the disk usage comparison was nonsensical, since we don't yet have libscyllacore{.a,.so}. But even so we see a significant improvement.

With a libscyllacore we'd see much better results.

**Comment by avikivity** [comment]
Perhaps it can be improved by building libseastar.so with -ftls-model=local-dynamic, but I'm not sure what the implications are.

**Pull request closed without merging**
