### PR TITLE
api: task_manager: fix indentation

### PR DESCRIPTION
**Pull request by Deexie**

### CODE REVIEW

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
Re-kicked CI.

**Comment by denesb** [comment]
Conflicts with https://github.com/scylladb/scylladb/pull/15172, please rebase once https://github.com/scylladb/scylladb/pull/15172 is promoted.

**Comment by Deexie** [comment]
- rebase

**Comment by Deexie** [comment]
- rebase

**Pull request closed without merging**
