### PR TITLE
Update tools/java submodule

### PR DESCRIPTION
**Pull request by denesb**
* tools/java b7ebfd38...43427dfa (1):
  > treewide: update "guava" package

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]
Thanks @denesb

**Comment by yaronkaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5332/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/6749/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5332/)
> 
> #### Failed Tests (1/23491):
> * [test_connectivity_with_cassandra_stress](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5332/testReport/junit/cloud_bundle_test/TestScyllaCloudBundle/Tests___dtest___test_connectivity_with_cassandra_stress) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_connectivity_with_cassandra_stress)
> 
> #### Build Details:
> * Duration: 2 hr 17 min
> * Builder: spider8.cloudius-systems.com

dtest got spot termination, re-running CI

**Comment by yaronkaikov** [comment]
It seems that this change is failing dtest, i will check it

**Comment by yaronkaikov** [comment]
Unfortunately, this is breaking dtest, so I submitted https://github.com/scylladb/java-driver/pull/266 to fix it. But @avelanarius is on vacation, so it will have to wait

**Comment by mykaul** [comment]
> Unfortunately, this is breaking dtest, so I submitted [scylladb/java-driver#266](https://github.com/scylladb/java-driver/pull/266) to fix it. But @avelanarius is on vacation, so it will have to wait

@yaronkaikov - the bug is in the Java driver.
See https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/ScyllaCloudDatacenter.java#L77
vs. https://github.com/scylladb/java-driver/blob/085dd34ef46b1de5111629bdccfe4056c4355676/driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java#L198

CC @Bouncheck

**Comment by yaronkaikov** [comment]
Yes I know , this is why I have submitted a fix over there 😄

**Comment by tchaikov** [comment]
https://github.com/scylladb/java-driver/pull/267 has been merged, retriggering the build and test.

**Comment by mykaul** [comment]
Failure is fixed via https://github.com/scylladb/java-driver/pull/267 - not sure why we still see it.

**Comment by avelanarius** [comment]
Yes, I need to release the driver first for this patch to actually be used.

**Comment by mykaul** [comment]
> Yes, I need to release the driver first for this patch to actually be used.

And update the driver (https://github.com/scylladb/scylla-tools-java/issues/343 ) I reckon.

**Comment by nyh** [comment]
Merged a new tools/java submodule update, commit 61395a3658acbe786928090913b047373cea21fa
(I hope I won't regret that I didn't try CI myself, but @yaronkaikov things the new fix will fix the build).
When that commit promotes to master, this pull request should be closed.

**Comment by yaronkaikov** [comment]
> Merged a new tools/java submodule update, commit [61395a3](https://github.com/scylladb/scylladb/commit/61395a3658acbe786928090913b047373cea21fa) (I hope I won't regret that I didn't try CI myself, but @yaronkaikov things the new fix will fix the build). When that commit promotes to master, this pull request should be closed.

prompted

**Pull request closed without merging**
