### PR TITLE
common/scripts/scylla_util.py: use glob instead of

### LINKED ISSUE #8778: use glob instead of os.join.path for figuring out non root nvmes
address comments from https://github.com/scylladb/scylla/pull/8444

### PR DESCRIPTION
**Pull request by tarzanek**
os.join.path for figuring out non root nvmes

fixes #8778

### CODE REVIEW

**Comment by tarzanek** [comment]
@penberg re your glob review comment, tested and verified on GKE (negative test), Azure VM and GCP VM (positive tests)

**Comment by psarna** [comment]
It looks like this pull request contains tons of unrelated commits due to next being repushed. Could you rebase on top of master and make it the target branch? That way there's no risk of such things happening if commits get dequeued from next

**Comment by slivne** [comment]
@tarzanek - are you cloding this PR and sending a new one

**Comment by tarzanek** [comment]
moved to https://github.com/scylladb/scylla-machine-image/blob/master/common/scylla_cloud_io_setup , closing

**Pull request closed without merging**
