### PR TITLE
cql: Add support for IN clause on indexed column without filtering

### LINKED ISSUE #21430: Allow IN clause on indexed column, without filtering
Cassandra only allows IN restrictions on primary key columns. With filtering allowed (ALLOW FILTERING), this limitation makes little sense, so Scylla lifted this limitation and we can use IN on any column - but only if ALLOW FILTERING is specified.

But when we have an IN restriction on an **indexed** column, it should be possible to support query efficiently _without_ ALLOW FILTERING, in exactly the same way we implement IN on a partition key. This is the feature requested in this issue.

This issue is marked "enhancement" because this feature doesn't exist in Cassandra either. The Cassandra issue requesting this feature, https://issues.apache.org/jira/browse/CASSANDRA-4386 was closed 8 years ago as WONTFIX - but the closing comments suggests this feature may have been implemented in SASI (I didn't test).

We have xfailing cql-pytest for this feature:
* `test_secondary_index.py`::`test_index_in_restriction`
* `test/cql-pytest/test_allow_filtering.py`::`test_allow_filtering_pk_in`

If we continue to delay this feature for a long time, we should consider more promptly addressing issue https://github.com/scylladb/scylladb/issues/12908. I.e., we should enable the `scrict_allow_filtering` configuration option by default. When `scrict_allow_filtering` is off (unfortunately, this is the current default), users are actually allowed to do IN on a secondary index, but it is implemented inefficiently - as filtering, but doesn't require "ALLOW FILTERING".

See the history of this issue in  https://github.com/scylladb/scylladb/issues/5545 and https://github.com/scylladb/scylladb/issues/13533.

### PR DESCRIPTION
**Pull request by Jager227**
Fixes #21430

### CODE REVIEW

**Comment by nyh** [comment]
There's another test for this issue which I think I forgot to mention on the issue (sorry, I updated the ist now) - `test_allow_filtering.py`::`test_allow_filtering.py`. Can you please verify if it gets fixed too, and if it does, remove the "xfail" from it too? Thanks.

**Comment by nyh** [comment]
> #### 🔴 CI State: FAILURE
> 
> ❌ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13337/)
> #### Build Details:
> 
>     * Duration: 12 min
> 
>     * Builder: spider8.cloudius-systems.com

The compilation failed:
```
2024-11-25T08:20:43.479Z] FAILED: build/debug/cql3/restrictions/statement_restrictions.o 
[2024-11-25T08:20:43.480Z] clang++ -MD -MT build/debug/cql3/restrictions/statement_restrictions.o -MF build/debug/cql3/restrictions/statement_restrictions.o.d -std=gnu++23 -I/jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include -I/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/gen/include -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEBUG_PROMISE -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -I/usr/include/p11-kit-1 -DWITH_GZFILEOP -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -Og -DSCYLLA_BUILD_MODE=debug -g -gz -Xclang -fexperimental-assignment-tracking=disabled -iquote. -iquote build/debug/gen -std=gnu++23  -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -march=westmere -DBOOST_ALL_DYN_LINK    -fvisibility=hidden -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-enum-constexpr-conversion -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/debug/cql3/restrictions/statement_restrictions.o cql3/restrictions/statement_restrictions.cc
[2024-11-25T08:20:43.488Z] In file included from cql3/restrictions/statement_restrictions.cc:10:
[2024-11-25T08:20:43.488Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/algorithm:60:
[2024-11-25T08:20:43.489Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_algobase.h:64:
[2024-11-25T08:20:43.491Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/stl_pair.h:60:
[2024-11-25T08:20:43.492Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/type_traits:3155:5: error: no type named 'type' in 'std::invoke_result<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, interval<managed_bytes> &>'
[2024-11-25T08:20:43.492Z]  3155 |     using invoke_result_t = typename invoke_result<_Fn, _Args...>::type;
[2024-11-25T08:20:43.493Z]       |     ^~~~~
[2024-11-25T08:20:43.493Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1132:2: note: in instantiation of template type alias 'invoke_result_t' requested here
[2024-11-25T08:20:43.493Z]  1132 |         invoke_result_t<_Visitor, __get_t<_Idxs, _Variant>>...
[2024-11-25T08:20:43.493Z]       |         ^
[2024-11-25T08:20:43.494Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1872:6: note: in instantiation of function template specialization 'std::__detail::__variant::__check_visitor_results<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &, 0UL, 1UL>' requested here
[2024-11-25T08:20:43.497Z]  1872 |             __check_visitor_results<_Visitor, _Vp>(
[2024-11-25T08:20:43.497Z]       |             ^
[2024-11-25T08:20:43.498Z] cql3/restrictions/statement_restrictions.cc:789:17: note: in instantiation of function template specialization 'std::visit<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &>' requested here
[2024-11-25T08:20:43.499Z]   789 |     return std::visit(overloaded_functor {
[2024-11-25T08:20:43.500Z]       |                 ^
[2024-11-25T08:20:43.500Z] In file included from cql3/restrictions/statement_restrictions.cc:11:
[2024-11-25T08:20:43.500Z] In file included from /usr/include/boost/range/algorithm.hpp:30:
[2024-11-25T08:20:43.500Z] In file included from /usr/include/boost/range/iterator_range.hpp:14:
[2024-11-25T08:20:43.501Z] In file included from /usr/include/boost/range/iterator_range_io.hpp:32:
[2024-11-25T08:20:43.503Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/ostream:43:
[2024-11-25T08:20:43.503Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/format:52:
[2024-11-25T08:20:43.504Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1871:44: error: constexpr variable '__visit_rettypes_match' must be initialized by a constant expression
[2024-11-25T08:20:43.505Z]  1871 |           constexpr bool __visit_rettypes_match = __detail::__variant::
[2024-11-25T08:20:43.505Z]       |                                                   ^~~~~~~~~~~~~~~~~~~~~
[2024-11-25T08:20:43.506Z]  1872 |             __check_visitor_results<_Visitor, _Vp>(
[2024-11-25T08:20:43.506Z]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2024-11-25T08:20:43.507Z]  1873 |               make_index_sequence<variant_size_v<remove_reference_t<_Vp>>>());
[2024-11-25T08:20:43.508Z]       |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2024-11-25T08:20:43.508Z] cql3/restrictions/statement_restrictions.cc:789:17: note: in instantiation of function template specialization 'std::visit<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &>' requested here
[2024-11-25T08:20:43.509Z]   789 |     return std::visit(overloaded_functor {
[2024-11-25T08:20:43.509Z]       |                 ^
[2024-11-25T08:20:43.509Z] In file included from cql3/restrictions/statement_restrictions.cc:11:
[2024-11-25T08:20:43.509Z] In file included from /usr/include/boost/range/algorithm.hpp:30:
[2024-11-25T08:20:43.509Z] In file included from /usr/include/boost/range/iterator_range.hpp:14:
[2024-11-25T08:20:43.510Z] In file included from /usr/include/boost/range/iterator_range_io.hpp:32:
[2024-11-25T08:20:43.510Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/ostream:43:
[2024-11-25T08:20:43.511Z] In file included from /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/format:52:
[2024-11-25T08:20:43.512Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1874:18: error: constexpr if condition is not a constant expression
[2024-11-25T08:20:43.513Z]  1874 |           if constexpr (!__visit_rettypes_match)
[2024-11-25T08:20:43.513Z]       |                         ^~~~~~~~~~~~~~~~~~~~~~~
[2024-11-25T08:20:43.515Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1874:19: note: initializer of '__visit_rettypes_match' is not a constant expression
[2024-11-25T08:20:43.516Z]  1874 |           if constexpr (!__visit_rettypes_match)
[2024-11-25T08:20:43.516Z]       |                          ^
[2024-11-25T08:20:43.517Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1871:19: note: declared here
[2024-11-25T08:20:43.517Z]  1871 |           constexpr bool __visit_rettypes_match = __detail::__variant::
[2024-11-25T08:20:43.518Z]       |                          ^
[2024-11-25T08:20:43.518Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1876:22: error: static assertion expression is not an integral constant expression
[2024-11-25T08:20:43.519Z]  1876 |               static_assert(__visit_rettypes_match,
[2024-11-25T08:20:43.520Z]       |                             ^~~~~~~~~~~~~~~~~~~~~~
[2024-11-25T08:20:43.520Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1876:22: note: initializer of '__visit_rettypes_match' is not a constant expression
[2024-11-25T08:20:43.522Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1871:19: note: declared here
[2024-11-25T08:20:43.523Z]  1871 |           constexpr bool __visit_rettypes_match = __detail::__variant::
[2024-11-25T08:20:43.523Z]       |                          ^
[2024-11-25T08:20:43.524Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1879:8: error: non-void constexpr function 'visit<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &>' should return a value
[2024-11-25T08:20:43.525Z]  1879 |               return;
[2024-11-25T08:20:43.525Z]       |               ^
[2024-11-25T08:20:43.525Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1060:11: error: no matching function for call to '__invoke'
[2024-11-25T08:20:43.525Z]  1060 |           return std::__invoke(std::forward<_Visitor>(__visitor),
[2024-11-25T08:20:43.525Z]       |                  ^~~~~~~~~~~~~
[2024-11-25T08:20:43.526Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1820:5: note: in instantiation of member function 'std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<std::vector<std::optional<seastar::basic_sstring<signed char, unsigned int, 31, false>>>> (*)(overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)> &&, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &)>, std::integer_sequence<unsigned long, 1>>::__visit_invoke' requested here
[2024-11-25T08:20:43.528Z]  1820 |                   _GLIBCXX_VISIT_CASE(1)
[2024-11-25T08:20:43.528Z]       |                   ^
[2024-11-25T08:20:43.528Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1811:4: note: expanded from macro '_GLIBCXX_VISIT_CASE'
[2024-11-25T08:20:43.528Z]  1811 |           __visit_invoke(std::forward<_Visitor>(__visitor),             \
[2024-11-25T08:20:43.528Z]       |           ^
[2024-11-25T08:20:43.528Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/variant:1882:18: note: in instantiation of function template specialization 'std::__do_visit<std::__detail::__variant::__deduce_visit_result<std::vector<std::optional<seastar::basic_sstring<signed char, unsigned int, 31, false>>>>, overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &>' requested here
[2024-11-25T08:20:43.529Z]  1882 |             return std::__do_visit<_Tag>(
[2024-11-25T08:20:43.529Z]       |                         ^
[2024-11-25T08:20:43.529Z] cql3/restrictions/statement_restrictions.cc:789:17: note: in instantiation of function template specialization 'std::visit<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, std::variant<std::vector<managed_bytes>, interval<managed_bytes>> &>' requested here
[2024-11-25T08:20:43.531Z]   789 |     return std::visit(overloaded_functor {
[2024-11-25T08:20:43.531Z]       |                 ^
[2024-11-25T08:20:43.531Z] /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:90:5: note: candidate template ignored: substitution failure [with _Callable = overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, _Args = <interval<managed_bytes> &>]: no type named 'type' in 'std::__invoke_result<overloaded_functor<(lambda at cql3/restrictions/statement_restrictions.cc:790:9)>, interval<managed_bytes> &>'
[2024-11-25T08:20:43.535Z]    89 |     constexpr typename __invoke_result<_Callable, _Args...>::type
[2024-11-25T08:20:43.535Z]       |                                                              ~~~~
[2024-11-25T08:20:43.535Z]    90 |     __invoke(_Callable&& __fn, _Args&&... __args)
[2024-11-25T08:20:43.536Z]       |     ^
[2024-11-25T08:20:43.536Z] 6 errors generated.
```

**Comment by denesb** [comment]
Please don't merge master into your branch, rebase your branch onto latest master instead.

**Comment by Jager227** [comment]
> Please don't merge master into your branch, rebase your branch onto latest master instead.

Accidentally merged, when tried to sync fork, going to fix this in a moment

**Comment by Jager227** [comment]
It seems that recent push has stuck for several hours, i think i will re-create PR.

**Pull request closed without merging**
