### PR TITLE
doc: add the upgrade guide from 5.0 to 2022.1 on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by annastuchlik**
Ubuntu 22.04 is supported by both ScyllaDB Open Source 5.0 and Enterprise 2022.1.

### CODE REVIEW

**Comment by annastuchlik** [comment]
I've converted this PR to draft so that it is not merged.
@tzach This PR shows that the upgrade guides for all supported Ubuntu versions are identical. I think we should merge the guides to have one guide for Ubuntu. The guide should say "See [OS Support by Platform and Version](https://docs.scylladb.com/stable/getting-started/os-support.html) for supported Ubuntu versions".

In this way:
- We will be able to maintain the list of supported OS versions only in one place - on the OS Support page.
- We will limit the number of, in fact, redundant pages in the Upgrade section.
- The search results will be less polluted with multiple irrelevant results on various upgrade pages.
- This will be the first step to unifying the upgrade guides and getting rid of OS version numbers for all platforms.

**Comment by tzach** [comment]
Make sense
The advantage of an upgrade guide per Ubuntu release is each guide can be slightly different.
It was useful when Ubuntu 16.04 (pre system) was different than Ubuntu 18.0 (post systemd)
This is not the case any more.

**Comment by annastuchlik** [comment]
@tzach I've made the change.
This PR only covers Ubuntu and the 5.0 to 2022.1 upgrade guide, but I'll send more PRs to do the same for Debian, as well as for other upgrade guides (if possible).

**Comment by tzach** [comment]
We should list the supported Debian / Ubuntu OS one can upgrade to 
Ubuntu 18.04, 20.04, 22.04 
Debian 10, 11

**Comment by annastuchlik** [comment]
> We should list the supported Debian / Ubuntu OS one can upgrade to Ubuntu 18.04, 20.04, 22.04 Debian 10, 11

@tzach I don't like this solution because it is error-prone. It's best when support for platforms, environments, etc. is maintained on one page, which can be referred from other places.
But I can make that change and see how good we are at being consistent with versions across different upgrade guides :)

**Comment by tzach** [comment]
> It's best when support for platforms, environments, etc. is maintained on one page, which can be referred from other places.

Make sense, let link to the OS support page

**Comment by annastuchlik** [comment]
@tzach I've rebased and this PR is ready for final review.

**Review by tzach — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to 5.1

Done.

**Pull request merged**
