### PR TITLE
[Backport 5.2] repair: streaming: handle no_such_column_family from remote node

### PR DESCRIPTION
**Pull request by Deexie**
RPC calls lose information about the type of returned exception.
Thus, if a table is dropped on receiver node, but it still exists
on a sender node and sender node streams the table's data, then
the whole operation fails.

To prevent that, add a method which synchronizes schema and then
checks, if the exception was caused by table drop. If so,
the exception is swallowed.

Use the method in streaming and repair to continue them when
the table is dropped in the meantime.

Fixes: https://github.com/scylladb/scylladb/issues/17028.
Fixes: https://github.com/scylladb/scylladb/issues/15370.
Fixes: https://github.com/scylladb/scylladb/issues/15598.

### CODE REVIEW

**Comment by Deexie** [comment]
@kbr-scylla please review f9488939d54b83c66d1197a96d37eae1c8805de5, I needed to rewrite it as 5.2 uses different mechanisms

**Comment by kbr-scylla** [comment]
> @kbr-scylla please review https://github.com/scylladb/scylladb/commit/f9488939d54b83c66d1197a96d37eae1c8805de5, I needed to rewrite it as 5.2 uses different mechanisms

This particular commit LGTM but question --- what do we do for non-Raft mode? It seems that the PR only addresses Raft mode; understandable for 6.0, where Raft is mandatory, but is it enough for 5.2? I guess it's enough if we don't consider the issue critical and the main motivation is to unflake tests.

**Comment by Deexie** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-5.2/job/scylla-ci/98/
> 
> Build failed. @Deexie please check.

Looks like https://github.com/scylladb/scylladb/issues/14042. Re-kicking

**Comment by denesb** [comment]
> > @kbr-scylla please review [f948893](https://github.com/scylladb/scylladb/commit/f9488939d54b83c66d1197a96d37eae1c8805de5), I needed to rewrite it as 5.2 uses different mechanisms
> 
> This particular commit LGTM but question --- what do we do for non-Raft mode? It seems that the PR only addresses Raft mode; understandable for 6.0, where Raft is mandatory, but is it enough for 5.2? I guess it's enough if we don't consider the issue critical and the main motivation is to unflake tests.

Yes, that is the main motivation, although correctly handling this in production is also important.

**Comment by Deexie** [comment]
- use seastar namespace

**Comment by denesb** [comment]
Queued.

**Pull request merged**
