### PR TITLE
counters: move fmt::formatter<counter_{shard,cell}_view>::format() to…

### PR DESCRIPTION
**Pull request by tchaikov**
… .cc

to reduce the size of header file, in hope to speed the compilation. let's implement the implementation of format() function into .cc file.

Refs #13245

### CODE REVIEW

**Review by denesb — APPROVED** [review]
Should we do this with other formatters too?

**Comment by tchaikov** [comment]
> Should we do this with other formatters too?

yes, that's the plan. see https://github.com/scylladb/scylladb/pull/13967#discussion_r1200022472

**Comment by tchaikov** [comment]
i will do this in larger batch. the reason this change was sent out separately was that it was the side product of resolving the conflicts between #13967 to the latest master HEAD .

**Comment by tchaikov** [comment]
just realized that `fmt::to_string()` uses another context type: `fmt::basic_format_context<std::back_insert_iterator<std::string>>`, so if we want to format the type in question using `fmt::to_string()`, we would either need to keep the `format()` function in the header file, or, we can explicit instantiate it in .cc file. but unfortunately, the `auto` return type does not work in that case.. neither clang nor gcc accepts the explicitly instantiated template function with the `auto` return type.

**Pull request closed without merging**
