### PR TITLE
locator: util: add a workaround for a clang 15 coroutine miscompile

### LINKED ISSUE #14412: ARM only (compiler issue): cql-pytest.test_describe killed a node with stack smashing (master, release mode, aarch64)
https://jenkins.scylladb.com/job/scylla-master/job/build/1515

Scylla tail logs:
```
INFO  2023-06-27 11:52:50,314 [shard 0] schema_tables - Creating cql_test_1687866770276.cql_test_1687866770317 id=243b3080-14e1-11ee-88d2-bfd957b62ce4 version=9419773b-1880-3a0a-a4f8-a1990b1c875b
INFO  2023-06-27 11:52:50,323 [shard 0] schema_tables - Schema version changed to 9d84b17b-1e0a-3c51-8abb-d7ed9b6f793b
INFO  2023-06-27 11:52:50,340 [shard 0] migration_manager - Drop table 'cql_test_1687866770276.cql_test_1687866770317'
INFO  2023-06-27 11:52:50,342 [shard 0] schema_tables - Dropping cql_test_1687866770276.cql_test_1687866770317 id=243b3080-14e1-11ee-88d2-bfd957b62ce4 version=9419773b-1880-3a0a-a4f8-a1990b1c875b
INFO  2023-06-27 11:52:50,342 [shard 0] database - Dropping cql_test_1687866770276.cql_test_1687866770317 without snapshot
INFO  2023-06-27 11:52:50,342 [shard 0] database - Truncating cql_test_1687866770276.cql_test_1687866770317 without snapshot
INFO  2023-06-27 11:52:50,345 [shard 1] compaction - [Compact system.truncated 24403990-14e1-11ee-8858-bfda57b62ce4] Compacting [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_21aw022n71qbfgwr1g-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x00_2zt6922n71qbfgwr1g-big-Data.db:level=0:origin=compaction]
INFO  2023-06-27 11:52:50,345 [shard 0] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table cql_test_1687866770276.cql_test_1687866770317 compaction_group=0/1 due to table removal
INFO  2023-06-27 11:52:50,346 [shard 1] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table cql_test_1687866770276.cql_test_1687866770317 compaction_group=0/1 due to table removal
INFO  2023-06-27 11:52:50,353 [shard 1] compaction - [Compact system.truncated 24403990-14e1-11ee-8858-bfda57b62ce4] Compacted 2 sstables to [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_225r422n71qbfgwr1g-big-Data.db:level=0]. 109kB to 104kB (~95% of original) in 7ms = 14MB/s. ~384 total partitions merged to 151.
INFO  2023-06-27 11:52:50,360 [shard 0] schema_tables - Schema version changed to 5c8b2acd-36f9-30e2-b243-4247d67aadf2
INFO  2023-06-27 11:52:50,365 [shard 0] migration_manager - Drop table 'cql_test_1687866769228.cql_test_1687866769274'
INFO  2023-06-27 11:52:50,367 [shard 0] schema_tables - Dropping cql_test_1687866769228.cql_test_1687866769274 id=24384a50-14e1-11ee-88d2-bfd957b62ce4 version=962694f2-0c12-339e-8e64-c8969b5194c5
INFO  2023-06-27 11:52:50,367 [shard 0] database - Dropping cql_test_1687866769228.cql_test_1687866769274 without snapshot
INFO  2023-06-27 11:52:50,368 [shard 0] database - Truncating cql_test_1687866769228.cql_test_1687866769274 without snapshot
INFO  2023-06-27 11:52:50,373 [shard 0] compaction - [Compact system.truncated 24447f50-14e1-11ee-88d2-bfd957b62ce4] Compacting [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_26vi822wl683eaxbz8-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_1g30122wl683eaxbz8-big-Data.db:level=0:origin=compaction]
INFO  2023-06-27 11:52:50,375 [shard 0] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table cql_test_1687866769228.cql_test_1687866769274 compaction_group=0/1 due to table removal
INFO  2023-06-27 11:52:50,376 [shard 1] compaction_manager - Stopping 1 tasks for 0 ongoing compactions for table cql_test_1687866769228.cql_test_1687866769274 compaction_group=0/1 due to table removal
INFO  2023-06-27 11:52:50,390 [shard 0] schema_tables - Schema version changed to cb56a0f7-f258-3a28-b8c1-641b8a03c1ad
INFO  2023-06-27 11:52:50,392 [shard 0] compaction - [Compact system.truncated 24447f50-14e1-11ee-88d2-bfd957b62ce4] Compacted 2 sstables to [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_285sw22wl683eaxbz8-big-Data.db:level=0]. 108kB to 103kB (~94% of original) in 13ms = 7MB/s. ~384 total partitions merged to 142.
INFO  2023-06-27 11:52:50,392 [shard 0] compaction - [Compact system.truncated 24476580-14e1-11ee-88d2-bfd957b62ce4] Compacting [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_2738022wl683eaxbz8-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_285sw22wl683eaxbz8-big-Data.db:level=0:origin=compaction]
INFO  2023-06-27 11:52:50,397 [shard 0] compaction - [Compact system.truncated 24476580-14e1-11ee-88d2-bfd957b62ce4] Compacted 2 sstables to [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/me-3g76_0x02_2c0ox22wl683eaxbz8-big-Data.db:level=0]. 108kB to 103kB (~94% of original) in 4ms = 25MB/s. ~384 total partitions merged to 142.
INFO  2023-06-27 11:52:50,398 [shard 0] compaction - [Compact system_schema.tables 24484fe0-14e1-11ee-88d2-bfd957b62ce4] Compacting [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3g76_0x02_2738122wl683eaxbz8-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3g76_0wzx_35li922wl683eaxbz8-big-Data.db:level=0:origin=compaction]
INFO  2023-06-27 11:52:50,400 [shard 0] migration_manager - Drop Keyspace 'cql_test_1687866770276'
INFO  2023-06-27 11:52:50,401 [shard 0] schema_tables - Dropping keyspace cql_test_1687866770276
INFO  2023-06-27 11:52:50,409 [shard 0] schema_tables - Schema version changed to bf69a67f-2500-3e02-8c9c-258db299a0ab
INFO  2023-06-27 11:52:50,411 [shard 0] compaction - [Compact system_schema.tables 24484fe0-14e1-11ee-88d2-bfd957b62ce4] Compacted 2 sstables to [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system_schema/tables-afddfb9dbc1e30688056eed6c302ba09/me-3g76_0x02_2dazl22wl683eaxbz8-big-Data.db:level=0]. 23kB to 16kB (~69% of original) in 4ms = 4MB/s. ~256 total partitions merged to 32.
INFO  2023-06-27 11:52:50,411 [shard 0] compaction - [Compact system.compaction_history 244a4bb0-14e1-11ee-88d2-bfd957b62ce4] Compacting [/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/me-3g76_0x02_27axs22wl683eaxbz8-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/scylla-152/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/me-3g76_0x01_53gxs22wl683eaxbz8-big-Data.db:level=0:origin=compaction]
*** stack smashing detected ***: terminated
------ Ending test cql-pytest.test_describe.1 ------
```

Test logs:
```
=== TEST.PY STARTING TEST cql-pytest.test_describe.1 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/build/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
pytest --host=127.176.42.14 -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/jenkins/workspace/scylla-master/build/scylla/testlog/aarch64/release/xml/cql-pytest.test_describe.1.xunit.xml test/cql-pytest/test_describe.py
=== TEST.PY TEST cql-pytest.test_describe.1 OUTPUT ===
Driver name Scylla Python Driver, version 3.26.1
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.1.3, pluggy-1.0.0
rootdir: /jenkins/workspace/scylla-master/build/scylla/test/cql-pytest, configfile: pytest.ini
plugins: asyncio-0.19.0
asyncio: mode=Mode.STRICT
collected 26 items

test/cql-pytest/test_describe.py .....Using seed 1687866769.5260117
.Using seed 1687866769.5862942
.Using seed 1687866769.6423957
.Using seed 1687866769.7636583
.Using seed 1687866769.8803518
.Using seed 1687866769.9343603
.Using seed 1687866769.9932933
..Using seed 1687866770.1687355
.Using seed 1687866770.2756462
.F
! _pytest.outcomes.Exit: Scylla appears to have crashed in test test_describe.py::test_desc_cluster !
Traceback (most recent call last):
```

### PR DESCRIPTION
**Pull request by michoecho**
llvm/llvm-project#51843 causes clang-15 to miscompile some coroutines. We hit it with describe_ring() on ARM.

The fmt::to_string() call inside the coroutine triggers the bug. The workaround is to move the call out of the coroutine.

Fixes #14412

### CODE REVIEW

**Comment by avikivity** [comment]
Is this relevant after the switch to clang 16?

**Comment by michoecho** [comment]
I didn't actually compile this workaround on ARM, but I think it should be effective based on my investigation of the bug..

We have already upgraded to clang-16, so this workaround is not needed in master, but we might want it to backport it to older releases.

**Comment by michoecho** [comment]
Although now I see that the `fmt` call was only added in the 5.3 cycle. So it's quite likely that existing releases aren't affected.

**Comment by tchaikov** [comment]
> Although now I see that the `fmt` call was only added in the 5.3 cycle. So it's quite likely that existing releases aren't affected.

how about checking the clang version in the build scripts? so they error out at seeing clang 15 or older ?

**Comment by michoecho** [comment]
I'll close this because I've checked that existing releases aren't affected by the bug. (At least not in the same way).

> how about checking the clang version in the build scripts? so they error out at seeing clang 15 or older ?

I think we aren't planning to update the compiler for existing versions.

**Pull request closed without merging**
