### PR TITLE
Upgrade node-exporter to 1.8.1

### PR DESCRIPTION
**Pull request by mykaul**
Fixes: https://github.com/scylladb/scylladb/issues/18493

Should be backported to active branches.

Probably need a new toolchain.

### CODE REVIEW

**Comment by amnonh** [comment]
It looks good, but the build failed during the promoter run, so we better be sure it's unrelated

**Comment by mykaul** [comment]
> It looks good, but the build failed during the promoter run, so we better be sure it's unrelated

IIRC, it fails as the toolchain is not updated with the binaries yet. It happens on every such update :-/
```
00:05:50.255  [295/3246] tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.8.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.8.1.linux-amd64 build/node_exporter
00:05:50.255  FAILED: build/node_exporter/node_exporter 
00:05:50.255  tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.8.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.8.1.linux-amd64 build/node_exporter
00:05:50.255  tar: /opt/scylladb/dependencies/node_exporter-1.8.1.linux-amd64.tar.gz: Cannot open: No such file or directory
```

**Comment by mykaul** [comment]
@yaronkaikov - how can I easily build the toolchain with it?

**Comment by yaronkaikov** [comment]
@mykaul today it's a manual process, since you need to build it also on `aarch64` and then create a manifest so it will be multi-arch, 

I will set it for you

**Comment by yaronkaikov** [comment]
> @mykaul today it's a manual process, since you need to build it also on `aarch64` and then create a manifest so it will be multi-arch,
> 
> I will set it for you

please change `tools/toolchain/image` to `docker.io/scylladb/scylla-toolchain:fedora-38-20240619`
image

**Comment by mykaul** [comment]
@yaronkaikov - in my PR?

**Comment by yaronkaikov** [comment]
yes, just modify the file and push the changes to your PR
CI will run and will pass (if i did everything right ;-)

**Pull request closed without merging**
