### PR TITLE
test/topology: disable for debug/aarch64

### PR DESCRIPTION
**Pull request by alecco**
Due to issues in this platform disable debug tests for now.

### CODE REVIEW

**Comment by kbr-scylla** [comment]
TBH I'm sceptical about doing this. @avikivity @mykaul what do you think?

**Comment by alecco** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3463/

"ninja: build stopped: subcommand failed."

restarted

**Comment by mykaul** [comment]
> TBH I'm sceptical about doing this. @avikivity @mykaul what do you think?

I'm OK with doing it for a week or two, waiting at the very least for an updated clang (with fixes @tchaikov backported). Right now - it just adds noise.

**Comment by mykaul** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3467/

ARGH!!!
```
 BUILD FAILED
 /jenkins/workspace/scylla-master/scylla-ci/scylla/tools/java/.build/build-resolver.xml:181: Can't get https://raw.githubusercontent.com/apache/cassandra/27de93ebb1285e731570eb8585d66832c79c4289/lib/sigar-bin/libsigar-amd64-freebsd-6.so to /home/jenkins/.m2/repository/org/apache/cassandra/deps/sigar-bin/libsigar-amd64-freebsd-6.so
```

**Comment by alecco** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3467/
> 
> ARGH!!!
> 
> ```
>  BUILD FAILED

Maybe CI became self-aware and it's just messing with us.

**Comment by alecco** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3471/

Unrelated dtest failure:

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3471/testReport/junit/cql_tests/TestTruncate/Tests___Sanity_Tests___test_cql_query_filtering_without_indexes/

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4259/artifact/logs-full.release.000/1693916116164_cql_tests.py%3A%3ATestTruncate%3A%3Atest_cql_query_filtering_without_indexes/

Restarting

**Comment by avikivity** [comment]
I don't understand the patch. The tests fail, so disable them?

Vague commit messages about "issues" ensure it will never be enabled.

**Comment by kostja** [comment]
> I don't understand the patch. The tests fail, so disable them?
> 
> Vague commit messages about "issues" ensure it will never be enabled.

I asked Alejo to prepare the patch. We don't want to look at topology failures on arm in debug mode. Most of the time it is white noise. Time is better spent writing focused tests and running them on faster hardware.

**Comment by tchaikov** [comment]
> > I don't understand the patch. The tests fail, so disable them?
> > Vague commit messages about "issues" ensure it will never be enabled.
> 
> I asked Alejo to prepare the patch. We don't want to look at topology failures on arm in debug mode. Most of the time it is white noise. Time is better spent writing focused tests and running them on faster hardware.

IMHO, it might be more helpful to the posterity to understand the issue when they look at the commit message. probably we could add a link referencing the issue in the commit message? or we'd like to so when applying the `skip_aarch64` fixture?

**Comment by mykaul** [comment]
@kostja - ignoring the crashes on ARM that are caused by clang most likely, why aren't we fixing (stabilizing) the topology tests on ARM instead of disabling?

**Comment by kostja** [comment]
In short - because it's debug only, and our time is better spent elsewhere. Imagine the effort of running dtest in debug mode on arm and running in a stable mode. Right now we're the first to take the hit, whatever functional regression there is in arm debug, it's going to first of all break the topology tests.

@kbr-scylla convinced me today that we should wait for the compiler fix to get in. OK.

**Pull request closed without merging**
