### PR TITLE
create-relocatable-package.py: add version file with tempfile

### LINKED ISSUE #15018: create-relocatable-package.py fails to create reloc package
we build multiple relocatable packages for different builds in parallel using ninja. all these relocatable packages are built using the same script of
`create-relocatable-package.py`. but this script always uses the same directory and file for the .relocatable_package_version file.

so there are chances that the jobs building the relocatable packages can race and writing / accessing the same file at the same time. this issue is manifested like
```
[2023-08-10T09:38:00.019Z] FAILED: build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz
[2023-08-10T09:38:00.019Z] scripts/create-relocatable-package.py --mode debug 'build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz'
[2023-08-10T09:38:00.019Z] Traceback (most recent call last):
[2023-08-10T09:38:00.019Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/scripts/create-relocatable-package.py", line 130, in <module>
[2023-08-10T09:38:00.019Z]     os.makedirs(f'build/{SCYLLA_DIR}')
[2023-08-10T09:38:00.019Z]   File "<frozen os>", line 225, in makedirs
[2023-08-10T09:38:00.019Z] FileExistsError: [Errno 17] File exists:
'build/scylla-package'
```

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, we build multiple relocatable packages for different builds in parallel using ninja. all these relocatable packages are built using the same script of
`create-relocatable-package.py`. but this script always uses the same directory and file for the `.relocatable_package_version` file.

so there are chances that these jobs building the relocatable package can race and writing / accessing the same file at the same time. so, in this change, instead of using a fixed file path for this temporary file, we use a NamedTemporaryFile for this purpose. this should helps us avoid the build failures like

```
[2023-08-10T09:38:00.019Z] FAILED: build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz
[2023-08-10T09:38:00.019Z] scripts/create-relocatable-package.py --mode debug 'build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz'
[2023-08-10T09:38:00.019Z] Traceback (most recent call last):
[2023-08-10T09:38:00.019Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/scripts/create-relocatable-package.py", line 130, in <module>
[2023-08-10T09:38:00.019Z]     os.makedirs(f'build/{SCYLLA_DIR}')
[2023-08-10T09:38:00.019Z]   File "<frozen os>", line 225, in makedirs
[2023-08-10T09:38:00.019Z] FileExistsError: [Errno 17] File exists:
'build/scylla-package'
```
Fixes #15018

### CODE REVIEW

**Comment by tchaikov** [comment]
hi Takuya San, could you help review this change? it's a follow up of #13978 . i think the only explanation is what you put in https://github.com/scylladb/scylladb/pull/13978#issuecomment-1565613124 . this solution might be better.

**Review by syuu1228 — APPROVED** [review]
LGTM.

**Comment by avikivity** [comment]
Since it fixes a bug, please file an issue and link to it so it's easier to track for backporting.

**Comment by tchaikov** [comment]
> Since it fixes a bug, please file an issue and link to it so it's easier to track for backporting.

sure. done. but the chance of the racing is rare.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you please help queue this change?

**Pull request closed without merging**
