### PR TITLE
[branch-5.1] Update ./tools/jmx and ./tools/java submodules

### PR DESCRIPTION
**Pull request by denesb**
* tools/jmx 06f2735...ed3cc6d (1):
  > Merge "scylla-apiclient: update several Java dependencies" from Piotr Grabowski

* tools/java be0aaf7597...7459a11815 (1):
  > Merge 'build: update several dependencies' from Piotr Grabowski

Update build dependencies which were flagged by security scanners.

Refs: scylladb/scylla-jmx#220
Refs: scylladb/scylla-tools-java#351

Fixes: https://github.com/scylladb/scylla-jmx/issues/221
Fixes: https://github.com/scylladb/scylla-jmx/issues/222
Fixes: https://github.com/scylladb/scylla-jmx/issues/223

Fixes: https://github.com/scylladb/scylla-tools-java/issues/348
Fixes: https://github.com/scylladb/scylla-tools-java/issues/349
Fixes: https://github.com/scylladb/scylla-tools-java/issues/350

### CODE REVIEW

**Comment by denesb** [comment]
@avelanarius I had some conflicts in tools/java:
```
+<<<<<<< HEAD                                                  
           <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.11.2.0" classifier="shaded" />
+=======                                 
+          <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.11.5.0" classifier="shaded" />
+>>>>>>> 97c490947c (Merge 'build: update several dependencies' from Piotr Grabowski)
```

I resolved by simply choosing the latter line, but it is clear, that 5.2. had a different base version for the driver, than master. Is this fine?

**Comment by mykaul** [comment]
> @avelanarius I had some conflicts in tools/java:
> 
> ```
> +<<<<<<< HEAD                                                  
>            <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.11.2.0" classifier="shaded" />
> +=======                                 
> +          <dependency groupId="com.scylladb" artifactId="scylla-driver-core" version="3.11.5.0" classifier="shaded" />
> +>>>>>>> 97c490947c (Merge 'build: update several dependencies' from Piotr Grabowski)
> ```
> 
> I resolved by simply choosing the latter line, but it is clear, that 5.1. had a different base version for the driver, than master. Is this fine?

Yes, it's fine - we also want to use the latest-greatest driver, IMHO. It may also has some deps that were updated

**Comment by mykaul** [comment]
> Yes, it's fine - we also want to use the latest-greatest driver, IMHO. It may also has some deps that were updated

In fact, it may not be enough and we'll need a new driver version :(
https://github.com/scylladb/java-driver/commits/scylla-3.x has some deps updated and I don't think we've released a new driver since.
CC @roydahan

**Comment by denesb** [comment]
Queued.

**Comment by denesb** [comment]
Promoted, closing.

**Pull request closed without merging**
