### PR TITLE
Allow explicitly enabling or disabling tablets when creating a new keyspace

### PR DESCRIPTION
**Pull request by bhalevy**
Separate the configuration for enabling the tablets feature from the enablement of tablets when creating new keyspaces.

This change always enables the TABLETS cluster feature and the tablets logic respectively.

The `enable_tablets` config option just controls whether tablets are enabled or disabled by default for new keyspaces.

If `enable_tablets` is set to `true`, tablets can be disabled using `CREATE KEYSPACE WITH tablets = { 'enabled': false }` as it is today.

If `enable_tablets` is set to `false`, tablets can be enabled using `CREATE KEYSPACE WITH tablets = { 'enabled': true }`.

The motivation for this change is to simplify the user experience of using tablets by setting the default for new keyspaces to false amd allowing the user to simply opt-in by using tablets = {enabled: true }.
This is not pissible today.
The user has to enable tablets by default for all new keyspaces (that use the NetworkTopologyStrategy) and then actively opt-out to use vnodes.

* Not required to be backported to OSS versions.  May be backported to specific enterprise versions

* This PR resubmits https://github.com/scylladb/scylladb/pull/20729 that was reverted in 73b1f66b707682c95c6a9427f00a94c5080c2f91 due to https://github.com/scylladb/scylladb/issues/21159 which is now fixed

### CODE REVIEW

**Comment by avikivity** [comment]
What work was done to ensure tests don't break like last time?

**Comment by bhalevy** [comment]
> What work was done to ensure tests don't break like last time?

For dtests we have:
- [ ] https://github.com/scylladb/scylla-dtest/pull/5047
  - [ ] and https://github.com/scylladb/scylla-dtest/pull/5271
- [ ] https://github.com/scylladb/scylla-dtest/pull/5128
  - already backported to 2024.2
- [ ] https://github.com/scylladb/scylla-dtest/pull/5139
  - already backported to 2024.2

For unit test, there's only https://github.com/scylladb/scylladb/issues/21159 that's fixed in master and 2024.2 is not susceptible to it since it doesn't have https://github.com/scylladb/scylladb/commit/8cc99973ebaf9d664c4c2a20b8ce3f1b2eb7100a

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12994/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12994/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/tablets_test 🔹 topology_custom/test_tablets 🔹 topology_experimental_raft/test_topology_upgrade 🔹 topology_experimental_raft/test_topology_upgrade_not_stuck_after_recent_removal ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/107/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4635/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1561/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12662/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12994/)
> #### Failed Tests (3/42906):
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12994/testReport/junit/boost.secondary_index_test.test_secondary_index_case_sensitive.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12994/testReport/junit/boost.view_complex_test.test_3362_with_ttls_with_set.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
>     * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12994/testReport/junit/boost.view_schema_test.test_updates.1.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
> 

all three of them are #20772

**Comment by denesb** [comment]
@bhalevy there are conflicts, needs rebase.

**Comment by bhalevy** [comment]
- rebased onto latest master

**Pull request closed without merging**
