### PR TITLE
cql: remove global_req_id from schema_altering_statement

### PR DESCRIPTION
**Pull request by nuivall**
Such field is no longer needed as the information comes
directly from group0_batch.

Fixes scylladb/scylladb#19365

Backport: no, we don't backport code cleanups

### CODE REVIEW

**Comment by tchaikov** [comment]
@nuivall it's now mandatory to add a `backport/*` label when contributing a PR . see https://github.com/scylladb/scylladb/blob/master/.github/workflows/pr-require-backport-label.yaml for the workflow enforcing this policy. so you might want to add it and better off adding the explanation accordingly in the cover letter of the PR.

**Comment by piodul** [comment]
It's just a code cleanup, so IMO it should not be backported, but I'll let @nuivall express his opinion/rationale and assign the labels

**Comment by nuivall** [comment]
set the label, I think we may want to backport iff we backport something which depends on it (or simplifies patch) but alone doesn't make sense

**Comment by piodul** [comment]
The unit tests job seems to be stuck since yesterday (https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9800/). I'll abort and then rerun.

**Comment by piodul** [comment]
Queued

**Pull request closed without merging**
