### PR TITLE
[5.2 backport] Update node-exporter to v1.6.1

### PR DESCRIPTION
**Pull request by mykaul**
Update from 1.4.0 to 1.6.1, (updated Go packages mainly)

[I assume it'll require a toolchain update to pass CI]

Refs: #15044
Closes: #15781

### CODE REVIEW

**Comment by mykaul** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-5.2/job/scylla-ci/57/

As expected - need newer toolchain:
```
00:05:29.324  [258/2956] tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.6.1.linux-amd64 build/node_exporter
00:05:29.324  FAILED: build/node_exporter/node_exporter 
00:05:29.324  tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.6.1.linux-amd64 build/node_exporter
00:05:29.325  tar: /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz: Cannot open: No such file or directory
```

**Comment by mykaul** [comment]
@avikivity - I think this again needs a newer toolchain

**Comment by mykaul** [comment]
ping @avikivity - this will need toolchain update, I suspect.

**Comment by avikivity** [comment]
Why backport this? Does it fix a bug?

**Comment by mykaul** [comment]
> Why backport this? Does it fix a bug?

Go pkg vulnerabilities...

**Comment by mykaul** [comment]
Already handled elsewhere with an 1.7.0 update - https://github.com/scylladb/scylladb/pull/16086 and friends

**Pull request closed without merging**
