### PR TITLE
config: remove "experimental" option

### PR DESCRIPTION
**Pull request by tchaikov**
"experimental" option was marked "Unused" in 64bc8d2f7d. but we chose to keep it in hope that the upgrade test does not fail. despite that the upgrade tests per-se survived the "upgrade", after the upgrade, the tests exercising the experimental features are still failing hard. they have not been updated to set the "experimental-features" option, and are still relying on "experimental" to enable all the experimental features under test.

so, in this change, let's just drop the option so that scylla can fail early at seeing this "experimental" option. this should help us to identify the tests relying on it quicker. as the "experimental" features should only be used in development environment, this change should have no impact to production.

Refs #15214
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
We also have value_status::Invalid in addition to Unused. Do you know what this does and maybe it fits here?

While I agree with this patch, it raises a general question why we have "Unused" at all. When does it **ever** makes sense to drop support for an option, and while in version X it did something, in version Y it is completely ignored and the user may not realize it was ignored. Is this something we ever wanted to do?

**Review by nyh — APPROVED** [review]
Approving, but waiting before merging to see if anyone else has any opinions on the more general question (not just in this case) of Unused vs removal, and what is value_status::Invalid.

**Comment by tchaikov** [comment]
v2:

- drop the test for parsing "experimental" option.

**Comment by denesb** [comment]
> While I agree with this patch, it raises a general question why we have "Unused" at all. When does it **ever** makes sense to drop support for an option, and while in version X it did something, in version Y it is completely ignored and the user may not realize it was ignored. Is this something we ever wanted to do?

Good question indeed. It might make sense if e.g. there is a tunable which is later deprecated because ScyllaDB can tune the tunable better itself. In this case, the user looses nothing by the tunable now being ignored. Maybe this is a contrived example.

More importantly, we decided to deprecate options this way a long time ago and I think it is best to remain consistent. If we change our mind, we should remove all ignored options.

**Comment by avikivity** [comment]
Unused is for Cassandra options that we don't implement. We could extend it to ScyllaDB options that we no longer implement.

**Comment by nyh** [comment]
> Unused is for Cassandra options that we don't implement.

These are options that we chose never to implement because they are better off ignored, and users switching over from Cassandra shouldn't even be told that these options are being ignored?

> We could extend it to ScyllaDB options that we no longer implement.

I think the point is that we already did - we are options (like "experimental") which we marked Unused even though they were never Cassandra options.

**Comment by nyh** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3385/

This is https://github.com/scylladb/scylladb/issues/15210 and I think it was fixed in ccm so let me try to start the CI again...

**Comment by tchaikov** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3429/

new issue spotted: #15263

**Comment by nyh** [comment]
> Approving, but waiting before merging to see if anyone else has any opinions on the more general question (not just in this case) of Unused vs removal, and what is value_status::Invalid.

Ok, I didn't see anyone protesting this patch, so let's do it. I'll merge.
BTW, I still have no idea what is value_status::Invalid and when we would use that.

**Comment by vponomaryov** [comment]
> so, in this change, let's just drop the option so that scylla can fail early at seeing this "experimental" option...

Scylla doesn't fail early seeing this option:
```
Sep 26 16:11:16 ip-10-0-8-238 systemd[1]: Starting Scylla Cloud Image Setup service...
...
Sep 26 16:11:24 ip-10-0-8-238 scylla_image_setup[571]: 2023-09-26 16:11:24,725 - [scylla_configure] - INFO - Setting default experimental=False
Sep 26 16:11:24 ip-10-0-8-238 scylla_image_setup[571]: Setting default experimental=False
...
Sep 26 16:16:14 longevity-schemachanges-3h-dev-db-node-af080f7a-1 systemd[1]: Starting Scylla Server...
...
Sep 26 16:16:15 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] seastar - updated: blocked-reactor-notify-ms=1000000
Sep 26 16:16:15 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 1:main] seastar - updated: blocked-reactor-notify-ms=1000000
Sep 26 16:16:15 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] init - Unknown option : experimental
Sep 26 16:16:15 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] init - installing SIGHUP handler
Sep 26 16:16:16 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] init - Scylla version 2023.3.0~dev-0.20230910.4629201aceec with build-id 1df7b78b7d434b10361b954b08425bdf1921a763 starting ...
Sep 26 16:16:16 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] init - starting prometheus API server
Sep 26 16:16:16 longevity-schemachanges-3h-dev-db-node-af080f7a-1 scylla[5291]:  [shard 0:main] init - creating snitch
```

I still was able to run Scylla with that removed option, but started getting errors working with sstables the following way:
```
$ sudo scylla sstable dump-scylla-metadata --logger-log-level scylla-sstable=debug --sstables /var/lib/scylla/data/keyspace1/standard1-3b0feba05c8c11ee9779c2f8a4509a30/me-3g9p_1b7r_32lhc27195n6aboba6-big-Scylla.db --scylla-yaml-file /etc/scylla/scylla.yaml --keyspace keyspace1 --table standard1
DEBUG 2023-09-27 15:25:48,075 [shard 0:main] scylla-sstable - Single schema source provided
error processing arguments: could not load schema via : std::invalid_argument (Unknown option : experimental)
```

So, 
- The statement made in the change topic is not solved.
- The `scylla sstable` possibilities got reduced.

Do we consider it a bug?

**Comment by avikivity** [comment]
We ignore unknown options in scylla.yaml, this isn't new behavior. Whether it's good or not is another question.

**Comment by vponomaryov** [comment]
> We ignore unknown options in scylla.yaml, this isn't new behavior. Whether it's good or not is another question.

We ignore it not in all binaries. As mentioned above, the `scylla sstable` doesn't ignore it, it fails facing unknown option.
So, to me, it sounds as inconsistency in behaviour in addition to the reduced possibilities of the `scylla sstable` functionality.

**Comment by avikivity** [comment]
`scylla sstable` is separate functionality and doesn't support general scylladb options

It may pose a problem if we introduce experimental sstable features, but it won't be a problem for production as one doesn't use experimental there. /cc @denesb

**Comment by vponomaryov** [comment]
Filed bug about automatic addition of this, already removed, option to the `scylla.yaml` by the `scylla-machine-image` logic: https://github.com/scylladb/scylla-machine-image/issues/484

**Comment by denesb** [comment]
> `scylla sstable` is separate functionality and doesn't support general scylladb options
> 
> It may pose a problem if we introduce experimental sstable features, but it won't be a problem for production as one doesn't use experimental there. /cc @denesb

`scylla sstable` reads `scylla.yaml` to determine where to read the schema from. If said file contains the `experimental` option, it might fail as seen above.

**Pull request closed without merging**
