### PR TITLE
cql3: type_json: fix an edge case in float-to-int conversion

### PR DESCRIPTION
**Pull request by michoecho**
Refer to the added comment for details.

This problem was found by a compiler warning, and I'm fixing it mainly to silence the warning. I didn't give any thought to its effects in practice.

Refs #13077

### CODE REVIEW

**Comment by michoecho** [comment]
This is an alternative to https://github.com/scylladb/scylladb/pull/12874.

Functionally, there should only be one small difference: #12874 assumes FE_TONEAREST rounding, while this PR works regardless of rounding mode. But for usage in Scylla this probably doesn't matter.

Let's pick one of the fixes and get them merged, because the current code is tripping a compiler warning (in cmake builds).

**Comment by nyh** [comment]
> Refer to the added comment for details.
> 
> This problem was found by a compiler warning, and I'm fixing it mainly to silence the warning. I didn't give any thought to its effects in practice.
> 
> Refs #13077

What does "Refs" mean here? Does it fix #13077? If not, maybe you can had a whole sentence on why it doesn't fix it, or doesn't need to fix it, or it shouldn't be fixed, or whatever?

**Comment by michoecho** [comment]
> > Refer to the added comment for details.
> > This problem was found by a compiler warning, and I'm fixing it mainly to silence the warning. I didn't give any thought to its effects in practice.
> > Refs #13077
> 
> What does "Refs" mean here? Does it fix #13077? If not, maybe you can had a whole sentence on why it doesn't fix it, or doesn't need to fix it, or it shouldn't be fixed, or whatever?

I don't know, because I don't understand how much #13077 is supposed to cover.

This patch only fixes the mishandling of floats `std::ldexp(1, 64)` (and `std::ldexp(1, 63)` for the signed case) in the function `to_int`. But the issue talks about `fromJson()`, which involves more parts than just `to_int`. Perhaps fixing `to_int` is not enough to say that the handling of large floats has been fixed (e.g. because we also want the behavior of the float parser to be different or something).  

But https://github.com/scylladb/scylladb/pull/12874 says `Fixes`, and this patch does the same thing, so I guess it could be `Fixes` too.

**Review by nyh — CHANGES_REQUESTED** [review]
Very nice, I can actually understand this fix better than I understood @tchaikov's fix in https://github.com/tchaikov/scylladb/commit/b162c7b913bd420a6e6597575e1156554dd90a77 - @tchaikov can you please review this patch - if there's anything worse in this patch than your patch, and whether you think it can "Fixes" #13077 instead of just Refs.

Some requests:
1. For signed types, where min() is not 0, I think  you need to do the same trick for min as you did for max, no?
2. We should have a CQL test that checks that your condition still works and doesn't just silence a compiler warning ;-) The test should check that a float which is distinguishably higher than 2^64 should fail conversion to bigint, and one which is distinguishably lower than 2^64 should pass. @tchaikov had such a test in test_json.py in commit https://github.com/tchaikov/scylladb/commit/b162c7b913bd420a6e6597575e1156554dd90a77, maybe you can take that as-is.

**Comment by nyh** [comment]
I see @avikivity already merged your PR while I was reviewing it (of course he had no way to know that).
Please do send a follow-up patch with:
1. A test which confirms your change didn't break the **functionality** of the "if" (making the compiler happy is not enough). I think @tchaikov 's test in test_json.py in https://github.com/tchaikov/scylladb/commit/b162c7b913bd420a6e6597575e1156554dd90a77 would be good.
2. Please think if you don't need to apply the same trick for min(), not just max().
3. Since you did not add "Fixes" of https://github.com/scylladb/scylladb/issues/13077, please close the issue manually if you and/or @tchaikov consider it fixes it. Let's not leave solved issues open.

**Comment by nyh** [comment]
> > Please think if you don't need to apply the same trick for min(), not just max().
> 
> No, because min() is a power of 2, so it is exactly representable in floating point. So no rounding occurs there, and the comparison is exact.

Nice! I missed that.

> > A test which confirms your change didn't break the functionality of the "if"
> 
> I can do that, but don't you think that's slightly too paranoid in this case?

I don't know, how did you test this patch? What if your forumula had a typo? Imagine you put "1.0" instead of "2.0" - your code would compile but will simply not do the right test. Didn't you try to run cqlsh or something to test your patch? Well, this is what this test does .

**Comment by tchaikov** [comment]
@michoecho hi Michał, now that this change has been merged. and the original intention of the issue, the fix and the tests were actually intended for fixing this compiling warning and later the comments from the reviewers. so i am content with this change.

i was using a more formal way to compare the float and integer in my change. but your change addresses this very edge case in a more understandable way. 

 just for the posterity, #13423 also tried to introduce some tests related to this issue.

**Pull request closed without merging**
