### PR TITLE
api: storage_service: correct a typo

### PR DESCRIPTION
**Pull request by tchaikov**
s/a any keyspace/an arbitrary keyspace/

### CODE REVIEW

**Comment by tchaikov** [comment]
@amnonh hi Amnon, this change was introduced back in ef3c6b26475080f17d81ae602462a0199cf72cbc. could you please help me understand why we need to provide such an API? i checked the corresponding change in jmx, see https://github.com/scylladb/scylla-jmx/blob/3257897ae8ed05d778038abb8a94b88c56c5be9b/src/main/java/org/apache/cassandra/service/StorageService.java#L381 . and we always use the other API which accepts the keyspace.

FWIW, i am collecting the background information for preparing for #16509. so this fact should help me have a better image of what the new API should look like.

**Comment by amnonh** [comment]
If I understand correctly, this original patch handles two things. The important one returns a list of objects (similar to how the JMX handles it), and the second adds an option to return all the token rings. The other API was added for completeness

**Review by denesb — APPROVED** [review]

**Comment by tchaikov** [comment]
> If I understand correctly, this original patch handles two things. The important one returns a list of objects (similar to how the JMX handles it), and the second adds an option to return all the token rings. The other API was added for completeness

@amnonh , thank you for your prompt reply. i am more interested in `ss::describe_any_ring`, which returns the token rings of the first "keyspace" -- the arbitrary one. but it seems that this API is never used. was it added for completeness ? how come it returns "all the token rings" ?

**Comment by amnonh** [comment]
> > If I understand correctly, this original patch handles two things. The important one returns a list of objects (similar to how the JMX handles it), and the second adds an option to return all the token rings. The other API was added for completeness
> 
> @amnonh , thank you for your prompt reply. i am more interested in `ss::describe_any_ring`, which returns the token rings of the first keyspace -- the arbitrary one. but it seems that this API is never used. was it added for completeness ? how come it returns "all the token rings" ?

I don't remember; I'm only guessing; maybe back then, nodetool had a different behavior for calling describe ring without a keyspace (or maybe it was some other jmx functionality)

**Comment by tchaikov** [comment]
> > > If I understand correctly, this original patch handles two things. The important one returns a list of objects (similar to how the JMX handles it), and the second adds an option to return all the token rings. The other API was added for completeness
> > 
> > 
> > @amnonh , thank you for your prompt reply. i am more interested in `ss::describe_any_ring`, which returns the token rings of the first keyspace -- the arbitrary one. but it seems that this API is never used. was it added for completeness ? how come it returns "all the token rings" ?
> 
> I don't remember; I'm only guessing; maybe back then, nodetool had a different behavior for calling describe ring without a keyspace (or maybe it was some other jmx functionality)

thank you again. i will try to remove it and see what will happen.

**Pull request closed without merging**
