### PR TITLE
redis: remove redis/version.hh

### PR DESCRIPTION
**Pull request by tchaikov**
the only consumer of redis/version.hh is redis/lolwut.cc, which include this header for accessing the `redis_version` constant. in order to simplify the implementation, let's move the definition of `redis_version` into its only consumer.

---

it's a cleanup, hence no need to backport.

### CODE REVIEW

**Comment by avikivity** [comment]
I don't understand what this is fixing.

**Comment by tchaikov** [comment]
> I don't understand what this is fixing.

it fixes the same problem fixed by #21186

**Comment by avikivity** [comment]
> > I don't understand what this is fixing.
> 
> ~it fixes the same problem fixed by #21186, because we have another `version.hh` under the root of source directory.~
> 
> with #21193, this does not fix anything anymore. now this change is merely a cleanup.

How is it a cleanup? It makes sense to have a separate version.hh file, even if today it has one user.

**Comment by tchaikov** [comment]
i see. i don't feel strong either way. IMHO, a header file is supposed to be shared, or to split a complicated source file in a more structured way. but this `version.hh` is tiny, and its consumer is not complicated.

anyway, i am closing this PR.

**Pull request closed without merging**
