### PR TITLE
Add protobuf and Native histogram support

### LINKED ISSUE #12931: Support Prometheus native histograms once they will be available
Prometheus are replacing their histograms implementation, we should switch to that once it is available

### PR DESCRIPTION
**Pull request by amnonh**
Native histograms (also known as sparse histograms) are an experimental Prometheus feature. 
They use protobuf as the reporting layer. 
Native histograms hold the benefits of high resolution at a lower resource cost.

This series allows sending histograms in a native histogram format over protobuf.
By default, protobuf support is disabled. To use protobuf with native histograms, the command line flag prometheus_allow_protobuf should be set to true, and the Prometheus server should send the accept header with protobuf.

Fixes #12931

### CODE REVIEW

**Comment by tchaikov** [comment]
```
[2024-01-11T11:57:43.809Z] ERROR: Build x86_64 failed with error: script returned exit code 137
```

retriggering.

**Comment by denesb** [comment]
@amnonh please investigate why CI failed, and either link to existing issues, or open new ones for them.

**Comment by amnonh** [comment]
@denesb it was a test flakiness; re-running it solved the problem

**Comment by denesb** [comment]
> @denesb it was a test flakiness; re-running it solved the problem

Yes, but we want to keep tabs on our flaky tests, hence we ask all contributors to look into CI failures on their PR and link to existing issues/create issues for known/new flaky tests, so they can be tracked down and fixed eventually.

**Review by denesb — APPROVED** [review]

**Comment by amnonh** [comment]
I've resolved the conflict, pull rebased and forced push

**Comment by nyh** [comment]
We're under orders from @avikivity not to merge a PR with test failures before the patch author - or one of the reviewers - investigates each and every failure - and either saying that it's known flaky test or creating an issue for a previously-unknown issue.

I'll try to do this for this PR later.

**Comment by nyh** [comment]
> @nyh all tests have passed

I know. The point is that yesterday, before they passed, some test failed. It means there's a flaky test. Somebody needs to find this flaky test, and add another complaint in an existing issue, if there is one - or open a new issue if there isn't. Avi wants us to insist that somebody does this work - either you or one of us - before merging a PR.

**Comment by nyh** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6010/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6010/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7339/)
> #### Failed Tests (2/23830):
> 
>     * [test_partial_upgrade_can_be_finished_with_removenode](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6010/testReport/junit/%28root%29/test_raft_cluster_features/Tests___Unit_Tests___test_partial_upgrade_can_be_finished_with_removenode) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partial_upgrade_can_be_finished_with_removenode)
> 
>     * [topology_experimental_raft.test_raft_cluster_features.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6010/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_raft_cluster_features_debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_raft_cluster_features.debug.2)
> 
> 
> #### Build Details:
> 
>     * Duration: 2 hr 1 min
> 
>     * Builder: spider1.cloudius-systems.com

This probably a flaky test. The failure is in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6010/testReport/(root)/test_raft_cluster_features/Tests___Unit_Tests___test_partial_upgrade_can_be_finished_with_removenode_6/ - there is a 60-second timeout trying to create a node, and the timeout passes. I suspect https://github.com/scylladb/scylladb/issues/16821 but can't prove it - there are hundreds of log files and I can't find the right one :-( The state of our test log  debuggability is a disaster - see https://github.com/scylladb/qa-tasks/issues/1603 for a discussion. It doesn't need to be this way. I should be able to see the failure logs of a specific test immediately, without this nonsense :-(

**Comment by kbr-scylla** [comment]
> there is a 60-second timeout trying to create a node

The timeout is not on trying to create a node. Even from the link you provided it should be clear as it provides a stacktrace
```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f360569a450>

    @pytest.mark.asyncio
    async def test_partial_upgrade_can_be_finished_with_removenode(manager: ManagerClient) -> None:
        await manager.servers_add(3)
>       await test_cluster_features.test_partial_upgrade_can_be_finished_with_removenode(manager)

test/topology_experimental_raft/test_raft_cluster_features.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/topology/test_cluster_features.py:199: in test_partial_upgrade_can_be_finished_with_removenode
    host = (await wait_for_cql_and_get_hosts(cql, [srv], time.time() + 60))[0]
test/pylib/util.py:89: in wait_for_cql_and_get_hosts
    await asyncio.gather(*(wait_for_cql(cql, h, deadline) for h in hosts))
test/pylib/util.py:64: in wait_for_cql
    await wait_for(cql_ready, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_cql.<locals>.cql_ready at 0x7f360417f4c0>
deadline = 1706021554.939368, period = 1, before_retry = None

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float,
            period: float = 1,
            before_retry: Optional[Callable[[], Any]] = None) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:47: AssertionError
```


i.e.
```
test/topology/test_cluster_features.py:199: in test_partial_upgrade_can_be_finished_with_removenode
    host = (await wait_for_cql_and_get_hosts(cql, [srv], time.time() + 60))[0]
```

**Comment by nyh** [comment]
> #### 🔴 CI State: ABORTED
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5954/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7288/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5954/)
> #### Failed Tests (9/23759):
> 
>     * [test_streaming_on_repair](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest___test_streaming_on_repair) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_streaming_on_repair)
> 
>     * [test_counter_consistency_node_repair](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/counter_tests/TestCountersOnMultipleNodes/Tests___dtest___test_counter_consistency_node_repair) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_counter_consistency_node_repair)
> 
>     * [test_numeric_type_group](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/cql_group_functions_tests/TestGroupFunctions/Tests___dtest___test_numeric_type_group) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_numeric_type_group)
> 
>     * [test_system_clients](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/cql_system_clients_test/TestSystemClients/Tests___dtest___test_system_clients) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_system_clients)
> 
>     * [test_repair_schema](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest___test_repair_schema) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_schema)
> 
>     * [test_replace_node_diff_ip_take_write[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest___test_replace_node_diff_ip_take_write_use_endpoint_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_node_diff_ip_take_write%5Buse_endpoint-rbo_enabled%5D)
> 
>     * [test_replace_node_diff_ip[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest___test_replace_node_diff_ip_use_endpoint_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_node_diff_ip%5Buse_endpoint-rbo_enabled%5D)
> 
>     * [test_simple_rf_3_consistency_level](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/simple_cluster_driver_test/TestSimpleCluster/Tests___dtest___test_simple_rf_3_consistency_level) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_rf_3_consistency_level)
> 
>     * [test_large_partition_detector_with_node_stop[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/wide_rows_test/TestWideRows/Tests___dtest___test_large_partition_detector_with_node_stop_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_large_partition_detector_with_node_stop%5BTimeWindowCompactionStrategy%5D)
> 
> 
> #### Build Details:
> 
>     * Duration: 1 hr 56 min
> 
>     * Builder: spider3.cloudius-systems.com

@avikivity I invite you to try to understand this failure if you think we can't commit this unrelated PR without it. We're getting weird "worker 'gw4' crashed" errors when dtest is starting, and I can't find any logs in Jenkins and have no idea what went wrong. It's a disaster, but has nothing to do with Amnon's patch.

**Comment by nyh** [comment]
> > there is a 60-second timeout trying to create a node
> 
> The timeout is not on trying to create a node. Even from the link you provided it should be clear as it provides a stacktrace

This sort of condescension will not help anything. I obviously saw this link (I pasted it, and it wasn't easy to find the correct one!). I am not familiar with test code which **your team** wrote, so maybe it's not my fault when doesn't work or when I don't immediately understand what went wrong when it doesn't work.

I saw `await wait_for(cql_ready, deadline)`. In the code. This told me we're waiting for CQL to come up on some node. Which is why I called it "create a node" - I meant it's a new node in the cluster - why will we be waiting for CQL to come up on a node which is already up? Maybe it's not a brand new node with empty data, maybe "create" is too strong a word, but it's a node which has just been rebooted, brought up, or something, no, and for some reason we can't connect to it? Or am I still misunderstanding?

Also, can you or Avi please explain to me why you think @amnonh's patch needs to be delayed while we fix our broken tests? Can we please get the person who actually wrote the failing test to look at it instead of me and @amnonh and then we'll be told how much we don't understand?

**Comment by kbr-scylla** [comment]
The node was rebooted before this line, which can be seen by looking at the test code (`test/topology_experimental_raft/test_raft_cluster_features.py`, the place to look at -- from the stacktrace):
```python3
    # Re-enable the feature again and restart
    await manager.server_update_config(servers[0].server_id, 'error_injections_at_startup', [
        'features_enable_test_feature',
    ])
    await manager.server_start(servers[0].server_id)

    # Nodes should start supporting the feature
    cql = cql = manager.get_cql()
    hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
```

and for some reason the driver session connected to the cluster cannot (doesn't even attempt to, judging from the logs) reestablish a connection to this node after it was rebooted, so `wait_for_cql_and_get_hosts` times out.

It doesn't mean though that the node is not up or CQL on this node is not working. It can be a driver issue. And most likely is, from the log it seems the driver doesn't even try to reestablish a connection, just assumes that the node is down.

It's also not my fault that the driver UX is so bad. I don't think it's the fault of anybody in this company even, after all it's a fork, we inherited the design. We have to work with the tools we have and go forward and fix them as we go. If we threw our hands in the air and gave up and blamed our surroundings, we would have no tests at all and not even be aware of such issues.

I think what @avikivity is asking for in case such as this is only to report an issue and proceed. You don't have to fix the test or the driver to unblock an unrelated PR. But if there's no ticket reported then the process of fixing the problem will probably not even start.

**Comment by kbr-scylla** [comment]
It's a small miracle that topology tests even work at all.

When we started developing them we immediately encountered driver issues. Mysterious timeouts for no particular reason. They are still haunting us... But there were more of them back then than there are now.

Did we give up and blame the tool saying that it's impossible to work with? Did we give up trying to develop these tests?
No, this is victim mentality and it wouldn't lead us anywhere.

We looked for workarounds. I even investigated the damn driver code even though it's not my area of expertise and I hated it but still, and I reported issues like https://github.com/scylladb/python-driver/issues/170. You want to get anything done, this is the way, I think.

**Comment by nyh** [comment]
> I think what @avikivity is asking for in case such as this is only to report an issue and proceed. You don't have to fix the test or the driver to unblock an unrelated PR. But if there's no ticket reported then the process of fixing the problem will probably not even start.

Ok, so let's make it real: What do you propose we do here? There is no open issue to link to. Can I create an issue? What will I say in the issue? Maybe just mention the specific test that failed hoping that if it fails again it will be in the same test?

**Comment by kbr-scylla** [comment]
I always do a preliminary investigation to identify the possible root cause and which logs are relevant and attach them. But I try not to go into a rabbit hole if I encounter one, spending at most a few minutes on the investigation and leaving the rest to whoever will get the assignment.

In current case that part is already done. I propose the following: please create an issue in Scylla repo and copy-paste my explanations from https://github.com/scylladb/qa-tasks/issues/1603#issuecomment-1908413845 and perhaps link to https://github.com/scylladb/python-driver/issues/170 as it seems similar -- driver is not reconnecting to a restarted node. (We can always move the issue to driver repo if it's at some point determined that yes, it is 100% a driver issue)

**Comment by avikivity** [comment]
> > #### 🔴 CI State: ABORTED
> > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5954/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/7288/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5954/)
> > #### Failed Tests (9/23759):
> > ```
> > * [test_streaming_on_repair](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest___test_streaming_on_repair) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_streaming_on_repair)
> > 
> > * [test_counter_consistency_node_repair](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/counter_tests/TestCountersOnMultipleNodes/Tests___dtest___test_counter_consistency_node_repair) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_counter_consistency_node_repair)
> > 
> > * [test_numeric_type_group](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/cql_group_functions_tests/TestGroupFunctions/Tests___dtest___test_numeric_type_group) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_numeric_type_group)
> > 
> > * [test_system_clients](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/cql_system_clients_test/TestSystemClients/Tests___dtest___test_system_clients) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_system_clients)
> > 
> > * [test_repair_schema](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest___test_repair_schema) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_schema)
> > 
> > * [test_replace_node_diff_ip_take_write[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest___test_replace_node_diff_ip_take_write_use_endpoint_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_node_diff_ip_take_write%5Buse_endpoint-rbo_enabled%5D)
> > 
> > * [test_replace_node_diff_ip[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest___test_replace_node_diff_ip_use_endpoint_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_node_diff_ip%5Buse_endpoint-rbo_enabled%5D)
> > 
> > * [test_simple_rf_3_consistency_level](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/simple_cluster_driver_test/TestSimpleCluster/Tests___dtest___test_simple_rf_3_consistency_level) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_rf_3_consistency_level)
> > 
> > * [test_large_partition_detector_with_node_stop[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5954/testReport/junit/wide_rows_test/TestWideRows/Tests___dtest___test_large_partition_detector_with_node_stop_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_large_partition_detector_with_node_stop%5BTimeWindowCompactionStrategy%5D)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Build Details:
> > ```
> > * Duration: 1 hr 56 min
> > 
> > * Builder: spider3.cloudius-systems.com
> > ```
> 
> @avikivity I invite you to try to understand this failure if you think we can't commit this unrelated PR without it. We're getting weird "worker 'gw4' crashed" errors when dtest is starting, and I can't find any logs in Jenkins and have no idea what went wrong. It's a disaster, but has nothing to do with Amnon's patch.

The requirement is to make an honest effort (which can include finding someone who knows more and asking them for help). If it requires proving that P=NP, then it's not gating.

Saying "the tests are flaky" is not sufficient.

**Comment by nyh** [comment]
Ok, then I think I did an honest effort (@amnonh, next time you can do it, you won't be more unsuccessful than I was in this case ;-)), and I'll merge Amnon's PR which @denesb already approved a few days ago.

**Review by Kali-27 — COMMENTED** [review]
> ❌ DO NOT SHARE THIS SESSION-ID WITH ANYBODY

**Comment by Kali-27** [comment]
> ❌ DO NOT SHARE THIS SESSION-ID WITH ANYBODY

**Comment by Kali-27** [comment]
> ❌ DO NOT SHARE THIS SESSION-ID WITH ANYBODY

**Review by Kali-27 — COMMENTED** [review]
> ❌ DO NOT SHARE THIS SESSION-ID WITH ANYBODY

**Pull request merged**
