### PR TITLE
[Backport 6.0] cql3/statement/select_statement: do not parallelize single-partition aggregations

### PR DESCRIPTION
**Pull request by Jadw1**
This patch adds a check if aggregation query is doing single-partition read and if so, makes the query to not use forward_service and do not parallelize the request.

Fixes https://github.com/scylladb/scylladb/issues/19349

(cherry picked from commit https://github.com/scylladb/scylladb/commit/e9ace7c2031523099de0b076b9678264ddd74e5c)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/8eb5ca820289d3ebec42e3108f3706bd0156ef79)

Refs https://github.com/scylladb/scylladb/pull/19350

### CODE REVIEW

**Comment by piodul** [comment]
>     * [test_concurrent_restart](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/105/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest___test_concurrent_restart) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_restart)

Sounds like https://github.com/scylladb/scylladb/issues/15192, right?

**Comment by Jadw1** [comment]
> > ```
> > * [test_concurrent_restart](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/105/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest___test_concurrent_restart) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_restart)
> > ```
> 
> Sounds like #15192, right?

Yep, it looks like. I'll retrigger the CI once the issue is solved.

**Comment by piodul** [comment]
>     * [test_service_levels_upgrade](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/103/testReport/junit/%28root%29/test_raft_service_levels/Tests___Unit_Tests___test_service_levels_upgrade) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_service_levels_upgrade)

Looks like https://github.com/scylladb/scylla-enterprise/issues/4236. Perhaps we should move the issue from Enterprise to OSS if it reproduces in OSS

>     * [test_serve_writes_during_bootstrap[use_endpoint-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/103/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_serve_writes_during_bootstrap_use_endpoint_rbo_disabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_serve_writes_during_bootstrap%5Buse_endpoint-rbo_disabled%5D)

This one looks like https://github.com/scylladb/scylladb/issues/18603

**Comment by piodul** [comment]
I'm retriggering CI right now. The failing tests are known issues and are most likely flaky, no need to wait with this until they are fixed.

**Comment by piodul** [comment]
> * [test_simple_decommission_node_while_query_info[2]](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/113/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_decommission_node_while_query_info_2_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_decommission_node_while_query_info%5B2%5D)

@kbr-scylla @temichus Looks like https://github.com/scylladb/scylladb/issues/17903. I can see that nodes in this test operate in gossiper mode. Are we missing https://github.com/scylladb/scylla-dtest/pull/4398 when testing the 6.0 branch somehow?

In any case, I'd rather not wait with the backport, I'll retrigger in hope that CI passes this time...

**Comment by kbr-scylla** [comment]
@piodul https://github.com/scylladb/scylla-dtest/pull/4535

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued

**Pull request merged**
