### PR TITLE
test_allocation_failure: Tighten memory to increase test pass chances

### LINKED ISSUE #9391: commitlog test: test_allocation_failure might not create memory tight enough environment
We have seen a failure of this test with:
`std::runtime_error (Adding mutation of size 16777203 succeeded unexpectedly`

https://jenkins.scylladb.com/view/enterprise-2020.1/job/enterprise-2020.1/job/next/336/testReport/junit/test_boost_commitlog_test/cc/test_allocation_failure/

Examining the code path that can lead to this revealed that this test might leave behind just enough memory to create the
desired size of fragmented buffer.

The problem is that it is wrogly assumed that after:
https://github.com/scylladb/scylla/blob/d7ac699a555a2d5423b6bc66458df3b9c53002fc/test/boost/commitlog_test.cc#L592

The memory content will be equal to 128K which means that after the continuation allocation it is guarantied that there are no more default_size fragments for the fragmented output stream.
However, after the aforementioned line, all that we can guarantee is that there is no more than `(128K*2) - 1` but this amount of
memory might (and probably was in the failure instance) just enough to accommodate the continuation and the fragmented buffer together.

### PR DESCRIPTION
**Pull request by eliransin**
In order to create an out of memory condition in the right time, the
test begins with a loop that exhaust all `fragmented_temporary_buffer::default_fragment_size` 
chunks of memory. Just after the loop exhaust all memory it releases one chunk out of
the implicit assumption that it will be used for continuation creation. However, this assumption 
is not necessarily true as the memory exhaustion is not tight enough.
1. At the end of the loop we can only be sure that Available_Memory <
`fragmented_temporary_buffer::default_fragment_size`
2. After erasing the last element we can actually end up with
Available_Memory >
`fragmented_temporary_buffer::default_fragment_size`*2
3. The continuation seams (empirically) to be able to use the <
`fragmented_temporary_buffer::default_fragment_size`
memory for allocation
which can have us end up with a free 128K buffer and the additional last
fragment after the continuation allocation.
In order to tighten the memory shortage we changed the following:
Right after the `fragmented_temporary_buffer::default_fragment_size` allocation loop breaks,
save an iterator to the last `fragmented_temporary_buffer::default_fragment_size` chunk,
assume that there are (`fragmented_temporary_buffer::default_fragment_size` - 1) available bytes in the system and try
to allocate them all. Release one chunk by resetting the pointer instead of erasing the
list element (which might return some more extra bytes to the heap).

Tested with prints that confirmed that indeed there is more memory to be
allocated. Except for proving that there is more memory to be allocated,
I didn't prove that it can be used for continuation allocation, this was
deduced from the previous code flow and path that generated the unexpected
success exception.

Fixes #9391

Signed-off-by: Eliran Sinvani <eliransin@scylladb.com>

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]

**Comment by avikivity** [comment]
The exception mentions being able to allocate 16MB of memory. How does having 128k or 256k make any difference?

**Comment by eliransin** [comment]
> The exception mentions being able to allocate 16MB of memory. How does having 128k or 256k make any difference?

Unless I am missing something I don't think it makes any difference in this test. The commit message was written in the spirit of
the comments in the test, however it might be a good idea to replace those with 
`fragmented_temporary_buffer::default_fragment_size` and `commitlog::max_record_size()` whenever appropriate because 
AFAICU the test is actually dependent on the relation between the two.

**Comment by eliransin** [comment]
@avikivity should I do anything else here?
Last version:
Changed the commit and PR messages to use the more accurate term 
`fragmented_temporary_buffer::default_fragment_size` instead of 128K.

**Comment by avikivity** [comment]
The problem is not the changelog. The problem is that I don't understand how the patch fixes the problem. It shouldn't matter if there are 128k free, 256k free, default_fragment_size free, or 2*default_fragment_size free. In all four cases it should be equally impossible to allocate 16MB.

**Comment by eliransin** [comment]
Irrelevant anymore

**Pull request closed without merging**
