### PR TITLE
doc: mark the in-memory tables feature as deprecated

### PR DESCRIPTION
**Pull request by annastuchlik**
Related: https://github.com/scylladb/scylla-enterprise/issues/2507

### CODE REVIEW

**Comment by annastuchlik** [comment]
@tzach Please review and leave a comment if this PR should be backported to 5.1.

**Comment by tzach** [comment]
We do not yet have an Enterprise doc site from the Enterprise tree.

**Review by tzach — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge.

**Pull request closed without merging**
