### PR TITLE
Adjust repair module to other task manager modules' conventions

### PR DESCRIPTION
**Pull request by Deexie**
Files with task manager repair module and related classes 
are modified to be consistent with task manager compaction module.

### CODE REVIEW

**Comment by bhalevy** [comment]
@Deexie looks good over all.
Please just give the PR a more descriptive title than "Modify".
Modify in what way?

> File with task manager repair module and related classes

nit: s/File/File(s)/

> are modified to be consistent with task manager compaction module.

**Comment by Deexie** [comment]
- delete tasks namespace from repair

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
@Deexie please rebase, there are conflicts.

**Comment by Deexie** [comment]
- rebased

**Pull request merged**
