### PR TITLE
test/pylib: scylla_cluster: protect `ScyllaCluster.stop` with a lock

### PR DESCRIPTION
**Pull request by kbr-scylla**
test.py calls `uninstall()` and `stop()` concurrently from exit artifacts, and `uninstall()` internally calls `stop()`. This leads to premature releasing of IP addresses from `uninstall()` (returning IPs to the pool) while the servers using those IPs are still stopping. Then a server might obtain that IP from the pool and fail to start due to "Address already in use".

Put a lock around the body of `stop()` to prevent that.

Fixes: scylladb/scylladb#15755

### CODE REVIEW

**Comment by kbr-scylla** [comment]
> by the way, is there anyway to confirm it fixes the problem?

I guess we'll just see if the IP clash problem stops reproducing on CI.

**Comment by denesb** [comment]
> I approve the patch (by the way, is there anyway to confirm it fixes the problem?) but think the entire scylla_cluster.py design should eventually be reconsidered. I think its implementation is too complex for what it does.

I agree on the complexity, but I'm not sure a simpler implementation is possible.
My pet peeve problem is that it is not possible to run tests relying on the cluster manager on their own. I like being able to run tests directly with `pytest`.

**Comment by kostja** [comment]
stop and uninstall should not be running concurrently, it doesn't make sense for a ton of reasons - if the server is still running, it is part of the cluster, so uninstalling it under its feet is asking for an undefined behaviour. The fix is OK of course but we need an assert that uninstall is never called for a running server.

**Review by kostja — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Rebased, retriggered CI.

**Comment by kbr-scylla** [comment]
> Can't the cluster manager be a fixure or something?

`manager: ManagerClient`, the thing that the test uses to communicate with cluster manager, is a fixture.

>  My pet peeve problem is that it is not possible to run tests relying on the cluster manager on their own. I like being able to run tests directly with pytest.

What do you mean "on their own" -- you mean without cluster manager? But what would happen when the test requests a topology change?

Or you mean you want to have your own instance of cluster manager, and run the test on that?
I think that should already be possible (if you have a method to create your own instance of cluster manager).

This is how we run tests:
```python3
    async def run(self, options: argparse.Namespace) -> Test:

        self._prepare_pytest_params(options)

        test_path = os.path.join(self.suite.options.tmpdir, self.mode)
        async with get_cluster_manager(self.mode + '/' + self.uname, self.suite.clusters, test_path) as manager:
            self.args.insert(0, "--mode={}".format(self.mode))
            self.args.insert(0, "--manager-api={}".format(manager.sock_path))

            try:
                # Note: start manager here so cluster (and its logs) is availale in case of failure
                await manager.start()
                self.success = await run_test(self, options)
```

`run_test` is basically calling `pytest` with a bunch of arguments.
For example:
```
16:23:13.594 INFO> Starting test topology_raft_disabled.test_raft_upgrade_majority_loss.1: pytest --manager-api=/tmp/manager-2uoap4r8/api --mode=dev -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/home/kbraun/dev/scylladb/testlog/dev/xml/topology_raft_disabled.test_raft_upgrade_majority_loss.1.xunit.xml -rs test/topology_raft_disabled/test_raft_upgrade_majority_loss.py
```

So I guess you could do the same. The path to cluster manager is provided with `--manager-api` parameter. You'd have to create your own instance of cluster manager first listening on the socket that you then provide to `--manager-api`.

**Comment by avikivity** [comment]
> So I guess you could do the same. The path to cluster manager is provided with `--manager-api` parameter. You'd have to create your own instance of cluster manager first listening on the socket that you then provide to `--manager-api`.

It should be automatic. If --manager-api is not provided, create one at the point of use.

**Comment by kbr-scylla** [comment]
@scylladb/scylla-maint please merge

**Pull request closed without merging**
