### PR TITLE
sstables: add for tombstone count

### PR DESCRIPTION
**Pull request by 851110504**
Add functionality to track tombstone count generated via the Alternator interface in SSTables

Related to #18212

### CODE REVIEW

**Comment by mykaul** [comment]
Thanks for the submission!
Will you be adding a test for it?

**Comment by raphaelsc** [comment]
Hi @851110504, could you please say a few more words about the motivation? How do you plan to use it? New metadata is added to scylla_metadata (lives in Scylla.db file that goes with every SSTable and it's backward compatible unlinke Statistics.db). Please take a look at scylla_metadata in sstables/type.hh. You can eventually count tombstone count by summing entries from stats_metadata::estimated_tombstone_drop_time. There will be an entry for every tombstone. You can use it for counting droppable tombstones (using gc_before = now() - gc_grace_seconds) and also total tombstone count. I will be glad to help you if you have any further questions. Note that not all tombstones are droppable, only those that are older than gc_before can be dropped, so that's the metric you're interested in.

**Comment by 851110504** [comment]
> Hi @851110504, could you please say a few more words about the motivation? How do you plan to use it? New metadata is added to scylla_metadata (lives in Scylla.db file that goes with every SSTable and it's backward compatible unlinke Statistics.db). Please take a look at scylla_metadata in sstables/type.hh. You can eventually count tombstone count by summing entries from stats_metadata::estimated_tombstone_drop_time. There will be an entry for every tombstone. You can use it for counting droppable tombstones (using gc_before = now() - gc_grace_seconds) and also total tombstone count. I will be glad to help you if you have any further questions. Note that not all tombstones are droppable, only those that are older than gc_before can be dropped, so that's the metric you're interested in.

Thank you. I have reviewed the parameter estimated_tombstone_drop_time, and it seems that the definition of tombstones stored in it differs slightly from what I need. Specifically, when a record contains both liveness_info and deletion_info, estimated_tombstone_drop_time considers it a tombstone and includes it in the count. However, my requirement is different: in such cases, the record is actually live, so it should not be considered a tombstone. Therefore, I have added a new parameter to track the number of tombstones. I understand that this parameter is stored in the statistics file corresponding to the sstable. However, after making these changes, I encountered an issue when trying to read previously generated sstable statistics files: the value read appears to be random. Upon inspecting the source code for reading the statistics file, I found that the file is read based on the size occupied by this parameter, leading to reading extra content due to the absence of this parameter in the previously generated statistics files. Hence, I would like to confirm whether adding a new parameter directly to stats_metadata could cause any issues, and whether it is necessary to modify the sstable version to add a new parameter (since I noticed that new parameters were added when upgrading from md to me versions). If adding a new parameter requires modifying the sstable version, then I will continue to use the estimated_tombstone_drop_time parameter.

image
image

**Comment by raphaelsc** [comment]
> 
> Thank you. I have reviewed the parameter estimated_tombstone_drop_time, and it seems that the definition of tombstones stored in it differs slightly from what I need. Specifically, when a record contains both liveness_info and deletion_info, estimated_tombstone_drop_time considers it a tombstone and includes it in the count. However, my requirement is different: in such cases, the record is actually live, so it should not be considered a tombstone. Therefore, I have added a new parameter to track the number of tombstones.

But it can happen that a partition stores tombstone shadowing older data, but not live data newer than that. estimated_tombstone_drop_time considers it a tombstone is because it's a tombstone.

For example, let's say you have partition A in sstable 1. Then you delete that partition A, the tombstone now exists in sstable 2. And new data is inserted into partition A, in sstable 3. After sstables 1,2,3 are merged by compaction, now you will have a partition record storing tombstone originally written in 2, and also live data written in 3. 

And that partition or row tombstones are candidates to being dropped. And tombstones aren't immediately droppable, which is why we need a histogram and not a count. It can happen tombstone count is high, you start major compaction, yet compaction won't be able to purge any of them because they haven't expired yet.

It's not clear to me what your motivation is yet. Do you want to purge tombstones faster or what? Get rid of deleted data faster? You're proposing a solution, but I don't understand the problem yet.

> I understand that this parameter is stored in the statistics file corresponding to the sstable. However, after making these changes, I encountered an issue when trying to read previously generated sstable statistics files: the value read appears to be random. Upon inspecting the source code for reading the statistics file, I found that the file is read based on the size occupied by this parameter, leading to reading extra content due to the absence of this parameter in the previously generated statistics files. Hence, I would like to confirm whether adding a new parameter directly to stats_metadata could cause any issues, and whether it is necessary to modify the sstable version to add a new parameter (since I noticed that new parameters were added when upgrading from md to me versions). If adding a new parameter requires modifying the sstable version, then I will continue to use the estimated_tombstone_drop_time parameter.
> 

Like I said above, stats_metadata is not backport compatible. You need to extend scylla metadata (please take a look at  scylla_metadata in sstables/type.hh).

**Comment by 851110504** [comment]
> For example, let's say you have partition A in sstable 1. Then you delete that partition A, the tombstone now exists in sstable 2. And new data is inserted into partition A, in sstable 3. After sstables 1,2,3 are merged by compaction, now you will have a partition record storing tombstone originally written in 2, and also live data written in 3.
> 
> And that partition or row tombstones are candidates to being dropped. And tombstones aren't immediately droppable, which is why we need a histogram and not a count. It can happen tombstone count is high, you start major compaction, yet compaction won't be able to purge any of them because they haven't expired yet.

I'm confused about why the tombstone information for partition A in sstable 2 is retained, given that there is new, active data written for partition A. Why can't it be cleaned up directly during the merge? Because of this, I want to modify the tombstone statistics. At this point, partition A is alive, so this tombstone information should not be included in the statistics.

**Comment by raphaelsc** [comment]
> > For example, let's say you have partition A in sstable 1. Then you delete that partition A, the tombstone now exists in sstable 2. And new data is inserted into partition A, in sstable 3. After sstables 1,2,3 are merged by compaction, now you will have a partition record storing tombstone originally written in 2, and also live data written in 3.
> > And that partition or row tombstones are candidates to being dropped. And tombstones aren't immediately droppable, which is why we need a histogram and not a count. It can happen tombstone count is high, you start major compaction, yet compaction won't be able to purge any of them because they haven't expired yet.
> 
> I'm confused about why the tombstone information for partition A in sstable 2 is retained, given that there is new, active data written for partition A. Why can't it be cleaned up directly during the merge? Because of this, I want to modify the tombstone statistics. At this point, partition A is alive, so this tombstone information should not be included in the statistics.

Tombstone GC is a distributed problem. You have to make sure all replicas have the tombstone, before it can be GCed. otherwise, replica that missed tombstone is at risk of data resurrection. Tombstone is only a record of deletion, statistics tells us how many tombstones there are in the sstable, and the fact partition A has live data, doesn't result in tombstone not having any effect. 

Also, tombstone could still be shadowing data in other sstables, and therefore it cannot removed. For example, sstable 1 has partition A. sstable 2 has tombstone for that partition A, shadowing data in sstable 1, and sstable 2 also has live data for that same partition A written later than the tombstone. tombstone in sstable 2 cannot be removed, otherwise you are at risk of having data resurrection.

We can't have a tombstone count that will ignore tombstones.

**Comment by raphaelsc** [comment]
I need a motivation (problem statement), so maybe I can help you with the solution. Without that, we'll probably not make forward progress here.

**Pull request closed without merging**
