### PR TITLE
[Backport 5.2] properly update storage service after schema changes

### PR DESCRIPTION
**Pull request by bhalevy**
This is a backport of https://github.com/scylladb/scylladb/pull/14158 to branch 5.2

### CODE REVIEW

**Review by ptrsmrn — APPROVED** [review]

**Comment by denesb** [comment]
This is a pretty big change to a very sensitive area of the code. I don't know how to evaluate this for backport.

**Comment by ptrsmrn** [comment]
> This is a pretty big change to a very sensitive area of the code. I don't know how to evaluate this for backport.

@denesb I can only offer some background. This change is already in OSS and `enterprise`, we need it in `branch-2023.1` in enterprise for 1 dtest to start to pass - https://github.com/scylladb/scylla-enterprise/issues/3539

**Comment by denesb** [comment]
> > This is a pretty big change to a very sensitive area of the code. I don't know how to evaluate this for backport.
> 
> @denesb I can only offer some background. This change is already in OSS and `enterprise`, we need it in `branch-2023.1` in enterprise for 1 dtest to start to pass - [scylladb/scylla-enterprise#3539](https://github.com/scylladb/scylla-enterprise/issues/3539)

That is not what I mean, I could infer the above myself.

We have some (vague) guidelines on how to decide what changes qualify for a backport and what not. Something along the line of some risk/reward ration -- simple bugs justify backporting only simple fixes, severe bugs can justify backporting complicated and risky changes. I don't know how to evaluate this equation here. The change looks risky. On the other hand, a single flaky test doesn't sound very severe.

**Comment by ptrsmrn** [comment]
I generally agree, but replying to:

> On the other hand, a single flaky test doesn't sound very severe

greening 2023.1 is a P1, and we already put lots of effort into stabilizing it. Perhaps @mykaul could comment?

**Comment by denesb** [comment]
Queued.

**Pull request merged**
