### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by nyh**
* seastar ae8449e0...e0d515b6 (24):
  > reactor: poll less frequently in debug mode

This change can speed up Scylla's debug-mode tests two-fold!

  > build: s/exec_program/execute_process/
  > test: add more tests for app_template
  > rpc/rpc_types: add formatter for rpc::optional<T>
  > exception_hacks: do not initialize phdrs_cache multiple times
  > core: cleanup left bits
  > memory: do not set_reclaim_hook if cpu_mem_ptr is not set
  > circleci: do not set disable dpdk explicitly
  > fair_queue: Do not pop unplugged class immediately
  > build: install Finducontext.cmake and FindSystem-SDT.cmake
  > treewide: include used headers
  > httpd: add test for redirect exception
  > http: make redirect_exception work from inside futures
  > http: permit custom status on redirect_exception
  > build: define SEASTAR_COROUTINES_ENABLED for Seastar module
  > seastar.cc: include "core/prefault.hh"
  > build: enable build C++20 modules with GCC 14
  > build: replace seastar_supports_flag() with check_cxx_compiler_flag()
  > build: remove space after ": "
  > build: remove spaces around "="
  > build: add two empty lines between top-level function definitions
  > circleci: build with dpdk enabled
  > build: add "--enable-cxx-modules" option to configure.py
  > build: use a different *_CMAKE_API for CMake 3.27

### CODE REVIEW

**Comment by nyh** [comment]
I'm creating this PR so that it will:
1. Test that the Seastar update doesn't break anything.
2. If CI passes, will allow me or any other maintainer to easily merge it.

**Comment by nyh** [comment]
The Boost test offstrategy_incremental_compaction_test failed, but I don't see any information. I'll try the CI again, maybe this is a flaky test - or maybe not (I can't create an issue about it because I don't have any information on what failed).

**Comment by avikivity** [comment]
https://github.com/scylladb/scylladb/pull/16510

**Comment by nyh** [comment]
I don't understand what dtest failed on. Looks like a generic "timeout" and I can't figure out where. I'm restarting the CI :-(

@avikivity please let me know if you updated the Seastar submodule already in another means, and this PR is no longer needed.

**Comment by avikivity** [comment]
It's not needed.

**Pull request closed without merging**
