### PR TITLE
Update tools/java submodule

### PR DESCRIPTION
**Pull request by denesb**
* tools/java 4ee15fd9...88809606 (2):
  > Update Scylla Java driver to 3.11.5.3.
  > install-dependencies.sh: s/python/python3/

[botond: regenerate toolchain image]

### CODE REVIEW

**Comment by denesb** [comment]
Submodule update is from a fork, will push the submodule update to origin once CI passes.

**Comment by denesb** [comment]
> > Submodule update, no backport needed.
> 
> I believe a backport is needed. [scylladb/java-driver@3.11.5.2...3.11.5.3](https://github.com/scylladb/java-driver/compare/3.11.5.2...3.11.5.3) shows the changelog - 2 dependency fixes among them.

This PR bundles two changes, just because both requires submodule updates.
We will backport the individual changes if needed, but not the entire submodule updates (we cannot directly backport those anyway).

**Comment by denesb** [comment]
CI passed, I pushed tools/java:master, updated the commit with the correct remote and queued (I don't think there is a point in another CI, the content is identical).

**Comment by denesb** [comment]
> > > Submodule update, no backport needed.
> > 
> > 
> > I believe a backport is needed. [scylladb/java-driver@3.11.5.2...3.11.5.3](https://github.com/scylladb/java-driver/compare/3.11.5.2...3.11.5.3) shows the changelog - 2 dependency fixes among them.
> 
> This PR bundles two changes, just because both requires submodule updates. We will backport the individual changes if needed, but not the entire submodule updates (we cannot directly backport those anyway).

On second thought I added backport labels. Just to remind us that there is backport work to be done here, even if the bot won't be able to do it.

**Comment by yaronkaikov** [comment]
@denesb this is breaking Gating, the updated toolchain doesn't support `aarch64`

**Comment by yaronkaikov** [comment]
@denesb you can push this change again 
image

**Comment by denesb** [comment]
Thanks @yaronkaikov!

**Pull request closed without merging**
