### PR TITLE
Update tools/cqlsh submodule

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh b9a606f...45a6f68 (10):
  > pylib/setup, requirement.txt: remove Six
  > setup: do not support python2
  > install.sh: install files with correct permission in struct umask settings
  > Remove unneed LC_ALL=en_US.UTF-8
  > Support using other driver (datastax or older scylla ones)
  > Fix RPM based downgrade command on scylla-cqlsh
  > gitignore: ignore pylib/cqlshlib/__pycache__
  > dist/redhat: add a proper changelog entry
  > github actions: enable starting on tags
  > Add support for building docker image

### CODE REVIEW

**Comment by fruch** [comment]
@avikivity some fixes of the fallout of the change to scylla-cqlsh

and last one should be (and also in docs), downgrading with RPMs is new extra step:
https://github.com/scylladb/scylla-cluster-tests/pull/5939

**Comment by michoecho** [comment]
CI failed due to #13211

**Comment by tchaikov** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/312/

#13276

**Comment by fruch** [comment]
@scylladb/scylla-maint I think CI has proven cqlsh is o.k., other failures are not unique to the PR (should be handled), but should prevent merging this PR

**Comment by fruch** [comment]
@syuu1228 changes are mostly related to packaging, can you review this one ?

**Review by syuu1228 — APPROVED** [review]
LGTM.

**Comment by denesb** [comment]
> @scylladb/scylla-maint I think CI has proven cqlsh is o.k., other failures are not unique to the PR (should be handled), but should prevent merging this PR

I re-kicked CI. We need a passing CI on all non-trivial PRs. The non-related failures can potentially hide related failures.

**Comment by tchaikov** [comment]
@fruch hi Israel, could you help merge and piggyback https://github.com/scylladb/scylla-cqlsh/pull/18 in this change? so we can get #13222 fixed sooner?

**Comment by denesb** [comment]
> @fruch hi Israel, could you help merge and piggyback [scylladb/scylla-cqlsh#18](https://github.com/scylladb/scylla-cqlsh/pull/18) in this change? so we can get #13222 fixed sooner?

After CI succeeds, I will add the packaging changes on top. Those are not tested by CI anyway.

**Comment by fruch** [comment]
> > @scylladb/scylla-maint I think CI has proven cqlsh is o.k., other failures are not unique to the PR (should be handled), but should prevent merging this PR
> 
> I re-kicked CI. We need a passing CI on all non-trivial PRs. The non-related failures can potentially hide related failures.

that's true, but in this case, there are only handful cases using cqlsh, and from my POV those were passing o.k. in both runs.
but 3rd is a winner :)

**Comment by tchaikov** [comment]
@fruch i think so. c7131a05741da13c96612da6223b90f914b6b7ee is a superset of this commit.

**Comment by denesb** [comment]
Now that I think of it I could have added "Closes: #13328" to the commit manually so we don't have to keep track of when the promotion happens. But anyway the commit was promoted so all is well.

**Pull request closed without merging**
