### PR TITLE
docs: how to run scylla with monitoring

### PR DESCRIPTION
**Pull request by sitano**
add a doc to Docker Hub description on how to run Scylla with monitoring.

Related PR in scylla-monitoring, but can't be reused https://github.com/scylladb/scylla-monitoring/pull/1181.

### CODE REVIEW

**Comment by sitano** [comment]
We have discussed with Tzach that I need to rework it to use default scylla-monitoring start-all.sh script if it possible for this doc section.

**Comment by tzach** [comment]
@amnonh please comment
I'm worried we are duplicating info from the monitoring stack into this project

**Comment by sitano** [comment]
@tzach it's just a description of how to run monitoring manually with docker and prometheus, without implying scylla-monitoring. Nothing special. Mostly it's a squeeze of Scylla-monitoring scripts that demonstrate the simple approach.

**Comment by tzach** [comment]
mentioning Scylla Monitoring in docker hub page make sense, but IMHO we should not copy content from the monitoring Stack, rather link to it.
@annastuchlik can you please send a new PR?

**Pull request closed without merging**
