### PR TITLE
[test.py] Unbreak cql-pytest and alternator

### PR DESCRIPTION
**Pull request by xtrey**
Provide possibility to run pytest without explicitly providing mode parameter

### CODE REVIEW

**Review by nyh — COMMENTED** [review]
I'm not happy about this fix. It just circumvents the layering violation by making this "mode" stuff optional. But we still have garbage in test/alternator/conftest.py et al which adds two bizarre options that aren't needed, and then calls some external "test.py"-specific code to register this stuff which test/alternator/conftest.py shouldn't have ever imported or called :-(

By why?

If test.py wants to do that registration stuff, let it do it on its own. Why does it need to pass this into test/alternator/conftest.py which doesn't need these option?

And the help messages you put on the "--mode" option is misleading. You wrote "tests can use it to adjust their behavior", but this isn't true - no test wants to do this, and shouldn't do this. A test shouldn't know how Scylla was run for it - it can be some ancient version of Scylla, or even Cassandra.  If a test needs some specific mode-related feature, such as injection, it can check that - not the build mode. See for example scylla_inject_error() in test/cql-pytest/rest_api.py: This function will only work if running against a modern version of Scylla with injections compiled in, and will skip the test on Cassandra or some wrong build mode.

**Comment by nyh** [comment]
I'll merge this PR. As I said, I'm not happy about this patch - I don't like introducing bizarre paths and imports into test/*/conftest.py and don't like introducing configuration parameters that users shouldn't use and won't know when to use, and don't even fit the model of "run pytest on an already running server". But this PR will unblock my own work, so I'll merge it for now. Please reconsider the whole approach later in a different PR.

**Comment by xtrey** [comment]
> I'm not happy about this fix. It just circumvents the layering violation by making this "mode" stuff optional. But we still have garbage in test/alternator/conftest.py et al which adds two bizarre options that aren't needed, and then calls some external "test.py"-specific code to register this stuff which test/alternator/conftest.py shouldn't have ever imported or called :-(
> 
> By why?
> 
> If test.py wants to do that registration stuff, let it do it on its own. Why does it need to pass this into test/alternator/conftest.py which doesn't need these option?
> 
> And the help messages you put on the "--mode" option is misleading. You wrote "tests can use it to adjust their behavior", but this isn't true - no test wants to do this, and shouldn't do this. A test shouldn't know how Scylla was run for it - it can be some ancient version of Scylla, or even Cassandra. If a test needs some specific mode-related feature, such as injection, it can check that - not the build mode. See for example scylla_inject_error() in test/cql-pytest/rest_api.py: This function will only work if running against a modern version of Scylla with injections compiled in, and will skip the test on Cassandra or some wrong build mode.

test.py is invoking pytest under the hood. conftest.py file is a configuration for pytest, not test.py. These two bizzare options needed to distinguish test executed several times and for different modes. You was one of the people who complained that there is a bug in jenkins results that was showing incorrect test. This is the good enough way to fix it.

**Comment by nyh** [comment]
> test.py is invoking pytest under the hood. conftest.py file is a configuration for pytest, not test.py. These two bizarre options needed to distinguish test executed several times and for different modes.

Why does **pytest** or any of the tests in it need to distinguish which run this is?
They don't.
It's something that Jenkins (or test.py) needs to distinguish - the output of the different runs it is running - not the individual pytest run.
Anyway, pytest already has an option of where to place the output file. Or test.py wants to move that file between runs, or rename it, it can also do that.

> You was one of the people who complained that there is a bug in jenkins results that was showing incorrect test. This is the good enough way to fix it.

I honestly think that this approach is missing the "purpose" of test/alternator/conftest.py. Alternator's conftest doesn't need to know about "build mode" - I don't WANT to know about build mode and don't want tests to rely on it, or forget that those tests don't even always run on Scylla. I don't want Alternator's conftest.py to import bizarre registration libraries that don't make any sense when not run through test.py.

I wouldn't mind terribly if eventually, Alternator's pytest will have some sort of option to let it run Scylla itself instead of assuming someone has already run it. I know you're planning this. BUT, if you do that, you should always remember that this is an **option**. People will still be able to run Alternator's pytest against the Scylla they ran themselves, or against DynamoDB or against DynamoDB local. This parameter would be optional, and its help string will explain that its optional and the README.md would explain how to use the different options. We won't just pretend that because Jenkins wants it - it's suddenly mandatory, or the help string can suggest it is somehow necessary.

> Regarding the help is just copy paste that you can find almost in any conftest, since we do not provide centralized conftest where we will be able to do thing one time instead of jumping on different files and making adoptions and fixes for each folder.

I don't know where you copy-pasted this "--mode" thing, but as I explained here and in several comments before, "--mode" should NOT be used by Alternator tests, and I don't want a help string suggesting that tests should start to use it. They shouldn't. 

> I'm more than happy to leave alternator and cql-pytest for you and never touch them at all. But in that case please accept responsibility for all issues that we have or which will appear in the future: issues with non-unique names, problems with concurrency, resource consumption etc.

You gave me two options, but I want to suggest two other options:
3. If you modify test/alternator/conftest.py, you do this after understanding fully its goals - which DO NOT END with running in Jenkins. If you don't understand its goals fully, you can wait for my review on these files.
4. You can avoid the monolithic approach that the test/pylib developers have been taking, and start thinking what it means - what it **really means** for test.py to run different test suites which **are not** tightly integrated. Some might even use different languages (!!) and shouldn't call code from each other. Yes, you can stuff weird imports into the Alternator test suite and add options, but how will you do this in the C++ test suite? What if one day we want a Rust test suite?. Test.py could run a test suite in a temporary directory, collect its output and THEN move it to the right place. It doesn't need to be tightly integrated with the test suite and teach it how to register itself and how it needs to handle the "run number".

To be honest, I still don't understand that that register() thing and "run number" you added to alternator/conftest.py is doing. Can you help me understand that?

Anyway, after merging this PR, I'm less frustrated, at least my way of running tests won't break, even if suddenly we have two weird options and an extra import. But what does still frustrate me is that it seems my ideas on writing tests are not getting across:
1. That it's important to write thousands of lines of tests (e.g., I just wrote this today: https://github.com/scylladb/scylladb/pull/19343...), it's not important to write thousands of line of test infrastructure before they serve thousands of lines of tst.
2. That in areas where we're compatible with competitors (i.e., CQL and DynamoDB API) it's important to run tests against our competitors. It drives me bonkers that not everyone understands that - to the point that I actually got opposition for https://github.com/scylladb/scylladb/issues/10098. It's not just about running tests on Scylla in Jenkins. The fact that test/cql-pytest/run-cassandra et al. has been broken for 3 days and nobody noticed makes me sad - but doesn't make be think it's any less important than it was before.

**Comment by xtrey** [comment]
> > test.py is invoking pytest under the hood. conftest.py file is a configuration for pytest, not test.py. These two bizarre options needed to distinguish test executed several times and for different modes.
>
> Why does **pytest** or any of the tests in it need to distinguish which run this is? They don't. It's something that Jenkins (or test.py) needs to distinguish - the output of the different runs it is running - not the individual pytest run. Anyway, pytest already has an option of where to place the output file. Or test.py wants to move that file between runs, or rename it, it can also do that.

You are simplifying the issue. I know that we can use different output locations, but during aggregation we still face the same issue: test names are the same. So we need additional information to make them unique, and at the same time we need to have connection between runs and env. That's why we need to additional parameters mode and run_id that actually are used only for test name modification.

> > You was one of the people who complained that there is a bug in jenkins results that was showing incorrect test. This is the good enough way to fix it.
>
> I honestly think that this approach is missing the "purpose" of test/alternator/conftest.py. Alternator's conftest doesn't need to know about "build mode" - I don't WANT to know about build mode and don't want tests to rely on it, or forget that those tests don't even always run on Scylla. I don't want Alternator's conftest.py to import bizarre registration libraries that don't make any sense when not run through test.py.
>
> I wouldn't mind terribly if eventually, Alternator's pytest will have some sort of option to let it run Scylla itself instead of assuming someone has already run it. I know you're planning this. BUT, if you do that, you should always remember that this is an **option**. People will still be able to run Alternator's pytest against the Scylla they ran themselves, or against DynamoDB or against DynamoDB local. This parameter would be optional, and its help string will explain that its optional and the README.md would explain how to use the different options. We won't just pretend that because Jenkins wants it - it's suddenly mandatory, or the help string can suggest it is somehow necessary.
>

The idea is not changed: possibility to run through test.py and with pytest, possibility to start cluster or use provided for any test.

> > Regarding the help is just copy paste that you can find almost in any conftest, since we do not provide centralized conftest where we will be able to do thing one time instead of jumping on different files and making adoptions and fixes for each folder.
>
> I don't know where you copy-pasted this "--mode" thing, but as I explained here and in several comments before, "--mode" should NOT be used by Alternator tests, and I don't want a help string suggesting that tests should start to use it. They shouldn't.
>

You are forgetting one thing, that alternator test are executed through test.py->pytest with PythonTestSuite. Test.py needs this to start cluster with a correct mode.

> > I'm more than happy to leave alternator and cql-pytest for you and never touch them at all. But in that case please accept responsibility for all issues that we have or which will appear in the future: issues with non-unique names, problems with concurrency, resource consumption etc.
>
> You gave me two options, but I want to suggest two other options: 3. If you modify test/alternator/conftest.py, you do this after understanding fully its goals - which DO NOT END with running in Jenkins. If you don't understand its goals fully, you can wait for my review on these files. 4. You can avoid the monolithic approach that the test/pylib developers have been taking, and start thinking what it means - what it **really means** for test.py to run different test suites which **are not** tightly integrated. Some might even use different languages (!!) and shouldn't call code from each other. Yes, you can stuff weird imports into the Alternator test suite and add options, but how will you do this in the C++ test suite? What if one day we want a Rust test suite?. Test.py could run a test suite in a temporary directory, collect its output and THEN move it to the right place. It doesn't need to be tightly integrated with the test suite and teach it how to register itself and how it needs to handle the "run number".
>

Alternator tests are written in python and using pytest as a launcher. So stack is the same, and I don't see any reason to copy and paste the same logic in different files, this is very prone to human error and harder to maintain.
When there will be a RustSuite we will be passing what it needs to modify test names himself, the same as we do for PythonTestSuite.

> To be honest, I still don't understand that that register() thing and "run number" you added to alternator/conftest.py is doing. Can you help me understand that?
>

ReportPlugin is a simple *pytest* hook that modifies the test name enriching with information about mode and run_id. At the same time register() method is telling to pytest to register specified hook.

> Anyway, after merging this PR, I'm less frustrated, at least my way of running tests won't break, even if suddenly we have two weird options and an extra import. But what does still frustrate me is that it seems my ideas on writing tests are not getting across:
>
>     1. That it's important to write thousands of lines of tests (e.g., I just wrote this today: [test/cql-pytest: tests verifying UUID sort order #19343](https://github.com/scylladb/scylladb/pull/19343)...), it's not important to write thousands of line of test infrastructure before they serve thousands of lines of tst.
>
>     2. That in areas where we're compatible with competitors (i.e., CQL and DynamoDB API) it's important to run tests against our competitors. It drives me bonkers that not everyone understands that - to the point that I actually got opposition for [Create script for running test/cql tests against Cassandra #10098](https://github.com/scylladb/scylladb/issues/10098). It's not just about running tests on Scylla in Jenkins. The fact that test/cql-pytest/run-cassandra et al. has been broken for 3 days and nobody noticed makes me sad - but doesn't make be think it's any less important than it was before.

Nobody noticed because it's not executed in CI. It's not enough to write tests, they should be executed on some schedule, monitored, triaged and maintained.
I like the idea to run test against cassandra, but I don't like the idea of writing script instead of using pytest.
When someone is rejecting my idea, maybe I'm presenting it incorrectly. But when people around me reject my ideas, that's a sign for me that my ideas seem not so good as I thought.

**Comment by nyh** [comment]
> When someone is rejecting my idea, maybe I'm presenting it incorrectly. But when people around me reject my ideas, that's a sign for me that my ideas seem not so good as I thought.

You couldn't be further from the truth. The only reason why Alternator works out of the box for our customers and their existing DynamoDB applications is my insistence of writing hundreds of tests and the ability that I implemented to run all of them against DynamoDB, not scylladb. I don't understand if you and Kostja don't understand why I think it's important. I sill insist that it is.

**Comment by kbr-scylla** [comment]
> what it really means for test.py to run different test suites which are not tightly integrated. Some might even use different languages (!!) and shouldn't call code from each other

The different suites were coupled for a long time, importing from each other, hence all of these `sys.path` hacks that I hate and want to purge. We could continue pretending that they are not coupled but what's the point?

**Comment by nyh** [comment]
@kbr-scylla let's have this discussion after you spend an hour looking at test/alternator and test/cql-pytest in addition to the test/topology you're faniliar with, and tell me if you find more then 20 lines in common...

**Comment by kbr-scylla** [comment]
> That it's important to write thousands of lines of tests (e.g., I just wrote this today: https://github.com/scylladb/scylladb/pull/19343...), it's not important to write thousands of line of test infrastructure before they serve thousands of lines of tst.

This is probably the simplest type of test that is possible to write. A test which requires only a single node, needs to run a sequence of CQL statements on it and verify them against some expected output. What does your argument prove?

There's a chicken and egg problem there. Some tests **require** (a lot of) infrastructure. So how do you implement a test that requires infrastructure without first implementing that infrastructure?

Perhaps we could pretend that it's "not infrastructure" and for example write all the logic of setting up a distributed cluster inside a test file and then call it "test code" (thousands of lines of it!) instead of "infrastructure code". And then when another test case in another file needs to setup a cluster too, either copy-paste (another thousands of lines of tests, yay!) or do a `sys.path` hack or something to import from the other test file. But again what's the point? Better to put the infra code into a library or a framework that multiple tests can then use, and call it what it is.

I feel like we're having this discussion for the `n`th time.

> The fact that test/cql-pytest/run-cassandra et al. has been broken for 3 days and nobody noticed makes me sad - but doesn't make be think it's any less important than it was before.

Apparently you're the only person who uses it. If you want it to not break, there has to be a protection in CI (a regression test).

**Comment by xtrey** [comment]
> > When someone is rejecting my idea, maybe I'm presenting it incorrectly. But when people around me reject my ideas, that's a sign for me that my ideas seem not so good as I thought.
> 
> You couldn't be further from the truth. The only reason why Alternator works out of the box for our customers and their existing DynamoDB applications is my insistence of writing hundreds of tests and the ability that I implemented to run all of them against DynamoDB, not scylladb. I don't understand if you and Kostja don't understand why I think it's important. I sill insist that it is.

I still think that we **need** to run against Cassandra and DynamoDB as we are claiming the compatibility with them. But I can't understand why you are trying to persuade me in this when I fully agree with you, and I've mentioned this in previous message?

**Comment by nyh** [comment]
> This is probably the simplest type of test that is possible to write. A test which requires only a single node, needs to run a sequence of CQL statements on it and verify them against some expected output. What does your argument prove?

```
$ wc -l test/cql-pytest/**/*test*.py  test/alternator/**/*test*.py
63405
```

But it's "the simplest type of test", so I guess it doesn't matter and the lessons learned from it are not important.

> > The fact that test/cql-pytest/run-cassandra et al. has been broken for 3 days and nobody noticed makes me sad - but doesn't make be think it's any less important than it was before.
> 
> Apparently you're the only person who uses it. If you want it to not break, there has to be a protection in CI (a regression test).

What makes me sad isn't that this script broke (which, indeed, CI would have solved), but the fact that according to you (not even @xtrey), I'm the only person who thinks it's important to check our CQL features also against Cassandra (and DynamoDB) - the raison d'etre for these "run" scripts. The fact that the easy https://github.com/scylladb/scylladb/issues/10098 has been open for two years proves that you're right - many other developers don't care about Cassandra compatibility, we have an entire test suite which could have been run against Cassandra, but doesn't. But issues like https://github.com/scylladb/scylla-enterprise/issues/4253 show that users do care, and I'm not giving up on this Don Quixotic quest.

**Comment by nyh** [comment]
> I still think that we **need** to run against Cassandra and DynamoDB as we are claiming the compatibility with them. But I can't understand why you are trying to persuade me in this when I fully agree with you, and I've mentioned this in previous message?

Let me explain why your patch made me think you didn't fully agree with on this point:

My most basic point (forget all the nonsense about programming styles, languages, infrastructure size etc.) is that the **API functionality test suite** (test/cql-pytest and test/alternator) needs to run on **any implementation of that API**. It can be Scylla you compiled your self, can be some old version of Scylla you dug up, it can be some unknown version of Scylla run by a customer, or - importantly - it can be our competitors which implement the same API, e.g., Cassandra, DynamoDB, DynamoDB Local, and so on.

Once you realize **that**, you immediately understand that this suite cannot assume that the runner gives it some information like "build mode" which you added in your patch, and you don't even **think** of adding such a parameter. This "build mode" concept doesn't even make sense when running against Cassandra, or maybe you don't even know it if you run the test against some already running Scylla cluster. If one specific test only works on a specific build mode it should check what it needs (e.g., injections) and not the "build mode", with the understanding that these tests won't work on competitor APIs so these tests should be rare.

So, you might ask me - if I'm so against the the "build mode" and "run number" option, what would I have wanted?

My answer is simple: Go back to the problem you're _really_ trying to solve. The problem you're trying to solve is giving the runner or pytest an option to add a prefix to every test name. So.... Just do that! Add an option like "--test-name-prefix" or "--test-name-suffix", or something, which does this. test.py can use this option and use the build mode or run number or other test.py-only concepts. Users who want to run "pytest" directly won't need to pass this extra prefix option.

**Comment by nyh** [comment]
Another thought of something wrong that seems to be happening now:

Now when I run cql-pytest tests I get messages like:
```
test_limit.py::test_limit_full_table_scan 
test_limit.py::test_limit_full_table_scan.no_mode.1 PASSED
```

This looks like something which @avikivity repeatedly warned against in the past: If Jenkins remembers that the test called `test_limit.py::test_limit_full_table_scan.no_mode.1` is the test which failed, it's bad, because if the repetition number is part of the failed test's name, it means there is separate history for run 1 and run 2, when you look for a history of when this failed in the past.

Jenkins needs to consider the nine runs of the same test as **nine different runs** of **the same test**. It should consider them nine different tests, and shouldn't confuse them as one run.

**Comment by kbr-scylla** [comment]
> But it's "the simplest type of test", so I guess it doesn't matter and the lessons learned from it are not important.

I still don't understand what you are trying to prove. You're just saying that "look I wrote a lot of test code". Yes, I know that -- but I ask what you're trying to prove by saying this. Then you show that you indeed wrote a lot of test code by providing `wc -l` output. I believed you in the first place, so you didn't need to do that. You still didn't answer my question.

Just in case -- I'm not claiming that those tests are not important.

But it looks to me that you're claiming that the other type of tests -- the more complex ones, which require cluster operations -- are less important? Or what?

Please answer me this question: suppose the topology framework doesn't exist. No cluster management infrastructure. You're trying to implement a topology test that involves multiple nodes. What do you do?

**Comment by kbr-scylla** [comment]
> I'm the only person who thinks it's important to check our CQL features also against Cassandra (and DynamoDB) 

You're not. I also think it's important. But this is not the topic of this dispute.

The topic is not *what* should be done (I agree that checking stuff against Cassandra/DynamoDB is a very good idea) but *how* we do it.


If you commit a script to the ScyllaDB repository, but there's nothing that automatically checks if the script continues working with the interface you envisioned for it, don't be surprised if the script breaks from time to time.

---

BTW. there's a large difference between testing against Scylla vs testing against Cassandra or DynamoDB.
- Testing against Scylla needs to be done **on every change** that we commit to Scylla. It serves to prevent regressions.
- Testing against Cassandra/DynamoDB needs to be done **once** -- when you write the test. You only do it to check that indeed, the thing we have in Scylla corresponds to the thing that Cassandra does, and now we just need to continue making sure that Scylla continues doing that.

Unless, of course, we also want to check for regressions in Cassandra. But I don't think that's a good idea; we don't have control over those regressions. We need to check once, against a single Cassandra version that we chose to be compatible with for that particular piece of functionality.

Given that, do we really need a script serving only that second use case to be committed to the ScyllaDB repo?

**Comment by kbr-scylla** [comment]
> My answer is simple: Go back to the problem you're really trying to solve. The problem you're trying to solve is giving the runner or pytest an option to add a prefix to every test name. So.... Just do that! Add an option like "--test-name-prefix" or "--test-name-suffix", or something, which does this. test.py can use this option and use the build mode or run number or other test.py-only concepts. Users who want to run "pytest" directly won't need to pass this extra prefix option.

With this I agree 100%, and in fact I suggested the same to @xtrey. Using `--mode` + `--run_id` in alternator/cql-pytest suites serves **only** to ensure test name uniqueness, so really, these are the wrong parameters to use. But apparently due to legacy (?) it was simpler to implement

**Comment by kbr-scylla** [comment]
> it means there is separate history for run 1 and run 2, when you look for a history of when this failed in the past.

I think this only applies to the built-in Jenkins history which doesn't work anyway (for me when I try to check this history, Jenkins always hangs...), we have our own collection mechanisms for ElasticSearch etc. and we can bucket test runs however we want -- e.g. according to their names only, without taking run ID into account.

**Comment by xtrey** [comment]
> > My answer is simple: Go back to the problem you're really trying to solve. The problem you're trying to solve is giving the runner or pytest an option to add a prefix to every test name. So.... Just do that! Add an option like "--test-name-prefix" or "--test-name-suffix", or something, which does this. test.py can use this option and use the build mode or run number or other test.py-only concepts. Users who want to run "pytest" directly won't need to pass this extra prefix option.
> 
> With this I agree 100%, and in fact I suggested the same to @xtrey. Using `--mode` + `--run_id` in alternator/cql-pytest suites serves **only** to ensure test name uniqueness, so really, these are the wrong parameters to use. But apparently due to legacy (?) it was simpler to implement

This is not a prefix that you can set how you like, it's always mode and run_id and should not be set in other way. So what the point to give separate parameter where you should take care of relation between them?

**Comment by xtrey** [comment]
> Another thought of something wrong that seems to be happening now:
> 
> Now when I run cql-pytest tests I get messages like:
> 
> ```
> test_limit.py::test_limit_full_table_scan 
> test_limit.py::test_limit_full_table_scan.no_mode.1 PASSED
> ```
> 
> This looks like something which @avikivity repeatedly warned against in the past: If Jenkins remembers that the test called `test_limit.py::test_limit_full_table_scan.no_mode.1` is the test which failed, it's bad, because if the repetition number is part of the failed test's name, it means there is separate history for run 1 and run 2, when you look for a history of when this failed in the past.
> 
> Jenkins needs to consider the nine runs of the same test as **nine different runs** of **the same test**. It should consider them nine different tests, and shouldn't confuse them as one run.

Well, but this contradicts to the information that I have. There is some discussion there how to treat results https://github.com/scylladb/scylladb/pull/17746.

**Comment by xtrey** [comment]
> > I still think that we **need** to run against Cassandra and DynamoDB as we are claiming the compatibility with them. But I can't understand why you are trying to persuade me in this when I fully agree with you, and I've mentioned this in previous message?
> 
> Let me explain why your patch made me think you didn't fully agree with on this point:
> 
> My most basic point (forget all the nonsense about programming styles, languages, infrastructure size etc.) is that the **API functionality test suite** (test/cql-pytest and test/alternator) needs to run on **any implementation of that API**. It can be Scylla you compiled your self, can be some old version of Scylla you dug up, it can be some unknown version of Scylla run by a customer, or - importantly - it can be our competitors which implement the same API, e.g., Cassandra, DynamoDB, DynamoDB Local, and so on.
> 
> Once you realize **that**, you immediately understand that this suite cannot assume that the runner gives it some information like "build mode" which you added in your patch, and you don't even **think** of adding such a parameter. This "build mode" concept doesn't even make sense when running against Cassandra, or maybe you don't even know it if you run the test against some already running Scylla cluster. If one specific test only works on a specific build mode it should check what it needs (e.g., injections) and not the "build mode", with the understanding that these tests won't work on competitor APIs so these tests should be rare.
> 
> So, you might ask me - if I'm so against the the "build mode" and "run number" option, what would I have wanted?
> 
> My answer is simple: Go back to the problem you're _really_ trying to solve. The problem you're trying to solve is giving the runner or pytest an option to add a prefix to every test name. So.... Just do that! Add an option like "--test-name-prefix" or "--test-name-suffix", or something, which does this. test.py can use this option and use the build mode or run number or other test.py-only concepts. Users who want to run "pytest" directly won't need to pass this extra prefix option.
 
Alternator test now PythonTestSuite test and are executing with test.py which needs this information. This mess with parameters is just inconsistency because we have 2 different launchers: test.py and run.
run_id needed for gathering logs for specific test and show them in one directory. Even this functionality is not in alternator eventually it will be there.

**Comment by nyh** [comment]
> Alternator test now PythonTestSuite test and are executing with test.py which needs this information. 

Since test.py is *running* the Alternator test, it has this information already.
I think you mean you want to cause pytest to add some sort of suffix to each test name. That's fine. But then this suffix should be called "test_name_suffix" and be optional - it shouldn't be called "mode"

> This mess with parameters is just inconsistency because we have 2 different launchers: test.py and run. run_id needed for gathering logs for specific test and show them in one directory. Even this functionality is not in alternator eventually it will be there.

The "2 different launchers" is a red herring. The problem is not the "launchers" - it is the fact that we really have multiple use cases - we have Jenkins, and we have running the same test against Cassandra / DynamoDB / old Scylla and so on. In the second use case, the concept of "mode" is simply irrelevant.

**Pull request closed without merging**
