### PR TITLE
Update stats-output.rst

### PR DESCRIPTION
**Pull request by comsky**
I read this doc to learn how to use nodetool commands, and I eventually found some typos in the docs. 😄

### CODE REVIEW

**Comment by nyh** [comment]
@avikivity do we need a signed CLA also for documentation patches?

**Comment by avikivity** [comment]
> @avikivity do we need a signed CLA also for documentation patches?

yes

**Comment by comsky** [comment]
I'll send a signed CLA according to the contributing guidelines!
thanks for mentioning it. @nyh

**Comment by comsky** [comment]
@avikivity I have sent a signed CLA. Is there any further action that I need to take?

**Comment by avikivity** [comment]
No, but we currently have a merge freeze so can't commit it just yet.

**Comment by denesb** [comment]
Merge freeze is over, queued.

**Pull request closed without merging**
