### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by avikivity**
* seastar 72c7ac575...ca5f6539e (10):
  > log: drop specialization of boost::lexical_cast for log_level
  > stall-detector: Remove unused _stall_detector_reports_per_minute
  > Merge 'when_all: add Sentinel support to when_all_succeed() ' from Kefu Chai
  > scripts/perftune.py: Implement AWS IMDSv2 call
  > net/tls: Add a way to disable certificate validation
  > tests: Improve websocket parser tests
  > scripts/stall-analyser: improve error messages on invalid input
  > reserve-memory: document that seastar just doesnt use the reserves
  > Merge 'Minor metrics memory optimizations' from Stephan Dollberg
  > json_formatter: Add support for standard range containers

Merging Seastar updates, none fix a bug that requires backport.

### CODE REVIEW

**Comment by avikivity** [comment]
Very odd:

```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 1 errors
ERROR 2024-12-09 17:42:36,565 [shard 0:main] seastar_memory - seastar/src/core/memory.cc:2126 @void seastar::memory::maybe_dump_memory_diagnostics(size_t, bool): failed to log message: fmt='Failed to allocate {} bytes at {}': std::__ios_failure (error iostream:1, basic_ios::clear: iostream error)"
```

Could be that it ran out of memory so badly that the logging failed on OOM.

**Comment by avikivity** [comment]
Both dtest failures were the same test, with the same error. Doubly odd.

**Comment by avikivity** [comment]
Does not reproduce locally.

**Comment by mykaul** [comment]
> strange enough, i was able to reproduce this issue with the release build. and after reverting [scylladb/seastar@05b20c8](https://github.com/scylladb/seastar/commit/05b20c8612e0cade7d8f7c259c7d1a53166161c2), the issue went away. but i cannot figure out the root cause. anyway, i managed to create [scylladb/seastar#2572](https://github.com/scylladb/seastar/pull/2572), with which, the issue is addressed.

@tchaikov - and now with https://github.com/scylladb/seastar/pull/2572 , do we get a nice backtrace for the OOM, or there's no failure?

**Comment by tchaikov** [comment]
> > strange enough, i was able to reproduce this issue with the release build. and after reverting [scylladb/seastar@05b20c8](https://github.com/scylladb/seastar/commit/05b20c8612e0cade7d8f7c259c7d1a53166161c2), the issue went away. but i cannot figure out the root cause. anyway, i managed to create [scylladb/seastar#2572](https://github.com/scylladb/seastar/pull/2572), with which, the issue is addressed.
> 
> @tchaikov - and now with [scylladb/seastar#2572](https://github.com/scylladb/seastar/pull/2572) , do we get a nice backtrace for the OOM, or there's no failure?

the former -- a nice backtrace for the OOM. FWIW, this is also what i got after reverting scylladb/seastar@05b20c8](https://github.com/scylladb/seastar/commit/05b20c8612e0cade7d8f7c259c7d1a53166161c2 . let me be more specific, after reverting scylladb/seastar@05b20c8](https://github.com/scylladb/seastar/commit/05b20c8612e0cade7d8f7c259c7d1a53166161c2 or after applying my fmt::format change, the test completed with the OOM error:
```console
$ JAVA_HOME=/usr/lib/jvm/jre-11 pytest -s --log-cli-level=debug -c $PWD/pytest.ini --cassandra-dir $HOME/dev/scylladb/build/RelWithDebInfo commitlog_test.py::TestCommitLog::test_mixed_mode_commitlog_same_partition_smp_2 --keep-test-dir     
=========== test session starts ======
...
========== 1 passed, 3 warnings in 8.28s ========
```

and in `$HOME/.dtest/dtest-qxd227im/test/node1/logs/system.log`
```
TRACE 2024-12-10 15:18:12,736 [shard 0:main] lsa - Releasing segment 0x60000ffe0000
DEBUG 2024-12-10 15:18:12,736 [shard 0:main] seastar_memory - Failed to allocate 131072 bytes at 0x130cf7e 0x130d2a0 0x130d598 0x122be82 0x122a60f 0x122a59f 0x122c6c5 0x5559036 0x13c9b3f 0x13c95c5 0x130ed96
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<int>, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda()#2}, seastar::future<int> >(scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}&&)::{lambda(seastar::internal::promise_base_with_type<int>&&, seastar::async<scylla_main(int, char**)::$_0::operator()() const::{lambda()#2}>(seastar::thread_attributes, auto:1&&, (auto:2&&)...)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
...
INFO  2024-12-10 15:18:17,140 [shard 0:main] init - Shutting down configurables
INFO  2024-12-10 15:18:17,140 [shard 0:main] init - Shutting down configurables was successful
INFO  2024-12-10 15:18:17,140 [shard 0:main] init - Scylla version 6.3.0~dev-0.20241210.cc9539158c2f shutdown complete.
```

**Comment by avikivity** [comment]
Looks like I can reproduce locally, if I use the correct ScyllaDB package.

**Comment by avikivity** [comment]
Now I'm confused, it passes for me with the backtrace formatting fix.

**Comment by avikivity** [comment]
Obsoleted by https://github.com/scylladb/scylladb/pull/21869

**Comment by mykaul** [comment]
I just had a private build (on top of 2024.2.2) failing test_mixed_mode_commitlog_same_partition_smp_1 with:
```
failed on teardown with "AssertionError: Unexpected errors found:
node1: 1 errors
ERROR 2024-12-31 13:26:43,398 [shard 0:main] seastar_memory - seastar/src/core/memory.cc:2130 @void seastar::memory::maybe_dump_memory_diagnostics(size_t, bool): failed to log message: fmt='Failed to allocate {} bytes at {}': std::bad_alloc (std::bad_alloc)"
```

@tchaikov - it's fixed via https://github.com/scylladb/seastar/pull/2572 , right?

**Comment by tchaikov** [comment]
yes.

**Pull request closed without merging**
