### PR TITLE
tools/scylla-nodetool: correct tablestats filtering

### PR DESCRIPTION
**Pull request by tchaikov**
before this change, we failed to apply the filtering of tablestats command in the right way:

1. `table_filter` failed to check if delimiter is npos before extract the cf component from the specified table name.
2. the stats should not included the keyspace which are not included by the filter.
3. the total number of tables in the stats report should contain all tables no matter they are filtered or not.

in this change, all the problems above are addressed. and the tests are updated to cover these use cases.

### CODE REVIEW

**Comment by tchaikov** [comment]
was testing on my local branch which included the refactor to extract the printers. repushed the fixed change.

**Review by denesb — APPROVED** [review]

**Comment by tchaikov** [comment]
this change conflicts with #17437. whichever lands first, i will rebase the other one.

**Comment by denesb** [comment]
> this change conflicts with #17437. whichever lands first, i will rebase the other one.

I didn't yet merge the above, but I already hit conflicts when trying to merge. Likely, some other nodetool related PR I queued this morning.

**Comment by tchaikov** [comment]
rebased onto master HEAD

**Pull request closed without merging**
