### PR TITLE
Update tools/jmx submodule

### PR DESCRIPTION
**Pull request by tchaikov**
this helps to use OpenJDK 11 instead of OpenJDK 8 for running scylla-jmx, in hope to alleviate the pain of the crashes found in the JRE shipped along with OpenJDK 8, as it is aged, and only security fixes are included now.

    Update tools/jmx submodule
    
 * tools/jmx 88d9bdc5...88d9bdc5 (7):
   > dist/redhat: split Requires items into multiple lines
   > dist/redhat: support jre 11 instead of jre 8
   > install.sh: point java to /usr/bin/java
   > install.sh: prefer Java 11 over Java 8
   > build: install java 11 instead of java 8
   > build: install JRE instead devel package
   > install.sh: detect java located under /usr/lib/jvm also

Refs https://github.com/scylladb/scylla-jmx/issues/194

### CODE REVIEW

**Comment by mykaul** [comment]
nit: the ref link is probably wrong - should be https://github.com/scylladb/scylla-jmx/issues/194 ?

**Comment by tchaikov** [comment]
ahh, indeed! fixed and repushed.

**Comment by tchaikov** [comment]
somehow, `git submodule summary tools/jmx` failed to list all commits in between `88d9bdc...48e1699` -- some merge commits were omitted.

**Comment by nyh** [comment]
> somehow, `git submodule summary tools/jmx` failed to list all commits in between `88d9bdc...48e1699` -- some merge commits were omitted.

If you can improve `scripts/refresh-submodules.sh` to fix this problem, it will be very helpful for the people who have to do this next time (including your future self). Thanks in advance :-)

**Comment by tchaikov** [comment]
> > somehow, `git submodule summary tools/jmx` failed to list all commits in between `88d9bdc...48e1699` -- some merge commits were omitted.
> 
> If you can improve `scripts/refresh-submodules.sh` to fix this problem, it will be very helpful for the people who have to do this next time (including your future self). Thanks in advance :-)


yes, i already have a patch. still working on the commit message. that's always the difficult part.

**Comment by tchaikov** [comment]
@avikivity i think, since we are installing `java-11-openjdk-headless` instead of `java-1.8.0-openjdk-headless` in https://github.com/scylladb/scylla-jmx/commit/19097f2d73d0c42e60f35d3d1fa4d231cfd4809b , and scylla-jmx now depends on jre-11, see https://github.com/scylladb/scylla-jmx/blob/master/dist/redhat/scylla-jmx.spec#L14 . shall we update the dbuild docker image with this new install-dependencies.sh ? or the existing dbuild image would not be able to fulfill the needs of the scylla-jmx rpm package?

**Comment by avikivity** [comment]
rpm and deb pull java from the distribution repositories, not the frozen toolchain.

But it's better to refresh the toolchain to avoid surprises.

**Comment by avikivity** [comment]
```
$ podman run  --rm docker.io/centos:7 yum info jre-11-headless
...
Error: No matching Packages to list
```

So, we lost the ability to run on centos 7.

**Comment by tchaikov** [comment]
thanks. thought it was a clean room building / runtime environment. that's a relief.

**Comment by tchaikov** [comment]
> ```
> $ podman run  --rm docker.io/centos:7 yum info jre-11-headless
> ...
> Error: No matching Packages to list
> ```
> 
> 
>      
>   
> 
> So, we lost the ability to run on centos 7.

shall i add the runtime dep back so it depends on jre-8 *or* jre-11, if this is a must-have or even a nice-to-have?

**Comment by nyh** [comment]
> ```
> $ podman run  --rm docker.io/centos:7 yum info jre-11-headless
> ...
> Error: No matching Packages to list
> ```
> 
> So, we lost the ability to run on centos 7.

Looks like I'm not going to review any more packaging-related patches in the near future, I didn't do a very good job at this review :-(

But it also means the CI might not be strong enough for our demands - because it didn't figure out that this broke our ability to run on CentOS 7.

**Comment by avikivity** [comment]
CI can't do everything.

**Comment by tchaikov** [comment]
> ```
> $ podman run  --rm docker.io/centos:7 yum info jre-11-headless
> ...
> Error: No matching Packages to list
> ```
> 
> So, we lost the ability to run on centos 7.

@avikivity 
i think the reason you had this output was that `jre-11-headless` is *provided* by `java-11-openjdk-headless`. so `yum info` is not able to find this package.

on my fedora 37 box, i have the same output
```console
$ lsb_release -c
Codename:       ThirtySeven
$ dnf info jre-11-headless
Last metadata expiration check: 0:02:06 ago on Thu 30 Mar 2023 10:33:58 AM CST.
Error: No matching Packages to list
$ dnf whatprovides jre-11-headless
Last metadata expiration check: 0:03:19 ago on Thu 30 Mar 2023 10:33:58 AM CST.
java-11-openjdk-headless-1:11.0.17.0.1-0.1.ea.fc37.x86_64 : OpenJDK 11 Headless Runtime Environment
Repo        : fedora
Matched from:
Provide    : jre-11-headless = 1:11.0.17.0.1-0.1.ea.fc37

java-11-openjdk-headless-1:11.0.18.0.10-1.fc37.x86_64 : OpenJDK 11 Headless Runtime Environment
Repo        : @System
Matched from:
Provide    : jre-11-headless = 1:11.0.18.0.10-1.fc37

java-11-openjdk-headless-1:11.0.18.0.10-1.fc37.x86_64 : OpenJDK 11 Headless Runtime Environment
Repo        : updates
Matched from:
Provide    : jre-11-headless = 1:11.0.18.0.10-1.fc37

$ podman run  --rm docker.io/centos:7 yum whatprovides jre-11-headless                            
Trying to pull docker.io/library/centos:7...                                                                           
Getting image source signatures                            
Copying blob 2d473b07cdd5 done                             
Copying config eeb6ee3f44 done                                                                                         
Writing manifest to image destination                                                                                  
Storing signatures                                         
Loaded plugins: fastestmirror, ovl                         
Determining fastest mirrors                                                                                            
 * base: ftp.sjtu.edu.cn                                                                                               
 * extras: ftp.sjtu.edu.cn                                 
 * updates: mirrors.ustc.edu.cn                            
1:java-11-openjdk-headless-11.0.8.10-1.el7.i686 : OpenJDK Headless Runtime                                             
                                                : Environment 11                                                       
Repo        : base                                         
Matched from:                                              
Provides    : jre-11-headless = 1:11.0.8.10-1.el7                                                                      
....
```

see also https://centos.pkgs.org/7/centos-x86_64/java-11-openjdk-headless-11.0.8.10-1.el7.x86_64.rpm.html

**Comment by tchaikov** [comment]
> > ```
> > $ podman run  --rm docker.io/centos:7 yum info jre-11-headless
> > ...
> > Error: No matching Packages to list
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, we lost the ability to run on centos 7.
> 
> ~shall i add the runtime dep back so it depends on jre-8 _or_ jre-11, if this is a must-have or even a nice-to-have?~
> 
> EDIT, not necessary.

just for myself and our posterity, the OSes we need to support is listed at https://github.com/scylladb/scylladb/blob/master/docs/getting-started/os-support.rst

**Pull request closed without merging**
