### PR TITLE
test/cql-pytest: test_tools.py: fix flaky schema load failure test

### PR DESCRIPTION
**Pull request by denesb**
The test TestScyllaSsstableSchemaLoading.test_fail_schema_autodetect was observed to be flaky. Sometimes failing on local setups, but not in CI. As it turns out, this is because, when run via test.py, the test's working directory is root directory of scylla.git. In this case, scylla-sstable will find and read conf/scylla.yaml. After having done so, it will try look in the default data directory (/var/lib/scylla/data) for the schema tables. If the local machine happens to have a scylla data-dir setup at the above mentioned location, it will read the schema tables and will succeed to find the tested table (which is system table, so it is always present). This will fail the test, as the test expects the opposite -- the table not being found.

The solution is to change the test's working directory to the random temporary work dir, so that the local environment doesn't interfere with it.

Fixes: #16828

### CODE REVIEW

**Comment by nyh** [comment]
By the way, if you really want NOT to use scylla.yaml, another option besides changing cwd, which is more self-explanatory, is to use something like "--options-file=/dev/null" (at least, I think this would work, I didn't checked).

**Review by nyh — APPROVED** [review]

**Comment by denesb** [comment]
@scylladb/scylla-maint @nyh ping.

**Comment by xemul** [comment]
Conflicts, please, rebase

**Comment by denesb** [comment]
Rebased.

**Pull request closed without merging**
