### PR TITLE
Fix a typo in the metric description of cas_dropped_prune

### PR DESCRIPTION
**Pull request by tzach**
Fix "perfom" to "perform"

### CODE REVIEW

**Comment by tzach** [comment]
In the future, it would be nice to automatically spell-check text in the code as part of the original PR.
Probably, such tools exist.

**Comment by mykaul** [comment]
Yay!

```
./db/heat_load_balance.cc:47: preperation ==> preparation
./db/heat_load_balance.cc:103: defintion ==> definition
./db/heat_load_balance.cc:108: probablities ==> probabilities
./db/heat_load_balance.cc:112: probablities ==> probabilities
./db/heat_load_balance.cc:117: probablities ==> probabilities
./db/heat_load_balance.cc:141: probablity ==> probability
./db/heat_load_balance.cc:144: noticable ==> noticeable
./db/heat_load_balance.cc:149: probablity ==> probability
./db/heat_load_balance.cc:150: probablities ==> probabilities
./db/heat_load_balance.cc:190: probablities ==> probabilities
./db/heat_load_balance.cc:190: probablities ==> probabilities
./db/heat_load_balance.cc:289: anway ==> anyway
./db/heat_load_balance.cc:396: alorithm ==> algorithm
./db/system_keyspace.cc:2815: convertor ==> converter
./db/system_keyspace.cc:3184: suply ==> supply
```

(random result from running 'codespell')

**Comment by tzach** [comment]
Nice. Can codespell send a PR?

**Comment by mykaul** [comment]
Fixed in commit 862909ee4f6ee7426d62e74a591e52bcca420a27
Can be closed.

**Pull request closed without merging**
