### PR TITLE
storage_service: join_token_ring: reject replace on different dc or rack

### LINKED ISSUE #16858: Scylla allows replacing a node in one dc/rack with a node in a different dc/rack
Currently, when replacing a node, scylla doesn't check if the new node resides in the same dc and rack as the old node.
With network topology replication strategy this can lead into a state when the replication map changes in a way that is incompatible with our replace node operation that just rebuild the token ranges previously owned by the old node onto the new node.
But if the new node changes the topology, the mapping isn't not that trivial anymore and one must run full cluster repair and then cleanup all nodes (except the new one) to make sure the cluster conforms to the new topology, yet this is not the intention of replace node.
If a user really wants that, they should remove the old node and bootstrap the new one in the new dc/rack location.
Or if and when we support ignore-nodes with bootstrap one can add the new node first, ignoring the dead node, and then remove it.  This should be the default procedure done under the hood for tablet node replacement.

### PR DESCRIPTION
**Pull request by bhalevy**
Do not allow replacing a node on one dc/rack
with a node on a different dc/rack as this violates the assumption of replace node operation that
all token ranges previously owned by the dead
node would be rebuilt on the new node.

Fixes #16858
Refs scylladb/scylla-enterprise#3518

Reproducer test submitted as https://github.com/scylladb/scylla-dtest/pull/3881

* Needs backport to live branches

### CODE REVIEW

**Comment by bhalevy** [comment]
This change may depend on https://github.com/scylladb/scylladb/pull/15788
or we should allow replacing UNKNOWN_DC/UNKNOWN_RACK

**Comment by bhalevy** [comment]
Updated https://github.com/scylladb/scylla-dtest/pull/3881 to require https://github.com/scylladb/scylladb/issues/15787 for the failed dtests above.

**Comment by bhalevy** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6928/)
> ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6928/)
> ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/89/)
> ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8126/)

https://github.com/scylladb/scylladb/issues/14757

> ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6928/)

**Comment by bhalevy** [comment]
@kbr-scylla now that https://github.com/scylladb/scylladb/issues/15787 is fixed this PR can be merged.

Let me know if you to change Fixes to Refs in the patch commit message
to keep the issue opened for the raft-based fix.
Although this will still block the dtest from running as it depends on https://github.com/scylladb/scylladb/issues/16858
so maybe we should open a new issue to cover the raft topology changes path.

**Comment by bhalevy** [comment]
> @kbr-scylla now that #15787 is fixed this PR can be merged.
> 
> Let me know if you to change Fixes to Refs in the patch commit message to keep the issue opened for the raft-based fix. Although this will still block the dtest from running as it depends on #16858 so maybe we should open a new issue to cover the raft topology changes path.

ping @kbr-scylla

**Comment by kbr-scylla** [comment]
Looking at this patch again, I don't know why I wrote https://github.com/scylladb/scylladb/issues/16858#issuecomment-2006682053 -- perhaps the patch has changed, but if I understand correctly, the code path that this check runs on, is executed both for gossip-based and for raft-topology-based ops.

The branching of "are we running in raft-topology mode" is done later in the function:
```cpp
    if (raft_server) { // Raft is enabled. Check if we need to bootstrap ourself using raft
        rtlogger.info("topology changes are using raft");
```


so it should fix both cases and the aforementioned test should be passing.

@bhalevy did you indeed see that the test is still failing in raft-topology mode even with this patch?

**Comment by bhalevy** [comment]
> Looking at this patch again, I don't know why I wrote [#16858 (comment)](https://github.com/scylladb/scylladb/issues/16858#issuecomment-2006682053) -- perhaps the patch has changed, but if I understand correctly, the code path that this check runs on, is executed both for gossip-based and for raft-topology-based ops.
> 
> The branching of "are we running in raft-topology mode" is done later in the function:
> 
> ```c++
>     if (raft_server) { // Raft is enabled. Check if we need to bootstrap ourself using raft
>         rtlogger.info("topology changes are using raft");
> ```
> 
> so the patch should fix both cases and the aforementioned test should be passing.
> 
> @bhalevy did you indeed see that the test is still failing in raft-topology mode even with this patch?

No.  I rebased this branch and retested, and the following dtests pass both with gossip or raft topology changes:
- repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_replace_error_with_different_dc_or_rack
- repair_based_node_operations_test.py::TestRepairBasedNodeOperations::test_replace_node_after_cluster_restart (2 variants)
- replace_address_test.py::TestReplaceAddress::test_shutdown_all_and_replace_node (all 4 variants)

**Comment by bhalevy** [comment]
rebased and force-pushed to re-trigger CI

**Review by kbr-scylla — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Great, Qd

**Comment by bhalevy** [comment]
Removed backport-5.4 tag is it is too risky

**Comment by mykaul** [comment]
> Removed backport-5.4 tag is it is too risky

@bhalevy - why is it risky?

**Comment by bhalevy** [comment]
> > Removed backport-5.4 tag is it is too risky
> 
> @bhalevy - why is it risky?

Just because there is a relatively large numbet of conflicts to resolve.

I'm going to prepare a backport branch with prerequisite patches backported to it and then we'd be able to assess the risk better.

**Pull request closed without merging**
