### PR TITLE
test/topology: add read barrier

### PR DESCRIPTION
**Pull request by alecco**
Add read barrier for random table tests before query-based verifications.

### CODE REVIEW

**Comment by avikivity** [comment]
> Add read barrier for random table tests before query-based verifications.

Why?

**Review by kbr-scylla — COMMENTED** [review]
I suggested to do the read barrier, but now I'm not sure.
IMO we need answers to a few questions before we proceed:
1. we didn't see these particular tests failing earlier IIRC - why did they start failing now? It looks like a regression. What caused it?
2. read_barrier should not be necessary because the driver should wait for schema agreement after perfoming a schema change; all nodes should see the new table thanks to the wait. Does the wait happen in those failing tests? If it doesn't - why? If it does - then we may have some larger problem, on Scylla side.

**Comment by avikivity** [comment]
Patch changelogs should explain why they do things, not just summarize what they do.

**Comment by alecco** [comment]
There's another failure on these tests

https://jenkins.scylladb.com/job/scylla-master/job/next/6026/

```
___________________________ test_alter_verify_schema ___________________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7f4732278390>
random_tables = <test.pylib.random_tables.RandomTables object at 0x7f4732953990>

    @pytest.mark.asyncio
    async def test_alter_verify_schema(manager, random_tables):
        """Verify table schema"""
        cql = manager.cql
        assert cql is not None
        await random_tables.add_tables(ntables=4, ncolumns=5)
        await random_tables.verify_schema()
        # Manually remove a column
        table = random_tables[0]
        await cql.run_async(f"ALTER TABLE {table} DROP {table.columns[-1].name}")
>       with pytest.raises(AssertionError, match='Column'):
E       Failed: DID NOT RAISE <class 'AssertionError'>

test/topology/test_random_tables.py:52: Failed
```

**Comment by kbr-scylla** [comment]
> There's another failure on schema update for these tests. A test removing a table's column manually does not see it removed.

Now this is interesting, because `verify_schema()` already performs the read barrier, so it should have observed that the column is missing.

I'll try to repro and investigate.

**Comment by kbr-scylla** [comment]
Heh, interesting.

Our implementation of `read_barrier` in tests doesn't work:
```async def read_barrier(cql: Session, host: Host):
    """To issue a read barrier it is sufficient to attempt altering
       a non-existing table: in order to validate the DDL the node needs to sync
       with the leader and fetch latest group 0 state.
    """
    with pytest.raises(InvalidRequest, match="nosuch"):
        await cql.run_async("alter table nosuchkeyspace.nosuchtable with comment=''", host = host)

**Comment by kbr-scylla** [comment]
Heh, interesting.

Our implementation of `read_barrier` in tests doesn't work:
```
    with pytest.raises(InvalidRequest, match="nosuch"):
        await cql.run_async("alter table nosuchkeyspace.nosuchtable with comment=''", host = host)
```

because the error is thrown before we call `start_group0_operation()`.

cc @kostja

**Comment by kbr-scylla** [comment]
So I analyzed the failure and did some experimenting.

Unfortunately my conclusions are not too insightful. The root cause of the schema change test failures in both cases was that things are slow in debug mode on the `monster` machine, which leads to timeouts, which leads to failures.

The driver was behaving correctly and waiting for schema agreement. However, we do have a configured schema agreement timeout of 20 seconds. If this timeout is reached we skip schema agreement and the CQL statement finishes. The next statement may then fail if it depends on the previous schema change reaching all nodes, which happened in these tests.
```
07:57:14.806 DEBUG> Refreshing schema in response to schema change. {'target_type': 'TABLE', 'change_type': 'UPDATED', 'keyspace': 'test_1684299340339', 'table': 't_02'}
07:57:14.806 DEBUG> [control connection] Waiting for schema agreement
07:57:14.845 DEBUG> [control connection] Schemas mismatched, trying again
...
07:57:34.718 DEBUG> [control connection] Schemas mismatched, trying again
07:57:34.919 WARNING> Node 127.150.42.14:9042 is reporting a schema disagreement: {UUID('47f18692-bd87-3137-b87a-fafaf52e68fa'): [<DefaultEndPoint: 127.150.42.14:9042>, <DefaultEndPoint: 127.150.42.4:9042>], UUID('9e9eae25-5f80-300a-98c0-08059ef521c0'): [<DefaultEndPoint: 127.150.42.30:9042>]}
07:57:34.919 DEBUG> Skipping schema refresh due to lack of schema agreement
```


So why schema agreement wasn't reached in 20 seconds?
Out of 3 nodes, one was slower and constantly lagging behind. For example, node 1:
```
INFO  2023-05-17 07:56:02,387 [shard 0] schema_tables - Creating test_1684299340339.t_03 id=1ece7ef0-f46f-11ed-859e-fd7fe4482ef4 version=7f742875-0557-3d16-8dac-c951ca17e58c
```
node 2:
```
INFO  2023-05-17 07:56:01,589 [shard 0] schema_tables - Creating test_1684299340339.t_03 id=1ece7ef0-f46f-11ed-859e-fd7fe4482ef4 version=7f742875-0557-3d16-8dac-c951ca17e58c
```
but node 3 was 24 seconds late to notice this table:
```
INFO  2023-05-17 07:56:25,984 [shard 0] schema_tables - Creating test_1684299340339.t_03 id=1ece7ef0-f46f-11ed-859e-fd7fe4482ef4 version=7f742875-0557-3d16-8dac-c951ca17e58c
```

There are 2 sources from which a node learns about new schema mutations: `group0_state_machine::apply()` which applies entries from the Raft log and `migration_manager::on_change` which observes schema version changes in gossip and pulls schema directly from another node when it notices that it has changed.

Both sources were slow. It took about ~10 seconds to apply each command, causing the node to lag further and further behind with its group 0 state. Eventually it would only learn the newest schema from schema pulls because group 0 apply was far behind and it would apply old entries with schema mutations that the node already got from schema pulls.
But schema pulls were also slow, each taking ~20 seconds to perform.

I don't have an explanation for the slowness itself other than: it's debug mode + `monster` machine is slow and has slow disks (both failures happened on this machine) + there are many tests executing concurrently slowing everything down.

Although it is curious that one of the nodes was significantly falling behind while two of them were mostly going in sync together (like with creating the `test_1684299340339.t_03` table above, they applied the change in the same second). So maybe there's an underlying problem which causes one of the nodes to slow down compared to others?

I also noticed that in both failures, the clusters were reused in a sequence of tests: test_concurrent_schema.py and test_random_tables.py. I hypothesised that maybe the combined schema changes from these tests made the schema state grow (accumulating tombstones or whatever), making it harder to apply further schema changes. But after running the same sequence of tests on my laptop while reusing the same cluster a bunch of times, I didn't observe any significant increase in how long it takes to perform further schema changes. The longest time it took to pull schema on my laptop was ~4 seconds.

Another experiment I made is injecting a 10 seconds sleep into `group0_state_machine::apply()` on one of the nodes. Then it was easy to reproduce the schema agreement timeout by performing a sequence of schema changes quickly on the other nodes, because schema pulls are scheduled only about once in 60 seconds. But in the test the schema pulls were happening continuously one after another, except each took a long time.

So summarizing: the cause of the failures was slowness, which is expected in debug mode on a slow machine, but is the slowness itself caused by some recent performance regression, or is it just our slow machines getting slower with time, or our test suite growing larger and putting more strain on the machines? This I don't know how to determine.

For now I don't see solution other than increasing the schema agreement timeout.

cc @kostja @tgrabiec

**Comment by kostja** [comment]
Let's try to repro locally in dev mode by adding a sleep injection into apply on one of the  nodes.

**Comment by kbr-scylla** [comment]
> Let's try to repro locally in dev mode by adding a sleep injection into apply on one of the nodes.

Here's a reproducer
https://github.com/kbr-scylla/scylladb/commit/b556f170ea76695e035aeccc2dd9764f7ed91ad5

but the failure in this reproducer has a different cause than the observed CI/next failures:
- in the reproducer, we fail because once a node has bootstrapped and a minute has passed, schema pulls are scheduled ~once every 1 minute (`migration_manager::migration_delay`) (but once a pull is scheduled, it takes less than 1 second to finish)
- in the CI/next failures, we failed because schema pulls were slow (they take 20-30 seconds to finish)

**Comment by kostja** [comment]
@alecco please close this pull request now that the root cause is identified to be different.

**Pull request closed without merging**
