### PR TITLE
docs: add swagger ui extension

### PR DESCRIPTION
**Pull request by dgarcia360**
Depends on https://github.com/scylladb/scylladb/pull/18252

Closes https://github.com/scylladb/scylladb/issues/8180

## Motivation

Renders the API Reference from [api/api-doc](https://github.com/scylladb/scylladb/tree/master/api/api-doc) using [Swagger UI 2.2.10](https://github.com/swagger-api/swagger-ui?tab=readme-ov-file#compatibility).

## Limitations

- **Schemas from external files:** Some of the "Storage proxy" endpoints define schemas that are loaded from a external file named `utils.json` ([example](https://github.com/scylladb/scylladb/blob/master/api/api-doc/storage_proxy.json#L725)). This version of Swagger UI does not support including schemas from different files, which results in these schemas not being rendered.

- **Navigation highlighting issues:** The right-side navigation highlighting does not behave as expected. When a heading is clicked, sometimes it incorrectly highlights the previous section instead of the current one.  Will be fixed by https://github.com/scylladb/sphinx-scylladb-theme/pull/1092

## How to test

1. Clone this PR.
2. Build the docs:

    ```
    cd docs
    make preview
    ```
3. Open http://127.0.0.1:5500/reference/api-reference

    You should now view the API reference documentation.

### CODE REVIEW

**Comment by dgarcia360** [comment]
cc/ @annastuchlik

**Comment by dgarcia360** [comment]
Preview: http://previews.docs.scylladb.com/scylladb/18253/reference/api-reference/

**Comment by avikivity** [comment]
Should we update to more recent swagger? Does that cause any backwards compatibility problems?

**Comment by tzach** [comment]
Screen capture from the [preview](http://previews.docs.scylladb.com/scylladb/18253/reference/api-reference)
image

**Comment by mykaul** [comment]
I've looked at it. 
- I see no response other than '200' and I see no 'Headers' anywhere - I'm not sure it is what it is, or lack of coverage. I'm sure we do have other than 200 responses. Perhaps I've missed some.
- I see some have an example - most do not.
- Parameters in response are not alphabetically sorted.
- Do we support a response content type other than JSON?
- Examples are not truly examples, if they use 'string' everywhere for some values.

**Comment by mykaul** [comment]
> @mykaul Thanks for reviewing. The automation we've implemented takes the information from the source files and publishes it as part of the documentation. If some content is missing, it means that the source files must be updated, which is not the scope of this PR.
> 
> Following the discussion with @tzach, the goal is to publish the current API information and keep improving the API docs. @mykaul Are you OK with this approach? Do you have any suggestions about how it renders?

I'm OK. Note that you are also publishing API that has no public value such as test (for task manager) and error injection. I think they should be annotated as such.

**Comment by tzach** [comment]
We can tag the entire API doc as Experimental, adjusting expectations till we clean and improve the docs (mostly swagger source file). We did the same for Cloud API.

**Comment by dgarcia360** [comment]
@annastuchlik @tzach Tagged the page as experimental, adding (BETA) to the heading.

**Pull request closed without merging**
