### PR TITLE
Improve documentation-preview workflow

### PR DESCRIPTION
**Pull request by benipeled**
The Amplify PR preview recently added has no option to run against docs changes only but it triggers against all 
pull-requests and create a comment that is later deleted (part of the amplify-enhanced flow) - this flow creates too much noise

This change removes the Amplify workflow and implements the preview solution as part of the existing github-action workflow. The workflow is:

- Triggers for all doc changes, not just master/enterprise
- Docs preview will be published to S3 and hosted on a based-PR URL dev-docs.scylladb.com/repo-name/pr-number
- A PR comment will be posted with direct links to changed pages (mimic the amplify-enhanced flow)
- The preview content will be deleted from S3 once the PR will be merged/closed

Details: https://github.com/scylladb/sphinx-scylladb-theme/issues/852#issuecomment-1676818467

@dgarcia360 @annastuchlik @tzach

### CODE REVIEW

**Comment by tzach** [comment]
@dgarcia360 please review

**Comment by benipeled** [comment]
I thought we could make it work with the repo-fork permissions but seems like we have to go with the label-trigger as suggested by @dgarcia360. I'll adjust it.

**Comment by dgarcia360** [comment]
Some thoughts:

* We could create a separate workflow for triggering previews when the label is added. Then, `.github/workflows/docs-pr.yaml` could remain as it was.

* https://github.com/scylladb/scylladb/blob/master/amplify.yml could be deleted as part of this pull request.

* Instead of `dev-docs.scylladb.com` (all docs targets devs mainly), we could use a more descriptive subdomain name such as `previews.docs.scylladb.com` or `docs-previews.scylladb.com`.

**Comment by benipeled** [comment]
> Some thoughts:
> 
> * We could create a separate workflow for triggering previews when the label is added. Then, `.github/workflows/docs-pr.yaml` could remain as it was.

I tried to avoid the manual work and duplicate builds but I see no other options

> * Instead of `dev-docs.scylladb.com` (all docs targets devs mainly), we could use a more descriptive subdomain name such as `previews.docs.scylladb.com` or `docs-previews.scylladb.com`.

I don't mind changing it but it doesn't really matter, it's not a marketing site and no one is going to use this domain directly but click on the direct links. I'll change it to `previews.docs.scylladb.com`

**Comment by benipeled** [comment]
> > Some thoughts:
> > 
> > * We could create a separate workflow for triggering previews when the label is added. Then, `.github/workflows/docs-pr.yaml` could remain as it was.
> 
> I tried to avoid the manual work and duplicate builds but I see no other options
> 

Actually, if we can trust the content - we can add an add-label step on the docs-pr workflow and it will auto-trigger the new label workflow

**Comment by benipeled** [comment]
Another option is to generate the preview on a Jenkins pipeline triggered by the CI-Route pipeline (which already triggered for docs changes),
This way we save the need for manual intervation + allow (secure) build from forks

**Comment by annastuchlik** [comment]
> Another option is to generate the preview on a Jenkins pipeline triggered by the CI-Route pipeline (which already triggered for docs changes), This way we save the need for manual intervation + allow (secure) build from forks

@dgarcia360 @tzach Let's discuss this option in our weekly meeting.

**Comment by benipeled** [comment]
Closes in favor of https://github.com/scylladb/scylla-pkg/pull/3707

**Pull request closed without merging**
