### PR TITLE
gossip: Do not advertise SHUTDOWN gossip status

### PR DESCRIPTION
**Pull request by asias**
The SHUTDOWN status is a special NORMAL status. A node in SHUTDOWN status is part of the ring the same as NORMAL status. To simplify the handling, we can get rid of the SHUTDOWN status completely. There is no real difference between a node in SHUTDOWN status and a in NORMAL + DOWN status.

After this patch, when a node shutdown:

- The shutdown node does not advertise SHUTDOWN gossip status
- The shutdown node still sends the the SHUTDOWN rpc message
- The receivers of the SHUTDOWN rpc message do not change the status of the node to SHUTDOWN but only mark the node as DOWN, keep the node as NORMAL gossip status.

This way, other nodes still can mark the shutdown node as DOWN immediately while we have less gossip status in the system to handle and reason about.

For example, with this patch, we can now get rid of the hacks in f3bd7e9b8c6 to add LEFT status to avoid sending shutdown message.

```
// Need to set it otherwise gossiper will try to send shutdown on exit
co_await _gossiper.add_local_application_state({{
    gms::application_state::STATUS, gms::versioned_value::left({},
    _gossiper.now().time_since_epoch().count()) }});
```

### CODE REVIEW

**Comment by kostja** [comment]
I like the approach. Gossip purpose is failiure detection, and graceful shutdown is not a failure. I hope we will reflect graceful shutdown state in group0 at some point, but when it comes to gossip, having less state reduces confusion.

**Comment by bhalevy** [comment]
@tgrabiec WDYT?

**Comment by kostja** [comment]
@kbr-scylla could you please take over this pull request, i.e. review/fix/merge it within your team?
@gleb-cloudius

**Comment by kbr-scylla** [comment]
Principle of sufficient reason... There had to be a reason that SHUTDOWN state was introduced in the first place. Was it a simple mistake?

It should be given careful thought.

Maybe it's for nodes that did not manage to receive RPC, but we still want them to notice the graceful shutdown fast (faster than failure detector's 20 seconds)?

What about the drivers? Don't they rely on SHUTDOWN somehow?

Perhaps we have dtests that could help us answer the question?

**Comment by kbr-scylla** [comment]
> @kbr-scylla could you please take over this pull request, i.e. review/fix/merge it within your team?

For now I'm closing this PR, instead I opened https://github.com/scylladb/scylladb/issues/18552 and put it into backlog.

**Comment by kostja** [comment]
* Kamil Braun ***@***.***> [24/05/07 20:58]:
> > @kbr-scylla could you please take over this pull request, i.e. review/fix/merge it within your team?
> 
> For now I'm closing this PR, instead I opened https://github.com/scylladb/scylladb/issues/18552 and put it into backlog.

Gotcha.

-- 
Konstantin Osipov, Moscow, Russia

**Pull request closed without merging**
