### PR TITLE
sstables: coroutinize sstable::load()

### PR DESCRIPTION
**Pull request by lersek**
Best viewed with "git show -b -W".

Trivial refactoring, not subject to backporting.

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
lgtm

**Review by denesb — APPROVED** [review]

**Comment by lersek** [comment]
The clang-tidy step failed due to #20821.

Once #20805 is merged, clang-tidy should be restarted on this PR. (I could rebase + force-push manually, but that should not be needed; the context for this patch is not changed by #20805. Thus clang-tidy should simply attempt to merge this patch into refreshed master, and build the tree like that.)

@tchaikov @denesb how can I instruct clang-tidy to restart? Thank you.

**Comment by tchaikov** [comment]
> The clang-tidy step failed due to #20821.
> 
> Once #20805 is merged, clang-tidy should be restarted on this PR. (I could rebase + force-push manually, but that should not be needed; the context for this patch is not changed by #20805. Thus clang-tidy should simply attempt to merge this patch into refreshed master, and build the tree like that.)
> 

clang-tidy is driven by a github workflow. see https://github.com/scylladb/scylladb/blob/fac682df7e53e6a7e34aaf63aed7737270ec5b09/.github/workflows/clang-tidy.yaml#L4 . and this workflow is triggered by pull request or another workflow. so a push / update to `master` does not trigger it.

> @tchaikov @denesb how can I instruct clang-tidy to restart? Thank you.

if you have the write permissions to the repo, you are able to retrigger it manually, by following the link of https://github.com/scylladb/scylladb/actions/runs/11037057171/job/30657007581?pr=20822 
image

but if you are not, you might need to repush for rerunning it. but in this case, i think it's fine to have a red cross. c'est la vie..

**Comment by lersek** [comment]
@tchaikov 

> otherwise you might need to live with this red cross. c'est la vie..

sure; I asked because I was thinking about setting the new label `status/merge candidate`. The requirements for that label currently list "CI is green". I think it'd be justified to set that label now, but technically, CI is red. Hence my query.

**Comment by tchaikov** [comment]
> @tchaikov
> 
> > otherwise you might need to live with this red cross. c'est la vie..
> 
> sure; I asked because I was thinking about setting the new label `status/merge candidate`. The requirements for that label currently list "CI is green". I think it'd be justified to set that label now, but technically, CI is red. Hence my query.

@lersek i created #20841 to address this pain. could you take a look?

**Pull request closed without merging**
