### PR TITLE
types: move from boost ranges to standard ranges

### PR DESCRIPTION
**Pull request by avikivity**
Reduce depdendency load.

tuple_deserializing_iterator gained a default constructor so it matches iterator constraints.

code cleanup - no backport

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
```
05:04:45  Fetching all running CI for the past 24 hours
12:21:48  Resuming build at Thu Oct 10 07:21:48 IDT 2024 after Jenkins restart
12:21:48  Ready to run at Thu Oct 10 07:21:48 IDT 2024
12:21:48  [Pipeline] End of Pipeline
12:21:48  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 185d29f8-2d57-4ad3-8d3a-f531ce11fb3b
12:21:48  org.jenkinsci.plugins.workflow.steps.SynchronousResumeNotSupportedException: Resume after a restart not supported for non-blocking synchronous steps
12:21:48  	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.onResume(SynchronousNonBlockingStepExecution.java:75)
```
resume failed. retriggering the job.

**Comment by avikivity** [comment]
@nyh please review

**Comment by avikivity** [comment]
@nyh please review

**Comment by avikivity** [comment]
@xemul Looks like @nyh is out of office, so please review

**Pull request closed without merging**
