### PR TITLE
forward_service: rename to mapreduce_service

### PR DESCRIPTION
**Pull request by avikivity**
forward_service is nondescriptive and misnamed, as it does more than forward requests. It's a classic map/reduce algorithm (and in fact one of its parameters is "reducer"), so name it accordingly.

The name "forward" leaked into the wire protocol for the messaging service RPC isolation cookie, so it's kept there.

No backport needed, cosmetic change.

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
this change breaks the test in https://github.com/scylladb/scylla-dtest/commit/4ad6c7209395d4928fd789eb158b2932b1023a10#diff-b74f63fc2b62d771f1dcdb90485b8af316c7e4410b67aacca743309d35a2308cL757 . probably we can temporarily drop the command line option of 
`--logger-log-level forward_service=trace` to unblock this change, and put it back afterwards ?

@Jadw1 hi Michal, what do you think?

**Comment by avikivity** [comment]
v2: kept logger name for compatibility with dtest

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
Now the dtest failed because **tracing** used to contain the text "Dispatching forward_request to 3 endpoints" and I guess you changed that text :-(

**Comment by avikivity** [comment]
Relaunching CI after scylladb/scylla-test@1b530c54fd3e91053918cd7a987cd3cfcc3e55fa

**Comment by avikivity** [comment]
@nyh ping

**Comment by nyh** [comment]
> @nyh ping

Sorry, I'll merge it now. I didn't need to re-review, I already reviewed it.

**Pull request closed without merging**
