### PR TITLE
Shard major compaction task

### PR DESCRIPTION
**Pull request by Deexie**
Implementation of task_manager's task that covers major keyspace compaction
on one shard.

### CODE REVIEW

**Comment by Deexie** [comment]
Draft until https://github.com/scylladb/scylladb/pull/12661 gets merged.

**Comment by Deexie** [comment]
To add per table major compaction tasks I need to modify `run_on_existing_tables` function and start the tasks there. That would be quite messy, since the function is used not only for major compaction. Thus, I decided to start with top level and per shard tasks for the following types of compaction:
	- major - top level major tasks: #12661
	- cleanup - #12712
	- offstrategy - #12713
	- rewrite sstables - #12714
This way we will be able to create common table task for each of them and won't need temporary not task-covered version of the function.

**Comment by Deexie** [comment]
- rebased
- test added
- is_interrnal set to yes for shard tasks

**Comment by Deexie** [comment]
- rebased

**Comment by Deexie** [comment]
@bhalevy review please

**Review by bhalevy — APPROVED** [review]

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider merging

**Review by denesb — APPROVED** [review]

**Pull request closed without merging**
