### PR TITLE
maintenance_socket: change log message to differentiate from regular CQL ports

### PR DESCRIPTION
**Pull request by margdoc**
Scylla-ccm uses function `wait_for_binary_interface` that waits for scylla logs to print "Starting listening for CQL clients". If this log is printed far before the regular cql_controller is initialized, scylla-ccm assumes too early that node is initialized. It can result in timeouts that throw errors, for example in the function `watch_rest_for_alive`.

### CODE REVIEW

**Comment by avikivity** [comment]
Why wasn't CI run on this?

**Comment by kbr-scylla** [comment]
> Why wasn't CI run on this?

@benipeled

**Comment by margdoc** [comment]
v2:
* rebase on master
* `return parallel_for_each(configs, ...` => `co_await parallel_for_each(configs, ...`. `parallel_for_each` takes a reference to `configs` which is destroyed after `return` but before the future is resolved.

**Comment by margdoc** [comment]
@denesb or @bhalevy please review.
It's a simple PR, needed to merge https://github.com/scylladb/scylladb/pull/17596.

**Pull request closed without merging**
