### PR TITLE
Messaging service dropped ver

### LINKED ISSUE #4243: Add API for /messaging_service/messages/dropped/{verb}
JMX 3.0 calls a missing API, it should at least have an empty implementation

### PR DESCRIPTION
**Pull request by amnonh**
The series was sent via an email just before we switched to PR. 
So I'm sending it again.

This series adds an API of the moving average dropped messages by verb.

An example of using the API:
curl -X GET http://localhost:10000/messaging_service/messages/dropped/READ_DIGEST

Fixes #4243

### CODE REVIEW

**Comment by slivne** [comment]
@amnonh was this merged ? - if not can you rebase and I'll ask for reviews

**Comment by slivne** [comment]
@amnonh was this merged ? - if not can you rebase and I'll ask for reviews

**Comment by avikivity** [comment]
Please clarify what "Messaging service dropped ver" means.

**Comment by amnonh** [comment]
ok

**Comment by denesb** [comment]
@amnonh this PR has 200+ commits. Please rebase on top of current master and re-push and please fix the title as Avi requested it.

**Comment by mykaul** [comment]
> @amnonh this PR has 200+ commits. Please rebase on top of current master and re-push and please fix the title as Avi requested it.

@amnonh - not sure this PR is still relevant?

**Comment by amnonh** [comment]
@mykaul probably not, I'll need to go back and search for it to understand what it's about

**Pull request closed without merging**
