### PR TITLE
test/pylib: require Scylla driver for ScyllaCluster

### PR DESCRIPTION
**Pull request by alecco**
The `ScyllaCluster` class requires Scylla driver to work properly for detection, so check the driver before starting it.

While there, fix handling failed initialization of `ScyllaCluster`.

### CODE REVIEW

**Review by nyh — COMMENTED** [review]
I'm afraid I didn't understand the motivation of this series. Why do you need to insist on a Scylla driver and refuse to run with a Cassandra driver?

My philosophy in test/cql-pytest was that the tests should run using almost any conceivable version of the driver. A handful of specific tests that needed a specific version of the driver (because an older one had a bug) are skipped if running on the "wrong" driver. But why shouldn't 99% of the tests be able to run with a Cassandra driver?

It's not just "philosophy", also in practice, you want developers to be able to run "test.py" directly without dbuild. Right now you are forcing them to install the Scylla driver instead of the Cassandra driver, something which we never insisted on as far as I know. So my question is why - what do you need specifically from the Scylla driver?

**Comment by kostja** [comment]
The dbuild environment uses the scylla driver, as well as the next promotion procedure. 

So the goal of this patch is to create the same environment on the developer machine as is used in dbuild and in CI.

Specifically, recently we had a regression in Scylla driver which went unnoticed: https://github.com/scylladb/python-driver/issues/198
Thanks to the glitch in the scylla driver, the test would pass with Cassandra driver, but would be flaky with Scylla driver.
The problem would only flake in CI and was not easy to identify.

I agree it's a good goal to support the Cassandra drive. But I think in order to achieve it we could have a dedicated CI pipeline for it or a dedicated test suite. Given that the drivers are installed in the same path, switching today is difficult. If you have an idea how to switch between drivers in different suites, we could require both drivers to be installed in install-dependencies.py and run cql-pytest with cassandra driver. That would take the best from both worlds. Do you know how?

**Review by kostja — APPROVED** [review]

**Comment by nyh** [comment]
> The dbuild environment uses the scylla driver, as well as the next promotion procedure.

I know. I'm still not convinced we need to fail all tests if a developer choose not to use the dbuild environment.

> So the goal of this patch is to create the same environment on the developer machine as is used in dbuild and in CI.
> Specifically, recently we had a regression in Scylla driver which went unnoticed: [scylladb/python-driver#198](https://github.com/scylladb/python-driver/issues/198) Thanks to the glitch in the scylla driver, the test would pass with Cassandra driver, but would be flaky with Scylla driver. The problem would only flake in CI and was not easy to identify.

I understand, but I am not convinced this anecdote "excuses" this change. Basically, once in a (relatively rare) while we see a failure on Jenkins which doesn't reproduce locally. Sometimes the different compiler, different libraries, etc., make a difference so the first thing one does in this case is to use "dbuild" to at least make sure that this isn't what happened here. The conclusion shouldn't be that no developer should be allowed to build or run without their build environment being 100% identical to dbuild. We also allow you to compile even if clang isn't exactly at 15.0.6 - even if once in a blue moon this will cause slightly different failures than on dbuild.

> I agree it's a good goal to support the Cassandra drive. But I think in order to achieve it we could have a dedicated CI pipeline for it or a dedicated test suite. Given that the drivers are installed in the same path, switching today is difficult. If you have an idea how to switch between drivers in different suites, we could require both drivers to be installed in install-dependencies.py and run cql-pytest with cassandra driver. That would take the best from both worlds. Do you know how?

I think these two points are good and correct, but are irrelevant to the question of why you don't want to allow a developer who **chose**, perhaps deliberately, to install the Cassandra drivers, to run tests. Which is the point of this PR - to forbid this case.

Adding an anecdote of my own: Several times in the past, I deliberately uninstalled the Scylla driver and installed the Cassandra driver to run tests when I suspected something was broken in the driver and wanted to check if it's also broken in the other driver. Your patch will prevent me from doing this again. Although, to be honest, I'm not really worried because your patch doesn't affect `test/cql-pytest/run` and `test/alternator/run` which is what I usually use anyway.

**Comment by kostja** [comment]
The check is added to ScyllaCluster, it's not going to fail all tests, only those which use ScyllaCluster. Progamms should properly declare their expectations from the outside world. We are not supporting Cassandra driver in topology tests, and not making a dependency explicit will not change it - it will only make it harder for developers with a custom toolchain to debug issues.

**Comment by kostja** [comment]
I guess we're at a standstill with this one, so let's close this.

**Comment by nyh** [comment]
>  We are not supporting Cassandra driver in topology tests. 

Why is this the case? Do you need Scylla-driver specific features in *all* these tests? Really?

I think this is a mistake we'll regret later. Not only because it can annoy developers, but also because Scylla *should* work with classic Cassandra drivers and one day we might want to check that.

If there is a specific test that tests a Scylla-driver specific feature (maybe something related to the new serverless extensions?) then this one test can be skipped when running with the wrong driver. There is no need to refuse running all topology tests.

**Comment by mykaul** [comment]
> > We are not supporting Cassandra driver in topology tests.
> 
> Why is this the case? Do you need Scylla-driver specific features in _all_ these tests? Really?
> 
> I think this is a mistake we'll regret later. Not only because it can annoy developers, but also because Scylla _should_ work with classic Cassandra drivers and one day we might want to check that.
> 
> If there is a specific test that tests a Scylla-driver specific feature (maybe something related to the new serverless extensions?) then this one test can be skipped when running with the wrong driver. There is no need to refuse running all topology tests.

You assume Cassandra's driver works well, without bugs, and will pass all topology tests? What will it tell us if it doesn't? Bugs in their driver or our code?

**Comment by nyh** [comment]
> I guess we're at a standstill with this one, so let's close this.

Please note that I'm not against the check, I'm against the fact that the code works only on Scylla driver. If for some reason you're not planning to fix that (I think it's a mistake) then we might as well, indeed, have this patch.

**Comment by nyh** [comment]
> > > We are not supporting Cassandra driver in topology tests.
> > 
> > Why is this the case? Do you need Scylla-driver specific features in _all_ these tests? Really?
> > 
> > I think this is a mistake we'll regret later. Not only because it can annoy developers, but also because Scylla _should_ work with classic Cassandra drivers and one day we might want to check that.
> > 
> > If there is a specific test that tests a Scylla-driver specific feature (maybe something related to the new serverless extensions?) then this one test can be skipped when running with the wrong driver. There is no need to refuse running all topology tests.
> 
> You assume Cassandra's driver works well, without bugs, and will pass all topology tests? What will it tell us if it doesn't? Bugs in their driver or our code?

Why do I need to assume this? If one day we'll discover a bug that affects a test, we'll skip the test in the buggy version. There is one such case in cql-pytest.

In any case, the Scylla driver has only small improvements over the Cassandra one. It's not like the Cassandra one is riddled with bugs and everyone is avoiding it.

**Comment by kostja** [comment]
> > We are not supporting Cassandra driver in topology tests.
> 
> Why is this the case? Do you need Scylla-driver specific features in _all_ these tests? Really?
> 
> I think this is a mistake we'll regret later. Not only because it can annoy developers, but also because Scylla _should_ work with classic Cassandra drivers and one day we might want to check that.
> 
> If there is a specific test that tests a Scylla-driver specific feature (maybe something related to the new serverless extensions?) then this one test can be skipped when running with the wrong driver. There is no need to refuse running all topology tests.

Since recently, Scylla driver started identifying hosts by host id, while Cassandra driver still uses ip addresses. Since hosts are started, stopped, added and removed, sometimes with the same IP addresses in topology tests, this creates a behavioral difference between Scylla and Cassandra drivers: whenever a node is removed from the topology, by removenode or shutdown, we need to make sure the driver connection pool is up to date. The control connection can be pointing to that node. We wrote a function called wait_for_cql_and_get_hosts in util.py, which allows the test to wait for the driver to get fully up to date with the new state of the cluster.

The problem is that this function is apparently working slightly differently with Scylla and Cassandra driver. E.g. it may hang after a topology change in 1 out of 10 runs.
I don't think it's realistic to make all our topology tests not flaky with both Scylla and Cassandra drivers. We can change error to warning, to only promise best effort if Cassandra driver is used, but without a continuous runs of CI bashing out al the flaky bugs from the tests I don't believe we will ever make the tests work equally well with both drivers.

**Comment by nyh** [comment]
> Since recently, Scylla driver started identifying hosts by host id, while Cassandra driver still uses ip addresses. Since hosts are started, stopped, added and removed, sometimes with the same IP addresses in topology tests, this creates a behavioral difference between Scylla and Cassandra drivers: whenever a node is removed from the topology, by removenode or shutdown, we need to make sure the driver connection pool is up to date. The control connection can be pointing to that node. We wrote a function called wait_for_cql_and_get_hosts in util.py, which allows the test to wait for the driver to get fully up to date with the new state of the cluster.
> 
> The problem is that this function is apparently working slightly differently with Scylla and Cassandra driver. E.g. it may hang after a topology change in 1 out of 10 runs.

How come dtest and ccm don't have this same problem (at least, I think they don't... I think at some point I was using Cassandra's driver and dtest worked)? 
Can this problem perhaps be avoided altogether by **not** reusing IP addresses in the same cluster? Maybe you have specific tests that want to check the "same ip address" case, but I assume most don't.

> I don't think it's realistic to make all our topology tests not flaky with both Scylla and Cassandra drivers. We can change error to warning, to only promise best effort if Cassandra driver is used, but without a continuous runs of CI bashing out al the flaky bugs from the tests I don't believe we will ever make the tests work equally well with both drivers.

Since these two drivers are so similar (did we stop merging Datastax's fixes?) I doubt it has to be this way, but if you guys (the people who develop the topology/ tests) have given up on this then by all means - let's indeed have this patch that outright forbids the Cassandra driver. You just need to rebase this patch. Because, yes, what's even worse than not supporting the Datastax driver is not supporting it and not even telling the developer of this problem :-(

**Comment by kostja** [comment]
1. dtest is not really testing topology changes. With the rate of sleeps it has, it is very few tests even per the long time it takes to run it. Besides, dtest is not using all the ring-delay=0 settings we use in test.py so many issues just do not surface.
2. Some problems could perhaps be avoided by not reusing IP addresses, but the whole point is to reuse them. This is what will happen in the real world, we registered it more than once when we discussed the elasticity and cloud ups requirements. Scylla driver changes were part of the across-the-board transition to support the cloud team requirements.
3. Feel free to run the diff of the code base if you like. You'll find it's quite substantial.

Going forward, the value of supporting now increasingly old Cassandra drivers will be diminishing. New Cassandra features are already introduced and new Cassandra installations will be increasingly dependent on them. We are not porting all of the Cassandra features over, we were just lucky there aren't many of them. I think we need to focus on making our own drivers work great, we don't have too much focus to spare.

**Pull request closed without merging**
