### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by tchaikov**
* seastar 8fabb30a...2b43417d (6):
  > future: deprecate future::get0()
  > build: do not export valgrind with export()
  > http: deprecate buggy path param[]
  > http/request: add get_path_param method
  > http/request: get_query_param refactor
  > http/util: add path_decode method

Refs https://github.com/scylladb/seastar/issues/725
Refs https://github.com/scylladb/scylladb/issues/5883

### CODE REVIEW

**Review by nyh — CHANGES_REQUESTED** [review]
The "Fixes 5883" is wrong - it does not fix this issue, it just adds a new Seastar feature which can be used to fix this issue.

Here is the message I wrote in my PR:

Refs https://github.com/scylladb/scylladb/issues/5883 (fixes https://github.com/scylladb/seastar/issues/725 and provides a new API to read the decoded paths).

**Comment by nyh** [comment]
And what's the difference between this PR and your other Seastar update PR? :-(

**Comment by tchaikov** [comment]
> And what's the difference between this PR and your other Seastar update PR? :-(

@nyh https://github.com/scylladb/scylladb/pull/18327 includes a commit to use the new API.

**Comment by tchaikov** [comment]
> The "Fixes 5883" is wrong - it does not fix this issue, it just adds a new Seastar feature which can be used to fix this issue.
> 
> Here is the message I wrote in my PR:
> 
> Refs #5883 (fixes [scylladb/seastar#725](https://github.com/scylladb/seastar/issues/725) and provides a new API to read the decoded paths).

indeed. changed to Refs, and amended the commit message to explain the reason of the `Refs` as you did.

**Comment by nyh** [comment]
> > And what's the difference between this PR and your other Seastar update PR? :-(
> 
> @nyh #18327 includes a commit to use the new API.

1. The cover letter doesn't explain this. The two PRs seem (?) to have the same cover letter.
2. Avi forbids to update Seastar **and** add code in the same patch, although it is sometimes useful, because it makes it harder to know what to do in case of backports.

**Comment by tchaikov** [comment]
> > > And what's the difference between this PR and your other Seastar update PR? :-(
> > 
> > 
> > @nyh #18327 includes a commit to use the new API.
> 
>     1. The cover letter doesn't explain this. The two PRs seem (?) to have the same cover letter.
> 

ahh, yeah. the PR title of the other one is different though. anyway, i am marking #18327 draft.

>     2. Avi forbids to update Seastar **and** add code in the same patch, although it is sometimes useful, because it makes it harder to know what to do in case of backports.

that's my recollection as well.

**Comment by nyh** [comment]
> @nyh #18327 includes a commit to use the new API. because IIRC, we do not include other changes if a pull request bumps up a submodule, so i created another PR to do the follow-up change in hope that maintainer can cherry-pick the commit from that PR. but if it does not work. i will rebase it, after this one lands.

I'm confused now. First, it seems the second PR included the same Seastar update as first one. Second, it seems your "follow-up change" is to start using the new Seastar API, but this is https://github.com/scylladb/scylladb/pull/18286 - which includes not just the change (actually, many of them) , but also a test. Is that what your new patch tried to also do?

**Comment by tchaikov** [comment]
> > @nyh #18327 includes a commit to use the new API. because IIRC, we do not include other changes if a pull request bumps up a submodule, so i created another PR to do the follow-up change in hope that maintainer can cherry-pick the commit from that PR. but if it does not work. i will rebase it, after this one lands.
> 
> I'm confused now. First, it seems the second PR included the same Seastar update as first one. Second, it seems your "follow-up change" is to start using the new Seastar API, but this is #18286 - which includes not just the change (actually, many of them) , but also a test. Is that what your new patch tried to also do?

sorry, i didn't realize that you have #18286 already. i am closing mine. the reason i created it was that i spotted a bunch of warnings after updating seastar module locally today.

**Comment by nyh** [comment]
Sorry. It has indeed become a real pain to rely on code changes to Seastar :-( This simple bug fix in some esoteric Alternator LSI use case  has been dragging on for more than a week :-(

**Comment by tchaikov** [comment]
my apologies actually. wanted to save some cycles for building and gating tests.

**Comment by tchaikov** [comment]
closing in favor of #18297

**Pull request closed without merging**
