### PR TITLE
treewide: move log.hh into utils/log.hh

### PR DESCRIPTION
**Pull request by tchaikov**
the log.hh under the root of the tree was created to keep the backward compatibility when seastar was extracted into a separate library. so log.hh should belong to `utils` directory, as it is based solely on seastar, and can be used all subsystems.

in this change, we move log.hh into utils/log.hh to that it is more modularized. and this also improves the readability, when one see `#include "utils/log.hh"`, it is obvious that this source file needs the logging system, instead of its own log facility -- please note, we do have two other `log.hh` in the tree.

---

it's a cleanup, hence no need to backport.

### CODE REVIEW

**Comment by tchaikov** [comment]
the build failure when building the check-header target looks like
```
21:01:39  FAILED: cdc/CMakeFiles/check-headers-cdc.dir/Dev/__/check-headers/cdc/log.hh.cc.o 
21:01:39  /usr/lib64/ccache/clang++ -DDEVEL -DSCYLLA_BUILD_MODE=dev -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DXXH_PRIVATE_API -DCMAKE_INTDIR=\"Dev\" -I/jenkins/workspace/scylla-master/scylla-ci/scylla/cdc -I/jenkins/workspace/scylla-master/scylla-ci/scylla -I/jenkins/workspace/scylla-master/scylla-ci/scylla/build/gen -isystem /jenkins/workspace/scylla-master/scylla-ci/scylla/abseil -isystem /jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include -isystem /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Dev/seastar/gen/include -isystem /usr/include/p11-kit-1 -isystem /jenkins/workspace/scylla-master/scylla-ci/scylla/build/rust -O2 -std=gnu++23 -fvisibility=hidden -Wall -Werror -Wextra -Wno-error=deprecated-declarations -Wimplicit-fallthrough -Wno-c++11-narrowing -Wno-deprecated-copy -Wno-mismatched-tags -Wno-missing-field-initializers -Wno-overloaded-virtual -Wno-unsupported-friend -Wno-enum-constexpr-conversion -Wno-unused-parameter -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla/build=. -march=westmere -Xclang -fexperimental-assignment-tracking=disabled -Wno-unused-const-variable -Wno-unused-function -Wno-unused-variable -std=c++23 -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -DWITH_GZFILEOP -MD -MT cdc/CMakeFiles/check-headers-cdc.dir/Dev/__/check-headers/cdc/log.hh.cc.o -MF cdc/CMakeFiles/check-headers-cdc.dir/Dev/__/check-headers/cdc/log.hh.cc.o.d -o cdc/CMakeFiles/check-headers-cdc.dir/Dev/__/check-headers/cdc/log.hh.cc.o -c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:25:
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/tracing/trace_state.hh:16:
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/tracing/tracing.hh:21:
21:01:39 
 /jenkins/workspace/scylla-master/scylla-ci/scylla/cdc/log.hh:81:9: error: use of undeclared identifier 'tracing'
21:01:39     81 |         tracing::trace_state_ptr tr_state,
21:01:39        |         ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/cdc/log.hh:82:9: error: use of undeclared identifier 'db'
21:01:39     82 |         db::consistency_level write_cl
21:01:39        |         ^
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:25:
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/tracing/trace_state.hh:16:
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/tracing/tracing.hh:34:8: error: use of undeclared identifier 'logging'
21:01:39     34 | extern logging::logger tracing_logger;
21:01:39        |        ^
21:01:39  In file included from /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:25:
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/tracing/trace_state.hh:36:8: error: use of undeclared identifier 'logging'
21:01:39     36 | extern logging::logger trace_state_logger;
21:01:39        |        ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:65:7: error: redefinition of 'cdc_service'
21:01:39     65 | class cdc_service final : public async_sharded_service<cdc::cdc_service> {
21:01:39        |       ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/cdc/log.hh:65:7: note: previous definition is here
21:01:39     65 | class cdc_service final : public async_sharded_service<cdc::cdc_service> {
21:01:39        |       ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:87:8: error: redefinition of 'db_context'
21:01:39     87 | struct db_context final {
21:01:39        |        ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/cdc/log.hh:87:8: note: previous definition is here
21:01:39     87 | struct db_context final {
21:01:39        |        ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/check-headers/cdc/log.hh.cc:96:12: error: redefinition of 'operation'
21:01:39     96 | enum class operation : int8_t {
21:01:39        |            ^
21:01:39  /jenkins/workspace/scylla-master/scylla-ci/scylla/cdc/log.hh:96:12: note: previous definition is here
21:01:39     96 | enum class operation : int8_t {
21:01:39        |            ^
21:01:39  7 errors generated.
```

see also https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12541/consoleFull#1723059824dae97f28-980f-4dce-a662-1b9b15a76cc1

**Comment by avikivity** [comment]
I think the problem is with the cmake implementation. It doesn't test the header file in the same way it is used.

How will anyone guess what the rules are?

**Comment by tchaikov** [comment]
> I think the problem is with the cmake implementation. It doesn't test the header file in the same way it is used.

yes, as i explained this in the commit message. but i think it's always a compromise. it could be convoluted to bend CMake to work to at the level of ninja. but if you insist, i will try.

> 
> How will anyone guess what the rules are?

would this change be acceptable if i explain the rules clearly? i think the rules is: 

- we include a header file using `#include "foo.hh"` if `"foo.hh"` is located in the same directory, 
- we include a header file using `#include "bar/foo.hh"` if `"foo.hh"` is located in another directory
- but we should not include a header using `#include"fooo.hh"` if `"foo.hh"` is located under the root of the source directory.

**Comment by tchaikov** [comment]
@avikivity i think, even if we don't need this change to fix the header-check in CMake, this change is still an improvement. because we have "utils" for holding the utilities which should only depend on the 3rd party dependencies (like seastar, libc, libstdc++, etc). but currently, we are also using the root directory for collecting the headers which do not belong to a certain subdirectory. this is not quite structured or modularized. 

if it's acceptable to have this change as a cleanup instead of as a workaround for CMake building system, i will update the cover letter and commit message.

> > I think the problem is with the cmake implementation. It doesn't test the header file in the same way it is used.
> 
> yes, as i explained this in the commit message. but i think the solution of a certain problem is always a compromise. it could be convoluted to bend CMake to work to at the level of ninja. but if you insist, i will try.

i will come up with another solution -- to create a .cc file for each header under test. this .cc file only includes the header file being tested.

> 
> > How will anyone guess what the rules are?
> 
> would this change be acceptable if i explain the rules clearly? i think the rules are:
> 
>     * we include a header file using `#include "foo.hh"` if `"foo.hh"` is located in the same directory,
> 
>     * we include a header file using `#include "bar/foo.hh"` if `"foo.hh"` is located in another directory
> 
>     * but we should not include (directly or indirectly) a header using `#include"foo.hh"` if `"foo.hh"` is located under the root of the source directory, if we already have `"foo.hh"` under current source directory.

**Comment by tchaikov** [comment]
> if it's acceptable to have this change as a cleanup instead of as a workaround for CMake building system, i will update the cover letter and commit message.
> 
> > > I think the problem is with the cmake implementation. It doesn't test the header file in the same way it is used.
> > 
> > 
> > yes, as i explained this in the commit message. but i think the solution of a certain problem is always a compromise. it could be convoluted to bend CMake to work to at the level of ninja. but if you insist, i will try.
> 
> i will come up with another solution -- to create a .cc file for each header under test. this .cc file only includes the header file being tested.
> 

created #21193

**Comment by avikivity** [comment]
I agree moving it to utils/ makes independent sense.

**Comment by tchaikov** [comment]
v2:

- updated the commit message and cover letter to explain this is just a cleanup.

**Comment by nyh** [comment]
I agree with @avikivity that moving log.hh out of the top-level directory is a good idea - it also fits well with @regevran's project (https://github.com/scylladb/scylladb/issues/20981) of moving out **all** of the of the files from the top-level directory.
I like less the discussion about cmake - I don't like having to make unjustified changes just to please various cmake and CI   bugs - something we've seen too much of recently. But if as in this case there is a different justification (https://github.com/scylladb/scylladb/issues/20981), good.

In the long run, we could get rid of log.hh completely. The only thing it has today are some sort of old aliases for various Seastar logging types, and we could have stopped using these old names and switch tot he new names. But I guess it's not worth the hassle to do it now.

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12562/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12562/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/commitlog_test 🔹 boost/dirty_memory_manager_test 🔹 boost/error_injection_test 🔹 boost/locator_topology_test 🔹 boost/logalloc_test 🔹 boost/network_topology_strategy_test 🔹 unit/lsa_async_eviction_test 🔹 unit/lsa_sync_eviction_test 🔹 unit/row_cache_alloc_stress_test ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12562/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1259/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4324/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12347/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12562/)
> #### Failed Tests (3/38305):
> 
>     * [background_reclaim](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12562/testReport/junit/boost/logalloc_test/background_reclaim) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+background_reclaim)

#15677

> 
>     * [test_auth_raft_snapshot_transfer.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12562/testReport/junit/%28root%29/test_auth_no_quorum/Tests___Unit_Tests___test_auth_raft_snapshot_transfer_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_auth_raft_snapshot_transfer.release.2)
> 

#21195

>     * [test_auth_v2_during_recovery.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12562/testReport/junit/%28root%29/test_auth_v2_migration/Tests___Unit_Tests___test_auth_v2_during_recovery_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_auth_v2_during_recovery.release.1)
> 
> 
> #### Build Details:
> 
>     * Duration: 8 hr 25 min
> 
>     * Builder: i-056ad1b655d765027 (m5ad.8xlarge)

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12616/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12616/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/commitlog_test 🔹 boost/dirty_memory_manager_test 🔹 boost/error_injection_test 🔹 boost/locator_topology_test 🔹 boost/logalloc_test 🔹 boost/network_topology_strategy_test 🔹 unit/lsa_async_eviction_test 🔹 unit/lsa_sync_eviction_test 🔹 unit/row_cache_alloc_stress_test
> #### Failed Tests (1/1456):
> 
>     * [background_reclaim](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12616/testReport/junit/boost/logalloc_test/background_reclaim) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+background_reclaim)
> 

#15677

**Comment by denesb** [comment]
Queued. Had a trivial conflict which I resolved.

**Comment by tchaikov** [comment]
@denesb as always thank you !

**Comment by denesb** [comment]
Looks like I fumbled the queueing with the config resolution, this PR doesn't appear to be queued.
@tchaikov please rebase.

**Comment by tchaikov** [comment]
@denesb hi Botond, but it's already in master. see 6ead5a4696636f00fa673f4772dcb272eab2948e

anyway, i am closing this PR.

**Comment by yaronkaikov** [comment]
@tchaikov @denesb it seems that changes in `tools/cqlsh` got in by mistake

**Pull request closed without merging**
