### PR TITLE
Do not reset quarantine list in non raft mode

### LINKED ISSUE #21930: Abort in service::storage_service::handle_state_normal in test_decommission_after_changing_node_ip
Observed in CI:

```
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13404/artifact/logs-full.release.001/1734085322685_update_cluster_layout_tests.py%3A%3ATestUpdateClusterLayout%3A%3Atest_decommission_after_changing_node_ip/
```

Build and packages:
```
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13805/artifact/00-Build.txt
timestamp: 2024-12-13T11:14:31Z
git@github.com:scylladb/scylla.git-sha: 21861
jenkins-job-path: scylla-master/scylla-ci
jenkins-job-number: 13805
url-id: 2024-12-13T11:14:31Z
reloc-pack-url: downloads.scylladb.com/unstable/scylla/master/relocatable/2024-12-13T11:14:31Z/
rpm-deb-pack-url: downloads.scylladb.com/unstable/scylla/master/build-packages/2024-12-13T11:14:31Z/
scylla-product: scylla
scylla-release: 0.20241213.007ef34a896c
scylla-version: 6.3.0~dev
scylla-x86_64-BuildID[sha1]: 0247924dc5ca2597ec1ac278bc02bb69ceecfd41
scylla-debug-x86_64-BuildID[sha1]: e417ff9d13686ce6c9ee5efb599b3bca0e2b5caf
unified-pack-url-x86_64: downloads.scylladb.com/unstable/scylla/master/relocatable/2024-12-13T11:14:31Z/scylla-unified-6.3.0~dev-0.20241213.007ef34a896c.x86_64.tar.gz
docker-image-name-x86_64: scylladb-ci:6.3.0-dev-0.20241213.007ef34a896c-x86_64
docker-image-name: scylladb-ci:6.3.0-dev-0.20241213.007ef34a896c
```

Bactraces:
```
bash-5.2$ seastar/scripts/seastar-addr2line -e 47924dc5ca2597ec1ac278bc02bb69ceecfd41.debug 
0x5e31064
0x5debfab
0x5e23bd8
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x40cff
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x99663
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x40c4d
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x28901
0x5dbe44c
0x3f5746c
0x401c57f
0x401bff0
0x3d38d1d
0x3f6175d
0x3f5ea79
0x3cd0cfe
0x3c5336a
0x3cfa4df
0x146142a
0x5dfe96f
0x5dfff3a
0x5e01117
0x5e004c8
0x5d8e043
0x5d8d3a3
0x1405427
0x14072b0
0x1402f63
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x2a087
/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6+0x2a14a
0x1400f14

[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:69
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:850
 (inlined by) seastar::sigabrt_action() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3995
  (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3972
   (inlined by) seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3967
   addr2line: '/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6': No such file
   /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x40cff 
   /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x99663 
   /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x40c4d 
   /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x28901 
   seastar::on_fatal_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/on_internal_error.cc:80
   service::storage_service::handle_state_normal(gms::inet_address, utils::tagged_uuid<gms::permit_id_tag>) at ././service/storage_service.cc:2512
   service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0::operator()(gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>) const at ././service/storage_service.cc:2663
   seastar::future<void> std::__invoke_impl<seastar::future<void>, service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0&, gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag> >(std::__invoke_other, service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0&, gms::inet_address&&, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
    (inlined by) std::enable_if<is_invocable_r_v<seastar::future<void>, service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0&, gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag> >, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0&, gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag> >(service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0&, gms::inet_address&&, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:114
	 (inlined by) std::_Function_handler<seastar::future<void> (gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>), service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>)::$_0>::_M_invoke(std::_Any_data const&, gms::inet_address&&, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:290
	 gms::i_endpoint_state_change_subscriber::on_application_state_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, gms::application_state, utils::tagged_uuid<gms::permit_id_tag>, std::function<seastar::future<void> (gms::inet_address, gms::versioned_value const&, utils::tagged_uuid<gms::permit_id_tag>)>) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
	 service::storage_service::on_change(gms::inet_address, std::unordered_map<gms::application_state, gms::versioned_value, std::hash<gms::application_state>, std::equal_to<gms::application_state>, std::allocator<std::pair<gms::application_state const, gms::versioned_value> > > const&, utils::tagged_uuid<gms::permit_id_tag>) at ././service/storage_service.cc:2651
	 non-virtual thunk to service::storage_service::on_join(gms::inet_address, seastar::lw_shared_ptr<gms::endpoint_state const>, utils::tagged_uuid<gms::permit_id_tag>) at ././service/storage_service.cc:2620
	 seastar::noncopyable_function<seastar::future<void> (seastar::shared_ptr<gms::i_endpoint_state_change_subscriber>)>::indirect_vtable_for<gms::gossiper::handle_major_state_change(gms::inet_address, gms::endpoint_state, utils::tagged_uuid<gms::permit_id_tag>, bool)::$_1>::call(seastar::noncopyable_function<seastar::future<void> (seastar::shared_ptr<gms::i_endpoint_state_change_subscriber>)> const*, seastar::shared_ptr<gms::i_endpoint_state_change_subscriber>) at ././gms/gossiper.cc:1837
	 atomic_vector<seastar::shared_ptr<gms::i_endpoint_state_change_subscriber> >::for_each(seastar::noncopyable_function<seastar::future<void> (seastar::shared_ptr<gms::i_endpoint_state_change_subscriber>)>) const at ././seastar/include/seastar/util/noncopyable_function.hh:215
	 gms::gossiper::handle_major_state_change(gms::inet_address, gms::endpoint_state, utils::tagged_uuid<gms::permit_id_tag>, bool) at ././gms/gossiper.cc:1836
	 std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/coroutine:242
	  (inlined by) seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:122
	  seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:2606
	  seastar::reactor::run_some_tasks() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3078
	  seastar::reactor::do_run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3246
	  seastar::reactor::run() at ./build/release/seastar/./build/release/seastar/./seastar/src/core/reactor.cc:3136
	  seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:276
	  seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at ./build/release/seastar/./build/release/seastar/./seastar/src/core/app-template.cc:167
	  scylla_main(int, char**) at ././main.cc:778
	  std::function<int (int, char**)>::operator()(int, char**) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/std_function.h:591
	  main at ././main.cc:2391
	  /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x2a087 
	  /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/21861/libreloc/libc.so.6 0x2a14a 
	  _start at ??:?
```

Logs:

[1734085322685_update_cluster_layout_tests.py__TestUpdateClusterLayout__test_decommission_after_changing_node_ip.zip](https://github.com/user-attachments/files/18146096/1734085322685_update_cluster_layout_tests.py__TestUpdateClusterLayout__test_decommission_after_changing_node_ip.zip)

### PR DESCRIPTION
**Pull request by gleb-cloudius**
The series contains small fixes to the gossiper one of which fixes #21930. Others I noticed while debugged the issue.

Fixes: #21930

### CODE REVIEW

**Comment by gleb-cloudius** [comment]
[empty] one is this: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13905/artifact/testlog/x86_64/debug/boost.database_test.test_database_with_data_in_sstables_is_a_mutation_source_plain_reader_conversion_cg0.1.log

```
ERROR 2024-12-17 18:20:29,547 [shard 1:goss] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 12: Cannot allocate memory). Aborting, at 0x2a410d5 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469a357 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4699fa1 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469bb70 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469e70f 0x3965c8c 0x2b86496 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3738b90 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3744e9d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x374a33d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3833fc3 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x38325a0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3832490 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3831bfc /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x34f8a58 0x2a94b98 /lib64/libc.so.6+0x976d6 /lib64/libc.so.6+0x11b60b

```

Out of memory during write.

**Comment by gleb-cloudius** [comment]
Created https://github.com/scylladb/scylladb/issues/21966 for [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13905/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)

**Comment by gleb-cloudius** [comment]
@kbr-scylla this is ready for review/merge

**Comment by gleb-cloudius** [comment]
> [empty] one is this: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13905/artifact/testlog/x86_64/debug/boost.database_test.test_database_with_data_in_sstables_is_a_mutation_source_plain_reader_conversion_cg0.1.log
> 
> ```
> ERROR 2024-12-17 18:20:29,547 [shard 1:goss] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 12: Cannot allocate memory). Aborting, at 0x2a410d5 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469a357 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4699fa1 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469bb70 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x469e70f 0x3965c8c 0x2b86496 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3738b90 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3744e9d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x374a33d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3833fc3 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x38325a0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3832490 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3831bfc /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x34f8a58 0x2a94b98 /lib64/libc.so.6+0x976d6 /lib64/libc.so.6+0x11b60b
> ```
> 
> Out of memory during write.

Apparently there is an issue about it: https://github.com/scylladb/scylladb/issues/21968

**Review by kbr-scylla — APPROVED** [review]

**Pull request merged**
