### PR TITLE
counters.hh: drop unused boost includes

### PR DESCRIPTION
**Pull request by avikivity**
Re-add them to source files that need them.

Code cleanup; no need to backport.

### CODE REVIEW

**Comment by avikivity** [comment]
@kbr-scylla please review

**Comment by avikivity** [comment]
v2: rebased

**Comment by kbr-scylla** [comment]
CI ran but no report was posted https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13568/
@yaronkaikov

**Comment by kbr-scylla** [comment]
```
[2024-12-03T16:39:13.528Z] + docker run -w /jenkins/workspace/scylla-master/scylla-ci-docker/scylla-pkg/scripts/argus-client -v /jenkins:/jenkins -v /home/jenkins:/home/jenkins scylladb/argus-client-generic:latest argus-client-generic finish --api-key **** --id c99104b2-e806-476a-a9d5-d5f64920a879 --status failed
[2024-12-03T16:39:13.529Z] Traceback (most recent call last):
[2024-12-03T16:39:13.529Z]   File "/usr/local/bin/argus-client-generic", line 8, in <module>
[2024-12-03T16:39:13.529Z]     sys.exit(cli())
[2024-12-03T16:39:13.529Z]              ^^^^^
[2024-12-03T16:39:13.529Z]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2024-12-03T16:39:13.529Z]     return self.main(*args, **kwargs)
[2024-12-03T16:39:13.529Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-03T16:39:13.529Z]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2024-12-03T16:39:13.529Z]     rv = self.invoke(ctx)
[2024-12-03T16:39:13.529Z]          ^^^^^^^^^^^^^^^^
[2024-12-03T16:39:13.529Z]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
[2024-12-03T16:39:13.529Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2024-12-03T16:39:13.530Z]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-03T16:39:13.530Z]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2024-12-03T16:39:13.530Z]     return ctx.invoke(self.callback, **ctx.params)
[2024-12-03T16:39:13.530Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-03T16:39:13.530Z]   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2024-12-03T16:39:13.548Z]     return __callback(*args, **kwargs)
[2024-12-03T16:39:13.548Z]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-12-03T16:39:13.548Z]   File "/usr/local/lib/python3.11/site-packages/argus/client/generic/cli.py", line 39, in finish_run
[2024-12-03T16:39:13.548Z]     client.finalize_generic_run(run_id=id, status=status, scylla_version=scylla_version)
[2024-12-03T16:39:13.548Z]   File "/usr/local/lib/python3.11/site-packages/argus/client/generic/client.py", line 31, in finalize_generic_run
[2024-12-03T16:39:13.549Z]     self.check_response(response)
[2024-12-03T16:39:13.549Z]   File "/usr/local/lib/python3.11/site-packages/argus/client/base.py", line 68, in check_response
[2024-12-03T16:39:13.549Z]     raise ArgusClientError(
[2024-12-03T16:39:13.549Z] argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/testrun/generic/c99104b2-e806-476a-a9d5-d5f64920a879/finalize', 'DoesNotExist')
```


```
[2024-12-03T16:39:14.093Z] Error when executing always post condition:
[2024-12-03T16:39:14.102Z] Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 7af5fb45-18a9-44a1-b488-180edccdd61e
[2024-12-03T16:39:14.102Z] hudson.AbortException: script returned exit code 1
[2024-12-03T16:39:14.102Z] 	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:669)
[2024-12-03T16:39:14.102Z] 	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:615)
[2024-12-03T16:39:14.102Z] 	at PluginClassLoader for workflow-durable-task-step//org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:556)
[2024-12-03T16:39:14.102Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-12-03T16:39:14.102Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-12-03T16:39:14.102Z] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[2024-12-03T16:39:14.102Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-12-03T16:39:14.102Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-12-03T16:39:14.102Z] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-12-03T16:39:14.102Z] 
```

```
[2024-12-03T16:39:29.103Z] Also:   hudson.remoting.ProxyException: org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: f56fd3e3-ace9-494c-89f9-f03487c10620
[2024-12-03T16:39:29.103Z] hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: BUILD_USER_ID for class: Script1
[2024-12-03T16:39:29.103Z] 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
[2024-12-03T16:39:29.103Z] 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:471)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:377)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:347)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:375)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:379)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for script-security//org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:355)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.LoggingInvoker.getProperty(LoggingInvoker.java:133)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
[2024-12-03T16:39:29.103Z] 	at Script1.argusRun(Script1.groovy:410)
[2024-12-03T16:39:29.103Z] 	at ___cps.transform___(Native Method)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:73)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:65)
[2024-12-03T16:39:29.103Z] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[2024-12-03T16:39:29.103Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Next.step(Next.java:83)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:422)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:140)
[2024-12-03T16:39:29.103Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-12-03T16:39:29.103Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
[2024-12-03T16:39:29.103Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
[2024-12-03T16:39:29.103Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
[2024-12-03T16:39:29.103Z] 	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
[2024-12-03T16:39:29.103Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[2024-12-03T16:39:29.103Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-12-03T16:39:29.103Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[2024-12-03T16:39:29.103Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
[2024-12-03T16:39:29.103Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
[2024-12-03T16:39:29.103Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
[2024-12-03T16:39:29.103Z] 	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
[2024-12-03T16:39:29.103Z] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[2024-12-03T16:39:29.427Z] Finished: FAILURE
```

**Comment by kbr-scylla** [comment]
Restarted CI: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13592/

**Comment by yaronkaikov** [comment]
> Restarted CI: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13592/

We had a bug in pkg that was already fixed by @Annamikhlin - https://github.com/scylladb/scylla-pkg/pull/4643

**Review by nyh — APPROVED** [review]

**Pull request closed without merging**
