### PR TITLE
cql: make options case insensitive

### LINKED ISSUE #15336: upper-case "replication_factor" gives wrong error message
The command
```
CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}"
```
works - it sets the same replication factor for each DC. It's known as "auto expand".

I tried _by mistake_ the same with with an upper-case R:
```
CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'Replication_factor': 3}"
```

The result was truly bizarre - it didn't do the auto-expand (apparently the code that looks for it is case-sensitive),  and instead gave the **false** error message:

> replication_factor is an option for SimpleStrategy, not NetworkTopologyStrategy

We should decide if we want to allow case-insensitive option names, but even if we don't, this error message is wrong and misleading.

The bug is in locator/network_topology_strategy.cc:
```c++
        if (boost::iequals(key, "replication_factor")) {
            throw exceptions::configuration_exception(
                "replication_factor is an option for SimpleStrategy, not "
                "NetworkTopologyStrategy");
        }
```

IIUC, earlier code already handled **and removed** just the lower-case "replication_factor" from the list of options, but then this code expects that no version of "replication_factor" with any case exists, while it can. Maybe this error should be an on_internal_error, saying that this code expects the earlier code to have removed the "replication_factor" option that reached the network_topology_strategy constructor. And both codes should be case sensitive or insensitive.

### PR DESCRIPTION
**Pull request by alezzqz**
fix an issue when options typed in various cases treat as different

This is just a possible solution. Probably we should add some tests as well

Fixes #15336

### CODE REVIEW

**Comment by avikivity** [comment]
Is Cassandra case sensitive or not?

I prefer case sensitivity, but no need to diverge from Cassandra here.

**Comment by alezzqz** [comment]
> Is Cassandra case sensitive or not?
> 

Cassandra is case sensitive. Issues like #15336 reproduced there as well. @nyh thinks it's a cassandra bug (and I agree: all commands are case insensitive but not options)

**Comment by nyh** [comment]
> > Is Cassandra case sensitive or not?
> 
> Cassandra's options are case sensitive. Issues like #15336 reproduced there as well. @nyh thinks it's a cassandra bug (and I agree: all commands are case insensitive but not options)

Note that what I called a Cassandra bug isn't the fact that it's case-sensitive ("replication_factor" works, "Replication_factor" doesn't) but the fact that it gives a misleading and even wrong error message message when you use the wrong case.

**Comment by alezzqz** [comment]
> 
> Note that what I called a Cassandra bug isn't the fact that it's case-sensitive ("replication_factor" works, "Replication_factor" doesn't) but the fact that it gives a misleading and even wrong error message message when you use the wrong case.

While I researched the problem I found few similar strange situations, for instance when we pass (by mistake) options in various case like:
CREATE KEYSPACE IF NOT EXISTS test3 WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 2, 'Replication_factor': 3} ;

well, maybe that's not a problem. Concerning #15336 the only difference between Scylla and Cassandra is the text of error message. As I wrote above Im not sure making options case insensitive is a real solution. Just asking you.

**Comment by alezzqz** [comment]
> 
> CQL/SQL is case insensitive. But the option map is not traditional CQL/SQL, it's json, and json is case-sensitive.

If we don't consider options as a part of cql - ignoring case isn't a solution. Closed.

**Pull request closed without merging**
