### PR TITLE
install.sh: fix more incorrect permission on strict umask

### LINKED ISSUE #14383: install.sh still installing files with incorrect permission on strict umask setting
We have fixed incorrect permission problem with strict umask settings in https://github.com/scylladb/scylladb/commit/13caac7ae6e408f54e0ae8641697348b706a6328, but there are more incorrect permission issue.

We use `cp -r` to installing some files recursively, umask will be apply to them:
```
$ grep "cp -r" install.sh 
cp -r swagger-ui/dist "$rprefix"/swagger-ui
cp -r api/api-doc "$rprefix"/api
cp -r tools/scyllatop/* "$rprefix"/scyllatop
cp -r dist/common/scripts/* "$rprefix"/scripts
```

So we will get 600 permission something like this on OEL81 AMI, since it uses `umask 077`:
```
$ sudo ls -l swagger-ui/dist/
total 3136
drwx------. 2 root root    4096 Jun 24 05:59 css
drwx------. 2 root root    4096 Jun 24 05:59 fonts
drwx------. 2 root root    4096 Jun 24 05:59 images
-rw-------. 1 root root    4359 Jun 24 05:59 index.html
drwx------. 2 root root    4096 Jun 24 05:59 lang
drwx------. 2 root root    4096 Jun 24 05:59 lib
-rw-------. 1 root root     479 Jun 24 05:59 o2c.html
-rw-------. 1 root root 2716443 Jun 24 05:59 swagger-ui.js
-rw-------. 1 root root  455379 Jun 24 05:59 swagger-ui.min.js

$ sudo ls -l api/api-doc
total 356
-rw-------. 1 root root   556 Jun 24 05:59 authorization_cache.json
-rw-------. 1 root root 19117 Jun 24 05:59 cache_service.json
-rw-------. 1 root root  6907 Jun 24 05:59 collectd.json
-rw-------. 1 root root 96451 Jun 24 05:59 column_family.json
-rw-------. 1 root root  3911 Jun 24 05:59 commitlog.json
-rw-------. 1 root root 10777 Jun 24 05:59 compaction_manager.json
-rw-------. 1 root root   724 Jun 24 05:59 config.json
-rw-------. 1 root root  2243 Jun 24 05:59 endpoint_snitch_info.json
-rw-------. 1 root root  2934 Jun 24 05:59 error_injection.json
-rw-------. 1 root root  7055 Jun 24 05:59 failure_detector.json
-rw-------. 1 root root  5257 Jun 24 05:59 gossiper.json
-rw-------. 1 root root  6662 Jun 24 05:59 hinted_handoff.json
-rw-------. 1 root root   532 Jun 24 05:59 lsa.json
-rw-------. 1 root root  7268 Jun 24 05:59 messaging_service.json
-rw-------. 1 root root 30862 Jun 24 05:59 storage_proxy.json
-rw-------. 1 root root 89950 Jun 24 05:59 storage_service.json
-rw-------. 1 root root  7663 Jun 24 05:59 stream_manager.json
-rw-------. 1 root root   612 Jun 24 05:59 swagger20_header.json
-rw-------. 1 root root  5419 Jun 24 05:59 system.json
-rw-------. 1 root root 10565 Jun 24 05:59 task_manager.json
-rw-------. 1 root root  5190 Jun 24 05:59 task_manager_test.json
-rw-------. 1 root root  3129 Jun 24 05:59 utils.json

$ sudo ls -l scyllatop/
total 48
-rw-------. 1 root root 2482 Jun 24 05:59 collectd.py
-rw-------. 1 root root  226 Jun 24 05:59 defaults.py
-rw-------. 1 root root  717 Jun 24 05:59 dumptostdout.py
-rw-------. 1 root root 1292 Jun 24 05:59 fake.py
drwxr-xr-x. 2 root root 4096 Jun 24 05:59 libexec
-rw-------. 1 root root 3490 Jun 24 05:59 livedata.py
-rw-------. 1 root root 2902 Jun 24 05:59 metric.py
-rw-------. 1 root root   42 Jun 24 05:59 parseexception.py
-rwx------. 1 root root  838 Jun 24 05:59 prometheus.py
-rwxr-xr-x. 1 root root  570 Jun 24 05:59 scyllatop.py
-rw-------. 1 root root  648 Jun 24 05:59 userinput.py
drwx------. 2 root root 4096 Jun 24 05:59 views
```

It will be problematic when accessing these files from scylla user.

### PR DESCRIPTION
**Pull request by syuu1228**
Even after 13caac7, we still have more files incorrect permission, since we use "cp -r" and creating new file with redirect.

To fix this, we need to replace "cp -r" with "cp -pr", and "chmod <perm>" on newly created files.

Fixes #14383
Related #19775

### CODE REVIEW

**Review by yaronkaikov — COMMENTED** [review]
@syuu1228 please use BYO to build and then run the artifacts tests to make sure nothing is broken

**Comment by syuu1228** [comment]
> @syuu1228 please use BYO to build and then run the artifacts tests to make sure nothing is broken

Built on byo:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/byo/job/byo_build_tests_dtest/66/
Built on centos-rpm which runs artifact-tests on rpm based distros:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/centos-rpm/215/
Buit on unified-deb which runs artifact-tests on deb based distros:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/unified-deb/269/

However, some of additional artifact test on centos-rpm and unified-deb are failed with `exception=Wait for: artifacts-amazon2-jenkins-db-node-deab2d48-1: Waiting for SSH to be up: timeout - 500 seconds - expired`.
And I found that the error is not 100% reproducible, it can disappear when I just re-running the test.
It seems like db-node is not yet launched after 500 sec or something like that.
log:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-amazon2-test/5/consoleFull#928762808fcc21424-66d2-4bd8-8e0d-9746405e5b16
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-debian11-test/4/consoleFull#-519875844fcc21424-66d2-4bd8-8e0d-9746405e5b16


Also, I tried to build offline-installer with artifact-tests, but it always causes ABORTED on the artifact test:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/offline-installer/127/
I at least tried more than 5 times, and it always cause ABORTED.
Seems like Jenkins says:
```
status:201 request:0.116s [2024-07-22T12:42:49.828Z] < t:2024-07-22 12:42:49,200 f:file_logger.py l:101 c:sdcm.sct_events.file_logger p:INFO > 2024-07-22 12:42:49.193: (JMXServiceEvent Severity.NORMAL) period_type=begin event_id=2e48845d-4e4e-4d8d-ad78-f7d0dbd15a8b node=artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1

2024-07-22T12:55:38.838Z Cancelling nested steps due to timeout
```


aborted job: https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts-offline-install/job/artifacts-ubuntu2204-test/15/

And detail log of the job:
```
21:37:56  < t:2024-07-22 12:37:43,543 f:wait.py         l:79   c:sdcm.wait            p:ERROR > Wait for: artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1: Waiting for JMX service to be up: timeout - 500 seconds - expired
21:37:56  < t:2024-07-22 12:37:43,544 f:wait.py         l:83   c:sdcm.wait            p:ERROR > last error: RetryError(<Future at 0x7fd59b5a91b0 state=finished returned bool>)
21:37:56  < t:2024-07-22 12:37:44,913 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-22 12:37:44.909: (JMXServiceEvent Severity.NORMAL) period_type=end event_id=9ad08df8-77e9-4cc1-b271-7262746ec569 duration=2m21s node=artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1
21:37:56  < t:2024-07-22 12:37:44,923 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-22 12:37:44.910: (ScyllaServerStatusEvent Severity.NORMAL) period_type=end event_id=4ca732fe-1416-4002-be40-766dbfd002d7 duration=9m23s node=artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1
21:37:56  < t:2024-07-22 12:37:47,726 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-22 12:37:47.719: (ScyllaServerStatusEvent Severity.NORMAL) period_type=begin event_id=4bc9bc74-b4c8-4673-a4fb-018b0f92cf53 node=artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1
21:37:56 
 < t:2024-07-22 12:37:49,212 f:base.py         l:274  c:elasticsearch        p:INFO  > PUT https://746f0ad652a3447d83b1572f657c67cb.us-east-1.aws.found.io:9243/sct-adaptive-timeouts/_create/461b967e-af01-41d0-9c8c-a1110b41c146 [status:201 request:0.116s]
21:42:49  < t:2024-07-22 12:42:49,200 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-07-22 12:42:49.193: (JMXServiceEvent Severity.NORMAL) period_type=begin event_id=2e48845d-4e4e-4d8d-ad78-f7d0dbd15a8b node=artifacts-ubuntu2204-jenkins-db-node-e3d9d421-0-1
21:55:38  Cancelling nested steps due to timeout
21:55:38  Sending interrupt signal to process
21:55:58  After 20s process did not stop
```

**Comment by syuu1228** [comment]
Rebased with master, since it was conflicted.
Also added missing `chmod 644` on newly added files and scylla_sysconfdir.py.

**Review by yaronkaikov — APPROVED** [review]

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint please merge this

**Comment by denesb** [comment]
There are conflicts, needs a rebase. Will possibly have to happen after promotion, I think it conflicts with something in next.

**Comment by yaronkaikov** [comment]
Probably https://github.com/scylladb/scylladb/pull/19976, let's wait for promotion then @syuu1228 please rebase

**Comment by syuu1228** [comment]
Rebased with latest master.

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint can you please help merge this?

**Pull request closed without merging**
