### PR TITLE
perf_simple_query: add attach/detach points for perf

### PR DESCRIPTION
**Pull request by denesb**
Instrumenting `perf_simple_query` with perf is tricky as the startup and
teardown code introduces a lot of unpredictable and undesired noise into
measurements. One can try to work around this by attaching perf at the
runtime, after the measure cycle has actually started, and cancel right
before or right after it ends. But even this is unreliable when one
wants to do a perf-diff between two runs as in this case the two runs
should be as identical as possible and even the time at which the
attach/detach happens can introduce noise.
This patch offers a crude yet effective solution: when the new
--perf-attach-detach-point flag is used, there will be a 5 second wait
just before/after starting/ending the measure cycle. During this wait
time the system is effectively idle. This time should be enough to
quickly alt-tab into another terminal and run a prepared perf-attach
statement and to CTRL+C at the end.

### CODE REVIEW

**Review by michoecho — CHANGES_REQUESTED** [review]
Synchronizing software with sleeps :-1: 

`perf` has an interface for synchronization, via `--control`. So to do this properly, we can e.g.:

```
int CTL_FD = 3, ACK_FD = 4;

setup

barrier

if (this_shard_id == 0 && args.perf) {
    char enable_cmd[] = "enable\n";
    write(CTL_FD, enable_cmd, sizeof(enable_cmd));
    char buf[5];
    read(ACK_FD, buf, 5);
}

barrier

benchmark

barrier

if (this_shard_id == 0 && args.perf) {
    char disable_cmd[] = "disable\n";
    write(CTL_FD, disable_cmd, sizeof(disable_cmd));
    char buf[5];
    read(ACK_FD, buf, 5);
}

barrier

teardown
```

and run the test with:

```
#!/bin/bash -eu

CTL_FD=3 && ACK_FD=4
ctl_dir="$(mktemp --directory)"
ctl_fifo="${ctl_dir}/perf_ctl.fifo" && mkfifo "${ctl_fifo}" && exec CTL_FD<>"${ctl_fifo}"
ack_fifo="${ctl_dir}/perf_ack.fifo" && mkfifo "${ack_fifo}" && exec ACK_FD<>"${ack_fifo}"
rm -r "${ctl_dir}"

perf stat --delay=-1 --control=fd:"$CTL_FD,$ACK_FD" -- ./my_benchmark --perf
```

There is also `--control=fifo` for named pipes instead of file descriptors.

**Comment by denesb** [comment]
> Synchronizing software with sleeps -1

Yes, I admit it is not sophisticated, but it is simple and it works without a separate script wrapping perf.

**Comment by michoecho** [comment]
If you want to avoid a script which launches both the test and the perf (which I agree would be cumbersome), you can create the fifos inside the test (with names derived from PID, e.g. `/tmp/${PID}_ctl.fifo`, `/tmp/${PID}_ack.fifo`), and then attach the recording with
```
PID=$(pgrep -xn perf_simple_query); perf stat --delay=-1 --control=fifo:/tmp/$PID_{ctl,ack}.fifo --pid $PID
```
Then the only difference between your version and the `--control` version is adding `--control=fifo:/tmp/$PID_{ctl,ack}.fifo` to the perf invocation. In exchange you don't have to "alt-tab quickly".

But I don't insist; messing with `--control` is probably not worth your time. But I have experience with it, so be warned that I will eventually attempt to replace your solution with `--control`.

**Comment by denesb** [comment]
> But I don't insist; messing with `--control` is probably not worth your time. But I have experience with it, so be warned that I will eventually attempt to replace your solution with `--control`.

I don't mind you replacing my crude stone-age solution with something better. In fact, if this is already in the works or you plan on doing it soon, I don't mind retracting my PR in favor of your future one.

**Comment by michoecho** [comment]
> or you plan on doing it soon

There, done:

https://github.com/michoecho/scylla/commit/05c26adc0d24556c7b492677b83b614a6a57def3

**Comment by denesb** [comment]
Ok, closing this PR then.

**Pull request closed without merging**
