### PR TITLE
main: reload service levels data accessor after join_cluster

### PR DESCRIPTION
**Pull request by nuivall**
Setting data accessor implicitly depends on node joining the cluster
with raft leader elected as only then service level mutation is put
into scylla_local table. Calling it after join_cluster avoids starting
new cluster with older version only to immediately migrate it to the
latest one in the background.

### CODE REVIEW

**Comment by nuivall** [comment]
I hope order change doesn't violate any other implicit dependency - tests will tell.

**Comment by nuivall** [comment]
@piodul @Jadw1 ping

**Review by Jadw1 — APPROVED** [review]
LGTM

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued

**Pull request merged**
