### PR TITLE
docs: add the list of new metrics in 5.1

### PR DESCRIPTION
**Pull request by annastuchlik**
Fix https://github.com/scylladb/scylladb/issues/11377

This PR adds the list of new metrics to the upgrade guide for ScyllaDB Open Source from 5.0 to 5.1

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@nyh @denesb Could you merge this PR? This is the last missing part of the 5.0 to 5.1 upgrade guide.

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to 5.1

Doesn't apply cleanly to 5.1.

**Comment by annastuchlik** [comment]
I think this PR will be backported with https://github.com/scylladb/scylladb/pull/12034.

**Pull request closed without merging**
