### PR TITLE
doc: specify the versions where Alternator TTL is no longer experimental

### PR DESCRIPTION
**Pull request by annastuchlik**
This PR adds a note to the Alternator TTL section to specify in which Open Source and Enterprise versions the feature was promoted from experimental to non-experimental.

The challenge here is that OSS and Enterprise are (still) **documented together**, but they're **not in sync** in promoting the TTL feature: it's still experimental in 5.1 (released) but no longer experimental in 2022.2 (to be released soon).

We can take one of the following approaches:
a) Merge this PR with master and ask the 2022.2 users to refer to master.
b) Merge this PR with master and then backport to branch-5.1. If we choose this approach, it is necessary to backport https://github.com/scylladb/scylladb/pull/11997 beforehand to avoid conflicts.

I'd opt for a) because it makes more sense from the OSS perspective and helps us avoid mess and backporting.

### CODE REVIEW

**Comment by nyh** [comment]
I still don't understand the policy on this across our documentation. We are adding, changing and un-experimentaling features all the time. We don't have a "since version XYZ" for every feature in our documentation. And we usually don't (as far as I know) mention enterprise versions in the open-source documentation. We can change this policy, but I think we should make a deliberate decision across-the-board, not just a temporary decision for Alternator TTL.

I think an approach more suited to how we do the rest of the documentation would be:
1. In master and 5.2, we have the patch that removes the "experimental text". That's already
2. In Enterprise 2022.2, if it's based on 5.2 but we decided to revert the un-exprimentalizing of Alternator TTL, we also need to revert the documentation patch in 2022.2's documentation directory.
3. If 5.2 and 2022.2 have the same documentation, Website, maybe this is a mistake? After all, they don't have the same features. The Alternator TTL exprimentalness is a weird case of not having the same features (which I personally consider a mistake), but there are other Enterprise features that do not exist in 5.2, so how can we have the same documentation website for both?

**Comment by tzach** [comment]
@nyh, we still need to get a separate doc site for Enterprise - it is planned.
Till we do, we managed the Enterprise feature in the same repo as open source  (BTW, it was always the case, but in a different repo).
The cost is such compromises.

**Review by tzach — APPROVED** [review]

**Comment by annastuchlik** [comment]
@scylla/scylla-maint Please merge this PR.

**Comment by nyh** [comment]
The patch says "Remove the note below in version 5.2/2023.1". But you're asking in this PR to commit it to **master** branch, which will, indeed, be 5.2 or 2023.1 - it's not 5.1 or 2022.2, which have already been branched long ago.
Maybe you want to commit this patch to various old releases (5.1? 2022.2? or what?).

**Comment by annastuchlik** [comment]
@nyh You're right; it's my mistake. It should be removed in version 5.3. I'll send another commit to fix it right away. Then, please, merge it to master.

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint @nyh I've fixed the mistake, so the PR is ready to be merged.

We had this discussion last month, and now I can see that branch-5.2 has already been added, so this PR needs to be backported to version 5.2.

**Comment by nyh** [comment]
> @scylladb/scylla-maint @nyh I've fixed the mistake, so the PR is ready to be merged.
> 
> We had this discussion last month, and now I can see that branch-5.2 has already been added, so this PR needs to be backported to version 5.2.

Do you mean you want to merge this patch *only* on branch-5.2 and not on master? This isn't something we normally do, but I guess we can make an exception for documentation (unless @avikivity disapproves).
Or maybe I misunderstood you?

**Comment by annastuchlik** [comment]
@nyh Please see my reply. Could you help us?

**Comment by annastuchlik** [comment]
@nyh Could you help us? This PR should be merged on BOTH master and branch-5.2.

**Comment by nyh** [comment]
I'm on vacation today (and tomorrow) without my computer, sorry...

**Comment by annastuchlik** [comment]
Sure. I'm just making sure it goes to the 5.2 docs, but it can be merged later. Thanks :)

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint This PR has been merged, but it mus be backported to branch-5.2, too.

**Comment by denesb** [comment]
> @scylladb/scylla-maint This PR has been merged, but it mus be backported to branch-5.2, too.

Done.

**Pull request merged**
