### PR TITLE
Update tools/cqlsh submodule

### PR DESCRIPTION
**Pull request by tchaikov**
* tools/cqlsh 66ae7eac...e651e12e (6):
  > setup.py: specify Cython language_level explicitly
  > setup.py: pass extensions as a list
  > setup.py: reindent block in else branch
  > setup.py: early return in get_extension()
  > reloc: install build==0.10.0
  > reloc: add --verbose option to build_reloc.sh

### CODE REVIEW

**Comment by tchaikov** [comment]
for including https://github.com/scylladb/scylla-cqlsh/pull/51

**Comment by tchaikov** [comment]
@fruch hi Israel, could you help review this change?

**Comment by fruch** [comment]
> @fruch hi Israel, could you help review this change?

If CI passes, I think @scylladb/scylla-maint would merge.

I.e. it was re reviewed on the submodule, this is just the test

**Comment by tchaikov** [comment]
i see. will ping the maintainer directly in future. thanks for your explanations.

**Pull request closed without merging**
