### PR TITLE
Update tools/cqlsh submodule to v6.0.17

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh e5f5eafd...28a95c0f (10):
  > cqlshlib/sslhandling.py: don't use empty userkey/usercert
  > Dockerfile: noninteractive isn't enough for answering yet on apt-get
  > fix cqlsh version print
  > cqlshlib/sslhandling: change `check_hostname` deafult to False
  > Introduce new ssl configuration for disableing check_hostname
  > set the hostname in ssl_options.server_hostname when SSL is used
  > issue-73 Fixed a bug where username and password from the credentials file were ignored.
  > issue-73 Fixed a bug where username and password from the credentials file were ignored.
  > issue-73
  > github actions: update `cibuildwheel==v2.16.5`

Fixes: scylladb/scylladb#18590

- [x] ** Backport reason (please explain below if this patch should be backported or not) **

This should be backported to 5.4 - it was found on 2024.1 by a customer waiting for this fix

### CODE REVIEW

**Comment by fruch** [comment]
@scylladb/scylla-maint 

what's that `clang-tidy` check ? and why it's failing ?

**Comment by piodul** [comment]
> @scylladb/scylla-maint
> 
> what's that `clang-tidy` check ? and why it's failing ?

Should be fixed by https://github.com/scylladb/scylladb/pull/18596 (not related to your change)

**Comment by fruch** [comment]
need this fix in dtest first:
https://github.com/scylladb/scylla-dtest/pull/4249

**Comment by fruch** [comment]
@scylladb/scylla-maint 

Can we get this merged ?

**Comment by fruch** [comment]
@yaronkaikov 

This doesn't get a back port PR ?

**Comment by yaronkaikov** [comment]
> @yaronkaikov
> 
> This doesn't get a back port PR ?

It did with https://github.com/scylladb/scylladb/pull/18652, but AFAIK we shouldn't backport the submodule. @denesb is that right? we should probably open a branch in the submodule backport from the submodule and then update it

**Comment by denesb** [comment]
> > @yaronkaikov
> > This doesn't get a back port PR ?
> 
> It did with #18652, but AFAIK we shouldn't backport the submodule. @denesb is that right? we should probably open a branch in the submodule backport from the submodule and then update it

Yes, we cannot directly backport submodule updates.

**Pull request closed without merging**
