### PR TITLE
tools/scylla-nodetool: extract and use {yaml,json}_writers

### PR DESCRIPTION
**Pull request by tchaikov**
simpler this way.

### CODE REVIEW

**Review by denesb — COMMENTED** [review]
I think we should just move this to the top of the file. It is too specific to be reused in other places. Also, we already have a `json_writer.hh` (shared between two .cc files) in `tools/`, it will be hard to tell which is what.

That said, I do not have a strong opinion on this.

**Comment by tchaikov** [comment]
renamed to `format_printers.hh`, as strictly speaking, they don't print tables. so used the more general "printer" here. should be better now.

**Review by denesb — APPROVED** [review]

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6833/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6833/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8058/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/17/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6833/)
> 
> #### Failed Tests (2/23255):
> * [test_change_two](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6833/testReport/junit/%28root%29/test_change_ip/test_change_two) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_change_two)
> * [topology.test_change_ip.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6833/testReport/junit/%28root%29/non-boost%20tests/topology_test_change_ip_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology.test_change_ip.release.3)
> 
> #### Build Details:
> * Duration: 1 hr 43 min
> * Builder: spider8.cloudius-systems.com

#17444

**Comment by tchaikov** [comment]
yes, i will annotate the test failures.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

i have another patch conflict with it. so would be great if this one can be merged sooner.

**Comment by nyh** [comment]
> renamed to `format_printers.hh`, as strictly speaking, they don't print tables. so used the more general "printer" here. should be better now.

Please modify the commit message to refer to the new name.

I don't really have a stake in the organization of the Scylla tools source code, so I'll leave it to @denesb to make a decision on this PR, but In my humble opinion, if some code is specific only to scylla-nodetool.cc, it is better that the code stays in that file, even if it reaches 3000 lines, then move to a different file with a super-general name ("format_printers.hh") which doesn't even begin with a comment explaining its purpose (it should...). If you decide to go with this patch, please at a minimum add to the top of format_printers.hh a comment explaining the purpose of this file.

Another option, if scylla-nodetool.cc grew beyond the size you want to put in a single source file, then you can create a **subdirectory** `nodetool`, and put several source files there (and note that the utility code can also be in a source file, .cc, it doesn't all have to be a header file).

**Comment by tchaikov** [comment]
> > renamed to `format_printers.hh`, as strictly speaking, they don't print tables. so used the more general "printer" here. should be better now.
> 
> Please modify the commit message to refer to the new name.

i didn't reference the filename in the commit message. and i double checked.

> 
> I don't really have a stake in the organization of the Scylla tools source code, so I'll leave it to @denesb to make a decision on this PR, but In my humble opinion, if some code is specific only to scylla-nodetool.cc, it is better that the code stays in that file, even if it reaches 3000 lines, then move to a different file with a super-general name ("format_printers.hh") which doesn't even begin with a comment explaining its purpose (it should...). If you decide to go with this patch, please at a minimum add to the top of format_printers.hh a comment explaining the purpose of this file.

i would add a comment in the top of the file. may i do this in a follow-up change? if this change can be queued today? otherwise i will do so tomorrow.

> 
> Another option, if scylla-nodetool.cc grew beyond the size you want to put in a single source file, then you can create a **subdirectory** `nodetool`, and put several source files there (and note that the utility code can also be in a source file, .cc, it doesn't all have to be a header file).

that's how C* structure nodetool. but that'd involve more changes. i'd leave it to Botond.

**Comment by tchaikov** [comment]
> > > Please modify the commit message to refer to the new name.
> > 
> > 
> > i didn't reference the filename in the commit message. and i double checked.
> 
> I misunderstood the commit title "tools/scylla-nodetool: add {json,yaml}_writer ". I thought this was the name of a file. Turns out it's the name of a class. Which is strange, because you don't actually **add** a class in this patch - you just move it. Right?

not exactly, i actually 1) refactored the code into two classes with the same set interface so they can be reused in a simple way and 2) moved them into a separate header file. 
> 
> > i would add a comment in the top of the file. may i do this in a follow-up change? if this change can be queued today? otherwise i will do so tomorrow.
> 
> Sure. I'll let @denesb queue it, this code is his "baby" :-)

**Comment by denesb** [comment]
I queued this, so we can move forward.

**Pull request merged**
