### PR TITLE
readers/flat_mutation_reader_v2: call set_close_required() from consume*()

### LINKED ISSUE #16520: flat_mutation_reader_v2: consume*() variants don't set `set_close_is_required()`
Since these methods are forwarded to `_impl`, they will not use the wrapper (`flat_mutation_reader_v2`) methods, like `fill_buffer()`, they will use the `flat_mutation_reader_v2::impl` equivalents. This means a reader, consumed entirely by `consume*()` will not set `_is_close_required` and will not complain if destroyed without closing it first.

### PR DESCRIPTION
**Pull request by denesb**
The `consume*()` variants just forward the call to the `_impl` method with the same name. The latter, being a member of `::impl`, will bypass the top level `fill_buffer()`, etc. methods and thus will never call `set_close_required()`. Do this in the top-level `consume*()` methods instead, to ensure a reader, on which only `consume*()` is called, and then is destroyed, will complain as it should (and abort).
Only one place was found in core code, which didn't close the reader: `split_mutation() in `mutation/mutation.cc` and this reader is the "from-mutation" one which has no real close routine. All other places were in tests. All this is to say, there were no real bugs uncovered by this PR.

Fixes #16520

Improvement, no backport required.

### CODE REVIEW

**Comment by denesb** [comment]
https://github.com/scylladb/scylladb/pull/16521 has to be merged first, otherwise most `scylla-sstable` tests will fail with this patch. Possibly some other failures will pop up as well.

**Comment by tchaikov** [comment]
now that #16521 has landed, re-triggering the build and test.

**Comment by tchaikov** [comment]
@denesb looks like a genuine test failure caused by this change.

**Comment by denesb** [comment]
> @denesb looks like a genuine test failure caused by this change.

Yes, it seems there are many more unclosed readers exposed by this change. I expected this.

**Comment by mykaul** [comment]
@denesb - what's the status of this PR ? (specifically for 6.0 inclusion)

**Comment by denesb** [comment]
> @denesb - what's the status of this PR ? (specifically for 6.0 inclusion)

This PR was starved of attention and I don't think it will get the required attention to push it in to 6.0.

**Comment by denesb** [comment]
New in v2:
* Rebase
* Fix all the code which didn't close the reader, after they were uncovered by making `consume()` set `_is_close_required`.

**Review by tgrabiec — APPROVED** [review]

**Pull request merged**
