### PR TITLE
test: give tests less-unique identifiers

### PR DESCRIPTION
**Pull request by avikivity**
Test identifiers are very unique, but this makes them less useful in Jenkins Test Result Analyzer view. For example, counter_test can be counter_test.432 in one run and counter_test.442 in another. Jenkins considers them different and so we don't see a trend.

Limit the id uniqueness within a test case, so that we'll have counter_test.{1, 2, 3} consistently. Those test will be grouped together so we can see pass/fail trends.

### CODE REVIEW

**Comment by avikivity** [comment]
@kostja @fruch need some python help:

```
Traceback (most recent call last):
  File "/home/avi/scylla/./test.py", line 1342, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 1299, in main
    await find_tests(options)
  File "/home/avi/scylla/./test.py", line 1135, in find_tests
    await suite.add_test_list()
  File "/home/avi/scylla/./test.py", line 237, in add_test_list
    await asyncio.gather(*pending)
  File "/home/avi/scylla/./test.py", line 228, in add_test
    await self.add_test(shortname)
  File "/home/avi/scylla/./test.py", line 443, in add_test
    test = RunTest(self.next_id((shortname, self.suite_path, self.mode)), shortname, self)
                   ^^^^^^^^^^^^
TypeError: TestSuite.next_id() missing 1 required positional argument: 'test_key'
```

But, I did provide a positional argument.

**Comment by nyh** [comment]
counter_test.1 seems better than counter_test.442, but don't we still have a problem that counter_test.1 and counter_test.2 are still considered different tests?

What I don't understand is that I remember in the past the history of a specific test did work. Did we have a regresson on this?

**Comment by kostja** [comment]
> > @kostja @fruch need some python help:
> > ```
> > Traceback (most recent call last):
> >   File "/home/avi/scylla/./test.py", line 1342, in workaround_python26789
> >     code = await main()
> >            ^^^^^^^^^^^^
> >   File "/home/avi/scylla/./test.py", line 1299, in main
> >     await find_tests(options)
> >   File "/home/avi/scylla/./test.py", line 1135, in find_tests
> >     await suite.add_test_list()
> >   File "/home/avi/scylla/./test.py", line 237, in add_test_list
> >     await asyncio.gather(*pending)
> >   File "/home/avi/scylla/./test.py", line 228, in add_test
> >     await self.add_test(shortname)
> >   File "/home/avi/scylla/./test.py", line 443, in add_test
> >     test = RunTest(self.next_id((shortname, self.suite_path, self.mode)), shortname, self)
> >                    ^^^^^^^^^^^^
> > TypeError: TestSuite.next_id() missing 1 required positional argument: 'test_key'
> > ```


@avikivity  Are double (()) on purpose?

**Comment by nyh** [comment]
The double parentheses make this into one parameter (which is a tuple) instead of three parameters.

**Comment by avikivity** [comment]
> counter_test.1 seems better than counter_test.442, but don't we still have a problem that counter_test.1 and counter_test.2 are still considered different tests?

It's becomes a minor problem. We'll see counter_test.1 regress and counter_test.2 fixed. That's easy to understand.

Now we see counter_test.442 come to life 5 builds ago and die at the end of the build, and counter_test.541 come to life 4 builds ago, fail, and die at the end of the build.

(we'll have nr_test*3 timelines instead of very sparse nr_test*br_build*3 timelines).


> 
> What I don't understand is that I remember in the past the history of a specific test did work. Did we have a regresson on this?

Without the unique id, Jenkins combined the results of the "identical" tests. I don't remember if it combined them with OR or AND semantics, but both are wrong.

**Comment by kostja** [comment]
I don't get it, I just checked the code and next_id is a property. 
@avikivity is it like you submit a broken pull request and ask me to review it in htis kind manner?)
I don't like the motivation of the fix anyway. Jenkins should truncate the part after the last dot to maintain its database. You can always get from the unique test id to a fully qualified test name using the xml file, and that's what you should do.

**Comment by avikivity** [comment]
> I don't get it, I just checked the code and next_id is a property. @avikivity is it like you submit a broken pull request and ask me to review it in htis kind manner?) 

I'm asking for help because I'm stumped, in a language I'm less familiar with. If you don't want to help that's okay.

> I don't like the motivation of the fix anyway. Jenkins should truncate the part after the last dot to maintain its database. You can always get from the unique test id to a fully qualified test name using the xml file, and that's what you should do.

We don't maintain Jenkins. It collects data from xml files and expect the names to be unique.

I could post-process the xml file, but seems simpler to generate unique ids.

**Comment by avikivity** [comment]
v2:
 - fixed weird python error by dropping @property annotation from next_id. Since the function accepts a non-self parameter, it is not a property.
 - use suite_key instead of path, mode since suite_key is already path, mode

**Comment by avikivity** [comment]
test_raft_upgrade fails, looks spurious. @kbr-

**Comment by kbr-** [comment]
> We don't maintain Jenkins. It collects data from xml files and expect the names to be unique.

How exactly does it determine what the "test name" is?
Does it use the name of the XML file or the contents?

I ran a test `test_stuff` in dev mode and I see two files in `testlog/dev/xml/` directory that could be relevant: junit.xml and test_stuff.1.xunit.xml.

I see that junit.xml contains the unique ID of a test:
```
<testsuite name="non-boost tests" errors="0" tests="1" failures="0"><testcase name="test_stuff.dev.1" /></testsuite>
```

If Jenkins takes the name from junit.xml, we could easily fix the problem by changing the "testcase name" to be `test_stuff.dev` instead of `test_stuff.dev.1`. Then it would consolidate all runs, `counter_test.1` and `counter_test.2` would be the same test.

**Comment by kbr-** [comment]
> If Jenkins takes the name from junit.xml, we could easily fix the problem by changing the "testcase name" to be test_stuff.dev instead of test_stuff.dev.1. Then it would consolidate all runs, counter_test.1 and counter_test.2 would be the same test.

Ok I guess not, if Jenkins expects the names to be unique.

(but then is there no way to tell Jenkins that these are different runs of the same test, and we want the analyzer to consolidate them?)

**Comment by fruch** [comment]
> > If Jenkins takes the name from junit.xml, we could easily fix the problem by changing the "testcase name" to be test_stuff.dev instead of test_stuff.dev.1. Then it would consolidate all runs, counter_test.1 and counter_test.2 would be the same test.
> 
> Ok I guess not, if Jenkins expects the names to be unique.
> 
> (but then is there no way to tell Jenkins that these are different runs of the same test, and we want the analyzer to consolidate them?)

I don't think Jenkins analyzer has this option.

For dtest for example we are sending the test results into elasticsearch, and then we have much better control view/control over results.

Jenkins is limit to a per job history, which mean you can track failures across branches  or scylla-ci.

**Comment by kbr-** [comment]
> For dtest for example we are sending the test results into elasticsearch, and then we have much better control view/control over results.

That sounds very useful. Perhaps we should do this for test.py runs as well.

From my experience, Jenkins analyzer is quite useless. For example, in Scylla-CI, it simply hangs when I want to show the history of a given test. I don't know if it's sorting the results in O(n^5) or what.
(even if it didn't hang, it would still be useless without this PR)

**Comment by avikivity** [comment]
> > We don't maintain Jenkins. It collects data from xml files and expect the names to be unique.
> 
> How exactly does it determine what the "test name" is? Does it use the name of the XML file or the contents?
> 
> I ran a test `test_stuff` in dev mode and I see two files in `testlog/dev/xml/` directory that could be relevant: junit.xml and test_stuff.1.xunit.xml.
> 
> I see that junit.xml contains the unique ID of a test:
> 
> ```
> <testsuite name="non-boost tests" errors="0" tests="1" failures="0"><testcase name="test_stuff.dev.1" /></testsuite>
> ```
> 
> If Jenkins takes the name from junit.xml, we could easily fix the problem by changing the "testcase name" to be `test_stuff.dev` instead of `test_stuff.dev.1`. Then it would consolidate all runs, `counter_test.1` and `counter_test.2` would be the same test.

Those unique IDs were introduced exactly because it merged test results. It merged them with OR semantics, so a flakey test was ignored.

Or maybe I'm misremembering, git says 505f2c1008fdb842bc25e22d792690b517cd18f1

**Comment by avikivity** [comment]
@kostja review please

**Review by kostja — APPROVED** [review]

**Comment by kostja** [comment]
Approved. The new ids looks much nicer. I thought a bit about the number - it's not globally unique any longer, but we don't use these ids anywhere, and even if we do, we can always change the numeric key to the fully qualified test name key (name.id) in these places. But once again, there are no such places as I recall. 

You could improve the patch by providing the motivation for the id generation scheme in a comment to next_id()  - that would help preserve the goals you pursued in your scheme in the future. Not everyone reads the commit comments.

**Comment by avikivity** [comment]
v3: added comment explaining the reasoning behind next_id()

**Comment by avikivity** [comment]
(this is why I want this patch:

image
)

**Pull request closed without merging**
