### PR TITLE
storage_service: Reject decommission if nodes are down

### LINKED ISSUE #11302: Node decommissions successfully in a split-brain cluster, forever staying DL for its peers
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6.3, not tested against other versions
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): N/A

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): Kubernetes, only reproduced in [kind](https://kind.sigs.k8s.io/) so far

The issue originated from a functional test created by QA (@vponomaryov): https://github.com/scylladb/scylla-cluster-tests/blob/4af808c848863d1b3e96c3581bb51fe13a9f986f/functional_tests/scylla_operator/test_functional.py#L174. See https://github.com/scylladb/scylla-operator/issues/982 for the original issue.

Below a very brief description of the issue, for more context please see [my comment under the original issue](https://github.com/scylladb/scylla-operator/issues/982#issuecomment-1205214536) and the discussion that follows it.

The minimal scenario to reproduce this issue would be as follows:
```
1. Set up a 3 node Scylla Cluster
2. Stop the last Scylla node
3. Start the last Scylla node again
4. Immediately decommission the last Scylla node
```

When you run the above scenario in [kind](https://kind.sigs.k8s.io/), you hit the very specific conditions that are required to reproduce the bug:
1. **There is no gossip traffic going from nodes 1 and 2 to node 3.** 
2. All the other rpc traffic flows normally, including gossip traffic from node 3 to nodes 1 and 2 and **responses to node_ops commands from nodes 1 and 2 to node 3.**

What happens then is that, due to the lack of gossip exchange, the cluster goes split-brain. Nodes 1 and 2 see each other as UN and both see node 3 as DN. Node 3 sees itself as UN and all the other nodes as DN.
Since node_ops commands are exchanged without any issues, the decommissioning of node 3 succeeds, despite it seeing other nodes as DN.

This, in turn, causes node 3 to stay in nodes 1 and 2's peers tables as DL forever. 

To sum up, what causes this issue is the unfortunate timing of the decommissioning happening before there's successful gossip exchange. You won't observe it if you wait for all the nodes to see each other as UN.

I believe that the expected behavior should be for the decommissioning to fail in that scenario.

Again, to see the details, including logs and tcpdumps, see [the discussion in the original issue](https://github.com/scylladb/scylla-operator/issues/982).

Although I was only able to reproduce it in [kind](https://kind.sigs.k8s.io/), I think there are enough reasons to think that's a Scylla bug. Dropping the gossip packets going from nodes 1 and 2 to node 3 should be enough to reproduce it.

@fruch also claims he has a viable reproducer: https://github.com/scylladb/scylla-operator/issues/982#issuecomment-1207434655

fyi @slivne

### PR DESCRIPTION
**Pull request by asias**
- Start n1, n2, n3

- Apply network nemesis as below:
  + Block gossip traffic going from nodes 1 and 2 to node 3.
  + All the other rpc traffic flows normally, including gossip traffic
    from node 3 to nodes 1 and 2 and responses to node_ops commands from
    nodes 1 and 2 to node 3.

- Decommission n3

Currently, the decommission will be successful because all the network
traffic is ok. But n3 could not advertise status STATUS_LEFT to the rest
of the cluster due to the network nemesis applied. As a result, n1 and
n3 could not move the n3 from STATUS_LEAVING to STATUS_LEFT, so n3 will
stay in DL forever.

I know why the node stays DL forever. The problem is that with
node_ops_cmd based node operation, we still rely on the gossip status of
STATUS_LEFT from the node being decommissioned to notify other nodes
this node has finished decommission and can be moved from STATUS_LEAVING
to STATUS_LEFT.

This patch fixes by checking gossip liveness before running
decommission. Reject if required peer nodes are down.

With the fix, the decommission of n3 will fail like this:

$ nodetool decommission -p 7300
nodetool: Scylla API server HTTP POST to URL
'/storage_service/decommission' failed: std::runtime_error
(decommission[adb3950e-a937-4424-9bc9-6a75d880f23d]: Rejected
decommission operation, removing node=127.0.0.3, sync_nodes=[127.0.0.2,
127.0.0.3, 127.0.0.1], ignore_nodes=[], nodes_down={127.0.0.1})

Fixes #11302

### CODE REVIEW

**Comment by fruch** [comment]
@asias would `nodetool removenode` would need similar issue ? or there we don't relay on gossip, since the node is dead already ? (i.e. trying to think if there are more topology changing sequences that we might hit something similar)

**Comment by asias** [comment]
> @asias would `nodetool removenode` would need similar issue ? or there we don't relay on gossip, since the node is dead already ? (i.e. trying to think if there are more topology changing sequences that we might hit something similar)

Yes, something similar would happen to removenode as well, although this is rare in practice. Can you add a similar test for removenode and report a scylla bug for what failed in the new test?

**Comment by fruch** [comment]
> > @asias would `nodetool removenode` would need similar issue ? or there we don't relay on gossip, since the node is dead already ? (i.e. trying to think if there are more topology changing sequences that we might hit something similar)
> 
> Yes, something similar would happen to removenode as well, although this is rare in practice. Can you add a similar test for removenode and report a scylla bug for what failed in the new test?

@asias here a new test:
https://github.com/scylladb/scylla-dtest/pull/2835/commits/276fd1fe975c5981c3f8b47c5ec58d525dcc3d2a

seems like something isn't working at this situation, and node2 thinks node1 and node2 are down. not clear why.

**Comment by asias** [comment]
> > > @asias would `nodetool removenode` would need similar issue ? or there we don't relay on gossip, since the node is dead already ? (i.e. trying to think if there are more topology changing sequences that we might hit something similar)
> > 
> > 
> > Yes, something similar would happen to removenode as well, although this is rare in practice. Can you add a similar test for removenode and report a scylla bug for what failed in the new test?
> 
> @asias here a new test: [scylladb/scylla-dtest@276fd1f](https://github.com/scylladb/scylla-dtest/commit/276fd1fe975c5981c3f8b47c5ec58d525dcc3d2a)
> 
> seems like something isn't working at this situation, and node2 thinks node1 and node2 are down. not clear why.

Thanks. I will take a look later. I am on something else.

**Comment by asias** [comment]
@avikivity Ping for merge. Useful for k8s deployment where ip changes.

**Comment by tnozicka** [comment]
@avikivity would you mind taking a look and possibly backporting it? (I was tracing down a flake on my TLS PR and it lead me here again.)

**Comment by avikivity** [comment]
Sorry about the delayed review. @asias doesn't this conflict with repair-based-node-ops? RBNO allows streaming from the two surviving replicas, so it can decommission if a node is down.

**Comment by asias** [comment]
> Sorry about the delayed review. @asias doesn't this conflict with repair-based-node-ops? RBNO allows streaming from the two surviving replicas, so it can decommission if a node is down.

This does not conflict with RBNO. We require all nodes in the cluster to be aware the node operation to avoid partitioned node to use wrong topology.  The ability to get data from more replicas has not help.

**Comment by avikivity** [comment]
> > Sorry about the delayed review. @asias doesn't this conflict with repair-based-node-ops? RBNO allows streaming from the two surviving replicas, so it can decommission if a node is down.
> 
> This does not conflict with RBNO. We require all nodes in the cluster to be aware the node operation to avoid partitioned node to use wrong topology. The ability to get data from more replicas has not help.

I see. This will only be truly fixed by the fencing work.

**Pull request closed without merging**
