### PR TITLE
treewide: replace seastar::future::get0() with seastar::future::get()

### PR DESCRIPTION
**Pull request by avikivity**
get0() dates back from the days where Seastar futures carried tuples, and get0() was a way to get the first (and usually only) element. Now it's a distraction, and Seastar is likely to deprecate and remove it.

Replace with seastar::future::get(), which does the same thing.

### CODE REVIEW

**Comment by nyh** [comment]
CI says that the build succeeds in dev mode, but fails in debug mode (in cql3/statements/select_statement.cc), perhaps due to different stuff optimized out.

**Review by nyh — APPROVED** [review]
Looks good to me, although for obvious reasons I can't say I actually went through every single one of the thousand changes in this patch, I trust that you did this change more-or-less automatically.

The patch version fails build in debug mode (see CI results), so it will need to be fixed before this PR can be merged.

**Comment by tchaikov** [comment]
@nyh @avikivity hi Nadav and Avi, since this change has been stalled for almost a week. i am willing help to move it forward, hence created #17022. could you please help take a look?

**Comment by denesb** [comment]
> @nyh @avikivity hi Nadav and Avi, since this change has been stalled for almost a week. i am willing help to move it forward, hence created #17022. could you please help take a look?

You mean https://github.com/scylladb/scylladb/pull/17130?

**Comment by tchaikov** [comment]
> > @nyh @avikivity hi Nadav and Avi, since this change has been stalled for almost a week. i am willing help to move it forward, hence created #17022. could you please help take a look?
> 
> You mean #17130?

indeed. thank you! fixed.

**Comment by avikivity** [comment]
Superseded by #17130 (784c2f8ad21f42cacc1aa3df068951108ebf2a9c)

**Pull request closed without merging**
