### PR TITLE
[branch 5.1 backport] doc: remove the Operator documentation pages from the core ScyllaDB docs

### PR DESCRIPTION
**Pull request by annastuchlik**
This is a backport of https://github.com/scylladb/scylladb/pull/11154.

### CODE REVIEW

**Comment by denesb** [comment]
Doesn't apply to 5.1. Maybe because I recently backported https://github.com/scylladb/scylladb/pull/11151.

**Comment by annastuchlik** [comment]
@denesb I can see that this PR and https://github.com/scylladb/scylladb/pull/11151 are related, but https://github.com/scylladb/scylladb/pull/11151 doesn't apply cleanly either.
I'm not sure what to do now. Could you advise?

**Comment by annastuchlik** [comment]
@denesb The changes introduced with this PR are correctly backported to 5.1 - I compared the conflicting "redirects.yaml" file on master and branch-5.1, and they look good. I think there is nothing else to do with this PR.

**Comment by denesb** [comment]
> 

Does that mean this backport is not needed anymore?

**Comment by annastuchlik** [comment]
It looks like the backport is still necessary. I checked all the files affected by the commits in https://github.com/scylladb/scylladb/pull/11154, and I can see that something went wrong with this backport PR. I didn't correctly resolve one conflict, but there is another issue that may be related to that another PR being merged.

I've no idea how to fix all that, so I'm closing this PR to open a new one.

**Comment by annastuchlik** [comment]
I will.

**Comment by annastuchlik** [comment]
@denesb I've rebased and resolved all the conflicts. Does it apply now?

**Comment by denesb** [comment]
> @denesb I've rebased and resolved all the conflicts. Does it apply now?

Yes, it applies now. Queued.
Note that you may have to close this PR manually after the merge promotes, AFAIK github only auto-closes PRs when the merge commit gets into master, which won't happen for a backport.

**Pull request merged**
