### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by tchaikov**
* seastar cd8a9133...b5fcf7ed (7):
  > timed_out_error: add fmt::formatter for timed_out_error
  > scripts/stall-analyser: change default branch-threshold to 3%
  > scripts/stall-analyser: resolve string escape sequence warning
  > stall-analyser: add space around '=' in param list
  > stall-analyser: add a space between 'var: Type' in type annotation
  > stall-analyser: move variables closer to where they are used
  > memory: drop support for compilers that don't support aligned new

### CODE REVIEW

**Comment by tchaikov** [comment]
@bhalevy just wanted to check with you, we don't need to backport "scripts/stall-analyser: change default branch-threshold to 3%" to LTS branches, right?

**Comment by tchaikov** [comment]
pending on #18114

**Comment by bhalevy** [comment]
> @bhalevy just wanted to check with you, we don't need to backport "scripts/stall-analyser: change default branch-threshold to 3%" to LTS branches, right?

No, no need.
We do need to update the seastar submodule in scylla_s3_reloc_server though

**Comment by tchaikov** [comment]
ack. lemme take care of this.

**Comment by tchaikov** [comment]
closing this one in favor of #18151

**Pull request closed without merging**
