### PR TITLE
gms: remove unused #includes 

### PR DESCRIPTION
**Pull request by tchaikov**
these unused includes are identified by clang-include-cleaner. after auditing the source files, all of the reports have been
confirmed.

---

it's a cleanup, hence no need to backport.

### CODE REVIEW

**Review by nyh — APPROVED** [review]
Looks good.

But I think if this "cleaner" looks for **unused** header files, we should stop calling it in commit messages (and in the workflow name) "include what you use". It's confusing.

**Comment by regevran** [comment]
I think that adding 
```c++
#include <seastar/core/distributed.hh>
```
to `./service/load_broadcaster.hh` wil do the trick.
It used to be in `"gms/gossiper.hh" but now it is not.

**Comment by tchaikov** [comment]
> I think that adding
> 
> ```c++
> #include <seastar/core/distributed.hh>
> ```
> 
> to `./service/load_broadcaster.hh` wil do the trick. The said include used to be in `"gms/gossiper.hh"` but now it is not.

thank you for the insights, i was on my way home. so didn't have access to my laptop.

**Comment by tchaikov** [comment]
> Looks good.
> 
> But I think if this "cleaner" looks for **unused** header files, we should stop calling it in commit messages (and in the workflow name) "include what you use". It's confusing.

this linter actually looks for unused header and used header but not included. i only enabled the former. but yes, it is less confusing if we can change the name to reflect what we're using it for.

**Pull request merged**
