### PR TITLE
select statement: verify EXECUTE permissions only for non native functions

### LINKED ISSUE #16526: System functions like count() don't work anymore for custom role after upgrade to 5.4.0
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.4.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

After upgrading from scylladb 5.2.11 to 5.4.0 I receive the following error(s):
```
User rw has no EXECUTE permission on <function system."countRows"()> or any of its parents
```

I use `--authenticator PasswordAuthenticator --authorizer CassandraAuthorizer` and create a role with `CREATE ROLE rw WITH PASSWORD='rw' AND LOGIN=true AND SUPERUSER=false;`.
Using that role and this simple query doesn't work anymore in 5.4.0:
```
SELECT count(*) from mykeyspace.mytable;
```

Reproducible with docker:
```
#!/bin/bash

SCYLLA_ARGS="--authenticator PasswordAuthenticator --authorizer CassandraAuthorizer --smp 1 --skip-wait-for-gossip-to-settle 0"
INIT_SCRIPT="CREATE ROLE rw WITH PASSWORD='rw' AND LOGIN=true AND SUPERUSER=false;
CREATE KEYSPACE mykeyspace WITH replication = {'class' : 'NetworkTopologyStrategy' ,'datacenter1': 1} AND durable_writes = 'true';
CREATE TABLE mykeyspace.mytable(id uuid, PRIMARY KEY(id));
GRANT SELECT ON KEYSPACE mykeyspace TO rw;
GRANT MODIFY ON KEYSPACE mykeyspace TO rw;"

echo "Running 5.2.11"

docker run --name scylla5211 -d scylladb/scylla:5.2.11 "$SCYLLA_ARGS"
sleep 5
docker exec -it scylla5211 cqlsh -u cassandra -p cassandra -e "$INIT_SCRIPT"

# Works with 5.2.11
docker exec -it scylla5211 cqlsh -u rw -p rw -e "SELECT count(*) from mykeyspace.mytable;"

docker stop scylla5211 > /dev/null
docker rm scylla5211 > /dev/null

echo "Running 5.4.0"

docker run --name scylla540 -d scylladb/scylla:5.4.0 "$SCYLLA_ARGS"
sleep 5
docker exec -it scylla540 cqlsh 172.17.0.2 -u cassandra -p cassandra -e "$INIT_SCRIPT"

# Now this fails with 5.4.0?
docker exec -it scylla540 cqlsh 172.17.0.2 -u rw -p rw -e "SELECT count(*) from mykeyspace.mytable;"

# Error is:
#<stdin>:1:Unauthorized: Error from server: code=2100 [Unauthorized] message="User rw has no EXECUTE permission on <function system."countRows"()> or any of its parents"

docker stop scylla540 > /dev/null
docker rm scylla540 > /dev/null
```

Output:
```
Running 5.2.11
13cfa76b8c08a6c3ffa8a068f1f769d847d2bedec612f5de6fbe5a054b2150ae

 count
-------
     0

(1 rows)
Running 5.4.0
5c1cce8924562838d0ea2192ee6a7de33297595295f572e561dde114ffa703c8

Warning: Using a password on the command line interface can be insecure.
Recommendation: use the credentials file to securely provide the password.


Warnings :
Using Replication Factor datacenter1=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.


Warning: Using a password on the command line interface can be insecure.
Recommendation: use the credentials file to securely provide the password.

<stdin>:1:Unauthorized: Error from server: code=2100 [Unauthorized] message="User rw has no EXECUTE permission on <function system."countRows"()> or any of its parents"
```

I haven't seen anything on this topic in the [upgrade guide](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.2-to-5.4/upgrade-guide-from-5.2-to-5.4-generic.html) so this is either a bug in Scylla or something is missing in the upgrade guide.

### PR DESCRIPTION
**Pull request by eliransin**
Commit 62458b8e4f9c387d5ff5ad294c3383c5e8d54ce1 introduced the enforcement of EXECUTE permissions of functions in cql select. However, according to the reference in #12869, the permissions should be enforced only on UDFs and UDAs.
The code does not distinguish between the two so the permissions are also unintenionally enforced also on native function. This commit introduce the distinction and only enforces the permissions on non native functions.

Fixes #16526

Manually verified (before and after change) with the reproducer supplied in #16526 and also with some the `min` and `max` native functions.
Also added test that checks for regression on native functions execution and verified that it fails on authorization before 
the fix and passes after the fix.

### CODE REVIEW

**Comment by nyh** [comment]
Please try to add a regression test for this and not just manually verify it. I hope that test/cql-pytest/test_permissions.py has all the facilities you need to check this.

**Review by nyh — CHANGES_REQUESTED** [review]
Looks good to me.

I wonder if we couldn't just create all these native functions from the get-go with "execute permissions for everyone", and then we wouldn't need to to add this extra exception, but actually this exception makes the check even faster for builtin functions, so maybe your approach is even better in this sense.

But I'd like to have a regression test please. I'm hoping it will be easy to add in test/cql-pytest/test_permissions.py (let me know if you need help in doing this, and @wmitros also has recent experience with this test file).

**Comment by eliransin** [comment]
> Looks good to me.
> 
> I wonder if we couldn't just create all these native functions from the get-go with "execute permissions for everyone", and then we wouldn't need to to add this extra exception, but actually this exception makes the check even faster for builtin functions, so maybe your approach is even better in this sense.
> 
> But I'd like to have a regression test please. I'm hoping it will be easy to add in test/cql-pytest/test_permissions.py (let me know if you need help in doing this, and @wmitros also has recent experience with this test file).

The way that permissions work is that they are granted to roles, not to users.
We could automatically grant EXECUTE permissions for the `system` keyspace, however it makes the solutions
complicated IMO, also if the permissions are implicit, why risking all sorts of edge cases like when user is revoked EXECUTE for all functions, then suddenly he will also not be able to execute native functions (or we will need to handle 
this edge case).
If at some point we will need to actually manage access to native functions we will need to revert to your solution.

**Comment by eliransin** [comment]
V2 added a regression test based on the reproducer and manual testing I did.

**Review by nyh — APPROVED** [review]
Thanks, looks good.
Can you please confirm that the new test fails before your patch?

**Comment by nyh** [comment]
> Thanks, looks good. Can you please confirm that the new test fails before your patch?

@eliransin as soon as you say "yes, the test fails before my patch", I'll merge your PR :-)

**Comment by eliransin** [comment]
> > Thanks, looks good. Can you please confirm that the new test fails before your patch?
> 
> @eliransin as soon as you say "yes, the test fails before my patch", I'll merge your PR :-)

Sorry, I missed it. "yes" :slightly_smiling_face: 

>lso added test that checks for regression on native functions execution and verified that it fails on authorization before
the fix and passes after the fix.

I edited the cover letter but failed to mention it :blush:

**Comment by mykaul** [comment]
I'm sure it was backported already...

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/commit/3d22f42cf9c347a7f1ddcd7f255501cd9cf96b31 is in 5.4.

**Pull request merged**
