### PR TITLE
[Backport 6.1] Fix node replace with inter-dc encryption enabled.

### PR DESCRIPTION
**Pull request by gleb-cloudius**
Currently if a coordinator and a node being replaced are in the same DC while inter-dc encryption is enabled (connections between nodes in the same DC should not be encrypted) the replace operation will fail. It fails because a coordinator uses non encrypted connection to push raft data to the new node, but the new node will not accept such connection until it knows which DC the coordinator belongs to and for that the raft data needs to be transferred.

The series adds the test for this scenario and the fix for the chicken&egg problem above.

The series (or at least the fix itself) is need to be backpooted because this is a serious regression.

Fixes: https://github.com/scylladb/scylladb/issues/19025

(cherry picked from commit https://github.com/scylladb/scylladb/commit/84757a4ed3f4038efb5724dd4f5acbf545aedd3b)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/b98282a976134606314b308ec933a1ec63fe1f96)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/2f1b1fd45e727cb65ae820d7d52aaf647fa6a743)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/17f4a151ce27114a66a83874705c223e0dba9ceb)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/32a59ba98f1cf7fd0cb96028d2874d66739ac158)

Refs https://github.com/scylladb/scylladb/pull/20290

### CODE REVIEW

**Comment by gleb-cloudius** [comment]
@yaronkaikov mergify will not create a backport to 6.0 for me?

**Comment by yaronkaikov** [comment]
> @yaronkaikov mergify will not create a backport to 6.0 for me?

Only from the original PR .. not from a release

**Comment by yaronkaikov** [comment]
There is one opened already https://github.com/scylladb/scylladb/pull/20354

**Comment by gleb-cloudius** [comment]
> > @yaronkaikov mergify will not create a backport to 6.0 for me?
> 
> Only from the original PR .. not from a release

Why not? Often a conflict resolution is the same.

**Comment by gleb-cloudius** [comment]
> There is one opened already #20354

Yes, but it has conflicts, so I need to create a new one. I created this one for 6.1. I am 99% sure it can be backported to 6.0 without a conflicts. So why not?

**Comment by yaronkaikov** [comment]
> > > @yaronkaikov mergify will not create a backport to 6.0 for me?
> > 
> > 
> > Only from the original PR .. not from a release
> 
> Why not? Often a conflict resolution is the same.

Because normally we will do backports from `master` to releases. At the moment this is how Mergify is configured

**Comment by yaronkaikov** [comment]
> > There is one opened already #20354
> 
> Yes, but it has conflicts, so I need to create a new one. I created this one for 6.1. I am 99% sure it can be backported to 6.0 without a conflicts. So why not?

We can check this option, but it will not be today or tomorrow :-), so yes, for now a new PR should be created

**Comment by kbr-scylla** [comment]
Is there no magic mergify-bot incantation that we could do to explicitly tell it to create backport based on this PR? cc @tchaikov

**Comment by gleb-cloudius** [comment]
> Is there no magic mergify-bot incantation that we could do to explicitly tell it to create backport based on this PR? cc @tchaikov

In this particular case one of the patches had conflict between 6.1 and 6.0 still. But I think the feature would be useful.

**Comment by tchaikov** [comment]
@Mergifyio backport branch-6.0

**Comment by tchaikov** [comment]
> Is there no magic mergify-bot incantation that we could do to explicitly tell it to create backport based on this PR? cc @tchaikov

i don't have the permission to do this. only maintainers who have the write permissions to this repo are allowed to create a backport branch.

**Comment by gleb-cloudius** [comment]
> @Mergifyio backport branch-6.0

Magic. It even gives thumb up.

**Comment by kbr-scylla** [comment]
@Mergifyio backport branch-6.0

**Comment by kbr-scylla** [comment]
it expects this PR to be merged first before creating the backport branch :D
(also it will probably be titled `[Backport 6.0] [Backport 6.1] ...`)

**Pull request merged**
