### PR TITLE
Update ./seastar submodule

### PR DESCRIPTION
**Pull request by denesb**
* ./seastar 69f88e2f...3c9c2696 (14):
  > core/reactor: don't check AIO block count when they are not needed
  > build: do not print the default value of --c++-standard in help output
  > json_formatter: Add tests for formatter::write
  > Add APIs to get group details and to change ownership of file.
  > scripts/perftune.py: improve a dry-run printout
  > build: drop the workaround for a GCC bug
  > cmake: Depend on libbsd if DPDK depends on it
  > http: clarify the ownership in the router's doxygen comment
  > build: check for P2582R1 support
  > python: introduce a python formatting CI check
  > addr2line: reformat with black
  > scripts: add pyproject.toml
  > json_formatter: Make formatter::write work for std::pair
  > README.md: use the github homepage of Ceph for Crimson

Fixes: https://github.com/scylladb/scylladb/issues/19185

Submodule update, no backport required.

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@avikivity @nyh Can you please merge this?

**Comment by avikivity** [comment]
I see some checks failed

**Comment by yaronkaikov** [comment]
@avikivity the only thing is clang-tidy  and I think it will be addressed by @tchaikov as part of https://github.com/scylladb/scylladb/pull/20841

**Comment by tchaikov** [comment]
> @avikivity the only thing is clang-tidy and I think it will be addressed by @tchaikov as part of #20841

#20824 should address the issue. unfortunately, #20841 does not.

**Comment by denesb** [comment]
> [test_kill_coordinator_during_op.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/11930/testReport/junit/%28root%29/test_crash_coordinator_before_streaming/Tests___Unit_Tests___test_kill_coordinator_during_op_debug_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_kill_coordinator_during_op.debug.1)

https://github.com/scylladb/scylladb/issues/20701

**Comment by denesb** [comment]
> [test_tablet_drain_failure_during_decommission.dev.5](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/11956/testReport/junit/%28root%29/test_topology_failure_recovery/Tests___Unit_Tests___test_tablet_drain_failure_during_decommission_dev_5) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_drain_failure_during_decommission.dev.5)

https://github.com/scylladb/scylladb/issues/20060

**Pull request closed without merging**
