### PR TITLE
service/storage_proxy: coroutinize handle_paxos_accept() 

### PR DESCRIPTION
**Pull request by tchaikov**
for better readability.

- [x] no need to backport. it's a cosmetic change.

### CODE REVIEW

**Review by avikivity — APPROVED** [review]

**Comment by avikivity** [comment]
> it's a cosmetic change.

I'm sure it's a small performance improvement too.

**Comment by tchaikov** [comment]
v2:

- rebased onto master HEAD.

**Comment by tchaikov** [comment]
> > it's a cosmetic change.
> 
> I'm sure it's a small performance improvement too.

hi Avi, why do you think this change improves the performance? because an `then_wrapped()` block is dropped, as `finally()` is implemented using it, and the awaiter of the inner coroutine can help propagate the exception to the caller when it is thrown?

**Comment by avikivity** [comment]
> > > it's a cosmetic change.
> > 
> > 
> > I'm sure it's a small performance improvement too.
> 
> hi Avi, why do you think this change improves the performance? because a `then_wrapped()` block is dropped, as `finally()` is implemented using it, and the awaiter of the inner coroutines can help propagate the exception to the caller when it is thrown?

I take it back. Sometimes long continuation chains cause one allocation per continuation, if the first one yields. But here get_schema_for_read() doesn't yield, and the finally() is conditional and unlikely.

It's probably a small performance loss due to the inner coroutine that adds an allocation.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

**Pull request closed without merging**
