### PR TITLE
db/config.cc: increment components_memory_reclaim_threshold config de…

### LINKED ISSUE #18607: bloom-filter: default value for components_memory_reclaim_threshold is too strict
`components_memory_reclaim_threshold` controls when we start evicting bloom filters from memory. It defaults to 0.1, which comes down to 10% of the shard's memory. It looks like this is too strict and causes unnecessary bloom filter eviction in otherwise healthy clusters. One cluster which was impacted by this, had a BF/memory ratio of 0.6. The eviction mechanism was introduced to avert OOM disasters, not to enforce lean bloom filters and so the default should be adjusted accordingly and increased to as high as 0.8 or even maybe 0.9. The idea is that by default it should only kick in when OOM is iminent, it should not intervene on clusters which have high BF memory consumption but are otherwise fine.

### PR DESCRIPTION
**Pull request by denesb**
…fault

Incremented the components_memory_reclaim_threshold config's default value to 0.2 as the previous value was too strict and caused unnecessary eviction in otherwise healthy clusters.

Fixes #18607

Needs backport all the way to 5.2, as the overly strict default is present in these versions.

### CODE REVIEW

**Comment by denesb** [comment]
This PR is an update of https://github.com/scylladb/scylladb/pull/18611. The author is on PTO and this PR is holding up a release.

**Comment by denesb** [comment]
> * [test_bloom_filter_reclaim_during_reload](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9318/testReport/junit/boost/sstable_datafile_test/test_bloom_filter_reclaim_during_reload) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_bloom_filter_reclaim_during_reload)
> 
> * [test_sstable_manager_auto_reclaim_and_reload_of_bloom_filter](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/9318/testReport/junit/boost/sstable_datafile_test/test_sstable_manager_auto_reclaim_and_reload_of_bloom_filter) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_sstable_manager_auto_reclaim_and_reload_of_bloom_filter)

I think I need to adjust the memory amount in the test, according to the change I did to the threshold.

**Comment by denesb** [comment]
Ok, I'm out of ideas why the test failed. We will have to wait for @lkshminarayanan to return and take a look.

**Comment by lkshminarayanan** [comment]
> Ok, I'm out of ideas why the test failed. We will have to wait for @lkshminarayanan to return and take a look.

@denesb you need to update the available memory to 500 in another testcase as well -  `test_bloom_filter_reclaim_during_reload`

**Comment by denesb** [comment]
> > Ok, I'm out of ideas why the test failed. We will have to wait for @lkshminarayanan to return and take a look.
> 
> @denesb you need to update the available memory to 500 in another testcase as well - `test_bloom_filter_reclaim_during_reload`

Thanks, done.

**Comment by mykaul** [comment]
@avikivity - please review.

**Review by avikivity — APPROVED** [review]

**Pull request closed without merging**
