### PR TITLE
Update seastar submodule

### LINKED ISSUE #18554: scylla-nodetool --help exits with error status
https://github.com/scylladb/scylla-ccm/pull/574 wants scylla nodetool to returns a success status when invoked with `--help` so we can detect when a nodetool command is supported by the native scylla nodetool.

But currently (2d9142250eac278286428f52f62d339691d3598a), all seastar-based applications, including scylla, return status code 1 on `--help`.
This was fixed by https://github.com/scylladb/seastar/pull/2213 , which requires seastar submodule update to take effect in scylla.

### PR DESCRIPTION
**Pull request by bhalevy**
* seastar b73e5e7d...d3657ec7 (26):
      > tests/unit: add a unit test for json2code
      > seastar-json2code: fix the path param handling
      > github/workflow: do not override <clang++,23,release>
      > github/workflow: add a github workflow for running tests
      > prometheus: support disabling aggregation at query time
      > apps/httpd: free allocated http_server_control
      > rpc: cast rpc::tuple to std::tuple when passing it to std::apply
      > stall-analyser: move `args` into main()
      > stall-analyser: move print_command_line_options() out of Graph
      > stall-analyser: pass branch_threshold via parameter
      > stall-analyser: move process_graph() into Graph class
      > scripts: addr2line: cache the results of resolve_address()
      > stall-analyser: document the parser of log lines
      > stall-analyser: move resolver into main()
      > stall-analyser: extract get_command_line_parser() out
      > stall-analyser: move graph into main()
      > stall-analyser: extract main() out
      > stall-analyser: extract print_command_line_options() out
      > stall-analyser: add more typing annotatins
      > stall-analyser: surround top-level function with two empty lines
      > core/app_template: return status code 0 for --help
      > iotune: Print file alignments too
      > seastar-json2code: extract Parameter class
      > seastar-json2code: use f-string when appropriate
      > seastar-json2code: use nickname in place of oper['nickname']
      > seastar-json2code: use dict.get() when checking allowMultiple
    
Fixes #18554

- [x] ** Backport reason (please explain below if this patch should be backported or not) **
No backport required as we rely on scylla nodetool for tablets and testing in general on in master (5.5-dev)

### CODE REVIEW

**Comment by tchaikov** [comment]
we need to merge https://github.com/scylladb/seastar/pull/2223 first.

**Comment by bhalevy** [comment]
Updated seastar HEAD to scylladb/seastar@d3657ec7
to include scylladb/seastar#2223

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8647/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8647/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9480/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1457/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8647/)
> #### Failed Tests (124/30662):
> 
>     * [test_read_by_gaussian_key_distribution](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/toppartitions_test/TestTopPartitions/Tests___dtest___test_read_by_gaussian_key_distribution) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_read_by_gaussian_key_distribution)

should be addressed by https://github.com/scylladb/scylla-dtest/pull/4233

> 
>     * [test_dropping_keyspace_system_auth_2_nodes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/auth_test/TestAuth/Tests___dtest_with_topology_changes___test_dropping_keyspace_system_auth_2_nodes) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_dropping_keyspace_system_auth_2_nodes)
> 
>     * [test_snapshot_defaults_to_all_keyspaces](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/snapshot_test/TestSnapshotOptions/Tests___dtest_with_topology_changes___test_snapshot_defaults_to_all_keyspaces) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_snapshot_defaults_to_all_keyspaces)
> 
>     * [test_replace_active_node[use_host_id-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_host_id_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_host_id-rbo_enabled%5D)
> 
>     * [test_replace_active_node[use_host_id-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_host_id_rbo_enabled__2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_host_id-rbo_enabled%5D)
> 
>     * [test_replace_active_node[use_host_id-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_host_id_rbo_disabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_host_id-rbo_disabled%5D)
> 
>     * [test_replace_active_node[use_host_id-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_host_id_rbo_disabled__2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_host_id-rbo_disabled%5D)
> 
>     * [test_replace_active_node[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_endpoint_rbo_enabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_endpoint-rbo_enabled%5D)
> 
>     * [test_replace_active_node[use_endpoint-rbo_enabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_endpoint_rbo_enabled__2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_endpoint-rbo_enabled%5D)
> 
>     * [test_replace_active_node[use_endpoint-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/8647/testReport/junit/replace_address_test/TestReplaceAddress/Tests___dtest_with_topology_changes___test_replace_active_node_use_endpoint_rbo_disabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_active_node%5Buse_endpoint-rbo_disabled%5D)
> 
> 
> #### Build Details:
> 
>     * Duration: 2 hr 35 min
> 
>     * Builder: spider1.cloudius-systems.com

**Comment by tchaikov** [comment]
also picked some random failing tests and tried to reproduce them locally, so far, no luck.

**Comment by tchaikov** [comment]
and we need to merge https://github.com/scylladb/seastar/pull/2232 ~~first~~ second.

**Comment by bhalevy** [comment]
@tchaikov why are we finding all those things now when trying to update the seastar submodule in scylla?
The changes committed to seastar should have been tested throughly beforehand, either by unit tests in seastar (which should be preferred) and/or tested with an application like scylla before they were submitted for inclusion.
We shouldn't do the dev testing on the master branch.  It must be only the last resort if preliminary testing didn't catch certain issues.

**Comment by tchaikov** [comment]
i think the reason is that we didn't have the test for either of the changes, and we didn't test it with scylla. as you pointed out in your comment. i think what we can do is to create better tests. and i am working on this. just created https://github.com/scylladb/seastar/issues/2233 .

**Comment by bhalevy** [comment]
@tchaikov I suggest that you prepare the seastar submodule update, after you test it locally to see ig anything else is missing, and we'll close this PR.
And then it can be followed up with patch addressing https://github.com/scylladb/scylladb/blob/a1af5e826e5dfcff6e11650fa7fb4fb1588d8926/test/nodetool/test_help.py#L56-L58

**Comment by nyh** [comment]
> @tchaikov why are we finding all those things now when trying to update the seastar submodule in scylla? The changes committed to seastar should have been tested throughly beforehand, either by unit tests in seastar (which should be preferred) and/or tested with an application like scylla before they were submitted for inclusion. 

I think the problem is the "or". I assume the person who sent this patch did test it on Redpanda, or thought that he did (obviously the test wasn't good enough)... We should probably insist more to get unit tests inside Seastar, that Seastar maintainers can see together with the patch - and not believe developers who say "I tested this in Scylla" or "I tested this in Redpanda". The problem will be that if we insist on this rule, it will make our own lives more difficult too. But it will make Seastar as a stand-alone project better.

**Comment by bhalevy** [comment]
> > @tchaikov why are we finding all those things now when trying to update the seastar submodule in scylla? The changes committed to seastar should have been tested throughly beforehand, either by unit tests in seastar (which should be preferred) and/or tested with an application like scylla before they were submitted for inclusion.
> 
> I think the problem is the "or". I assume the person who sent this patch did test it on Redpanda, or thought that he did (obviously the test wasn't good enough)... We should probably insist more to get unit tests inside Seastar, that Seastar maintainers can see together with the patch - and not believe developers who say "I tested this in Scylla" or "I tested this in Redpanda". The problem will be that if we insist on this rule, it will make our own lives more difficult too. But it will make Seastar as a stand-alone project better.

We can also do provisional seastar submodule update in scylla as part of seastar CI testing, and run the scylla CI tests on the provisionally updated submodule.  I know scylla is just one application that uses seastar, but it is the one we should care  about the most for regression purposes.
Other open source projects can also suggest CI integrations of their own...

**Comment by tchaikov** [comment]
> @tchaikov I suggest that you prepare the seastar submodule update, after you test it locally to see ig anything else is missing, and we'll close this PR. And then it can be followed up with patch addressing
> 
> https://github.com/scylladb/scylladb/blob/a1af5e826e5dfcff6e11650fa7fb4fb1588d8926/test/nodetool/test_help.py#L56-L58

thank you for your insights and suggestion. that's the plan.

**Comment by bhalevy** [comment]
Closing this PR.
Open https://github.com/scylladb/scylladb/pull/19026 instead

**Pull request closed without merging**
