### PR TITLE
./: not include unused headers

### PR DESCRIPTION
**Pull request by tchaikov**
these unused includes were identified by clangd. see https://clangd.llvm.org/guides/include-cleaner#unused-include-warning for more details on the "Unused include" warning.

### CODE REVIEW

**Comment by nyh** [comment]
>     * [test_clearnapshot](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/5754/testReport/junit/test.nodetool/test_snapshot/Tests___Unit_Tests___test_clearnapshot) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_clearnapshot)

Known flaky test: https://github.com/scylladb/scylladb/issues/16542
I'll restart the CI.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help review this change? i think it should help with #1 a little bit.

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
Dequeued, doesn't build.

**Comment by tchaikov** [comment]
thanks. lemme rebase.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

**Pull request closed without merging**
