### PR TITLE
docs: separate configuration parameters by groups

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes https://github.com/scylladb/scylladb/issues/15468

This PR:

- Formats comments in `db/config.cc` file as structured annotations to be able to parse groups.
- Modifies the custom sphinx extension `scylladb_cc_properties` to organize autogenerated configuration properties docs into distinct groups.

## How to test

1. Build the docs.
2. Open http://127.0.0.1:5500/reference/configuration-parameters/
3. See config parameters organized in groups:

    image

### CODE REVIEW

**Comment by dgarcia360** [comment]
@annastuchlik Ready for review

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
Dequeued, breaks the build:
```
db/config.cc:331:5: error: '/*' within block comment [-Werror,-Wcomment]
```

**Comment by mykaul** [comment]
@dgarcia360 - please see above - this is breaking the build - please fix and re-submit.

**Comment by dgarcia360** [comment]
@denesb @mykaul Sorry about that, I've submitted a potential fix:

```
    /**
    * Annotations used for autogenerating documentation. 
    * @Group: Names the category of subsequent config properties.
    * @GroupDescription: Provides an overview of the group.
    */ --> Added the missing "*"
    /**
    * @Group Ungrouped properties
    */
```

I've tried to build locally ScyllaDB, but I didn't manage yet to reproduce the error. Could you please re-run the Jenkins workflow and let me know if the build now passes?

Thanks!

**Comment by denesb** [comment]
> @denesb @mykaul Sorry about that, I've submitted a potential fix:
> 
> ```
>     /**
>     * Annotations used for autogenerating documentation. 
>     * @Group: Names the category of subsequent config properties.
>     * @GroupDescription: Provides an overview of the group.
>     */ --> Added the missing "*"
>     /**
>     * @Group Ungrouped properties
>     */
> ```
> 
> I've tried to build locally ScyllaDB, but I didn't manage yet to reproduce the error. Could you please re-run the Jenkins workflow and let me know if the build now passes?
> 
> Thanks!

You need to use the exact toolchain CI uses. To do that:
```
$ cd /path/to/scylla.git
$ ./tools/toolchain/dbuild ./configure.py --mode=dev --disable-dpdk
$ ./tools/toolchain/dbuild ninja build/dev/db/config.o
```

**Comment by denesb** [comment]
Kicked CI.

**Comment by denesb** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4061/

https://github.com/scylladb/scylladb/issues/15623

**Comment by dgarcia360** [comment]
Thanks @denesb! Let me try to reproduce the error with these commands.

**Comment by denesb** [comment]
Our CI is completely broken currently, the failure is unrelated. I will merge this because the build phase has passed successfully. Failed dtests should not block a doc PR.

**Pull request closed without merging**
