### PR TITLE
Backport 5.2 test.py stability/UX improvemenets

### PR DESCRIPTION
**Pull request by kbr-scylla**
Backport the following improvements for test.py topology tests for CI stability:
- https://github.com/scylladb/scylladb/pull/12652
- https://github.com/scylladb/scylladb/pull/12630
- https://github.com/scylladb/scylladb/pull/12619
- https://github.com/scylladb/scylladb/pull/12686
- picked from https://github.com/scylladb/scylladb/pull/12726: 9ceb6aba8143c97e144d8834e6db8bc6bbf1d798
- picked from https://github.com/scylladb/scylladb/pull/12173: fc604844227a9c1f2aa5f973d232be4ae340e1f5
- https://github.com/scylladb/scylladb/pull/12765
- https://github.com/scylladb/scylladb/pull/12804
- https://github.com/scylladb/scylladb/pull/13342
- https://github.com/scylladb/scylladb/pull/13589
- picked from https://github.com/scylladb/scylladb/pull/13135: 7309a1bd6bb7e1b6e55217e622b352bef8e6809e
- picked from https://github.com/scylladb/scylladb/pull/13134: 21b505e67c98239eaa01c52c74c1cc274c310cbd, a4411e9ec4f06beb9fa7d4a6959c45f0a93453d0, c1d0ee2bce135f18351adecdde85f6ab72708adf, 8e3392c64f624d9d30e3f697672f86dce2e8a649, 794d0e4000734e5857c6dc274941755a7b32f1a7, e407956e9f0e258326f1373553d98d09d87a2eb3
- https://github.com/scylladb/scylladb/pull/13271
- https://github.com/scylladb/scylladb/pull/13399
- picked from https://github.com/scylladb/scylladb/pull/12699: 3508a4e41e7cae7c8849944929186b6a9acdf1f0, 08d754e13fc5e02fe8852781277db503586c8052, 62a945ccd56675360c89d741f8b0e9144379bc64, 041ee3ffddc9b93914b86ffa142f26357abfec49
- https://github.com/scylladb/scylladb/pull/13438 (but skipped the test_mutation_schema_change.py fix since I didn't backport this new test)
- https://github.com/scylladb/scylladb/pull/13427
- https://github.com/scylladb/scylladb/pull/13756
- https://github.com/scylladb/scylladb/pull/13789
- https://github.com/scylladb/scylladb/pull/13933 (but skipped the test_snapshot.py fix since I didn't backport this new test)

### CODE REVIEW

**Comment by kbr-scylla** [comment]
@scylladb/scylla-maint please consider merging - it will improve CI stability for next-5.2.

**Comment by kbr-scylla** [comment]
https://github.com/orgs/scylladb/teams/scylla-maint ping

**Comment by kbr-scylla** [comment]
@scylladb/scylla-maint ping

**Comment by denesb** [comment]
I have no idea how to evaluate this backport. All touched files are in `test/` so I guess it is fine... @avikivity what do you think?

**Comment by denesb** [comment]
Two questions:
* Does this also solve the [ttl_test.TestDistributedTTL.test_ttl_is_respected_on_repair[parallel_aggregates_enabled]](https://jenkins.scylladb.com/job/scylla-5.2/job/next/170/testReport/junit/ttl_test/TestDistributedTTL/Sanity_Tests__dtest____dtest___test_ttl_is_respected_on_repair_parallel_aggregates_enabled_/)? I see this test failing in the last 4 next-5.2 jobs.
* Are all of these already in 5.3?

**Comment by kbr-scylla** [comment]
> Does this also solve the [ttl_test.TestDistributedTTL.test_ttl_is_respected_on_repair[parallel_aggregates_enabled]](https://jenkins.scylladb.com/job/scylla-5.2/job/next/170/testReport/junit/ttl_test/TestDistributedTTL/Sanity_Tests__dtest____dtest___test_ttl_is_respected_on_repair_parallel_aggregates_enabled_/)? I see this test failing in the last 4 next-5.2 jobs.

no, that's a dtest, the backports here only apply to test.py tests. AFAIR the cause of this test failure was analysed here: https://github.com/scylladb/scylladb/issues/11684
the issue is closed and it looks like the fix was backported to 5.2, but if it's still failing then maybe we should reopen? (cc @bhalevy)

> Are all of these already in 5.3?

All of them except the last two commits that I picked from #14047 (https://github.com/scylladb/scylladb/commit/ce13395ce49ed2c2b2c72d266e275de7c3b06bc9, https://github.com/scylladb/scylladb/commit/7e56388721afa7b7416ce0c736df85867e6bbb5f)

**Comment by denesb** [comment]
> All of them except the last two commits that I picked from #14047 ([ce13395](https://github.com/scylladb/scylladb/commit/ce13395ce49ed2c2b2c72d266e275de7c3b06bc9), [7e56388](https://github.com/scylladb/scylladb/commit/7e56388721afa7b7416ce0c736df85867e6bbb5f))

We cannot backport patch `p` to version `X`, if another version `Y` exists, such that `Y > X` and `p ∉ Y`.

**Comment by denesb** [comment]
> > All of them except the last two commits that I picked from #14047 ([ce13395](https://github.com/scylladb/scylladb/commit/ce13395ce49ed2c2b2c72d266e275de7c3b06bc9), [7e56388](https://github.com/scylladb/scylladb/commit/7e56388721afa7b7416ce0c736df85867e6bbb5f))
> 
> We cannot backport patch `p` to version `X`, if another version `Y` exists, such that `Y > X` and `p ∉ Y`.

In other words, please backport said patches to 5.3 first.

**Comment by kbr-scylla** [comment]
> no, that's a dtest, the backports here only apply to test.py tests. AFAIR the cause of this test failure was analysed here: https://github.com/scylladb/scylladb/issues/11684
> the issue is closed and it looks like the fix was backported to 5.2, but if it's still failing then maybe we should reopen? (cc @bhalevy)

Sorry, I pointed to the wrong issue/commit
the current issue with this test is https://github.com/scylladb/scylladb/issues/13137, it's not fixed yet

**Comment by kbr-scylla** [comment]
> In other words, please backport said patches to 5.3 first.

I think I'll just drop them from this PR.
We should consider backporting the entire https://github.com/scylladb/scylladb/pull/14047 to both 5.2 and 5.3 separately.

**Comment by kbr-scylla** [comment]
dropped:
> - picked from https://github.com/scylladb/scylladb/pull/14047: ce13395ce49ed2c2b2c72d266e275de7c3b06bc9, 7e56388721afa7b7416ce0c736df85867e6bbb5f

**Comment by avikivity** [comment]
@kbr-scylla you can backport directly (there's no need for a double-review of the same patch unless it's materially different). But remember not to create regressions by omitting 5.3.

**Pull request merged**
