### PR TITLE
docs: fix typo in using-scylla/local-secondary-indexes.rst

### PR DESCRIPTION
**Pull request by unknowntpo**
Fix typo.

### CODE REVIEW

**Comment by denesb** [comment]
Please use a more descriptive name, and prefix the subject with the subsytem changed, e.g.: "docs: fix typo in using-scylla/local-secondary-indexes.rst".
Also, before we can accept you contribution, please sign our CLA, see here: https://github.com/scylladb/scylladb/blob/master/CONTRIBUTING.md#contributing-code-to-scylla

**Comment by unknowntpo** [comment]
@denesb Thanks for correcting me.
I've already signed the CLA and modify the title of PR.

**Comment by denesb** [comment]
Thanks @unknowntpo. In the future, please give similarly descriptive names to commits as well. For now, I updated your commit when merging, to be the same as the PR title.

**Comment by unknowntpo** [comment]
@denesb  Got it, thanks !

**Pull request closed without merging**
