### PR TITLE
repair: row_level: coroutinize more functions

### PR DESCRIPTION
**Pull request by avikivity**
Coroutinize more functions in row-level repair to improve maintainability.

The functions all deal with repair buffers, so coroutinization does not affect performance.

Cleanup, no reason to backport

### CODE REVIEW

**Comment by avikivity** [comment]
@asias please review

**Comment by asias** [comment]
> @asias please review

Looks good. While it is good and fun, I hope this is not generating too much conflicts with other pending patches repair, mixed shard improvement / repair hint flush cache / tablet repair scheduler and more.

**Comment by avikivity** [comment]
It will generate some conflicts but will make life easier in the future. 

@xemul please review

**Comment by asias** [comment]
> It will generate some conflicts but will make life easier in the future.

I worried about backport of fix patches after this. We will not backport this coroutinize patches while the fix is on top of this large coroutinize patches.

**Comment by avikivity** [comment]
> > It will generate some conflicts but will make life easier in the future.
> 
> I worried about backport of fix patches after this. We will not backport this coroutinize patches while the fix is on top of this large coroutinize patches.

Right, backports will have to be reworked.

I'm not worried about it. Just like we can coroutinize a function, we can un-coroutinize a patch to a coroutinized function. It's a pain for a while, but afterwards we have more maintainable code.

**Comment by avikivity** [comment]
@xemul, ping

**Pull request merged**
