### PR TITLE
commitlog: Make flush threshold a config parameter

### PR DESCRIPTION
**Pull request by elcallio**
Perhaps useful for problem tracking.

### CODE REVIEW

**Comment by bhalevy** [comment]
Where is it used?
Did I miss anything?

**Comment by elcallio** [comment]
It just exposes the commitlog config parameter "flush threshold" to the outside. Given recent troubles it might be useful for testing at least. 
The commitlog config threshold value is read in segment init (was already), and used to set per-shard memtable flush thresholds.
This is just public exposure.

**Review by bhalevy — APPROVED** [review]
I see. LGTM then.

**Comment by mykaul** [comment]
Is this still needed / useful?

**Comment by elcallio** [comment]
This was merged. Not sure why it is open...

**Pull request closed without merging**
