### PR TITLE
Move pending ranges functions into effective_replication_map: part 1

### PR DESCRIPTION
**Pull request by bhalevy**
This pull request contains the first part of the series requested in #9703 ([effective_replication_map-pending_ranges-v6](https://github.com/bhalevy/scylla/commits/effective_replication_map-pending_ranges-v6))
which was dequeued due to a failure in https://jenkins.scylladb.com/job/scylla-master/job/next/4454/testReport/cdc_test/TestCdc/dtest___test_cluster_expansion_with_cdc/

Part 1 is focused on moving the pending ranges code form the `token_metadata` class into `effective_replication_map` and converting decommission to scan the e_r_m factory for pending ranges rather than inefficiently call `has_pending_ranges` for every keyspace.

Test: unit(dev)
DTest: cdc_test.py::TestCdc::test_cluster_expansion_with_cdc

### CODE REVIEW

**Comment by bhalevy** [comment]
@avikivity, sorry but https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4482/testReport/junit/cdc_test/TestCdc/dtest___test_cluster_expansion_with_cdc_Single_cluster_/
fails again in next. It passed for me reliably locally and I don't understand why it fails on Jenkins, but we'll need to sort this out somehow.

**Comment by raphaelsc** [comment]
On Fri, Jan 28, 2022, 8:58 AM Benny Halevy ***@***.***> wrote:

> @avikivity <https://github.com/avikivity>, sorry but
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4482/testReport/junit/cdc_test/TestCdc/dtest___test_cluster_expansion_with_cdc_Single_cluster_/
> fails again in next. It passed for me reliably locally and I don't
> understand why it fails on Jenkins, but we'll need to sort this out somehow.
>
IIRC Jenkins runs under an overprovisioned env. So the flakiness seems due
to some timing based condition introduced somewhere. When I looked at the
series I suspected a race was introduced with those new yielding points. So
I suggest taking a look there.

**Comment by bhalevy** [comment]
> IIRC Jenkins runs under an overprovisioned env. So the flakiness seems due to some timing based condition introduced somewhere. When I looked at the series I suspected a race was introduced with those new yielding points. So I suggest taking a look there.

I'm digging into this deeper using the repair_based_node_operations.py dtests.
Indeed there is a timing issue but it doesn't seem to be related to the low-level yielding since happens on a provisional token_metadata copy that is not published yet.

I speculate that the problem could be that gossip apply locally depended on the pending ranges to be updated in the token_metadata as they were built while now they are applied only later on by the storage_service, while gossip is updating stuff concurrently, with no serialization - hence the dependency on timing .

**Comment by bhalevy** [comment]
With the transition to tablets, this PR can be closed.

**Pull request closed without merging**
