### PR TITLE
build: regenerate frozen toolchain for tablets-aware Python driver

### PR DESCRIPTION
**Pull request by avikivity**
Pull in scylla-driver 3.26.5, which supports tablets.

### CODE REVIEW

**Comment by avikivity** [comment]
@benipeled why did CI not run?

**Comment by benipeled** [comment]
> @benipeled why did CI not run?

It does - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5841/

**Comment by avikivity** [comment]
ok, there's a window when it says all tests passed before it runs them.

**Comment by benipeled** [comment]
> ok, there's a window when it says all tests passed before it runs them.

Correct, it can take a few minutes until the `Build` check is added (as `Pending`),
I can try adding a pre-step but we anyway rely on the CI-comment so it's not in priority

**Pull request closed without merging**
