### PR TITLE
tools/scylla-nodetool: implement the checkAndRepairCdcStreams command

### PR DESCRIPTION
**Pull request by denesb**

### CODE REVIEW

**Comment by denesb** [comment]
Hopefully, the really last one this time.

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by denesb** [comment]
> * [topology_experimental_raft.test_tablets.debug.5](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/7775/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_tablets_debug_5) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_experimental_raft.test_tablets.debug.5)
> 
> * [test_tablet_split](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/7775/testReport/junit/%28root%29/test_tablets/Tests___Unit_Tests___test_tablet_split) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_split)

https://github.com/scylladb/scylladb/issues/18085

**Comment by denesb** [comment]
@scylladb/scylla-maint ping, this is a 6.0 release blocker.

**Comment by denesb** [comment]
> @scylladb/scylla-maint ping, this is a 6.0 release blocker.

I see Avi already queued, thanks.

**Pull request closed without merging**
