### PR TITLE
Update tools/java submodule

### PR DESCRIPTION
**Pull request by denesb**
* tools/java 1e7b872a61...0ddfac0715 (1):
  > scylla-tools-java: Update "six" library used by cqlsh/python driver

### CODE REVIEW

**Comment by denesb** [comment]
Let CI check before merging.

**Comment by denesb** [comment]
@scylladb/scylla-maint this PR fixes a build-failure on master. The failed step was `dist-tools-{mode}`, the latest CI job successfully built it already. Builds are failing all over the place, so please merge this ASAP.

**Comment by avikivity** [comment]
What's going on?

commit 11985bb173d178eb7908d567b4a4080752b9a23f
Author: Botond Dénes <bdenes@scylladb.com>
Date:   Thu Jul 28 13:10:00 2022 +0300

    Update tools/java submodule
    
    * tools/java 1e7b872a61...ad6764b506 (1):
      > scylla-tools-java: Update "six" library used by cqlsh/python driver
    
    Closes #11148

commit 2d4caa01341b8e581e971b858d31f0397c4c4533
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Jul 27 21:41:18 2022 +0300

    Update tools/java submodule
    
    * tools/java d0143b447c...1e7b872a61 (2):
      > scylla-tools-java: Update "six" library used by cqlsh/python driver
      > Add Scylla-specific table options to Option enum
    Fixes scylladb/scylla#10856.

**Comment by avikivity** [comment]
Ah, there are two commits in tools/java with the same subject line.

**Pull request closed without merging**
