### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by avikivity**
* seastar f2d70c4a17...2b2f6c080e (4):
  > perftune.py: special case a former 'MQ' mode in the new auto-detection code
  > iostream: Generalize flush and batched flush
  > Merge "Equip sharded<>::invoke_on_all with unwrap_sharded_args" from Pavel E
  > Merge "perftune.py: cosmetic fixes" from VladZ

### CODE REVIEW

**Comment by avikivity** [comment]
@benipeled I don't see continuous integration jumping on it and testing it

**Review by fruch — APPROVED** [review]
LGTM

**Comment by nyh** [comment]
@avikivity I committed this PR, but then started to wonder: Besides staying on the cutting edge, was one of the specific Seastar changes listed here important to fix a specific Scylla problem? Should we have made this PR "Fixes" something, and later consider backports?

**Comment by avikivity** [comment]
> @avikivity I committed this PR, but then started to wonder: Besides staying on the cutting edge, was one of the specific Seastar changes listed here important to fix a specific Scylla problem? Should we have made this PR "Fixes" something, and later consider backports?

These should be considered before merging, not after.

**Pull request closed without merging**
