### PR TITLE
cql-pytest/test_select_from_mutation_fragments: disable compaction on test_table

### PR DESCRIPTION
**Pull request by bhalevy**
Use NullCompactionStrategy for the test_table fixture rather than using the `no_autocompaction_context`.

Besides being simpler, as regular compaction just comes in the way for all tests that use `SELECT MUTATION_FRAGMENTS`

The latter would be problematic when we start run cql-pytest test cases in parallel rather than in serial since it will inadvertantly affect other test cases.

### CODE REVIEW

**Comment by bhalevy** [comment]
This PR replaces #15544

**Review by denesb — APPROVED** [review]

**Review by nyh — APPROVED** [review]

**Comment by bhalevy** [comment]
I'm not sure why CI hasn't run for this PR.  @benipeled ?

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3981/

**Comment by benipeled** [comment]
> I'm not sure why CI hasn't run for this PR. @benipeled ?

It triggered https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3976/ and failed on network-issue https://github.com/scylladb/scylla-pkg/issues/3608, please retrigger

**Comment by bhalevy** [comment]
> > I'm not sure why CI hasn't run for this PR. @benipeled ?
> 
> It triggered https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3976/ and failed on network-issue [scylladb/scylla-pkg#3608](https://github.com/scylladb/scylla-pkg/issues/3608),

Why isn't there a Unit Test failure status on this page?
It looks like something is broken in the integration.

> please retrigger

I already triggered a manual run: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3981/

**Comment by benipeled** [comment]
> > > I'm not sure why CI hasn't run for this PR. @benipeled ?
> > 
> > 
> > It triggered https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3976/ and failed on network-issue [scylladb/scylla-pkg#3608](https://github.com/scylladb/scylla-pkg/issues/3608),
> 
> Why isn't there a Unit Test failure status on this page? It looks like something is broken in the integration.
> 

See my comment above _"...and failed on network-issue [scylladb/scylla-pkg#3608](https://github.com/scylladb/scylla-pkg/issues/3608)"_ the build failed unexpectedly and didn't report failure, it's under investigations

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please merge

**Pull request closed without merging**
