### PR TITLE
[branch-5.0] Update tools/jmx submodule (jackson dependency)

### PR DESCRIPTION
**Pull request by avelanarius**
Updates tools/jmx submodule by 1 commit, which upgrades Jackson dependency version in jmx. The purpose of this PR is to backport this change to older Scylla versions.

* tools/jmx 53f7f55e8c...fe351e8491 (1):
  > Update jackson dependency

Refs #11929

### CODE REVIEW

**Comment by kbr-** [comment]
@avelanarius was this a cherry-pick of 41b098f54e33d0b9332a3e3d21ad505b624f6c19? If yes, you should do the cherry-pick with `git cherry-pick -x` so the commit contains a reference to the original commit. If not, it should be a cherry-pick; we prefer most of the changes to release branches to originate from the `master` branch.

(I know - the only difference will be a single line in the commit message - but let's stick to these principles)

**Comment by avelanarius** [comment]
@kbr- My commit was not a cherry pick of Avi's commit - I wasn't aware of that commit. In the amended commit I changed that commit to a cherry pick of 41b098f54e33d0b9332a3e3d21ad505b624f6c19 (as is evidenced by a typo in "Udpate").

As you could see, CI runs failed. This is because even though this PR is for branch-5.0, the dtests that are ran on CI are from scylla-dtest master (not scylla-dtest branch-5.0). The master has some changes in `cql_additional_tests.py::TestCQL::test_static_columns_cas` that make it fail when running with Scylla 5.0 (scylla-dtest master + Scylla 5.0). I tested it locally on my computer (this PR + scylla-dtest branch-5.0) and the tests passed.

Should I create an issue that PRs to branch-X should run CI with dtest of corresponding branch-X? cc: @roydahan

**Comment by kbr-** [comment]
> As you could see, CI runs failed. This is because even though this PR is for branch-5.0, the dtests that are ran on CI are from scylla-dtest master (not scylla-dtest branch-5.0).

Indeed, I haven't encountered this before (all past PRs to release branches were before the CI times)

cc @benipeled - could we choose the dtest branch based on the PR's target branch?
Or at least, an option to rebuild CI with a custom dtest branch specified.

**Comment by roydahan** [comment]
@yarongilor / @benipeled this is for you.

**Comment by benipeled** [comment]
> cc @benipeled - could we choose the dtest branch based on the PR's target branch?
> Or at least, an option to rebuild CI with a custom dtest branch specified.

I should adjust the CI to work with other branches as well, it might take some time,
Temporarily for this PR, you can use the byo job https://jenkins.scylladb.com/view/master/job/scylla-5.0/job/byo/job/byo_build_tests_dtest/build?delay=0sec
(or trust the manual test)

**Comment by avikivity** [comment]
I see 5.1 is fixed already.

**Comment by avikivity** [comment]
Is there a 4.6 branch? If not, it's easier for me to mangle the submodules myself.

**Pull request closed without merging**
