### PR TITLE
Update ./tools/jmx and ./tools/java submodules

### PR DESCRIPTION
**Pull request by denesb**
* ./tools/jmx 05bb7b68...80ce5996 (4):
  > StorageService: Normalize endpoint inetaddress strings to java form
  > ColumnFamilyStore: only quote table names if necessary
  > APIBuilder: allow quoted scope names
  > ColumnFamilyStore: don't fail if there is a table with ":" in its name

* ./tools/java 10480342...26f5f71c (1):
  > NodeProbe: allow addressing table name with colon in it

### CODE REVIEW

**Comment by denesb** [comment]
There is a submodule update for tools/java in next, I will rebase once CI passes. That update only brings in a dependency change, so if CI passes on this PR, we should be good, no need to rerun after rebase as well.

**Comment by denesb** [comment]
> > There is a submodule update for tools/java in next, I will rebase once CI passes. That update only brings in a dependency change, so if CI passes on this PR, we should be good, no need to rerun after rebase as well.
> 
> It seems CI is not running, I don't know why... Maybe it sees the same "conflicting files" that github is complaining about?

Possibly, I will rebase once promotion passes, and will also include https://github.com/scylladb/scylla-jmx/pull/229.

**Comment by nyh** [comment]
Thanks Botond. I opened a scylla.git issue, https://github.com/scylladb/scylladb/issues/16153, that this PR can "Fixes", and can be useful for backporting purposes.

**Comment by denesb** [comment]
Update: rebased on master, also included https://github.com/scylladb/scylla-jmx/pull/229

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
Thanks Botond, I merged it. I hope you don't mind that I edited the commit message to "Fixes" the two Scylla issues that these JMX fix: #16039 and #16153.

**Pull request closed without merging**
