### PR TITLE
cql3: statement_restrictions: cartestian product size error message fix.

### PR DESCRIPTION
**Pull request by Jager227**
This commit changes:
1.The error message will be specific about what type of keys exceeds the limit (e.g clustering keys or partition keys). 
2.Error message will be more general about what causes it, cartesian product or simple list.
3.Error message will advise to use --max-partition-key-restrictions-per-query or --max-clustering-key-restrictions-per-query configuration options to override current (100) limit.

Fixes#15627.

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
could use "cql3: statement_restrictions: " as the prefix of the title of the commit message. you could find more examples with

```shell
$ git log cql3/restrictions/statement_restrictions.cc
```

also, could you please add a space in the tag of "Fixes#15627" and drop the ending period so it looks like 

```
Fixes #15627 
```

see also https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by nyh — APPROVED** [review]

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4996/) ❌ - [Sanity Tests](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/6355/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4996/)
> 
> #### Failed Tests (1/21988):
> * [test_large_partition_detector_with_ttl_on_few_row_in_partition[TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4996/testReport/junit/wide_rows_test/TestWideRows/Tests___Sanity_Tests___test_large_partition_detector_with_ttl_on_few_row_in_partition_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_large_partition_detector_with_ttl_on_few_row_in_partition%5BTimeWindowCompactionStrategy%5D)
> 
> #### Build Details:
> * Duration: 2 hr 26 min
> * Builder: spider2.cloudius-systems.com

new flaky test: https://github.com/scylladb/scylladb/issues/16244

**Comment by Jager227** [comment]
Hi, @nyh, please merge or close my PR if everything's ok :).

**Comment by denesb** [comment]
Queued.

**Pull request closed without merging**
