### PR TITLE
gossiper: get rid of uses_host_id

### PR DESCRIPTION
**Pull request by bhalevy**
This function practically returned true from inception.
    
In d38deef499f72d4f4bd629e134fb15b750db6d6c
it started using messaging_service().knows_version(endpoint)
that also returns `true` unconditionally, to this day

So there's no point calling it since we can assume
that `uses_host_id` is true for all versions.

### CODE REVIEW

**Comment by bhalevy** [comment]
Ref https://github.com/scylladb/scylladb/issues/12282

**Comment by avikivity** [comment]
What's the last version that doesn't use host_id? Please add to the cover letter.

**Comment by avikivity** [comment]
Also, please explain it in more detail. I find I have no idea what this is about.

**Comment by bhalevy** [comment]
> Also, please explain it in more detail. I find I have no idea what this is about.

I updated the commit message.
Apparently this was inherited from origin but always returned `true` unconditionally.

**Review by tgrabiec — APPROVED** [review]

**Review by asias — APPROVED** [review]

**Pull request merged**
