### PR TITLE
Some cleanup in compaction group

### PR DESCRIPTION
**Pull request by raphaelsc**

### CODE REVIEW

**Comment by raphaelsc** [comment]
> * test_remove_garbage_members_from_group0_after_abort_decommission

@kbr- I see you're aware of it, but I wasn't able to find any issue tracking it.

**Comment by mykaul** [comment]
> > * test_remove_garbage_members_from_group0_after_abort_decommission
> 
> @kbr- I see you're aware of it, but I wasn't able to find any issue tracking it.

@kbr-scylla

**Comment by kbr-scylla** [comment]
> @kbr- I see you're aware of it, but I wasn't able to find any issue tracking it.

Aware in what sense? I know that the test exists, I didn't know that it was failing. And indeed it's a completely new failure. I opened https://github.com/scylladb/scylladb/issues/16466

**Comment by raphaelsc** [comment]
> * test_remove_garbage_members_from_group0_after_abort_decommission[Announcing_that_I_have_left_the_ring-]

that was my (possibly wrong) perception after seeing your comment right after the test failed in another PR: https://github.com/scylladb/scylladb/pull/16172#issuecomment-1852209272

**Pull request merged**
