### PR TITLE
tools: add tool to track task manager tasks

### PR DESCRIPTION
**Pull request by Deexie**
First version of tasks tracking tool.

Currently it's a one-shot script requesting tasks related info.
Supported commands:
- list_modules,
- list_tasks,
- watch_tasks - requests `list_tasks` every 10s, 
- get_status,
- wait,
- get_tree - recursive status; statuses of requested tasks and all its descendants,
- abort,
- set_ttl.

Example usages:
`./tasks.py list_tasks --module compaction --keyspace system`
Output:
```
200
╒══════════════════════════════════════╤═════════╤════════════════════════╤══════════╤════════════╤═════════╤══════════╤═══════════════════╕
│ task_id                              │ state   │ type                   │ scope    │ keyspace   │ table   │ entity   │   sequence_number │
╞══════════════════════════════════════╪═════════╪════════════════════════╪══════════╪════════════╪═════════╪══════════╪═══════════════════╡
│ c8078936-b8cf-45de-b0c7-495999656a9a │ done    │ offstrategy compaction │ keyspace │ system     │         │          │              1221 │
├──────────────────────────────────────┼─────────┼────────────────────────┼──────────┼────────────┼─────────┼──────────┼───────────────────┤
│ c218f030-ca76-4acf-8a1b-f6040794fcea │ done    │ cleanup compaction     │ keyspace │ system     │         │          │              1178 │
├──────────────────────────────────────┼─────────┼────────────────────────┼──────────┼────────────┼─────────┼──────────┼───────────────────┤
│ f156841b-7f7c-4620-942e-7d3ca24bf3c4 │ done    │ major compaction       │ keyspace │ system     │         │          │              1222 │
├──────────────────────────────────────┼─────────┼────────────────────────┼──────────┼────────────┼─────────┼──────────┼───────────────────┤
│ 421727dc-ddab-4be8-987e-899d8be2f1f0 │ done    │ major compaction       │ keyspace │ system     │         │          │               996 │
╘══════════════════════════════════════╧═════════╧════════════════════════╧══════════╧════════════╧═════════╧══════════╧═══════════════════╛
```

`./tasks.py get_status --id f156841b-7f7c-4620-942e-7d3ca24bf3c4`
```
200
id :  f156841b-7f7c-4620-942e-7d3ca24bf3c4
type :  major compaction
scope :  keyspace
state :  done
is_abortable :  True
start_time :  2024-02-12T16:15:05Z
end_time :  2024-02-12T16:15:06Z
error :  
parent_id :  00000000-0000-0000-0000-000000000000
sequence_number :  1222
shard :  0
keyspace :  system
table :  
entity :  
progress_units :  
progress_total :  1
progress_completed :  1
children_ids :  ['e8814fc1-30f0-4b98-acc5-b14948bf6e48', '8b48bb14-bbda-43a5-a0a0-c32aaaf313e2', 'a26fef61-cec4-49aa-a72a-d17569107a65']
```

`./tasks.py get_status --id f156841b-7f7c-4620-942e-7d3ca24bf3c5`
```
400   Bad Request
message :  task with id f156841b-7f7c-4620-942e-7d3ca24bf3c5 not found
code :  400
```

### CODE REVIEW

**Comment by avikivity** [comment]
Should this be part of nodetool? @denesb

**Comment by bhalevy** [comment]
> Should this be part of nodetool? @denesb

@denesb :point_up:

**Comment by denesb** [comment]
Yes, I think this should be a nodetool command.

**Comment by Deexie** [comment]
Closing, replaced with https://github.com/scylladb/scylladb/pull/19614

**Pull request closed without merging**
