### PR TITLE
test/alternator: more tests for listing streams

### PR DESCRIPTION
**Pull request by nyh**
In issue #12601, a dtest involving paging of ListStreams showed incorrect results - the paged results had one duplicate stream and one missing stream. We believe that the cause of this bug was that the unsorted map of tables can change order between pages. In this patch we add a test test_list_streams_paged_with_new_table which can demonstrate this bug - by adding a lot of tables in mid-paging, we cause the unsorted map to be reshufled and the paging to break. This is not the same situation as in #12601 (which did not involve new tables) but we believe it demonstrates the same bug - and check its fix. Indeed this passes with the fix in pull request #12614 and fails without it.

This patch also adds a second test, test_stream_arn_unchanging: That test eliminates a guess we had for the cause of #12601. We thought that maybe stream ARN changing on a table if its schema version changes, but the new test confirms that it actually behaves as expected (the stream ARN doesn't change).

Refs #12601
Refs #12614

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Comment by nyh** [comment]
Marked as draft as the test will fail until PR https://github.com/scylladb/scylladb/pull/12614 by @elcallio is merged.
I used this test to confirm that #12614 works as expected by applying that PR manually into my tree.

**Comment by nyh** [comment]
PR https://github.com/scylladb/scylladb/pull/12614 by @elcallio, fixing the Alternator Stream listing, has now been merged, so we can also merge these tests. The new tests now pass (they failed before this PR).

**Review by denesb — APPROVED** [review]

**Comment by nyh** [comment]
CI failed on some random dtest which failed to connect to JMX (https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4199/testReport/junit/cdc_test/TestCdc/Sanity_Tests___test_remove_field_with_cdc_Single_cluster_/) which has nothing to do with my patch. @fruch any idea what can cause this failure?
Anyway, restarting the CI...

**Comment by fruch** [comment]
> CI failed on some random dtest which failed to connect to JMX (https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4199/testReport/junit/cdc_test/TestCdc/Sanity_Tests___test_remove_field_with_cdc_Single_cluster_/) which has nothing to do with my patch. @fruch any idea what can cause this failure?
> Anyway, restarting the CI...

It's a crash on jmx that started happening from time to time:

https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4199/artifact/logs-gating.release.2/1675701098905_cdc_test.py%3A%3ATestCdc%3A%3Atest_remove_field_with_cdc%5BSingle_cluster%5D/node1_system.log.jmx/*view*/

https://github.com/scylladb/scylla-dtest/issues/3007

Didn't able to track it's source yet
And yes, it isn't related to these PR changes

**Comment by nyh** [comment]
Last CI run failed again on some unrelated Raft stuff :-( I'll rebase and hopefully get some Raft fixes and a working CI run....

**Pull request closed without merging**
