### PR TITLE
RPC: add [[ref]] attribute to heavy parameters

### PR DESCRIPTION
**Pull request by gusev-p**
By default `idl-compiler.py` emits code to pass parameters by value. There was an attribute `[[ref]]`, which makes it to use `const&`, but it was not used systematically and in many cases parameters were redundantly copied. In this PR, all `verb` directives have been reviewed and the `[[ref]]` attribute has been added where it makes sense.

The parameters [are serialised synchronously](https://github.com/scylladb/seastar/blob/master/include/seastar/rpc/rpc_impl.hh#L471) so there should be no lifetime issues. This was not the case before, but the behaviour changed in [this commit](https://github.com/scylladb/seastar/commit/3942546d4165071948104107b7c9626486a8c999). Now it's not a problem to get an object by reference when using `send_` methods.

Fixes: #12504

### CODE REVIEW

**Comment by avikivity** [comment]
@gleb-cloudius please review

**Comment by avikivity** [comment]
Should we not pass everything by reference except scalars?

**Comment by avikivity** [comment]
inet_address_vector_replica_set_why_is_my_name_so_long has a complex move constructor, so better to pass by reference.
trace_info is used once (to see it's empty and create an empty trace_state_ptr), so it doesn't matter either way.

**Comment by avikivity** [comment]
(in general a small aggregate is indeed better to pass by value, but IMO the penalty of passing a small aggregate by value is low, while the penalty of copying an expensive value is high)

**Review by gleb-cloudius — APPROVED** [review]

**Comment by gleb-cloudius** [comment]
> (in general a small aggregate is indeed better to pass by value, but IMO the penalty of passing a small aggregate by value is low, while the penalty of copying an expensive value is high)

If idl compiler would have been smart enough to recognize c++ types it could have automatically decide which to get by value (trivially copyable and small) and which to get by ref.

**Comment by gleb-cloudius** [comment]
> > > (in general a small aggregate is indeed better to pass by value, but IMO the penalty of passing a small aggregate by value is low, while the penalty of copying an expensive value is high)
> > 
> > 
> > If idl compiler would have been smart enough to recognize c++ types it could have automatically decide which to get by value (trivially copyable and small) and which to get by ref.
> 
> It can let C++ do that. e.g. the signature would be of type idl_ref_t, which translates to T if T is trivially copyable and small, and const T& if it's not.

Indeed.

> 
> Or it can pass everything by reference. We have few trivial parameters and the penalty of passing something small by reference isn't large.

Yes. We probably do not have a lot of parameters smaller then 8 bytes. I like idl_ref_t idea though.

**Comment by gusev-p** [comment]
> It can let C++ do that. e.g. the signature would be of type idl_ref_t, which translates to T if T is trivially copyable and small, and const T& if it's not.

The calling code will either have to pull `idl_ref_t` through the call chain to the place where the parameter was created, or become aware about the `idl_ref_t` implementation and pass a specific parameter by reference or value.

I like the explicit `[[ref]]` attribute more - less magic, and the explicit `byref/byval` choice is natural to C++ programming.

**Comment by gleb-cloudius** [comment]
> 
> I like the explicit `[[ref]]` attribute more - less magic, and the explicit `byref/byval` choice is natural to C++ programming.

I think we can leave it as is for now. Just musing ideas here.

**Comment by avikivity** [comment]
> > It can let C++ do that. e.g. the signature would be of type idl_ref_t, which translates to T if T is trivially copyable and small, and const T& if it's not.
> 
> The calling code will either have to pull `idl_ref_t` through the call chain to the place where the parameter was created, or become aware about the `idl_ref_t` implementation and pass a specific parameter by reference or value.

I thought this was for server function signatures, no? There is no calling code.

For client calls, is the client responsible for keeping the reference stable? In that case, we must have the [[ref]] attribute, since current clients don't know that they should keep the reference stable (IIRC).

> 
> I like the explicit `[[ref]]` attribute more - less magic, and the explicit `byref/byval` choice is natural to C++ programming.

**Comment by gusev-p** [comment]
new version:
  * new commit: pass `tracing::trace_info` by ref
  * new commit: pass `inet_address_vector_replica_set` by ref

**Comment by gusev-p** [comment]
> I thought this was for server function signatures, no? There is no calling code.

No, it's about client code, e.g. [here](https://github.com/scylladb/scylladb/blob/ffce6d94fc55cd47a41638585265c5db7229cbd6/service/storage_proxy.cc#L1441)  the `inet_address_vector_replica_set` byref/byval choice should match the one emitted by the idl_compiler for the client proxy.

> For client calls, is the client responsible for keeping the reference stable? In that case, we must have the [[ref]] attribute, since current clients don't know that they should keep the reference stable (IIRC).

As mentioned in the header of this PR, parameters [are serialised synchronously](https://github.com/scylladb/seastar/blob/master/include/seastar/rpc/rpc_impl.hh#L471), so the client doesn't have to keep the parameter alive for the duration of the call.

**Comment by gusev-p** [comment]
@avikivity please review/merge, @kbr-scylla referred me to you since you are already looking at this pr

**Comment by gusev-p** [comment]
> this idl_ref_t<T> thing. I don't see why it would change any call sites.

* the PR doesn't introduce `[[ref]]`, it just applies it consistently to eliminate redundant copies;
* I don't like `idl_ref_t<T>`, IIUC it will produce `send_mutation(idl_ref_t<inet_address_vector_replica_set> forward)` as a proxy for client, and we will have to use this `idl_ref_t` in places which calls `send_mutation`, e.g. [here](https://github.com/scylladb/scylladb/blob/ffce6d94fc55cd47a41638585265c5db7229cbd6/service/storage_proxy.cc#L1441).

> pass everything by value, with the understanding that the gain from not copying a heavy value that we forgot to [[ref]] is far greater than the few extra instructions needed to pass an int by reference.

You mean 'pass everything by ref'. This is inconsistent with C++ which passes parameters by val by default, having less surprises is valuable.

**Comment by avikivity** [comment]
> > Here, simplicity is mostly for the user, though avoiding growth in the complexity of the IDL compiler and language is also worthwhile.
> 
> Note that the patch does not introduce `[[ref]]` to the idl. It was already there. It just marks some fields with it.

Ah, don't know why I thought otherwise.

**Review by avikivity — APPROVED** [review]

**Pull request closed without merging**
