### PR TITLE
cql3: statement_restrictions, expr: move restrictions-related expression utilities out of expression.cc

### PR DESCRIPTION
**Pull request by avikivity**
Move all of the blatantly restriction-related expression utilities to statement_restrictions.cc.

Some are so blatant as to include the word "restriction" in their name. Others are just so specialized that they cannot be used for anything else.

The motivation is that further refactoring will be simplified if it can happen within the same module, as there will not be a need to prove it has no effect elsewhere.

Most of the declarations are made non-public (in .cc file) to limit proliferation. A few are needed for tests or in select_statement.cc and so are kept public.

Other than that, the only changes are namespace qualifications and removal of a now-duplicate definition ("inclusive").

Continued refactoring, no backport required

### CODE REVIEW

**Comment by avikivity** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11774/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11774/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/statement_restrictions_test ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11774/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/3742/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/686/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11757/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11774/)
> 
> #### Failed Tests (1/35517):
> * [test_tablet_drain_failure_during_decommission.dev.5](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/11774/testReport/junit/%28root%29/test_topology_failure_recovery/Tests___Unit_Tests___test_tablet_drain_failure_during_decommission_dev_5) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_drain_failure_during_decommission.dev.5)
> 
> #### Build Details:
> * Duration: 3 hr 49 min
> * Builder: spider5.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/20689

**Comment by avikivity** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11785/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11785/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/statement_restrictions_test ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11785/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/3749/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/693/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11764/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11785/)
> 
> #### Failed Tests (1/35517):
> * [test_concurrent_restart](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/11785/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_topology_changes___test_concurrent_restart) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_restart)
> 
> #### Build Details:
> * Duration: 3 hr 46 min
> * Builder: spider8.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/15192

**Review by nyh — APPROVED** [review]
Usually I like the idea of moving "supposedly generic" stuff that is actually used just once into the same source file that needs it instead of pretending these are general functions, so I approve this change.

That being said, I'm somewhat surprised because I had the impression that the work that you and Jan were doing was to move overly-CQL-specific stuff into more general "expressions" feature, and now it seems you're moving some stuff back. But I'll let you make the call of what belongs where - I don't have a clear enough picture of what goes best where but I'm sure that you do.

**Comment by avikivity** [comment]
> Usually I like the idea of moving "supposedly generic" stuff that is actually used just once into the same source file that needs it instead of pretending these are general functions, so I approve this change.
> 
> That being said, I'm somewhat surprised because I had the impression that the work that you and Jan were doing was to move overly-CQL-specific stuff into more general "expressions" feature, and now it seems you're moving some stuff back. But I'll let you make the call of what belongs where - I don't have a clear enough picture of what goes best where but I'm sure that you do.

This actually predates my work - it's the very earliest expression work. Most of it is going to collapse into the rest of the restrictions code.

**Pull request closed without merging**
