### PR TITLE
doc: fix the notes on the OS Support by Platform and Version page

### PR DESCRIPTION
**Pull request by annastuchlik**
Fix https://github.com/scylladb/scylladb/issues/11773

This PR fixes the notes by removing repetition and improving the clairy of the notes on the OS Support page.
In addition, "Scylla" was replaced with "ScyllaDB" on related pages.

### CODE REVIEW

**Review by tzach — APPROVED** [review]

**Review by nyh — APPROVED** [review]

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Comment by annastuchlik** [comment]
@denesb Could you backport this PR to 5.1? It will add critical information about version 5.1 to branch-5.1.

**Comment by denesb** [comment]
Can you please prepare a backport PR. There are some conflicts? Not too many but they are not trivial.

**Comment by annastuchlik** [comment]
@denesb Done. Backporting this PR adds the [missing information](https://github.com/scylladb/scylladb/commit/f6157a38a0b6745da6193573c7b97bfed70aa8d3#commitcomment-92214438) reported by @tzach, so I think we can skip backporting https://github.com/scylladb/scylladb/pull/11383.

**Pull request closed without merging**
