### PR TITLE
[branch-5.4] Update ./tools/jmx and ./tools/java submodules

### PR DESCRIPTION
**Pull request by denesb**
* ./tools/jmx 8d15342e...9a03d4fa (1):
  > Merge "scylla-apiclient: update several Java dependencies" from Piotr Grabowski

* ./tools/java 3c09ab97...dfbf3726 (1):
  > Merge 'build: update several dependencies' from Piotr Grabowski

Update build dependencies which were flagged by security scanners.

Refs: scylladb/scylla-jmx#220
Refs: scylladb/scylla-tools-java#351

Fixes: https://github.com/scylladb/scylla-jmx/issues/221
Fixes: https://github.com/scylladb/scylla-jmx/issues/222
Fixes: https://github.com/scylladb/scylla-jmx/issues/223

Fixes: https://github.com/scylladb/scylla-tools-java/issues/348
Fixes: https://github.com/scylladb/scylla-tools-java/issues/349
Fixes: https://github.com/scylladb/scylla-tools-java/issues/350

### CODE REVIEW

**Comment by mykaul** [comment]
I believe we need an issue for this (as we'd like to backport this), or is each PR separate (per 5.4, 5.2) ?

**Comment by nyh** [comment]
> I believe we need an issue for this (as we'd like to backport this), or is each PR separate (per 5.4, 5.2) ?

I created the issue in https://github.com/scylladb/scylla-jmx/issues/226 - I agree it sort of breaks our backport protocol, but not sure what to do here. It's **not** an issue in Scylla code - it involved the scylla-jmx, scylla-tools-java (nodetool) and dtest repositories, but not scylla.git. But I guess in some weird way it makes sense to create a scylla.git issue to explain *this* submodule update. I'll do it.

**Comment by nyh** [comment]
> > I believe we need an issue for this (as we'd like to backport this), or is each PR separate (per 5.4, 5.2) ?
> 
> I created the issue in [scylladb/scylla-jmx#226](https://github.com/scylladb/scylla-jmx/issues/226) - I agree it sort of breaks our backport protocol, but not sure what to do here. It's **not** an issue in Scylla code - it involved the scylla-jmx, scylla-tools-java (nodetool) and dtest repositories, but not scylla.git. But I guess in some weird way it makes sense to create a scylla.git issue to explain _this_ submodule update. I'll do it.

Oops. wrong issue. Sorry about the spam. I'll delete these comments (and maybe make them elsewhere).

**Comment by denesb** [comment]
> I believe we need an issue for this (as we'd like to backport this), or is each PR separate (per 5.4, 5.2) ?

This is a backport PR for 5.4. I want to run CI before pushing this.

**Comment by mykaul** [comment]
@avikivity - please merge.

**Comment by denesb** [comment]
> @avikivity - please merge.

This was already merged and also promoted in fact (just checked), but github's auto-close doesn't work on non-main branches. Closing manually.

**Pull request closed without merging**
