### PR TITLE
Update tools/cqlsh module

### PR DESCRIPTION
**Pull request by dawmd**
We update the module to include the changes
(primarily scylladb/scylla-cqlsh@4b4bcfc)
that make performing DESCRIBE statements
less reliant on cqlsh and more on Scylla
itself.

Refs scylladb/scylla-cqlsh#100

### CODE REVIEW

**Comment by fruch** [comment]
@scylladb/scylla-maint can we get this merged ?

**Comment by nyh** [comment]
@avikivity I think I forgot how to merge submodule updates. Should I just do the submodule-refresh myself, or should I merge this patch normally with scripts/pull_github_pr.sh?
I seem to remember that we had a discussion in the past about submodule refresh being problematic in this sense, but don't remember what was the conclusion.

**Comment by denesb** [comment]
I updated the submodule manually, so it gets all the latest changes.
Update commit: fc690a60d8b43fe678f3cbb267119c6ea57dd64c.

**Comment by fruch** [comment]
> @avikivity I think I forgot how to merge submodule updates. Should I just do the submodule-refresh myself, or should I merge this patch normally with scripts/pull_github_pr.sh? I seem to remember that we had a discussion in the past about submodule refresh being problematic in this sense, but don't remember what was the conclusion.

in this case the downside of doing thing manually, it might pull more the what is tested here.
but cqlsh doesn't have much ongoing development, so what ever done would probably gonna work o.k.

**Comment by denesb** [comment]
> > @avikivity I think I forgot how to merge submodule updates. Should I just do the submodule-refresh myself, or should I merge this patch normally with scripts/pull_github_pr.sh? I seem to remember that we had a discussion in the past about submodule refresh being problematic in this sense, but don't remember what was the conclusion.
> 
> in this case the downside of doing thing manually, it might pull more the what is tested here. but cqlsh doesn't have much ongoing development, so what ever done would probably gonna work o.k.

I checked the list of commits, and the ones on top of this seemed like test and dist related, so I thought it is safe enough to try.

**Comment by fruch** [comment]
> > > @avikivity I think I forgot how to merge submodule updates. Should I just do the submodule-refresh myself, or should I merge this patch normally with scripts/pull_github_pr.sh? I seem to remember that we had a discussion in the past about submodule refresh being problematic in this sense, but don't remember what was the conclusion.
> > 
> > in this case the downside of doing thing manually, it might pull more the what is tested here. but cqlsh doesn't have much ongoing development, so what ever done would probably gonna work o.k.
> 
> I checked the list of commits, and the ones on top of this seemed like test and dist related, so I thought it is safe enough to try.

I was referring to nadav question, about the general flow for submodules.

**Comment by dawmd** [comment]
The module has been updated

**Pull request closed without merging**
