### PR TITLE
cql3: untyped_result_set: document performance characteristics

### PR DESCRIPTION
**Pull request by avikivity**
untyped_result_set is optimized towards conventience and safety, so note that.

### CODE REVIEW

**Comment by avikivity** [comment]
@nyh ping

**Comment by avikivity** [comment]
@nyh ping

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
Sorry about the delayed review, but now this patch also needs a rebase to fix conflicts :-(

**Comment by avikivity** [comment]
v2:
 - rebased
 - fixed spelling errors

**Pull request closed without merging**
