### PR TITLE
Revert "replica: Pick new generation for SSTables being moved from staging dir

### PR DESCRIPTION
**Pull request by denesb**
This reverts commit ba6186a47fbae2b88af5e049b214b2148a7c55ca.

Said commit violates the widely held assumption that sstables generations can be used as sstable identity. One known problem caused this is potential OOO partition emitted when reading from sstables (#11843). We now also have a better fix for #11789 (the bug this commit was meant to fix): 4aa0b16852656ce11f13b78156fbf28cffbe8c1a. So we can revert without regressions.

Fixes: #11843

### CODE REVIEW

**Review by bhalevy — APPROVED** [review]
LGTM thanks

**Comment by raphaelsc** [comment]
https://github.com/scylladb/scylladb/commit/4aa0b16852656ce11f13b78156fbf28cffbe8c1a won't fix the problem once it happened, which means view building won't complete, but will fix the root cause.

**Comment by raphaelsc** [comment]
@bhalevy we need to fix generation clash on startup to really fix the problem.

**Comment by bhalevy** [comment]
> @bhalevy we need to fix generation clash on startup to really fix the problem.

If reshape / resharding is required on startup they will pick new, unique generation numbers with https://github.com/scylladb/scylladb/pull/11795

IIUC, your concern is that a system might already be in a state where there's clash of generation numbers between sstables in staging vs. sstables in the base directory, causing #11789.

However, #11789 is not a critical bug, i.e. scylla doesn't crash due to it, and there should be a workaround in the form of major compaction (or upgrade sstables), that will rewrite all sstables in the base directory, thus free up the conflicting generations, I don't think we need any provisioning for that case in the startup code.

**Comment by raphaelsc** [comment]
> > @bhalevy we need to fix generation clash on startup to really fix the problem.
> 
> If reshape / resharding is required on startup they will pick new, unique generation numbers with #11795
> 
> IIUC, your concern is that a system might already be in a state where there's clash of generation numbers between sstables in staging vs. sstables in the base directory, causing #11789.
> 
> However, #11789 is not a critical bug, i.e. scylla doesn't crash due to it, and there should be a workaround in the form of major compaction (or upgrade sstables), that will rewrite all sstables in the base directory, thus free up the conflicting generations, I don't think we need any provisioning for that case in the startup code.

It actually led to a crash, but due to a fragility that was already fixed in ICS. Major compaction isn't always a possibility for users, due to multiple reasons, a few are: not available free space, cannot afford the additional write amplification. But again, https://github.com/scylladb/scylladb/commit/4aa0b16852656ce11f13b78156fbf28cffbe8c1a fixes the root cause, so ok.

**Comment by raphaelsc** [comment]
ping merge.

**Review by raphaelsc — APPROVED** [review]

**Comment by avikivity** [comment]
After we have uuid names (@jul-stas) , we should make them mandatory and forget about generations forever (any time we see one we should immediately rename it)

**Pull request closed without merging**
