### PR TITLE
doc: document the procedure for updating the mode after upgrade

### PR DESCRIPTION
**Pull request by annastuchlik**
Fix https://github.com/scylladb/scylla-docs/issues/4126

### CODE REVIEW

**Comment by annastuchlik** [comment]
@vladzcloudius @roydahan I've added a new article covering https://github.com/scylladb/scylla-docs/issues/4126. Please, review it and let me know what should be updated.
I have two questions myself:
- Which versions should we specify in the opening paragraph? 2022.1 (now), 2021.1? I assume it affects open source users, so what's the related open source version? 5.0?
- The provided example specifies `scylla-server`. Shouldn't we have another example for ScyllaDB Enterprise `scylla-enterprise-server`?

When you tell me which ScyllaDB versions are affected and approve this PR, I'll add a link to the relevant upgrade guides.

**Comment by roydahan** [comment]
@slivne FYI

**Comment by roydahan** [comment]
> @vladzcloudius @roydahan I've added a new article covering [scylladb/scylla-docs#4126](https://github.com/scylladb/scylla-docs/issues/4126). Please, review it and let me know what should be updated. I have two questions myself:
> 
> * Which versions should we specify in the opening paragraph? 2022.1 (now), 2021.1? I assume it affects open source users, so what's the related open source version? 5.0?

- 2022.1
- The OSS version isn't 5.0 for now (unless it will be backported in later patch releases, it will be 5.1).

> * The provided example specifies `scylla-server`. Shouldn't we have another example for ScyllaDB Enterprise `scylla-enterprise-server`?
> 
> When you tell me which ScyllaDB versions are affected and approve this PR, I'll add a link to the relevant upgrade guides.

In any case, this should be merged only after the backport and the tests including this procedure (they aren't for now).

**Comment by annastuchlik** [comment]
@roydahan Thanks! 
- I'm leaving 2022.1 as is.
- I'll add 2021.1 and 5.1 (or 5.0) only if you give me the green light to do so.

> In any case, this should be merged only after the backport and the tests including this procedure (they aren't for now).

Don't we want to merge it now - for 2022.1? It's on my list of issues to do before the release.
I can update the page later on when it's backported to any other version.

**Comment by roydahan** [comment]
> 



> @roydahan Thanks!
> 
> * I'm leaving 2022.1 as is.
> * I'll add 2021.1 and 5.1 (or 5.0) only if you give me the green light to do so.
> 
> > In any case, this should be merged only after the backport and the tests including this procedure (they aren't for now).
> 
> Don't we want to merge it now - for 2022.1? It's on my list of issues to do before the release. I can update the page later on when it's backported to any other version.

No, because for now it's not in 2022.1.0 and possibly will go in only in 2022.1.1

**Review by vladzcloudius — APPROVED** [review]
Looks good. 
One small nitpick: you probably want to mention that the last step (where they wait for a node to become UN after restart) may take (sometime very long) time because of a `resharding` (we effectively reduce the number of shards there).

**Comment by annastuchlik** [comment]
@vladzcloudius I've added the information.
@roydahan Please let us know in a comment when this PR should be merged and how it should be linked with upgrade guides (which versions).

**Review by vladzcloudius — APPROVED** [review]
Looks good to me.

**Comment by annastuchlik** [comment]
@roydahan This PR has been reviewed but not merged - it's waiting for you to let us know when it can be merged and how it should be linked with upgrade guides. Please let me know when the right time comes.

**Comment by roydahan** [comment]
Time has come, for 5.1 and 2022.2 that are about to be released.

**Comment by annastuchlik** [comment]
@roydahan Thanks.

@scylladb/scylla-maint Please merge this PR to master and backport to 5.1.
I'm sorry for the late notice, but I had to wait for the approval.
Once this PR is merged, another one will be coming to add the link to the new KB article to the upgrade guides (I'd rather do it in a separate PR for this PR to backport cleanly).

**Comment by denesb** [comment]
Backported to 5.1 as fde4a6e92d835bc26609a1872ea988a3683e212e.

**Pull request closed without merging**
