### PR TITLE
database.hh: Remove unused headers

### PR DESCRIPTION
**Pull request by xemul**
Use forward declarations when needed

Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>

### CODE REVIEW

**Comment by xemul** [comment]
No test failures

```
[2022-09-29T22:40:31.858Z] Cannot contact spider1.cloudius-systems.com: java.lang.InterruptedException
[2022-09-29T23:02:10.004Z] wrapper script does not seem to be touching the log file in /jenkins/workspace/releng/Scylla-CI@tmp/durable-f46f4aee
[2022-09-29T23:02:10.004Z] (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
[2022-09-29T23:02:10.389Z] [Pipeline] }
[2022-09-29T23:02:10.475Z] [Pipeline] // dir
[2022-09-29T23:02:10.754Z] [Pipeline] echo
[2022-09-29T23:02:10.758Z] Error: dtest phase failed, going ahead to check tests and dtest status, error: |hudson.AbortException: script returned exit code -1|
```

@benipeled , does this ring any bell?

**Review by denesb — APPROVED** [review]
LGTM, I re-kicked CI.

**Comment by benipeled** [comment]
> No test failures
> 
> ```
> [2022-09-29T22:40:31.858Z] Cannot contact spider1.cloudius-systems.com: java.lang.InterruptedException
> [2022-09-29T23:02:10.004Z] wrapper script does not seem to be touching the log file in /jenkins/workspace/releng/Scylla-CI@tmp/durable-f46f4aee
> [2022-09-29T23:02:10.004Z] (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
> [2022-09-29T23:02:10.389Z] [Pipeline] }
> [2022-09-29T23:02:10.475Z] [Pipeline] // dir
> [2022-09-29T23:02:10.754Z] [Pipeline] echo
> [2022-09-29T23:02:10.758Z] Error: dtest phase failed, going ahead to check tests and dtest status, error: |hudson.AbortException: script returned exit code -1|
> ```
> 
> @benipeled , does this ring any bell?

It happened last weekend on a few jobs running on the local nodes,
we'll investigate but it has nothing with the change but some Jenkins issue

**Comment by avikivity** [comment]
Dequeued (breaks next)

**Comment by benipeled** [comment]
> Dequeued (breaks next)

@xemul the failure was [0] is it a result of a clash with other commits merged together or something we're missing in the CI flow?


[0]
```
19:52:47  [719/2991] CXX build/debug/multishard_mutation_query.o
19:52:47  FAILED: build/debug/multishard_mutation_query.o 
19:52:47  clang++ -MD -MT build/debug/multishard_mutation_query.o -MF build/debug/multishard_mutation_query.o.d -I/jenkins/workspace/scylla-master/next/scylla/seastar/include -I/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/gen/include -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_API_LEVEL=6 -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_TYPE_ERASE_MORE -DFMT_LOCALE -DFMT_SHARED -I/usr/include/p11-kit-1  -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -Og -DSCYLLA_ENABLE_WASMTIME -DSCYLLA_BUILD_MODE=debug -g -gz -iquote. -iquote build/debug/gen --std=gnu++20  -ffile-prefix-map=/jenkins/workspace/scylla-master/next/scylla=.  -march=westmere -DBOOST_TEST_DYN_LINK   -Iabseil -fvisibility=hidden  -Wall -Werror -Wno-mismatched-tags -Wno-tautological-compare -Wno-parentheses-equality -Wno-c++11-narrowing -Wno-sometimes-uninitialized -Wno-return-stack-address -Wno-missing-braces -Wno-unused-lambda-capture -Wno-overflow -Wno-noexcept-type -Wno-error=cpp -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-unused-command-line-argument -Wno-defaulted-function-deleted -Wno-redeclared-class-member -Wno-unsupported-friend -Wno-unused-variable -Wno-delete-non-abstract-non-virtual-dtor -Wno-braced-scalar-init -Wno-implicit-int-float-conversion -Wno-delete-abstract-non-virtual-dtor -Wno-uninitialized-const-reference -Wno-psabi -Wno-narrowing -Wno-array-bounds -Wno-nonnull -Wno-uninitialized -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN -DHAVE_LZ4_COMPRESS_DEFAULT  -c -o build/debug/multishard_mutation_query.o multishard_mutation_query.cc
19:52:47  multishard_mutation_query.cc:808:5: error: unknown type name 'reconcilable_result_builder'; did you mean 'reconcilable_result'?
19:52:47      reconcilable_result_builder _builder;
19:52:47      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
19:52:47      reconcilable_result
19:52:47  ./replica/database.hh:74:7: note: 'reconcilable_result' declared here
19:52:47  class reconcilable_result;
19:52:47        ^
.
.
.
```

**Comment by xemul** [comment]
`[2022-10-03T13:11:38.142Z] [2035/2423] alternator  debug  [ FAIL ] run.1 1789.31s`
```
[2022-10-03T13:29:07.825Z] E               AssertionError: assert not 'Item' in {'Item': {'expiration': Decimal('1664801284'), 'p': 'ECD5P8GQBV'}, 'ResponseMetadata': {'HTTPHeaders': {'content-lengt...-1.0', 'date': 'Mon, 03 Oct 2022 12:50:08 GMT', 'server': 'Seastar httpd'}, 'HTTPStatusCode': 200, 'RetryAttempts': 0}}
[2022-10-03T13:29:07.825Z] E                +  where {'Item': {'expiration': Decimal('1664801284'), 'p': 'ECD5P8GQBV'}, 'ResponseMetadata': {'HTTPHeaders': {'content-lengt...-1.0', 'date': 'Mon, 03 Oct 2022 12:50:08 GMT', 'server': 'Seastar httpd'}, 'HTTPStatusCode': 200, 'RetryAttempts': 0}} = <bound method ResourceFactory._create_action.<locals>.do_action of dynamodb.Table(name='alternator_Test_1664801341683')>(Key={'p': 'ECD5P8GQBV'})
[2022-10-03T13:29:07.826Z] E                +    where <bound method ResourceFactory._create_action.<locals>.do_action of dynamodb.Table(name='alternator_Test_1664801341683')> = dynamodb.Table(name='alternator_Test_1664801341683').get_item
[2022-10-03T13:29:07.826Z] 
[2022-10-03T13:29:07.826Z] test_metrics.py:286: AssertionError
```

The very same error was on PR #11664 (https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2444/consoleText) Cc @nyh

**Comment by xemul** [comment]
Re-kicked the CI

**Comment by nyh** [comment]
> `[2022-10-03T13:11:38.142Z] [2035/2423] alternator debug [ FAIL ] run.1 1789.31s`
> 
> ```
> [2022-10-03T13:29:07.825Z] E               AssertionError: assert not 'Item' in {'Item': {'expiration': Decimal('1664801284'), 'p': 'ECD5P8GQBV'}, 'ResponseMetadata': {'HTTPHeaders': {'content-lengt...-1.0', 'date': 'Mon, 03 Oct 2022 12:50:08 GMT', 'server': 'Seastar httpd'}, 'HTTPStatusCode': 200, 'RetryAttempts': 0}}
> [2022-10-03T13:29:07.825Z] E                +  where {'Item': {'expiration': Decimal('1664801284'), 'p': 'ECD5P8GQBV'}, 'ResponseMetadata': {'HTTPHeaders': {'content-lengt...-1.0', 'date': 'Mon, 03 Oct 2022 12:50:08 GMT', 'server': 'Seastar httpd'}, 'HTTPStatusCode': 200, 'RetryAttempts': 0}} = <bound method ResourceFactory._create_action.<locals>.do_action of dynamodb.Table(name='alternator_Test_1664801341683')>(Key={'p': 'ECD5P8GQBV'})
> [2022-10-03T13:29:07.826Z] E                +    where <bound method ResourceFactory._create_action.<locals>.do_action of dynamodb.Table(name='alternator_Test_1664801341683')> = dynamodb.Table(name='alternator_Test_1664801341683').get_item
> [2022-10-03T13:29:07.826Z] 
> [2022-10-03T13:29:07.826Z] test_metrics.py:286: AssertionError
> ```
> 
> The very same error was on PR #11664 (https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2444/consoleText) Cc @nyh

The failure log is https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2498/testReport/junit/(root)/non-boost%20tests/run_debug_1/
It's a very slow debug-build (100 times slower than a normal run on my laptop), but it's still surprising that it times out on Alternator TTL after 60 seconds, which should have just taken 0.5 seconds.

In commit 746c4bd9eb657dfc61fec56e6b2d38ead91cf9d6 I noticed that some expirations got delayed by even 60 seconds, so I used a 120 seconds timeout. It looks like I need to do this for this test as well :-(

**Comment by nyh** [comment]
> In commit [746c4bd](https://github.com/scylladb/scylladb/commit/746c4bd9eb657dfc61fec56e6b2d38ead91cf9d6) I noticed that some expirations got delayed by even 60 seconds, so I used a 120 seconds timeout. It looks like I need to do this for this test as well :-(

Yes, the full log https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2498/artifact/testlog/x86_64/debug/run.1.log has
```
WARN  2022-10-03 15:50:08,723 [shard 1] alternator_ttl - scan took 63.567 seconds, longer than period - not sleeping
```
So the scan that usually takes a fraction of a scan indeed took 63 seconds, which is more than this test's timeout. So it needs to increase. I'll open an issue and send a test fix.

**Comment by nyh** [comment]
Opened https://github.com/scylladb/scylladb/issues/11695 for the spurious test failure (unrelated to this PR)

**Pull request closed without merging**
