### PR TITLE
migration_manager: more verbose logging for schema versions

### PR DESCRIPTION
**Pull request by kbr-scylla**
We're observing nodes getting stuck during bootstrap inside `storage_service::wait_for_ring_to_settle()`, which periodically checks `migration_manager::have_schema_agreement()` until it becomes `true`: scylladb/scylladb#15393.

There is no obvious reason why that happens -- according to the nodes' logs, their latest in-memory schema version is the same.

So either the gossiped schema version is for some reason different (perhaps there is a race in publishing `application_state::SCHEMA`) or missing entirely.

Alternatively, `wait_for_ring_to_settle` is leaving the `have_schema_agreement` loop and getting stuck in
`update_topology_change_info` trying to acquire a lock.

Modify logging inside `have_schema_agreement` so details about missing schema or version mismatch are logged on INFO level, and an INFO level message is printed before we return `true`. To prevent logs from getting spammed, rate-limit the periodic messages to once every 5 seconds. This will still show the reason in our tests which allow the node to hang for many minutes before timing out. Also these schema agreement checks are done on relatively rare occasions such as bootstrap, so the additional logs should not be harmful.

Furthermore, when publishing schema version to gossip, log it on INFO level. This is happening at most once per schema change so it's a rare message. If there's a race in publishing schema versions, this should allow us to observe it.

Ref: scylladb/scylladb#15393

### CODE REVIEW

**Comment by bhalevy** [comment]
Looks reasonable to me

**Review by tgrabiec — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Rebased, the compaction test failures should be fixed by 1cccc8681377bdf65fbcbaaaacb89306f8cf1df1

**Comment by denesb** [comment]
> @scylladb/scylla-maint please merge

Next is broken, will merge once it is restored.

**Comment by denesb** [comment]
Q'd.

**Pull request closed without merging**
