### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by tchaikov**
* seastar cd8a9133...1cf4707e (13):
  > docs: remove unused parameter from handle_connection function of echo-HTTP-server tutorial example
  > stall-analyser: use 0 for the default value of --width
  > http: Move parsed params and urls
  > scripts: use raw string to avoid invalid escape sequences
  > timed_out_error: add fmt::formatter for timed_out_error
  > scripts/stall-analyser: change default branch-threshold to 3%
  > scripts/stall-analyser: resolve string escape sequence warning
  > io_queue: Use static vector for fair groups too
  > io_queue: Use static vector to store fair queues
  > stall-analyser: add space around '=' in param list
  > stall-analyser: add a space between 'var: Type' in type annotation
  > stall-analyser: move variables closer to where they are used
  > memory: drop support for compilers that don't support aligned new

### CODE REVIEW

**Comment by tchaikov** [comment]
pending on #18193

**Comment by denesb** [comment]
> pending on #18193

This PR is still not merged, so how is CI passing here?

**Comment by tchaikov** [comment]
> > pending on #18193
> 
> This PR is still not merged, so how is CI passing here?

@denesb because i include the referenced PR in this change, just to make sure that it builds and tests fine with its dependency.

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you please help queue this change?

**Comment by tchaikov** [comment]
superseded by #18235

**Pull request closed without merging**
