### PR TITLE
Update tools/cqlsh submodule

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh b8d86b76...e5f5eafd (2):
  > dist/debian: fix the trailer line format
  > `COPY TO STDOUT` shouldn't put None where a function is expected

 Fixes: scylladb/scylladb#17451

### CODE REVIEW

**Comment by fruch** [comment]
> @fruch please file issues in this repository and add Fixes tags here

done

**Comment by mykaul** [comment]
I think the 'fixes' line is wrong.

**Comment by fruch** [comment]
> I think the 'fixes' line is wrong.

Fixed the description

**Comment by fruch** [comment]
> @fruch - ping - what's the status of this PR? Waiting for merge after merge freeze?

I don't know, beside you no one said anything about this one.

@scylladb/scylla-maint ?

**Comment by avikivity** [comment]
I only merge CI stability fixes.

**Comment by fruch** [comment]
> I only merge CI stability fixes.

@scylladb/scylla-maint now can we get it merged ?

**Comment by denesb** [comment]
Queued.

**Comment by roydahan** [comment]
IIUC this PR should be backport to 5.4.

**Comment by roydahan** [comment]
@yaronkaikov / @denesb should I put the backport label myself or the maintainers/author should do it?

**Comment by yaronkaikov** [comment]
> @yaronkaikov / @denesb should I put the backport label myself or the maintainers/author should do it?

You can just add it (already did), The maintainers will decide if to merge it or not

**Comment by nyh** [comment]
@yaronkaikov @roydahan until today we never backported submodule updates at all. What we did do is to have a separate branch for the submodule (e.g., branch-5.4 in the scylla-tools-java repository), and there we only backport specific changes (not all the changes) in the submodule.

**Comment by denesb** [comment]
> @yaronkaikov @roydahan until today we never backported submodule updates at all. What we did do is to have a separate branch for the submodule (e.g., branch-5.4 in the scylla-tools-java repository), and there we only backport specific changes (not all the changes) in the submodule.

You still cannot backport a submodule, there is just no way to do that. You have to do what we did before: backport the submodule change in the submodule, then create a submodule update commit on the target scylla.git branch.

**Comment by mykaul** [comment]
@fruch ^^^ - please do the needful

**Comment by avikivity** [comment]
No, https://github.com/scylladb/scylladb/blob/master/docs/dev/maintainer.md#backporting-seastar-commits.

**Comment by fruch** [comment]
I've follow the instruction and here are the PRs, for both release needs this fix
- https://github.com/scylladb/scylladb/pull/17728
- https://github.com/scylladb/scylla-enterprise/pull/3992

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/commit/02182caff4fe526e3e59f7b5550e263093235124 is in 5.4.

**Pull request closed without merging**
