### PR TITLE
build: increase `SCHEDULING_GROUPS_COUNT`

### PR DESCRIPTION
**Pull request by Jadw1**
scylladb/scylladb#18715 introduced new internal scheduling group. Although OSS doesn't require any extra scheduling group, in enterprise version there is a feature which crate separate scheduling group for each service level.
Out documentation states that in enterprise user is able to create 7 service levels (up to 7 extra scheduling group). But after adding the new internal SG, the number of allowed service levels dropped to 6 in enterprise.

This patch reverse the regression. It's submitted to OSS to not increase differences between the repos.

Fixes scylladb/scylladb#21051

Backports:
The regression is present in 2024.2, which is based on OSS 6.0. Setting backport labels for all version down to 6.0.

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
```
21:00:02  ++ buildah from docker.io/ubuntu:24.04
21:00:03  Trying to pull docker.io/library/ubuntu:24.04...
21:00:14  Error: initializing source docker://ubuntu:24.04: Requesting bearer token: invalid status code from registry 502 (Bad Gateway)
21:00:14  + container=
21:00:14  [Pipeline] echo
21:00:14  Get local image name - command: cat output-container-build-x86_64-ubuntu.txt | grep image= | sed -e 's/.*image=//'
21:00:14  [Pipeline] sh
21:00:16  + cat output-container-build-x86_64-ubuntu.txt
21:00:16  + grep image=
21:00:16  + sed -e 's/.*image=//'
21:00:16  [Pipeline] echo
21:00:16  Get local image name - command output: 
21:00:17  [Pipeline] echo
21:00:17  Pull new docker image - command: podman pull 
21:00:17  [Pipeline] sh
21:00:18  + podman pull
21:00:18  Error: requires at least 1 arg(s), only received 0
21:00:19  [Pipeline] echo
21:00:19  ERROR: container build (x86_64) failed with error: script returned exit code 125
```

@yaronkaikov does this ring a bell?

**Comment by Jadw1** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12767/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12767/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/1364/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/12454/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/4432/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12767/)
> 
> #### Failed Tests (1/36343):
> * [cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/12767/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_entities_frozen_collections_test_debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.debug.2)

https://github.com/scylladb/scylladb/issues/9059

**Comment by yaronkaikov** [comment]
> ```
> 21:00:02  ++ buildah from docker.io/ubuntu:24.04
> 21:00:03  Trying to pull docker.io/library/ubuntu:24.04...
> 21:00:14  Error: initializing source docker://ubuntu:24.04: Requesting bearer token: invalid status code from registry 502 (Bad Gateway)
> 21:00:14  + container=
> 21:00:14  [Pipeline] echo
> 21:00:14  Get local image name - command: cat output-container-build-x86_64-ubuntu.txt | grep image= | sed -e 's/.*image=//'
> 21:00:14  [Pipeline] sh
> 21:00:16  + cat output-container-build-x86_64-ubuntu.txt
> 21:00:16  + grep image=
> 21:00:16  + sed -e 's/.*image=//'
> 21:00:16  [Pipeline] echo
> 21:00:16  Get local image name - command output: 
> 21:00:17  [Pipeline] echo
> 21:00:17  Pull new docker image - command: podman pull 
> 21:00:17  [Pipeline] sh
> 21:00:18  + podman pull
> 21:00:18  Error: requires at least 1 arg(s), only received 0
> 21:00:19  [Pipeline] echo
> 21:00:19  ERROR: container build (x86_64) failed with error: script returned exit code 125
> ```
> 
> @yaronkaikov does this ring a bell?
nope, but we will investigate this

**Comment by avikivity** [comment]
> #18715 introduced new internal scheduling group. Although OSS doesn't require any extra scheduling group, in enterprise version there is a feature which crate separate scheduling group for each service level. Out documentation states that in enterprise user is able to create 7 service levels (up to 7 extra scheduling group). But after adding the new internal SG, the number of allowed service levels dropped to 6 in enterprise.
> 
> This patch reverse the regression. It's submitted to OSS to not increase differences between the repos.
> 
> Fixes #21051
> 
> Backports: The regression is present in 2024.2, which is based on OSS 6.0. Setting backport labels for all version down to 6.0.

It's completely superfluous to OSS.

**Comment by piodul** [comment]
> It's completely superfluous to OSS.

In that case, @Jadw1 please submit a PR to enterprise

**Pull request closed without merging**
