### PR TITLE
Compaction resharding tasks

### PR DESCRIPTION
**Pull request by Deexie**
Task manager's tasks covering resharding compaction 
on table and shard level.

### CODE REVIEW

**Comment by Deexie** [comment]
@bhalevy review please

**Comment by Deexie** [comment]
- delete leftovers

**Comment by Deexie** [comment]
Moved to draft as sstables distribution shall not be covered by a separate task; need to delete it.

**Comment by Deexie** [comment]
- delete task for sstables distribution; fix test respectively

**Comment by Deexie** [comment]
- rebase

**Comment by Deexie** [comment]
- rebase

**Comment by Deexie** [comment]
- rename classes

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
Needs another rebase, there are conflicts. Let's wait until promotion succeeds, the conflicting PR might be in next.

**Comment by Deexie** [comment]
- rebase

**Pull request merged**
