### PR TITLE
docs: admin-tools: remove defunct sstable-index

### PR DESCRIPTION
**Pull request by denesb**
Said tool was supplanted by scylla-sstable in 4.6. Remove the page as
well as all references to it.

### CODE REVIEW

**Comment by denesb** [comment]
Note that https://docs.scylladb.com/master/operating-scylla/admin-tools/scylla-sstable.html doesn't have as much details as the removed page on what `scylla-sstable dump-index` does. We can make it similarly detailed, but then we should do it for all contained operations.

**Comment by denesb** [comment]
Ping.

**Comment by tzach** [comment]
Two very minor issues:
- We do not have a doc per version just yet, so the removed doc would not be available for 4.5 users (not too bad, its a non supported version by now)
- There might be external links *to* the remove page will hit 404. I validated with `make linkcheck` and there are no internal links. 

If you are good with both, I'm good with this change

**Comment by denesb** [comment]
The tool was very short-lived (just 2 releases), so I don't think it accumulated a lot of external links. It is also a somewhat obscure tool targeted at advanced users.

**Review by tzach — APPROVED** [review]
LGTM

**Review by annastuchlik — APPROVED** [review]
LGTM

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Pull request closed without merging**
