### PR TITLE
Update seastar submodule

### PR DESCRIPTION
**Pull request by avikivity**
* seastar 0784da8769...c1a5fbe701 (27):
  > memory: diable transparent hugepages if --overprovisioned is specified
  > http/exception: s/<TAB>/    /
  > install-dependencies.sh: re-add protobuf
  > Merge 'Keep capacity on fair_queue_entry' from Pavel Emelyanov
  > Merge 'Fix server-side RPC stream shutdown' from Pavel Emelyanov
Fixes https://github.com/scylladb/scylladb/issues/13100
  > smp: make service management semaphore thread local
  > tls_test: abort_accept() after getting server socket
  > Merge 'Print more IO info with ioinfo app' from Pavel Emelyanov
  > rpc: Fix client-side stream registration race
Ref https://github.com/scylladb/scylladb/issues/13100
  > tests: perf: shard_token_bucket: avoid capturing unused variables in lambdas
  > build: pass -DBoost_NO_CXX98_FUNCTION_BASE to C++ compiler
  > reactor: Drop some dangling friend declarations
  > fair_queue: Do not re-evaluate request capacity twice
  > build: do not use serial number file when signing a cert
  > shared_token_bucket: Make duration->tokens conversion more solid
  > tests: Add perf test for shard_token_bucket
  > Merge 'Make make_file_impl() less yielding' from Pavel Emelyanov
  > fair_queue: Remove individual requests counting
  > reactor, linux-aio: print value of aio-max-nr on error
  > Merge 'build, net: disable implicit fallthough' from Kefu Chai
  > shared_token_bucket: Fix duration_for() underflow
  > rpc: Generalize get_stats_internal() method
  > doc/building-dpdk.md: fix invalid file path of README-DPDK.md
  > install-dependencies: add centos9
  > Merge 'log: report scheduling group along with shard id' from Kefu Chai
  > dns: handle exception in do_sendv for udp
  > Merge 'Add a stall detector histogram' from Amnon Heiman

### CODE REVIEW

**Comment by tchaikov** [comment]
```
20:51:41  _________ TestStreamingLimitThroughput.test_limit_streaming_throughput _________
20:51:41  [gw4] linux -- Python 3.11.4 /usr/bin/python3
20:51:41  
20:51:41  self = <throughput_limits_test.TestStreamingLimitThroughput object at 0x7f55ec20dcd0>
20:51:41  
20:51:41      def test_limit_streaming_throughput(self):
...
20:51:41          for line, match in streaming_succeeded_lines[-3:]:
20:51:41              # verify only last 3/10 streaming indexes as first ones are not yet limited properly - possibly due too little data.
20:51:41              # also asserting 2.0MB instead 1MB due limited precision of throughput limiter
20:51:41  >           assert float(match.group(1)) < 2000, "Failed to limit bandwidth for streaming keyspace1"
20:51:41  E           AssertionError: Failed to limit bandwidth for streaming keyspace1
20:51:41  E           assert 170968.94 < 2000
```

looks like #12602

**Comment by avikivity** [comment]
Three related tests failed:

[Test Result](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3992/testReport/) (3 failures / +3)
[FullDtest / full-split004 / throughput_limits_test.TestStreamingLimitThroughput.test_limit_streaming_throughput](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3992/testReport/junit/throughput_limits_test/TestStreamingLimitThroughput/FullDtest___full_split004___test_limit_streaming_throughput/)
[FullDtest / full-split006 / throughput_limits_test.TestStreamingLimitThroughput.test_limit_rbno_bootstrap_throughput](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3992/testReport/junit/throughput_limits_test/TestStreamingLimitThroughput/FullDtest___full_split006___test_limit_rbno_bootstrap_throughput/)
[FullDtest / full-split000 / throughput_limits_test.TestCompactionLimitThroughput.test_can_limit_compaction_throughput](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3992/testReport/junit/throughput_limits_test/TestCompactionLimitThroughput/FullDtest___full_split000___test_can_limit_compaction_throughput/)
	
Identified problems
pytest failure

a pytest failed: throughput_limits_test.py::TestStreamingLimitThroughput::test_limit_streaming_throughput
[Indication 1](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/3992/consoleFull#-910744074fcc21424-66d2-4bd8-8e0d-9746405e5b16)


So it's probably a real regression in the bandwidth limiter. @xemul

**Comment by xemul** [comment]
@avikivity , please revert https://github.com/scylladb/seastar/commit/fa80682b047d514b0511ea10d68c6a5e41ba59d7. It has a bug, I'll resubmit

**Comment by avikivity** [comment]
@benipeled why was CI aborted?

**Comment by avikivity** [comment]
@xemul now gdb fails. Please patch scylla-gdb.py so it works before/after.

**Comment by benipeled** [comment]
> @benipeled why was CI aborted?

spot-termination that wasn't handled by the retry logic due to a "new" pattern
Handled on https://github.com/scylladb/scylla-dtest/pull/3531

**Comment by DoronArazii** [comment]
ping, what's holding this

**Comment by tchaikov** [comment]
@DoronArazii this change is not necessary. #15218 superseded it. i am closing this PR.

**Pull request closed without merging**
