### PR TITLE
test/cql-pytest: test out-of-range bigint from fromJson()

### PR DESCRIPTION
**Pull request by tchaikov**
user could insert out-of-range numbers using a float point number via "fromJson()" as bigint. and we should reject them. please note this is not exactly same issue as #10137, where we can barely do nothing other than improving RapidJson or use another library for parsing JSON so that it does not lose the accuracy when interpreting the float point numbers. while in this case, the accuracy is not lost because of RapidJson. instead, we're obliged to prevent user from inserting out-of-range numbers using fromJson() even if these numbers are very close to the boundaries of the range in question and these numbers are not rounded by RapidJson.

Refs #13077

### CODE REVIEW

**Comment by tchaikov** [comment]
@nyh hi Nadav, this is anther try to convince you that #13077 is not exactly identical to #10137, even they share the same root cause -- the way how RapidJson interprets a could-have-been-integer value. the difference is that we **can** do something to correct the wrong behavior here.

**Comment by nyh** [comment]
When I wrote the test in for #10137 (see commit https://github.com/scylladb/scylladb/pull/13423/commits/91ccd167fe98bcf2e932eaab914057ce032a83ac, it's the test right before the one you added now) I already knew that we have exactly the problem you test in your xfailing test, for 2^63 - I even saw the UBSAN problem (and mentioned it in the comment, take a look). But I used a smaller number because I thought it's exactly the same problem and wanted to reproduce it "cleanly" without ugly ubsan.

I still think you are looking at the issue wrongly when you think it can be solved outside rapidjson. Because of rapidJSON's limitations,  `9223372036854775808.0` (2^63, in your test) `9223372036854775807.0` (2^63-1, missing in your test) become the same number. NOTHING you can do after rapidJSON's mess of considering these the same number can make one of them be accepted and the other rejected.

You do make a good point though (or at least, that's my take-home from what you said) that it's not nice that `9223372036854775808.0` causes a UBSAN. It should have been rejected (IF it's rejected, and if I remember correctly, it is) cleanly, without UBSAN. If that's the bug you are trying to fix then I finally understand what you are trying to fix, but I think it's not what you explained.

**Comment by tchaikov** [comment]
replied in #13077

**Comment by nyh** [comment]
@tchaikov if you want me to review this PR again, please:
1. Rebase it and have the CI run again, and pass.
2. Please, instead of pointing me to lengthy discussions on this PR and on other issues, please edit the commit message and/or cover letter in this PR to explain only why you wrote this test and how it differs from other tests. Here is my **understanding** but I'm not sure I understood correctly, and it's not explained in the over letter: 

* The test test_fromjson_bigint_double_upper_boundary just checks that a if we try to convert a number higher than MAX_BIGINT to bigint, we can a clean error. Apparently we don't - and get a UBSAN instead. NOTE: if we get a UBSAN, currently IIRC (?) we crash Scylla in Jenkins, so this test should be "skipped" instead of "xfail" to not crash all the testing. Maybe this is why your CI failed?
* The other test, test_fromjson_bigint_double_boundary, I think is pointless. You try numbers close to (but below) 2^63, which we already KNOW work but yield inaccurate results (test_fromjson_bigint_nonoverflow_scientific), and you simply don't check their result, so what's the point of the test at all?

So unless I'm misunderstanding something, test_fromjson_bigint_double_upper_boundary is the only test that should remain in this PR, it should be skipped instead of xfail, and the commit message should explain what it tests (a case of UBSAN instead of clean error).

If I understand correctly, you also don't need test_fromjson_bigint_double_upper_boundary to specifically target the "boundary" of the range - this is just a red herring and confuses what this issue is about. If you use 2*MAX_BIG_INT, you'll get exactly the same UBSAN, no?

**Comment by tchaikov** [comment]
i am closing this PR. as i am not able to explain the issue in readable way at this moment.

**Pull request closed without merging**
