### PR TITLE
build: cmake: sync with `configure.py` (5/n) 

### PR DESCRIPTION
**Pull request by tchaikov**
- build: cmake: build release.cc as a library
- build: cmake: link alternator against cql3
- build: cmake: link scylla against xxHash::xxhash
- build: cmake: use lld or gold as linker if available

### CODE REVIEW

**Comment by tchaikov** [comment]
@denesb hi Botond, would you mind reviewing this change as well?

**Comment by denesb** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4527/

CI failed with an assert in seastar code. Opened issue to track: https://github.com/scylladb/seastar/issues/1514.

**Comment by avikivity** [comment]
@tchaikov do you think it's feasible to switch to cmake completely?

I'm not too happy about it since I will lose the ability contribute to the build or provide meaningful reviews. On the other hand I'm not thrilled about adding module support to ./configure.py.

**Review by denesb — APPROVED** [review]

**Comment by tchaikov** [comment]
as CMake structures the dependencies using different targets, despite that it obscures the exact way how the compiling options are populated and how the dependencies chain are formed. but i think it can really help when we need to sort out the dependencies between modules which we will have. as i can move the .cc around or change the linkage in a jiffy. after the dependency is fixed, if we need to stick to ninja, i will start to study the [dyndep](https://ninja-build.org/manual.html#ref_dyndep) support of ninja and port the rules from the generated ninja build files to `configure.py`.

regarding switching to CMake completely, the answer from the inner me would be a big "yes". for two reasons

1. simpler this way in the sense of better readability
2. no need to port the generated rule to ninja

but the cons is, as you mentioned that it is somewhat obscure. i am wondering, if our CMake building system is mature enough, it will surely have some patterns we can follow, and to contribute to it is following the existing practice?

**Pull request merged**
