### PR TITLE
doc: update supported os for 2022.1

### PR DESCRIPTION
**Pull request by yaronkaikov**
ubuntu22.04 is already supported on both `5.0` and `2022.1`

updating the table

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@annastuchlik ping

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge.
This PR must be backported to branch-5.1 and branch-5.2.

**Comment by annastuchlik** [comment]
@scylla/scylla-maint Please backport to to branch-5.1 and branch-5.2.

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to to branch-5.1 and branch-5.2.

Done.

**Comment by tzach** [comment]
This fix need to be backported to Enterprise
https://enterprise.docs.scylladb.com/stable/getting-started/os-support.html

**Comment by annastuchlik** [comment]
It was backported to branch-5.1, so it was automatically backported to Enterprise branch-2022.2 (the first versioned branch we have). It looks like that:
image

**Comment by tzach** [comment]
You are right. I was refering to Enterprise **2021.1** support for Ubuntu 22.04
Should be a different (Enterprise) issue.

**Pull request closed without merging**
