### PR TITLE
tablets, mv: disable self-pairing when tablets are used

### LINKED ISSUE #16260: Disable self-pairing optimization
A write to a base table generate (one or more) writes to a materialized view.  The writes to RF base replicas need to cause writes to RF view replicas. Our MV implementation, based on Cassandra's implementation, does this with "**pairing**" - each one of the base replicas writes to exactly one view replica. The function `get_view_natural_endpoint()` tells a base replica which of the view replicas it should send the update to.

The _standard_  pairing is based on the ring order - the first owner of the base token sends to the first owner of the view token, the second to the second, and so on. However, the existing code also uses an optimization we call **self-pairing**, where if a single node is both a base replica and a base replica, the pairing is this node would send the update to itself.

This self-pairing optimization can cause the pairing to change after view ranges are moved between nodes, so it can break base-view consistency in some edge cases (leading to "ghost rows"). So this issue proposes to remove the self-pairing exception in `get_view_natural_endpoint()`.

However, changing the pairing on an **existing** table can cause the very same inconsistencies we want to void, so we want an upgraded table to continue using the old pairing.

We could add a configuration option to turn self-pairing on or off on a view (similar to how we handle the `synchronous_updates` flag), but I propose to start with something simpler:

1. A table using **vnodes** will default to use self-pairing, like today.
2. A table using **tablets** will default to not use self-pairing.  Because old vnode tables cannot be upgrade to tablets, we don't risk pairing changes. In tablets, range movements are more common (even if the cluster itself doesn't grow, individual tables may move around nodes) so disabling the problematic optimization is more important.

Later, we can, if we want, add a configurable option to set this flag on a table, but we don't need to do it now (we did the same thing for `synchronous_updates`, which started with some automatic logic and only later we made it explicitly configurable).

### PR DESCRIPTION
**Pull request by nyh**
tablets, mv: disable self-pairing when tablets are used
    
A write to a base table can generate one or more writes to a materialized
view. The write to RF base replicas need to cause writes to RF view
replicas. Our MV implementation, based on Cassandra's implementation,
does this via "pairing": Each one of the base replicas involved in this
write sends each view update to exactly one view replica. The function
get_view_natural_endpoint() tells a base replica which of the view
replicas it should send the update to.
    
The standard pairing is based on the ring order: The first owner of the
base token sends to the first owner of the view token, the second to the
second, and so on. However, the existing code also uses an optimization
we call self-pairing: If a single node is both a base replica and a base
replica, the pairing is modified so this node sends the update to itself.
    
This patch *disables* the self-pairing optimization in keyspaces that
use tablets:
    
The self-pairing optimization can cause the pairing to change after
token ranges are moved between nodes, so it can break base-view consistency
in some edge cases, leading to "ghost rows". With tablets, these range
movements become even more frequent - they can happen even if the
cluster doesn't grow.  This is why we want to solve this problem for tablets.
    
For backward compatibility and to avoid sudden inconsistencies emerging
during upgrades, we decided to continue using the self-pairing optimization
for keyspaces that are *not* using tablets (i.e., using vnoodes).
    
Currently, we don't introduce a configuration option to override these
defaults - i.e., we don't provide a way to disable self-pairing with
vnodes or to enable them with tablets. We could introduce such a flag
later, if we ever want to (and I'm not sure we want to).
    
It's important to note, that in some cases, this change has implications
on when view updates become synchronous, in the tablets case.
For example:
    
      * If we have 3 nodes and RF=3, with the self-pairing optimization each
        node is paired with itself, the view update is local, and is
        implicitly synchronous (without requiring a "synchronous_updates"
        flag).
      * In the same setup with tablets, without the self-pairing optimization
        (due to this patch), this is not guaranteed. Some view updates may not
        be synchronous, i.e., the base write will not wait for the view
        write. If the user really wants synchronous updates, they should
        be requested explicitly, with the "synchronous_updates" view option.
    
Fixes #16260.

### CODE REVIEW

**Comment by avikivity** [comment]
Isn't the first patch part of a different series?

**Comment by avikivity** [comment]
please rebase

**Comment by avikivity** [comment]
we could disable self-pairing on vnodes too, by making it a schema attribute. new views can be created with the attribute, while old views will retain its lack.

**Comment by nyh** [comment]
> please rebase

Done. Got rid of the first patch (that came from an earlier PR).

**Comment by nyh** [comment]
@eliransin @wmitros please review

**Comment by nyh** [comment]
> we could disable self-pairing on vnodes too, by making it a schema attribute. new views can be created with the attribute, while old views will retain its lack.

By the way, I just realized something interesting (@eliransin @kostja FYI):

For the LSI (same-partition-key on base on view) case on **vnodes**, the self-pairing optimization was never really needed. With vnodes, the replication map of base and view were the same in base and view, and the token is the same in base and view, so the base and view's list of replicas is **identical** - not just the same nodes, but actually the same nodes in exactly the same order. So we get self-pairing without the "self-pairing optimization" code at all. Which makes this optimization even less useful on vnodes than I thought it was.

**Review by wmitros — APPROVED** [review]
I actually took a look at this earlier and it seems like there's not that much for me to review, but I can say that the changes look correct and the comments are in line with what I read in the design doc, so LGMT from me

**Comment by nyh** [comment]
> I actually took a look at this earlier and it seems like there's not that much for me to review, but I can say that the changes look correct and the comments are in line with what I read in the design doc, so LGMT from me

Thanks. @kostja instructed that we work more closely as a team, not as individuals working on separate assignments. This is why I'm asking @eliransin and you to review my patches - so you'll be familiar with my work and later be able to more easily and quickly join it. And of course, if you find errors in my code or in my judgement and point it out - that is important too.

**Comment by mykaul** [comment]
> > I actually took a look at this earlier and it seems like there's not that much for me to review, but I can say that the changes look correct and the comments are in line with what I read in the design doc, so LGMT from me
> 
> Thanks. @kostja instructed that we work more closely as a team, not as individuals working on separate assignments. This is why I'm asking @eliransin and you to review my patches - so you'll be familiar with my work and later be able to more easily and quickly join it. And of course, if you find errors in my code or in my judgement and point it out - that is important too.

<joke>
And we'll have more people to blame on bugs found out later!
</joke>

**Pull request closed without merging**
