### PR TITLE
doc: fix the outdated Networking section

### PR DESCRIPTION
**Pull request by annastuchlik**
Fixes https://github.com/scylladb/scylla-docs/issues/2467

This commit updates the Networking section. The scope is:
- Removing the outdated content, including the reference to the super outdated posix_net_conf.sh script.
- Adding the guidelines provided by @vladzcloudius.
- Adding the reference to the documentation for the perftune.py script.

### CODE REVIEW

**Comment by vladzcloudius** [comment]
By the time you got to this PR the `mode` option of `perftune.py` has become deprecated.

Didn't write some newer content about perftune.py lately? I do remember giving examples with `irq_cpu_mask` to you.

**Comment by annastuchlik** [comment]
image

**Comment by annastuchlik** [comment]
@vladzcloudius Following our discussion, I've updated the Networking section.
All other updates to the perftune.py documentation will be added in a separate PR, as they will fix the [Seastar Perftune](https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/perftune.html) page.

Could you re-review this PR?

**Comment by annastuchlik** [comment]
@vladzcloudius Could you have a look at this PR? It only fixes the Networking section, and nothing else.

**Comment by annastuchlik** [comment]
@vladzcloudius ping

**Review by vladzcloudius — APPROVED** [review]
Looks good. Thanks and sorry for a delay.

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please merge.

**Pull request closed without merging**
