### PR TITLE
Mv delete partition

### PR DESCRIPTION
**Pull request by eliransin**
Please ignore this PR it is for the purpose of testing code coverage in CI :slightly_smiling_face:

### CODE REVIEW

**Comment by eliransin** [comment]
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/)
:white_check_mark: - [Code Coverage](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10//artifact/coverage/html_report/index.html)
#### Failed Tests (6/4797):
- [test_delete_partition_rows_from_table_with_mv](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_mv_delete_partitions/test_delete_partition_rows_from_table_with_mv) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_partition_rows_from_table_with_mv)
- [topology_custom.test_mv_delete_partitions.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/topology_custom_test_mv_delete_partitions_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_mv_delete_partitions.release.1)
- [test_long_skipped_view_update_delete_with_timestamp[100]](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_materialized_view/test_long_skipped_view_update_delete_with_timestamp_100_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_long_skipped_view_update_delete_with_timestamp[100])
- [test_partition_deletion](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_secondary_index/test_partition_deletion) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partition_deletion)
- [cql-pytest.test_materialized_view.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/cql_pytest_test_materialized_view_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cql-pytest.test_materialized_view.release.1)
- [cql-pytest.test_secondary_index.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/cql_pytest_test_secondary_index_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cql-pytest.test_secondary_index.release.1)
#### Patch coverage report:
```
Reading tracefile /jenkins/workspace/scylla-staging/eliran/scylla-master/scylla-ci/coverage/patch.info

**Comment by eliransin** [comment]
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/)
:white_check_mark: - [Code Coverage](https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10//artifact/coverage/html_report/index.html)
#### Failed Tests (6/4797):
- [test_delete_partition_rows_from_table_with_mv](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_mv_delete_partitions/test_delete_partition_rows_from_table_with_mv) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_delete_partition_rows_from_table_with_mv)
- [topology_custom.test_mv_delete_partitions.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/topology_custom_test_mv_delete_partitions_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_mv_delete_partitions.release.1)
- [test_long_skipped_view_update_delete_with_timestamp[100]](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_materialized_view/test_long_skipped_view_update_delete_with_timestamp_100_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_long_skipped_view_update_delete_with_timestamp[100])
- [test_partition_deletion](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/test_secondary_index/test_partition_deletion) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partition_deletion)
- [cql-pytest.test_materialized_view.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/cql_pytest_test_materialized_view_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cql-pytest.test_materialized_view.release.1)
- [cql-pytest.test_secondary_index.release.1](https://jenkins.scylladb.com//job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/10/testReport/junit/%28root%29/non-boost%20tests/cql_pytest_test_secondary_index_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cql-pytest.test_secondary_index.release.1)
#### Patch coverage report:
```
Reading tracefile /jenkins/workspace/scylla-staging/eliran/scylla-master/scylla-ci/coverage/patch.info
17:45:14  Summary coverage rate:
17:45:14    lines......: 81.8% (121 of 148 lines)

**Comment by nyh** [comment]
@eliransin when you complete this work, can you please summarize in a document somewhere (maybe in doc/dev?) how the whole coverage thing works, how to use it to find coverage of the whole project and PRs?

Instead of the long "patch coverage report" dump in the above automated comment, which contains a lot of numbers that I don't know how to use, I think it would have been useful to have a direct link to the actual report, which after some non-trivial investigation I found in 
https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/16//artifact/coverage/html_report/patch/patches/index.html
The nice thing about this HTML is that it not only shows numbers like "patch 5 had 80% test coverage", but you also have a link to show which lines weren't covered. For example patch 5: https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/16//artifact/coverage/html_report/patch/patches/05%20-%20mv%3A%20throttle%20view%20update%20generation%20for%20large%20queries.patch.gcov.html

Because this link is not trivial to find, I ask that you please add it in the automated comment instead of hoping that readers can get to it from the "Code Coverage - Details" link at the bottom (which contains a lot of other stuff I don't understand, and you need to jump through at least 3 links until you get to the really relevant one).

**Comment by eliransin** [comment]
@nyh 
> @eliransin when you complete this work, can you please summarize in a document somewhere (maybe in doc/dev?) how the whole coverage thing works, how to use it to find coverage of the whole project and PRs?

https://github.com/scylladb/scylladb/blob/master/docs/dev/code-coverage.md

> 
> Instead of the long "patch coverage report" dump in the above automated comment, which contains a lot of numbers that I don't know how to use, I think it would have been useful to have a direct link to the actual report, which after 

The `Code Coverage` with the green tickmark is clickable and will take you to the report :slightly_smiling_face: 

>some non-trivial investigation I found in https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/16//artifact/coverage/html_report/patch/patches/index.html The nice thing about this HTML is that it not only shows numbers like "patch 5 had 80% test coverage", but you also have a link to show which lines weren't covered. For example patch 5: https://jenkins.scylladb.com/job/scylla-staging/job/eliran/job/scylla-master/job/scylla-ci/16//artifact/coverage/html_report/patch/patches/05%20-%20mv%3A%20throttle%20view%20update%20generation%20for%20large%20queries.patch.gcov.html
> 
> Because this link is not trivial to find, I ask that you please add it in the automated comment instead of hoping that readers can get to it from the "Code Coverage - Details" link at the bottom (which contains a lot of other stuff I don't understand, and you need to jump through at least 3 links until you get to the really relevant one).

It is trickier to include links to every patch in the report (but doable) since the report is actually an lcov command line output. 
I am glad you found the report useful and I hope many other will find it useful too.
@roydahan group will take responsibility for this ( specifically probably @yaronkaikov team)  so you can probably ask them for enhancements. Right now I am concentrated in putting an MVP out there so we feedback like the excellent feedback you just gave will start flowing and the coverage reporting will evolve as a result.
Thanks for taking the time to dig into the reports :slightly_smiling_face:

**Comment by bhalevy** [comment]
> Please ignore this PR it is for the purpose of testing code coverage in CI 🙂

closing

**Pull request closed without merging**
