### PR TITLE
Update seastar submodule (for sake of #5981)

### LINKED ISSUE #5981: Improve error message where fs.aio-max-nr is too low
*Installation details*
Scylla version (or git commit hash): 3.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

When running Scylla Docker on a server with high number of core, scylla fail to start and generate the following error:
```
scylla: ../../src/core/reactor.cc:1297: seastar::reactor::reactor(unsigned int, seastar::reactor_backend_selector, seastar::reactor_config): Assertion `r >= 0' failed.
```

The root cause is low value of kernel parameter `fs.aio-max-nr`
It would be good to check for this value and generate a more informative error message.

### PR DESCRIPTION
**Pull request by lersek**
~~~
* seastar 83e6cdfd...ec5da7a6 (1):
  > reactor, linux-aio: advise users in more detail on setting aio-max-nr
~~~

Fixes #5981

### CODE REVIEW

**Comment by lersek** [comment]
Example outputs from the Seastar commit can be seen here:
- https://github.com/scylladb/seastar/pull/2396#issuecomment-2303236346
- https://github.com/scylladb/seastar/pull/2396#issuecomment-2312376558

**Comment by mykaul** [comment]
I don't see a reason to remove this from docs. I'm happy we've improved the error message in seastar (which wasn't merged still to scylla, btw).

**Comment by lersek** [comment]
@mykaul

> I don't see a reason to remove this from docs. I'm happy we've improved the error message in seastar (which wasn't merged still to scylla, btw).

This PR consists of two commits; the first commit bumps the seastar submodule reference in scylla, the second commit removes the section in question from the documentation. In a mailing list based development workflow, the maintainer could just pick up the first patch (submodule update) and ignore (drop) the second patch. If the same does not work with github PRs -- do you want me to resubmit with the docs patch dropped?

(I'm not sure how "submodule update only" PRs are handled -- I vaguely recall @tchaikov mentioning that submodule updates per se didn't need to be reviewed, but I may have easily misunderstood @tchaikov.)

**Comment by tchaikov** [comment]
> @mykaul
> 
> > I don't see a reason to remove this from docs. I'm happy we've improved the error message in seastar (which wasn't merged still to scylla, btw).
> 
> This PR consists of two commits; the first commit bumps the seastar submodule reference in scylla, 

@lersek hi László, in general, when we include a change bumping up a submodule in a PR, that PR should only include the commit which include the submodule change. i guess that's matches the reason why we don't need the approvals from the reviewers when merging a submodule change. because, if we include a other commit, that would "taint" the PR, and hence the PR requires the approval from the reviewers so it can be queued in the next branch.

> the second commit removes the section in question from the documentation. In a mailing list based development workflow, the maintainer could just pick up the first patch (submodule update) and ignore (drop) the second patch. If the same does not work with github PRs -- do you want me to resubmit with the docs patch dropped?

i think that'd better.

> 
> (I'm not sure how "submodule update only" PRs are handled -- I vaguely recall @tchaikov mentioning that submodule updates per se didn't need to be reviewed, but I may have easily misunderstood @tchaikov.)

i don't think that you misunderstood me. but i missed a convention that we've been following -- as i explained above.

**Comment by lersek** [comment]
@tchaikov cool, thanks -- I'll drop the second patch and force-push. The seastar submodule update will still resolve #5981; I'll just retitle this PR.

**Comment by lersek** [comment]
updated title and PR desc

**Comment by lersek** [comment]
Conflict due to `d27fdf9f5756` ("Update seastar submodule", 2024-08-27). It updates the seastar checkout that scylla uses, but not quite to the commit that I need. (It bumps the submodule to `83e6cdfd80fa` ("fair_queue: Export the number of times class was activated", 2024-08-25), which is a predecessor of the commit that's needed for this PR -- `ec5da7a606dd` ("reactor, linux-aio: advise users in more detail on setting aio-max-nr", 2024-08-27).) I'll rebase.

**Comment by lersek** [comment]
v3: rebase, update PR desc

**Comment by tchaikov** [comment]
@lersek in addition to the supplementary information you included in the commit message, could you please also use `scripts/refresh-submodules.sh` to update the submodule? see https://github.com/scylladb/scylladb/blob/master/docs/dev/maintainer.md#updating-submodule-references

**Comment by lersek** [comment]
v4: redo per https://github.com/scylladb/scylladb/blob/master/docs/dev/maintainer.md#updating-submodule-references [@tchaikov]

**Comment by lersek** [comment]
Should I also change the target banch on this PR to "next"?

**Comment by lersek** [comment]
> Should I also change the target banch on this PR to "next"?

... assuming that's even possible to do (if not, I might have to close this PR and open a new one, targeting "next").

**Comment by denesb** [comment]
No, master is the correct target.

This PR seems to contain commits from next, please drop them.

**Comment by denesb** [comment]
> v4: redo per https://github.com/scylladb/scylladb/blob/master/docs/dev/maintainer.md#updating-submodule-references [@tchaikov]

When submitting a PR for the submodule change, you need to checkout the `master` branch, not the `next` branch (step 1). This is why you have next commits in your PR. You can just rebase those away: `git rebase HEAD^ --onto=master`.

**Comment by denesb** [comment]
> The referenced section literally starts with the following instruction:
> 
> > Check out the `next` branch and synchronize it using `git pull`
> 
> That's why my v4 here is based on the `next` branch.
> 
> Is the maintainer documentation bogus?

The maintainer documentation is aimed at maintainers for whom committing the submodule update to next is the correct procedure. This is not correct when one wants to open a PR for this.

**Comment by lersek** [comment]
v5: drop commits only in `next` [@denesb]

**Comment by denesb** [comment]
> The maintainer documentation is aimed at maintainers for whom committing the submodule update to next is the correct procedure. This is not correct when one wants to open a PR for this.

To elaborate on this a little bit: the procedure described by the maintainer documentation is the equivalent of bypassing the create pr + merge PR and commit the change to next directly. Normally submodule updates are commited to next directly, although based on some bad experience, I most of the time open a PR to get a CI run on them nowadays.

**Review by denesb — APPROVED** [review]

**Comment by lersek** [comment]
@denesb

> the procedure described by the maintainer documentation is the equivalent of bypassing the create pr + merge PR and commit the change to next directly.

Thanks for the explanation. Step 4 says, "Use `git push` to publish your work"; it wasn't clear to me that "publish your work" means "push to `next`". I took it to mean "open a PR".

**Comment by lersek** [comment]
@denesb

> Step 4 says, "Use `git push` to publish your work"; it wasn't clear to me that "publish your work" meant "push to `next`". I took it to mean "open a PR".

Upon re-reading that section very closely, I understand it. The whole procedure operates right on the local `next` branch (wich tracks the remote `next` branch). Therefore the final `git push` pushes the submodule update commits right back to `origin/next`.

The reason I missed this initially was that step 4 calls the submodule update commits "your work". I would never push "my work" directly to `next` as a maintainer. Pushing directly to `next` is only permitted (even for a maintainer) for patches that have been reviewed / approved / tested / etc. The lack of any validation in those steps (which is something you mention above too), plus the "publish your work" phrasing, strongly imply "publish *for review*". Hence my original interpretation that it meant "open a PR".

**Comment by tchaikov** [comment]
> Should I also change the target banch on this PR to "next"?

ahh, sorry for the misleading comment. i should have just referenced the script. but thought that the document would be better..

**Pull request closed without merging**
