### PR TITLE
Rename .github/ISSUE_TEMPLATE.md to .github/ISSUE_TEMPLATE/bug_report.yml

### PR DESCRIPTION
**Pull request by dani-tweig**
GitHub issue template process has changed.
The issue template file should be replaced and renamed from .github/ISSUE_TEMPLATE.md to .github/ISSUE_TEMPLATE/bug_report.yml

No need to backport this PR.

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]
LGTM

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint Can you please merge this?

**Comment by denesb** [comment]
I don't understand how nothing else has to be updated for this move? Is nothing using this file right now?

**Comment by tchaikov** [comment]
> GitHub issue template process has changed. The issue template file should be replaced and renamed from .github/ISSUE_TEMPLATE.md to .github/ISSUE_TEMPLATE/bug_report.yml
> 
> No need to backport this PR.

would be better to provide more context for this change. GitHub does not change its process in this regard. but probably our process has changed? GitHub allows both 

- single issue template
- multiple issue templates

see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository . so are we going to add more issue templates for the repo?

**Comment by dani-tweig** [comment]
> I don't understand how nothing else has to be updated for this move? Is nothing using this file right now?

@denesb , The former format stopped working. (If you open a new issue now, you will get a black issue)
The instructions in this article works, and this requires a change in the file's location and its extension.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by dani-tweig** [comment]
> so are we going to add more issue templates for the repo?

That is my plan. 
But I will start with more issue templates in the enterprise version first.

**Pull request closed without merging**
