### PR TITLE
scylla_raid_setup: configure SELinux file context

### LINKED ISSUE #19325: [centos9] install without setup of selinux fails on coredump configuration check
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

Scylla can't finish setup on centos9 when `--no-selinux-setup` flag was used

```
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 --setup-nic-and-disks --no-selinux-setup --swap-directory / '
Exit code: 1
Stdout:
Owner UID: 1000 (scylla-test)
Boot ID: 6f33cbb0b1bb448bbf0b72920cc40819
Machine ID: 3b0e2d5c20c14370a70a7f03c4dd1ea0
Hostname: artifacts-centos9-selinux-jenkins-db-node-d57fb40a-0-1
Storage: none
Message: Process 73647 (bash) of user 0 dumped core.
Does not able to detect coredump file, failed to configure systemd-coredump.
Your current Scylla release is 6.1.0~dev while the latest patch release is 6.0.0, update for the latest bug fixes and improvements
coredump setup failed.
Stderr:
Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /usr/lib/systemd/system/scylla-server.service.
Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-scylla.mount → /etc/systemd/system/var-lib-scylla.mount.
Created symlink /etc/systemd/system/local-fs.target.wants/var-lib-systemd-coredump.mount → /etc/systemd/system/var-lib-systemd-coredump.mount.
Created symlink /etc/systemd/system/scylla-server.service.wants/var-lib-systemd-coredump.mount → /etc/systemd/system/var-lib-systemd-coredump.mount.
```

## Impact

User that want to leave selinux enable, can install scylla on this distro

## How frequently does it reproduce?

100%

## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-centos9-selinux-jenkins-db-node-d57fb40a-0-1 (34.138.157.72 | 10.142.0.95) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-9` (gce: undefined_region)

Test: `artifacts-centos9-selinux-test`
Test id: `d57fb40a-da00-4272-9346-4850107c0b0d`
Test name: `scylla-staging/fruch/artifacts-centos9-selinux-test`
Test config file(s):

- [centos9-selinux.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea453de4edfbe2853750ea61131b1ef6d9087190/test-cases/artifacts/centos9-selinux.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d57fb40a-da00-4272-9346-4850107c0b0d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d57fb40a-da00-4272-9346-4850107c0b0d)
- Show all stored logs command: `$ hydra investigate show-logs d57fb40a-da00-4272-9346-4850107c0b0d`

## Logs:
- **db-cluster-d57fb40a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/db-cluster-d57fb40a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/db-cluster-d57fb40a.tar.gz)
- **sct-runner-events-d57fb40a.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-runner-events-d57fb40a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-runner-events-d57fb40a.tar.gz)
- **sct-d57fb40a.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-d57fb40a.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d57fb40a-da00-4272-9346-4850107c0b0d/20240609_150646/sct-d57fb40a.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-centos9-selinux-test/8/)
[Argus](https://argus.scylladb.com/test/f85b0648-41ce-46b0-80a8-f289d6a9b3ab/runs?additionalRuns[]=d57fb40a-da00-4272-9346-4850107c0b0d)
</details>

### PR DESCRIPTION
**Pull request by syuu1228**
On RHEL9, systemd-coredump fails to coredump on /var/lib/scylla/coredump because the service only have write acess with systemd_coredump_var_lib_t. To make it writable, we need to add file context rule for /var/lib/scylla/coredump, and run restorecon on /var/lib/scylla.

Fixes #19325

### CODE REVIEW

**Comment by yaronkaikov** [comment]
@syuu1228 i removed the backport label for `5.4` as it's EOL

**Comment by yaronkaikov** [comment]
@syuu1228 not sure this fix is working. please use your fork to create a repo , you can re-run https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2472/ (already tried), then verify it with https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-selinux-test/

**Comment by syuu1228** [comment]
Ah, this patch is not enough, because we also want to fixup existing /var/lib/scylla while package update.
So we also need fix on scylla_post_install.sh.

**Comment by syuu1228** [comment]
> @syuu1228 not sure this fix is working. please use your fork to create a repo , you can re-run https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/2472/ (already tried), then verify it with https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/artifacts-rocky9-selinux-test/

Okay, I tested the patch on Rocky9 GCE instance but haven't tried on the artifact test.
I will try to find what is the problem.

**Comment by fruch** [comment]
Having links like: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-rocky9-selinux-test/9/

kind of help show what the current situation.

**Comment by syuu1228** [comment]
> Okay, after I tested jenkins test I found the two bugs:
> 
> * restorecon requires "-F" option
> * When systemd package is not updated latest, we also hit this bug [scylla_coredump_setup: fix SELinux configuration for CentOS9 on GCE #19382](https://github.com/scylladb/scylladb/pull/19382)
> 
> I will update PR and run jenkins test again.

Updated PR.
Now trying to test on Jenkins.

**Comment by syuu1228** [comment]
> Updated PR.
> Now trying to test on Jenkins.

The patch is working finely on GCE Rocky9 instance but fails on the artifact test for some reason.
I will investigate why it happens (perhaps there are more SELinux permisson issue or something).

**Comment by syuu1228** [comment]
> The patch is working finely on GCE Rocky9 instance but fails on the artifact test for some reason.
> I will investigate why it happens (perhaps there are more SELinux permisson issue or something).

I just realized that I was specified wrong parameter on the artifact test, so the test did not used RPM repository on byo, it used master repo instead.
After I fixed the parameter, the test passed:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-rocky9-selinux-test/18/

**Review by yaronkaikov — APPROVED** [review]

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint can you please merge?

**Comment by denesb** [comment]
We need a passing CI, just re-kicked it.

**Comment by denesb** [comment]
> [background_reclaim](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/11568/testReport/junit/boost/logalloc_test/background_reclaim) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+background_reclaim)

https://github.com/scylladb/scylladb/issues/15677

**Comment by yaronkaikov** [comment]
> We need a passing CI, just re-kicked it.

This PR changes are not being tested by CI , although i re-kicked it

**Comment by yaronkaikov** [comment]
> > We need a passing CI, just re-kicked it.
> 
> This PR changes are not being tested by CI , although i re-kicked it

@denesb CI passed,

**Comment by yaronkaikov** [comment]
@avikivity @nyh can we merge this?

**Comment by yaronkaikov** [comment]
Note sure how but we didn't backport this to 6.2 and it;s failing , added the tag

**Pull request merged**
