### PR TITLE
dist: drop deprecated AMI parameters on setup scripts

### PR DESCRIPTION
**Pull request by syuu1228**
Since we moved all IaaS code to scylla-machine-image, we nolonger need AMI variable on sysconfig file or --ami parameter on setup scripts, and also never used /etc/scylla/ami_disabled.
So let's drop all of them from Scylla core core.

Related with scylladb/scylla-machine-image#61

### CODE REVIEW

**Comment by syuu1228** [comment]
Note that this would break existing user written script since they may use `scylla_setup --no-bootparam-setup ...`, since "For easily provisioning in a similar environment than this, type:" prompt would suggests to use --no-bootparam-setup.
If we want to avoid that, we must keep `parser.add_argument('--no-bootparam-setup', ...)` line on scylla_setup.

**Review by yaronkaikov — APPROVED** [review]

**Comment by avikivity** [comment]
@vladzcloudius I'd like to merge this for 5.2. Do you see a blocker for it?

Note that we can't keep deprecated options forever, I'm asking if you see useful functionality lost without replacement.

**Comment by vladzcloudius** [comment]
> @vladzcloudius I'd like to merge this for 5.2. Do you see a blocker for it?
> 
> Note that we can't keep deprecated options forever, I'm asking if you see useful functionality lost without replacement.

No, I don't. As long as the default mode remains to be what originally corresponded to `AMI=no` - we are golden.

Another thing that is probably unrelated to this patch is the ability to use precalculated `io_properties.yaml` values for "known platforms" that now moved to `scylla-machine-image` in a non-AMI environment (e.g. installation from .deb packages on one of "known" GCE VMs).

I asked about it some time ago but I never got an answer, @syuu1228 .

**Comment by vladzcloudius** [comment]
@syuu1228 ping

**Pull request closed without merging**
