### PR TITLE
Add rust/Cargo.lock to .gitignore

### PR DESCRIPTION
**Pull request by xemul**
The file appears after build

Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>

### CODE REVIEW

**Comment by michoecho** [comment]
The lock file should be committed, not ignored. That's its entire point.
Of course, it doesn't matter now, since we don't use `rust/` for anything yet.

**Comment by xemul** [comment]
For the record
https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by michoecho** [comment]
> https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

@xemul Did you link it to support ignoring or committing the file? I think we are dealing with the "binary" case here.

**Comment by xemul** [comment]
@michoecho , I've no experience with Rust so far so I don't know if the Cargo.lock should be "just committed as it was generated" or there should be some other changes made in the build process. Maybe at least some documentation telling how to maintain/update one? So I added this link just not to google it again next time :) and I'm fine with either review verdict -- approve or request changes (and "commit as it is generated")

**Comment by michoecho** [comment]
I don't have non-toy Rust experience either, but it's not a Rust-specific thing — it's a package management thing. E.g. golang does the same.

Each component has a hand-written file (here: `Cargo.toml`) which describes its desired dependency versions (e.g. ">2.1"), picked for their functionality, and there's a machine-generated file which chooses some exact versions which fulfill the needs of all components. The exact versions should be checked in to avoid the build breaking when some dependency updates to a version which in theory is compatible with needs, but breaks something inadvertently.

We have already manually implemented this in Scylla with dbuild. You have an `install-dependencies.sh` which specifies the dependencies manually, and you have the `tools/toolchain/image` file which references a specific set of dependencies that has been verified to work.

And the maintenance process for `Cargo.lock` should be the same as for `tools/toolchain/image`: a maintainer re-generates it when some interesting dependency updates appear, tests the program with new dependencies, and if there's no problems, the newly generated image/lockfile is committed.

**Comment by michoecho** [comment]
Though none of this matters until we actually use the Rust for something useful. So you can just gitignore it not to waste time and we will pester the person which pushes the first Rust module with this.

**Review by michoecho — APPROVED** [review]

**Comment by michoecho** [comment]
Well, it doesn't matter unless the authors of our only dependency, `cxx`, do a malicious update. Which is not unheard of...

**Review by denesb — APPROVED** [review]
Adding to `.gitignore` just documents the current practice. This PR doesn't change anything.

**Pull request closed without merging**
