### PR TITLE
scylla-gdb: Evaluate LSA object sizes dynamically

### PR DESCRIPTION
**Pull request by xemul**
The lsa-segment command tries to walk LSA segment objects by decoding their descriptors and (!) object sizes as well. Some objects in LSA have dynamic sizes, i.e. those depending on the object contents. The script tries to drill down the object internals to get this size, but bad news is that nowadays there are many dynamic objects that are not covered. Once stepped upon unsupported object, scylla-gdb likely stops because the "next" descriptor happens to be in the middle of the object and its parsing throws.

This patch fixes this by taking advantage of the virtual size() call of the migrate_fn_type all LSA objects are linked with (indirectly). It gets the migrator object, the LSA object itself and calls

  ((migrate_fn_type*)<migrator_ptr>)->size((const void*)<object_ptr>)

with gdb. The evaluated value is the live dynamic size of the object.

fixes: #11792
refs: #2455

Signed-off-by: Pavel Emelyanov <xemul@scylladb.com>

### CODE REVIEW

**Review by denesb — COMMENTED** [review]
This will only work for live processes (you can't execute code in coredumps).
This is fine -- nothing we can do about it -- yet it would be good to preserve some level of functionality (even if much reduced) in coredumps. How will this command currently behave in a coredump?

**Comment by xemul** [comment]
Currently it steps on "unsupported" object, gets wrong size of it, then picks up next bytes, tries to decode them as object descriptor and, very likely, throws, because these "random" bytes don't have bits in places it expects.

Unsupported objects are radix/B/B+ trees nodes, often leaf ones with cells/rows/partitions embedded in.

**Comment by denesb** [comment]
Ok, so there is no regression. It doesn't work currently either.

**Comment by xemul** [comment]
In fact gdb could run migrate_fn_type::size(). All of them are pure functions that don't need anything that's missing in the core. Oh, well...

**Comment by avikivity** [comment]
There are xfuncs that allow running functions on cores (you have to reimplement them in Python, but the experience is better).

**Pull request closed without merging**
