### PR TITLE
tools/toolchain/image: update python driver (implicit)

### PR DESCRIPTION
**Pull request by denesb**
Fixes: https://github.com/scylladb/scylladb/issues/17662

### CODE REVIEW

**Comment by avikivity** [comment]
Why does it need backports?

**Comment by denesb** [comment]
> Why does it need backports?

5.2 and 5.4 also suffer from the driver bug. They need regenerated toolchain too.
Maybe not a backport in a strict sense.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/commit/fd7d57b9fa264afe1fb2c3ada6bbc664c367d4bc is in 5.4.

**Comment by denesb** [comment]
https://github.com/scylladb/scylladb/commit/aca50c46b7c2da4e18268038e389a02e72b182fb is in 5.2.

**Pull request closed without merging**
