### PR TITLE
RFC: Store and propagage GC timestamp markers from commitlog

### LINKED ISSUE #14870: Writes in commitlog segments, that are pinned by another table, can be resurrected
Commitlog segments are only discarded when all tables have released their respective replay handles, that point to said segment. It is possible that one table, that receives very little writes, have very long lived memtables, that pin commitlog segments, containing writes to other tables. It is possible that these writes are covered with a tombstone, written in a later write. This tombstone can get to disk, be compacted and purged, while the commitlog segment containing the earlier (covered) writes is still pinned. A later unclean restart, can cause these segments to be replayed, resurrecting the data.

### LINKED ISSUE #14909: replica-side load shedding is not aggressive enough
We have observed, in multiple issues that when a shard on a replica is overloaded, it breaks down completely, throughput collapses, latencies go through the roof and the node/shard can even become completely unresponsive to new connection attempts.
Example issue: https://github.com/scylladb/scylladb/issues/13759.

I believe the root cause is that we have almost nonexistent load shedding on the replica side. When reads arrive, they have to wait for admission on the reader concurrency semaphore. If the node is overloaded, the reads will be queued. They can time out while in the queue, but will not time out once admitted. Once the shard is sufficiently loaded, it is possible that most queued reads will time out, because the average time it takes to for a queued read to be admitted is around that of the timeout. Reads admitted will possibly also only finish after their timeout expires.

We have coordinator side load-shedding, but when only a single replica is pushed over the limit, this is not enough. With speculative reads, the overloaded replica will be worked around, the other nodes shouldering the load. But the overloaded replica will be continued to be picked for new reads and therefore it will be hammered.

I think we need to do the following, to address this:
* keep mean time-to-finish statistic in semaphore
* when qeueing a read: if `mean_time * queue_size >= timeout * X` (I propose 0.5 for `X`), reject the read on the spot
* if a read times out in the queue: check the above condition again (`mean_time` could have changed since the queue was last checked), if it fails, kill reads from the front of the queue, such that the invariant is maintained
* add timeout check for all ongoing reads, maybe all readers should check timeout on each `fill_buffer()` call

### PR DESCRIPTION
**Pull request by elcallio**
Yet another approach to Fixes #14870

(Originally suggested by @avikivity). Use commit log stored GC clock min positions to narrow compaction GC bounds.
(Still requires augmented manual flush:es with extensive CL clearing to pass various dtest, but this does not affect "real" execution). 

Adds a lowest timestamp of GC clock whenever a CF is added to a CL segment the first time. Because GC clock is wall 
clock time and only connected to TTL (not cell/row timestamps), this gives a fairly accurate view of GC low bounds
per segment. This is then (in a rather ugly way) propagated to tombstone_gc_state to narrow the allowed GC bounds for 
a CF, based on what is currently left in CL. 

Note: this is a rather unoptimized version - no caching or anything. But even so, should not be excessively expensive, 
esp. since various other code paths already cache the results.

### CODE REVIEW

**Comment by elcallio** [comment]
Maint, please retrigger CI. It seems to have spuriously failed... (all tests verified locally at least)

**Comment by tgrabiec** [comment]
You probably meant a different issue than https://github.com/scylladb/scylladb/issues/14909?

**Review by denesb — APPROVED** [review]
I like this solution the best so far. I think it is pretty clean and does not introduce any considerable overhead.

**Comment by elcallio** [comment]
@avikivity : [https://github.com/scylladb/scylla-dtest/pull/3352 (merged)](https://github.com/scylladb/scylla-dtest/commit/9380e73204a012c94bb0fb1ce67efef3d53a598d)

**Comment by avikivity** [comment]
Good. I prefer tests in test.py (they have almost the same capability now).

**Comment by alezzqz** [comment]
guys, seems this commit https://github.com/scylladb/scylladb/commit/43a7d83fd0f68fe87cb8c49d9bb6bb169fc042a6
makes tombstones compaction on read unworkable:
`cache_flat_mutation_reader::copy_from_cache_to_buffer`
`_gc_before is always >= tomb.max_deletion_time()`

**Comment by mykaul** [comment]
@elcallio - please look into the above.

**Comment by elcallio** [comment]
https://github.com/scylladb/scylladb/commit/43a7d83fd0f68fe87cb8c49d9bb6bb169fc042a6 only adds an optional callback. It does not set it to anything. The result of that exact commit should just be a few extra cycles. I assume the "unworkable" part relates to the following patches, that actually adds a callback? And if so, in what way?

**Comment by elcallio** [comment]
Note that tombstone compaction requires (now) that potentially resurrecting info in commit log has been cleaned out before it can actually delete anything. Hence the timestamp callbacks. It is quite possible that previous aggressive compaction might be stifled a bit here. This is unfortunately by design.

**Comment by alezzqz** [comment]
it makes unworkable this patch https://github.com/scylladb/scylladb/commit/ca4e7f91c6f849c9437c0e44a2246f9a03f0af82
when tombstones stay in cache indefinitely (see #6033)

**Comment by denesb** [comment]
> it makes unworkable this patch [ca4e7f9](https://github.com/scylladb/scylladb/commit/ca4e7f91c6f849c9437c0e44a2246f9a03f0af82) when row/range tombstones stay in cache indefinitely (see #6033)

Can you please open a new issue for this bug, that you discovered? Discussing on a closed pull-request will mean that many people will miss notifications related to this.

**Pull request merged**
