### PR TITLE
[NOMERGE] Update tools/java/ submodule

### PR DESCRIPTION
**Pull request by denesb**
* tools/java/ b810e8b0...6a442143 (1):
  > install-dependencies.sh: s/python/python3/

[botond: regenerate frozen toolchain image]

### CODE REVIEW

**Comment by denesb** [comment]
@scylladb/scylla-maint please queue promtly, otherwise somebody else may update the java submodule by accident, without the toolchain image which should go with it.

**Comment by denesb** [comment]
> @scylladb/scylla-maint please queue promtly, otherwise somebody else may update the java submodule by accident, without the toolchain image which should go with it.

Hmm, actually we are allowed to queue our own submodule updates and toolchain regeneration PRs, so I will queue this myself.

**Comment by yaronkaikov** [comment]
@denesb this change is breaking `aarch64` with the following error
```
14:48:24  + bash -c 'set -o pipefail; /jenkins/workspace/scylla-master/next/scylla/tools/toolchain/dbuild    -- ./configure.py --date-stamp 20240425 --debuginfo 1 --tests-debuginfo 1 2>&1 | tee output-build-aarch64.txt'
14:48:24  Trying to pull docker.io/scylladb/scylla-toolchain:fedora-38-20240324...
14:48:24  Error: choosing an image from manifest list docker://scylladb/scylla-toolchain:fedora-38-20240324: no image found in image index for architecture arm64, variant "v8", OS linux
```

**Comment by denesb** [comment]
Dequeued.

**Comment by denesb** [comment]
We cannot regenerate toolchains at the moment. Marking as NOMERGE.

**Comment by denesb** [comment]
Replaced by https://github.com/scylladb/scylladb/pull/18790.

**Pull request closed without merging**
