### PR TITLE
test: test_crash_coordinator_before_streaming: enable TRACE for `raft_topology` logger

### PR DESCRIPTION
**Pull request by kbr-scylla**
Issue scylladb/scylladb#21114 reported that sometimes during the test we timeout when waiting for node to restart after it was killed. Preliminary investigation showed that the node appears to be hanging inside `topology_state_load`, while holding `token_metadata` lock, which prevents `join_topology` from progressing.

Enable TRACE level logging for `raft_topology` so we get more accurate info where inside `topology_state_load` the hang happens, once the problem reproduces again in CI.

Test improvement, no need to backport.

### CODE REVIEW

**Review by denesb — APPROVED** [review]

**Comment by kbr-scylla** [comment]
Hmm. We killed coordinator during bootstrap. And the bootstrapping node got stuck waiting for the bootstrap request sent to the coordinator to finish.

In the usual successful runs it sees that the request failed (due to the newly elected coordinator) and shuts down:
```
ERROR 2024-10-25 14:43:47,181 [shard 0:main] init - Startup failed: std::runtime_error (Bootstrap failed. See earlier errors (Rolled back: global_token_metadata_barrier failed in write_both_read_old state std::runtime_error (raft topology: exec_global_command(barrier) failed with seastar::rpc::closed_error (connection is closed))))
```

But here the new coordinator got stuck somehow
```
INFO  2024-10-23 20:28:07,985 [shard 0: gms] raft_topology - executing global topology command barrier, excluded nodes: {}
DEBUG 2024-10-23 20:28:07,985 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to e8232a16-1817-4701-8c4f-c037d1bd94ac/127.224.182.45
DEBUG 2024-10-23 20:28:07,986 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 96d77381-1404-4afd-886f-551159979c78/127.224.182.16
DEBUG 2024-10-23 20:28:07,986 [shard 0: gms] raft_topology - topology cmd rpc barrier is called
DEBUG 2024-10-23 20:28:07,986 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 5ad9d8ea-fcc3-4ce4-ba3b-b0c59a91c1ee/127.224.182.1
DEBUG 2024-10-23 20:28:07,986 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to fc78fc2a-9375-4a4d-9d8f-ebf6cfcba766/127.224.182.31
DEBUG 2024-10-23 20:28:07,986 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 1e66bcee-a6f6-466f-91c5-341a6bed493e/127.224.182.15
INFO  2024-10-23 20:29:07,867 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:29:37,867 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:29:37,868 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:30:07,868 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:30:07,868 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:30:37,868 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:30:37,868 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:31:07,868 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:31:07,868 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:31:37,869 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:31:37,869 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:32:07,869 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:32:07,869 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
DEBUG 2024-10-23 20:32:37,869 [shard 0: gms] raft_topology - raft topology: Tablet load stats refresher aborted
INFO  2024-10-23 20:32:37,869 [shard 0: gms] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 token owners
```

why would enabling more logging cause it to get stuck though?

**Comment by kbr-scylla** [comment]
Usually the barrier fails because of rpc::closed_error
```
INFO  2024-10-25 14:43:44,934 [shard 0: gms] raft_topology - executing global topology command barrier, excluded nodes: {}
DEBUG 2024-10-25 14:43:44,934 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 85cce807-2dd6-42d5-ba85-3f92d29d6c4a/127.181.234.5
DEBUG 2024-10-25 14:43:44,934 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 673be2a3-7e3e-43e4-87e8-e6a335db9daf/127.181.234.6
DEBUG 2024-10-25 14:43:44,934 [shard 0: gms] raft_topology - topology cmd rpc barrier is called
DEBUG 2024-10-25 14:43:44,934 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to b5da3cf2-ae56-4771-8040-426b051ad5df/127.181.234.2
DEBUG 2024-10-25 14:43:44,935 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 42d45586-ddf5-4c2a-adab-b7a4d649663d/127.181.234.3
DEBUG 2024-10-25 14:43:44,935 [shard 0: gms] raft_topology - send barrier command with term 4 and index 2 to 27ad4409-f24d-4d8c-882c-357c99b82607/127.181.234.4
ERROR 2024-10-25 14:43:44,970 [shard 0: gms] raft_topology - transition_state::write_both_read_old, global_token_metadata_barrier failed, error std::runtime_error (raft topology: exec_global_command(barrier) failed with seastar::rpc::closed_error (connection is closed))
```

the connection to the node that we crashed (previous coordinator) gets closed.
We can see it in other RPCs and connections as well:
```
ERROR 2024-10-25 14:43:44,885 [shard 1:strm] rpc - client 127.181.234.3:7000: client connection dropped: recv: Connection reset by peer
ERROR 2024-10-25 14:43:44,885 [shard 0:strm] rpc - client 127.181.234.3:7000: client connection dropped: recv: Connection reset by peer
ERROR 2024-10-25 14:43:44,886 [shard 1:main] rpc - client 127.181.234.3:7000: client connection dropped: recv: Connection reset by peer
WARN  2024-10-25 14:43:44,887 [shard 1:strm] gossip - failure_detector_loop: Send echo to node 127.181.234.3, status = failed: seastar::rpc::closed_error (connection is closed)
```


but in this run, we didn't get `closed_error`. Looks like the connection is kept open, even after the process crashed? And for example the gossiper failure detector RPCs gets a timeout instead of `closed_error`:
```
WARN  2024-10-23 20:28:07,855 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.224.182.31, status = failed: seastar::rpc::timeout_error (rpc call timed out)
```

The barrier RPC does not have a timeout. So it gets stuck forever.

@gleb-cloudius what could cause this behavior? Why do we usually have a `closed_error` when the process on other side gets killed, but not in this case? This is probably some low-level TCP stuff.

And what does it have to do with TRACE logging

**Comment by kbr-scylla** [comment]
logs from the failed run
[test_kill_coordinator_during_op.5.debug.5.zip](https://github.com/user-attachments/files/17522878/test_kill_coordinator_during_op.5.debug.5.zip)

**Comment by kbr-scylla** [comment]
The failure could also be caused simply by the fact that we apparently ran out of space on the Jenkins node when we were running these tests:
```
[2024-10-23T17:23:06.836Z] [17/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.8 98.96s
[2024-10-23T17:23:09.990Z] [18/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.7 102.97s
[2024-10-23T17:24:05.536Z] [19/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.9 95.79s
[2024-10-23T17:25:01.279Z] [20/30]    topology_experimental_raft   dev   [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.10 98.41s
[2024-10-23T17:25:01.971Z] [21/30]    topology_experimental_raft  debug  [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.2 319.96s
[2024-10-23T17:25:01.972Z] [22/30]    topology_experimental_raft  debug  [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.4 319.47s
[2024-10-23T17:25:04.002Z] [23/30]    topology_experimental_raft  debug  [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.1 322.22s
[2024-10-23T17:25:29.100Z] [24/30]    topology_experimental_raft  debug  [ PASS ] topology_experimental_raft.test_crash_coordinator_before_streaming.3 343.92s
[2024-10-23T17:34:44.787Z] /jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py:1485: RuntimeWarning: coroutine 'ScyllaClusterManager._mark_dirty' was never awaited
[2024-10-23T17:34:44.787Z]   self._mark_dirty(None)
[2024-10-23T17:34:44.787Z] RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[2024-10-23T17:36:48.257Z] Test topology_experimental_raft/test_crash_coordinator_before_streaming pre-check failed: [Errno 28] No space left on device
[2024-10-23T17:36:48.257Z] Server log of the first server:
[2024-10-23T17:36:48.257Z] 
[2024-10-23T17:36:48.257Z] Test topology_experimental_raft/test_crash_coordinator_before_streaming pre-check failed: [Errno 28] No space left on device
[2024-10-23T17:36:48.258Z] Server log of the first server:
[2024-10-23T17:36:48.258Z] 
[2024-10-23T17:36:48.258Z] Stopping S3 mock server
[2024-10-23T17:36:48.258Z] [Errno 28] No space left on device
[2024-10-23T17:36:48.258Z] Traceback (most recent call last):
[2024-10-23T17:36:48.258Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 2153, in workaround_python26789
[2024-10-23T17:36:48.258Z]     code = await main()
[2024-10-23T17:36:48.258Z]            ^^^^^^^^^^^^
[2024-10-23T17:36:48.258Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1860, in main
[2024-10-23T17:36:48.258Z]     await run_all_tests(signaled, options)
[2024-10-23T17:36:48.258Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1575, in run_all_tests
[2024-10-23T17:36:48.258Z]     failed += await reap(done, pending, signaled)
[2024-10-23T17:36:48.258Z]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-23T17:36:48.258Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1537, in reap
[2024-10-23T17:36:48.258Z]     result = coro.result()
[2024-10-23T17:36:48.258Z]              ^^^^^^^^^^^^^
[2024-10-23T17:36:48.259Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 243, in run
[2024-10-23T17:36:48.259Z]     await test.run(options)
[2024-10-23T17:36:48.259Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1097, in run
[2024-10-23T17:36:48.259Z]     await manager.start()
[2024-10-23T17:36:48.259Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1291, in start
[2024-10-23T17:36:48.259Z]     await self.site.start()
[2024-10-23T17:36:48.259Z]   File "/usr/lib64/python3.12/site-packages/aiohttp/web_runner.py", line 160, in start
[2024-10-23T17:36:48.259Z]     self._server = await loop.create_unix_server(
[2024-10-23T17:36:48.259Z]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-23T17:36:48.259Z]   File "/usr/lib64/python3.12/asyncio/unix_events.py", line 319, in create_unix_server
[2024-10-23T17:36:48.259Z]     sock.bind(path)
[2024-10-23T17:36:48.259Z] OSError: [Errno 28] No space left on device
```


Although the timestamps are different. Weird.

But due to out-of-space, I think it just makes sense to rerun CI.

**Comment by kbr-scylla** [comment]
New CI job: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12784/

**Comment by gleb-cloudius** [comment]
> @gleb-cloudius what could cause this behavior? Why do we usually have a closed_error when the process on other side gets killed, but not in this case? This is probably some low-level TCP stuff.

We will not get close error immediately either because an entire machine dies (which  is not the case here since all the processes run on the same machine) or the process did not die but stuck for some reason. All other cases we suppose to get close error especially if there is something to send (but IIRC we enable keep alive on all our sockets, so we have always something to send).

**Comment by avikivity** [comment]
Can it not be reproduced locally and fixed?

**Comment by kbr-scylla** [comment]
it wouldn't reproduce just by brute force, but last Friday I actually managed to reproduce it with tactical sleep: https://github.com/scylladb/scylladb/issues/21114#issuecomment-2438079090

Nevertheless the TRACE logging for raft_topology won't hurt.

**Comment by kbr-scylla** [comment]
> We will not get close error immediately either because an entire machine dies (which is not the case here since all the processes run on the same machine) or the process did not die but stuck for some reason. All other cases we suppose to get close error especially if there is something to send (but IIRC we enable keep alive on all our sockets, so we have always something to send).

Should we perhaps introduce a timeout in our topology coordinator commands to handle the dying machine case?

**Comment by kbr-scylla** [comment]
@denesb CI passed, could you merge please?

**Comment by gleb-cloudius** [comment]
> > We will not get close error immediately either because an entire machine dies (which is not the case here since all the processes run on the same machine) or the process did not die but stuck for some reason. All other cases we suppose to get close error especially if there is something to send (but IIRC we enable keep alive on all our sockets, so we have always something to send).
> 
> Should we perhaps introduce a timeout in our topology coordinator commands to handle the dying machine case?

It is not that the RPC will hang forever in this case. The connection will eventually be closed (in 3 minutes or so). Hmm, actually when failure detector will mark a node as down it suppose to kill all connection to it, so the RPC should fail simultaneously with DOWN notification in the log. Is there one?

**Comment by gleb-cloudius** [comment]
Also we cannot really add a timeout to all the commands since some commands are long running. And some you would not expect to be long running may also be (like barrier_and_drain) and you do not want to abort an operation just because an RPC took 1 second longer than you expected.

**Comment by kbr-scylla** [comment]
> Hmm, actually when failure detector will mark a node as down it suppose to kill all connection to it, so the RPC should fail simultaneously with DOWN notification in the log. Is there one?

```
WARN  2024-10-23 20:28:07,855 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.224.182.31, status = failed: seastar::rpc::timeout_error (rpc call timed out)
INFO  2024-10-23 20:28:07,855 [shard 0:strm] gossip - failure_detector_loop: Mark node 127.224.182.31 as DOWN
INFO  2024-10-23 20:28:07,856 [shard 0:strm] gossip - InetAddress fc78fc2a-9375-4a4d-9d8f-ebf6cfcba766/127.224.182.31 is now DOWN, status = NORMAL
```

(scylla-129.log)

so there was a DOWN notification. But still the global barrier failed. Maybe a new connection was established. But hard to say what exactly happened and what's supposed to happen because the machine ran out of disk.

**Comment by kbr-scylla** [comment]
> If the process is stuck it is possible that we mark it as down and next RPC hangs.

But the RPC won't hang forever due to TCP timeout, which will kill the connection causing `closed_error`, correct?

**Comment by gleb-cloudius** [comment]
> > If the process is stuck it is possible that we mark it as down and next RPC hangs.
> 
> But the RPC won't hang forever due to TCP timeout, which will kill the connection causing `closed_error`, correct?

No. If the process is stuck (for instance got SIGSTOP), the timeout will never happen. I am having a deja-vu. I remember we already discussed a test that made one of the nodes to STOP and expected coordinator's RPC to timeout.

**Comment by avikivity** [comment]
> it wouldn't reproduce just by brute force, but last Friday I actually managed to reproduce it with tactical sleep: [#21114 (comment)](https://github.com/scylladb/scylladb/issues/21114#issuecomment-2438079090)
> 
> Nevertheless the TRACE logging for raft_topology won't hurt.

Won't it slow down tests?

**Comment by kbr-scylla** [comment]
> Won't it slow down tests?

Not substantially, these are still rare events and the resulting log file is still small.

**Pull request closed without merging**
