### PR TITLE
tasks: move methods from task_manager to source file

### PR DESCRIPTION
**Pull request by Deexie**
Methods from tasks::task_manager and nested classes are moved to source file.

### CODE REVIEW

**Comment by denesb** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3136/

```
19:00:17  ERROR: Could not get unified-pack-url-x86_64 from relocatable metadata file
19:00:17  Finished: FAILURE
```
@benipeled

**Comment by denesb** [comment]
@Deexie also please rebase, there are conflicts.

**Comment by benipeled** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3136/
> 
> ```
> 19:00:17  ERROR: Could not get unified-pack-url-x86_64 from relocatable metadata file
> 19:00:17  Finished: FAILURE
> ```
> 
> @benipeled

Caused by https://github.com/scylladb/scylla-pkg/pull/3159 - I dequeued it - you can retrigger the CI

**Comment by avikivity** [comment]
> > > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3136/
> > 
> > 
> > ```
> > 19:00:17  ERROR: Could not get unified-pack-url-x86_64 from relocatable metadata file
> > 19:00:17  Finished: FAILURE
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @benipeled
> 
> Caused by [scylladb/scylla-pkg#3159](https://github.com/scylladb/scylla-pkg/pull/3159) - I dequeued it - you can retrigger the CI

@benipeled CI should use scylla-pkg master IMO, not next. CI for pull requests should test just the code introduced by the pull requests.

**Comment by benipeled** [comment]
> > > > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3136/
> > > 
> > > 
> > > ```
> > > 19:00:17  ERROR: Could not get unified-pack-url-x86_64 from relocatable metadata file
> > > 19:00:17  Finished: FAILURE
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @benipeled
> > 
> > 
> > Caused by [scylladb/scylla-pkg#3159](https://github.com/scylladb/scylla-pkg/pull/3159) - I dequeued it - you can retrigger the CI
> 
> @benipeled CI should use scylla-pkg master IMO, not next. CI for pull requests should test just the code introduced by the pull requests.

yes, it runs from pkg:master (except when we have some critical bug, so it temporarily changed to next),
The problem was a change in a pkg function uses by CI - fetch package metadata filed and package from s3
/dequeued/revert/

**Comment by Deexie** [comment]
- rebased

**Pull request closed without merging**
