### PR TITLE
test_fencing: disable the tablet balancer earlier

### PR DESCRIPTION
**Pull request by gusev-p**
To cause the stale topology exception the test reads the version from the last bootstrapped host and assigns its decremented value to version and `fence_version` fields of `system.topology`. The test assumes that `version == fence_version` here, if version is greater than `fence_version` we won't get state topology exception in this setup. Tablet balancer can break this -- it may increment the version after the last node is bootstrapped.

Fix this by disabling the tablet balancer earlier.

fixes https://github.com/scylladb/scylladb/issues/17807

### CODE REVIEW

**Comment by gusev-p** [comment]
```
Traceback (most recent call last):
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 93, in <module>
    main()
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 89, in main
    sync_labels(repo, args.number, args.label, args.action, args.is_issue)
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 66, in sync_labels
    linked_prs_or_issues = get_linked_issues_based_on_pr_body(repo, number)
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 54, in get_linked_issues_based_on_pr_body
    raise RuntimeError("No regex matches found in the body!")
RuntimeError: No regex matches found in the body!
Error: Process completed with exit code 1.
```

@yaronkaikov

**Comment by yaronkaikov** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 93, in <module>
>     main()
>   File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 89, in main
>     sync_labels(repo, args.number, args.label, args.action, args.is_issue)
>   File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 66, in sync_labels
>     linked_prs_or_issues = get_linked_issues_based_on_pr_body(repo, number)
>   File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 54, in get_linked_issues_based_on_pr_body
>     raise RuntimeError("No regex matches found in the body!")
> RuntimeError: No regex matches found in the body!
> Error: Process completed with exit code 1.
> ```
> 
> @yaronkaikov

I have a fix almost ready https://github.com/scylladb/scylladb/pull/17920

**Comment by kbr-scylla** [comment]
> The hypothesis is that this leadership change somehow reverts the effects of set_version and/or set_fence_version, and the expected 'stale topology exception' is not thrown on writes.

Is the hypothesis plausible? You said you couldn't confirm it. If so, we need another hypothesis.

**Comment by gusev-p** [comment]
> > The hypothesis is that this leadership change somehow reverts the effects of set_version and/or set_fence_version, and the expected 'stale topology exception' is not thrown on writes.
> 
> Is the hypothesis plausible? You said you couldn't confirm it. If so, we need another hypothesis.

It's plausible since all `test_fence_writes` failures on CI have leadership changes in the logs. It's highly unlikely that this is a coincidence. We can confirm just by merging this PR and seeing if the problem goes away.

**Comment by kbr-scylla** [comment]
> It's plausible since all test_fence_writes failures on CI have leadership changes in the logs. 

If there is no code path that would update fence version triggered by leadership change then it's not plausible. If it's leadership change then there must be such a code path.

**Comment by gusev-p** [comment]
> > It's plausible since all test_fence_writes failures on CI have leadership changes in the logs.
> 
> If there is no code path that would update fence version triggered by leadership change then it's not plausible. If it's leadership change then there must be such a code path.

I don't know such code path. Why is this important? The ticket was about `test_fencing.py` being flaky, this PR should help with that.

**Comment by gusev-p** [comment]
new version:
  * leadership change doesn't actually mater, in many successful test runs on arm/debug leadership change happens when the third node is restsarted;
  * move the `disable_tablet_balancing` earlier.

**Review by kbr-scylla — APPROVED** [review]

**Pull request closed without merging**
