### PR TITLE
Add directory change instruction

### PR DESCRIPTION
**Pull request by tenghuanhe**
Add directory change instruction while building scylla

### CODE REVIEW

**Comment by denesb** [comment]
Before we can merge your pull-request, you need to sign our CLA, as explained here: https://github.com/scylladb/scylladb/blob/master/CONTRIBUTING.md#contributing-code-to-scylla.

**Comment by tenghuanhe** [comment]
Hi @denesb thank you for reminding, already singed

**Comment by bhalevy** [comment]
@scylladb/scylla-maint ping

**Review by nyh — APPROVED** [review]

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Pull request closed without merging**
