### PR TITLE
test/topology: add --request-timeout option

### PR DESCRIPTION
**Pull request by tchaikov**
the default 200 second request_timeout might be too long in the manual tests. for instance, when the test completes, the python driver could still be trying to establish connections to the server, and when we shutdown the driver when teardown the test, the driver blocks on the connection in vain for up to 200 seconds, as the cluster is already down, until timeout expires. this test cycle is quite long.

so, in this change, an other option is added to configure the timeout, so one can override the default 200 seconds by changing the per test's pytest.ini like
```ini
[pytest]
addopts = --request-timeout=10
```

the existing behavior is preserved, so the default value of `--request-timeout` is still 200.

### CODE REVIEW

**Comment by tchaikov** [comment]
@asias could you please help review this change?

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help review this change?

**Comment by kbr-scylla** [comment]
> the default 200 second request_timeout might be too long in the manual tests. for instance, when the test completes, the python driver could still be trying to establish connections to the server, and when we shutdown the driver when teardown the test, the driver blocks on the connection in vain for up to 200 seconds, as the cluster is already down, until timeout expires. this test cycle is quite long.

Huh, so that is the cause of https://github.com/scylladb/python-driver/issues/172? Which was fixed by https://github.com/scylladb/python-driver/pull/292, it should be no longer happening.

@tchaikov do you still think this will be useful?

**Comment by kbr-scylla** [comment]
> Huh, so that is the cause of https://github.com/scylladb/python-driver/issues/172?

cc @sylwiaszunejko perhaps you could confirm

**Comment by tchaikov** [comment]
@kbr-scylla hi Kamil, i didn't know we had an issue for this. thank you. so it's not necessary anymore. and the driver-side fix is much better than mine.

**Comment by asias** [comment]
@sylwiaszunejko @kbr-scylla when will this fix (https://github.com/scylladb/python-driver/pull/292) be available in dbuild so people run test.py will not hit this issue ?

**Comment by Lorak-mmk** [comment]
> > @sylwiaszunejko @kbr-scylla when will this fix ([scylladb/python-driver#292](https://github.com/scylladb/python-driver/pull/292)) be available in dbuild so people run test.py will not hit this issue ?
> 
> @Lorak-mmk any chance for yet another driver release? 😅

Do you need it urgently or can I do it on Sunday?

**Comment by kbr-scylla** [comment]
not urgent, we lived it for many months, we can live for few days more

**Comment by Lorak-mmk** [comment]
3.26.6 released, you can update dbuild

**Pull request closed without merging**
