### PR TITLE
test/pylib: scylla_cluster: don't uninstall servers removed by `server_remove`

### PR DESCRIPTION
**Pull request by kbr-**
`ScyllaCluster` has a `server_remove` function which shuts down the server and 'removes' it from the `ScyllaCluster`'s set of servers so it cannot be brought back again by the cluster and the test that uses it.

However, it does not actually remove the server from the Scylla cluster. It only removes it from the test framework and shuts down the corresponding Scylla node. The other nodes in the cluster know about the server.

`server_remove` would `uninstall()` the `ScyllaServer`, which caused its IP to be released into `host_registry`, which means it could be reused by other clusters in other tests.

It could happen that after a test 'removed' a server (with `server_remove`), another test would start with a cluster that reused this server's IP; the tests would then run concurrently. The cluster from the old test would then contact the new server with the old IP in the new cluster, and weird things would happen. The driver session from the old test would contact the new server, considering it to be a part of the cluster. This would cause, for example, the test to fail on cleanup when it tried to drop the test keyspace - if it used the new server with the old IP to do that.

Another effect of `uninstall()` in `server_remove` was losing the removed server's logs and work directories. If the test that did `server_remove` failed, these logs and workdirs could be useful for analysis.

We fix all this by not `uninstall`ing the server in `server_remove`. Thus its IP won't be released until the end of the test that uses the cluster and its logs and workdirs won't be cleared.

Note: a side effect of this change is that we no longer `uninstall` servers in any other situation than suite cleanup (i.e. at the end of the entire test run). There is a `ScyllaCluster.uninstall` function which was probably intended to be used when we released a cluster (it calls `ScyllaServer.uninstall`) but that function is not used anywhere, not even when we get rid of a dirty cluster.

### CODE REVIEW

**Review by kostja — APPROVED** [review]

**Review by alecco — APPROVED** [review]
LGTM

**Review by nyh — CHANGES_REQUESTED** [review]
In general I approve the code change, but I think that if you needed to write a whole page of explanation of what "remove" did wrong before and nobody noticed - then you also need a comment on the server_remove() function explaining exactly what it does or doesn't do, so users will know what actually gets removed and what doesn't get removed.
"server_remove()" is currently documented as "Remove a specified server" - and that's it :-) Does "removing" a node kill the Scylla process it? Is its data streamed to other nodes (as in nodetool decomission) first or not? Is it removed from the ring or not? Is its logs removed? What does this function wait for (does it wait for other nodes to notice? For this driver to notice?) None of this is explained.

I think I specifically mentioned this in my review of one of the patches that added this or other functions, but maybe I was too lenient in my clicking "approve" anyway - so this time I won't  ;-)

**Comment by kbr-** [comment]
@nyh thanks for saying this, I agree.

In fact I think this function makes little sense in the first place. From what I understand it's basically a placeholder and in the future it's supposed to call `removenode`, so it will really *remove the node from the cluster*. But right now it doesn't do that, it just shuts the node down and forgets about it (but it's still part of the Scylla cluster). What's the point? I don't see it.

I'll add a comment.

**Comment by alecco** [comment]
Perhaps rename it to delete?

**Comment by kbr-** [comment]
But what is the purpose?
What is this supposed to test?

The server is not "removed" or "deleted" from the point of view of the Scylla cluster or from the point of view of the driver. Only from the point of view of the framework.

I would prefer to just get rid of this function and the corresponding test completely.

**Comment by nyh** [comment]
> But what is the purpose? What is this supposed to test?
> 
> The server is not "removed" or "deleted" from the point of view of the Scylla cluster or from the point of view of the driver. Only from the point of view of the framework.
> 
> I would prefer to just get rid of this function and the corresponding test completely.

I agree. There is also a server_stop() function which stops the server without removing it from the ring. So what does remove_node() add to it? Just the fact that it makes it impossible to restart the server later because the framework forgot it exists? It seems like a bug, not a feature ;-)

**Comment by kbr-** [comment]
Closing. I'll send another PR.

**Comment by kbr-** [comment]
https://github.com/scylladb/scylladb/pull/11657

**Pull request closed without merging**
