### PR TITLE
build: cmake: use the same options to configure seastar

### PR DESCRIPTION
**Pull request by tchaikov**
in `configure.py`, a set of options are specified when configuring seastar, but not all of them were ported to scylla's CMake building system.

for instance, `configure.py` explicitly disables io_uring reactor backend at build time, but the CMake-based system does not.

so, in this change, in order to preserve the existing behavior, let's port the two previously missing option to CMake-based building system as well.

---

it's a cmake-related change, hence no need to backport it.

### CODE REVIEW

**Review by kreuzerkrieg — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

**Comment by avikivity** [comment]
It says it's still building.

**Review by avikivity — APPROVED** [review]

**Comment by tchaikov** [comment]
> It says it's still building.

ah, sorry for jumping the gun.

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11129/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11129/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/180/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/3226/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/11250/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/11129/)
> #### Build Details:
> 
>     * Duration: 2 hr 51 min
> 
>     * Builder: spider7.cloudius-systems.com

#20268

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

**Pull request closed without merging**
