### PR TITLE
range_tombstone_change_generator: fix an edge case in flush()

### PR DESCRIPTION
**Pull request by michoecho**
range_tombstone_change_generator::flush() mishandles the case when two range
tombstones are adjacent and flush(pos, end_of_range=true) is called with pos
equal to the end bound of the lesser-position range tombstone.

In such case, the start change of the greater-position rtc will be accidentally
emitted, and there won't be an end change, which breaks reader assumptions by
ending the stream with an unclosed range tombstone, triggering an assertion.

This is due to a non-strict inequality used in a place where strict inequality
should be used. The modified line was intended to close range tombstones
which end exactly on the flush position, but this is unnecessary because such
range tombstones are handled by the last `if` in the function anyway.
Instead, this line caused range tombstones beginning right after the flush
position to be emitted sometimes.

Fixes https://github.com/scylladb/scylladb/issues/12462

### CODE REVIEW

**Comment by michoecho** [comment]
Affects 5.2 and 5.1, doesn't affect master. So the PR is against 5.2.

**Review by tgrabiec — APPROVED** [review]

**Comment by avikivity** [comment]
> Affects 5.2 and 5.1, doesn't affect master. So the PR is against 5.2.

What fixed it in master? For my records.

**Comment by michoecho** [comment]
> > Affects 5.2 and 5.1, doesn't affect master. So the PR is against 5.2.
> 
> What fixed it in master? For my records.

`mutation_partition_v2` (https://github.com/scylladb/scylladb/pull/12048), because the buggy code fell out of use in regular cache read path.

But you just made me realize that it wasn't deleted, and still has some users. I'm not sure if they can trigger the bug, but I'll also submit a PR to master after all.

**Comment by michoecho** [comment]
Submitted https://github.com/scylladb/scylladb/pull/13906 with the same patch against master.

Should be also backported to 5.1.

**Pull request merged**
