### PR TITLE
test/topology: split cluster features test

### PR DESCRIPTION
**Pull request by alecco**
Split the test cases into individual files as each takes minutes in debug mode and combined it piled up to 19 minutes.

### CODE REVIEW

**Comment by alecco** [comment]
Changes in https://github.com/scylladb/scylladb/commit/f3c27998ed6807a69bbfa29b7f2ac6228468576f:

- split the imported runs of these tests in `test/topology_experimental_raft/test_raft_cluster_features.py`

**Review by kostja — APPROVED** [review]

**Comment by kostja** [comment]
I think we should skip these tests in debug mode. The value of running topology tests in debug mode is lower than the cost of maintenance and the overhead in CI. @piodul @alecco WDYT

**Comment by piodul** [comment]
> I think we should skip these tests in debug mode. The value of running topology tests in debug mode is lower than the cost of maintenance and the overhead in CI. @piodul @alecco WDYT

I don't have a strong opinion about it. The cluster features code isn't any more tricky or prone to UB than the rest of the code, so if those tests slows down CI significantly then we can disable them in debug.

**Comment by alecco** [comment]
> I think we should skip these tests in debug mode. The value of running topology tests in debug mode is lower than the cost of maintenance and the overhead in CI. @piodul @alecco WDYT

Agree.

**Comment by alecco** [comment]
Disabled in debug mode in PR https://github.com/scylladb/scylladb/pull/14957

**Pull request closed without merging**
