### PR TITLE
Docs: Update support OS

### PR DESCRIPTION
**Pull request by tzach**
This PR change the CentOS 8 support to Rocky, and add 5.1 and 2022.1, 2022.2 rows to the list of Scylla releases

### CODE REVIEW

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please see https://github.com/scylladb/scylladb/commit/f6157a38a0b6745da6193573c7b97bfed70aa8d3#commitcomment-92214438. This is an important update missing from the 5.1 documentation. Could you help us with that?

**Comment by denesb** [comment]
The PR doesn't apply cleanly to 5.1. Looks like the 5.1 version of this table is missing the Ubuntu 22.04 column. The header is also different. Feels like we need to backport some other PR first. In any case, please prepare a backport PR.

**Comment by annastuchlik** [comment]
@denesb There are very many conflicts. We could avoid them if the following PR was backported instead: https://github.com/scylladb/scylladb/pull/11783 
Could you do it? I may not apply cleanly to 5.1, but there will be fewer conflicts to solve when I create a backport PR.

**Pull request closed without merging**
