### PR TITLE
docs: a single 5.0 -> 5.1 upgrade guide

### PR DESCRIPTION
**Pull request by kbr-**
There were 4 different pages for upgrading Scylla 5.0 to 5.1 (and the same is true for other version pairs, but I digress) for different environments:
- "ScyllaDB Image for EC2, GCP, and Azure"
- Ubuntu
- Debian
- RHEL/CentOS

THe Ubuntu and Debian pages used a common template:
```
.. include:: /upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p1.rst
.. include:: /upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p2.rst
```
with different variable substitutions.

The "Image" page used a similar template, with some extra content in the middle:
```
.. include:: /upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p1.rst
.. include:: /upgrade/_common/upgrade-image-opensource.rst
.. include:: /upgrade/_common/upgrade-guide-v5-ubuntu-and-debian-p2.rst
```

The RHEL/CentOS page used a different template:
```
.. include:: /upgrade/_common/upgrade-guide-v4-rpm.rst
```

This was an unmaintainable mess. Most of the content was "the same" for each of these options. The only content that must actually be different is the part with package installation instructions (e.g. calls to `yum` vs `apt-get`). The rest of the content was logically the same - the differences were mistakes, typos, and updates/fixes to the text that were made in some of these docs but not others.

In this commit I prepare a single page that covers the upgrade and rollback procedures for each of these options. The sections dependent on the system was implemented using Sphinx Tabs.

I also fixed and changed some parts:

- In the "Gracefully stop the node" section: Ubuntu/Debian/Images pages had:

```rst
.. code:: sh

   sudo service scylla-server stop
```

RHEL/CentOS pages had:
```rst
.. code:: sh

.. include:: /rst_include/scylla-commands-stop-index.rst
```

the stop-index file contained this:
```rst
.. tabs::

   .. group-tab:: Supported OS

      .. code-block:: shell

         sudo systemctl stop scylla-server

   .. group-tab:: Docker

      .. code-block:: shell

         docker exec -it some-scylla supervisorctl stop scylla

      (without stopping *some-scylla* container)
```

So the RHEL/CentOS version had two tabs: one for Scylla installed directly on the system, one for Scylla running in Docker - which is interesting, because nothing anywhere else in the upgrade documents mentions Docker.  Furthermore, the RHEL/CentOS version used `systemctl` while the ubuntu/debian/images version used `service` to stop/start scylla-server.  Both work on modern systems.

The Docker option is completely out of place - the rest of the upgrade procedure does not mention Docker. So I decided it doesn't make sense to include it. Docker documentation could be added later if we actually decide to write upgrade documentation when using Docker...  Between `systemctl` and `service` I went with `service` as it's a bit higher-level.

- Similar change for "Start the node" section, and corresponding stop/start sections in the Rollback procedure.

- To reuse text for Ubuntu and Debian, when referencing "ScyllaDB deb repo" in the Debian/Ubuntu tabs, I provide two separate links: to Debian and Ubuntu repos.

- the link to rollback procedure in the RPM guide (in 'Download and install the new release' section) pointed to rollback procedure from 3.0 to 3.1 guide... Fixed to point to the current page's rollback procedure.

- in the rollback procedure steps summary, the RPM version missed the "Restore system tables" step.

- in the rollback procedure, the repository links were pointing to the new versions, while they should point to the old versions.

There are some other pre-existing problems I noticed that need fixing:

- EC2/GCP/Azure option has no corresponding coverage in the rollback section (Download and install the old release) as it has in the upgrade section. There is no guide for rolling back 3rd party and OS packages, only Scylla. I left a TODO in a comment.
- the repository links assume certain Debian and Ubuntu versions (Debian 10 and Ubuntu 20), but there are more available options (e.g. Ubuntu 22). Not sure how to deal with this problem. Maybe a separate section with links? Or just a generic link without choice of platform/version?

### CODE REVIEW

**Comment by kbr-** [comment]
@annastuchlik is there a way for GitHub to give us a preview of the newly rendered docs?

**Comment by annastuchlik** [comment]
@kbr- Thank you so much for this PR! I'm going to review it soon.

We're in the process of enabling the preview - I'm waiting for [this PR](https://github.com/scylladb/scylladb/pull/11887) to be reviewed and merged to move on.
At the moment, you can only preview the changes locally:
1. Run `make preview `to build the documentation.
2. Preview the built documentation locally at http://127.0.0.1:5500/.

There are some prerequisites, though. They are listed [here](https://github.com/scylladb/scylladb/tree/master/docs#prerequisites).

**Comment by tzach** [comment]
@kbr- from initial looks: *great* work!
Tabs looks good, no compliation warnining

**Comment by kbr-** [comment]
Rebased.
Maybe GH will give a preview (for reviewers) after the recent changes to `master`?

**Comment by kbr-** [comment]
@annastuchlik / @tzach: so how do we use the feature added in https://github.com/scylladb/scylladb/pull/11591?

**Comment by annastuchlik** [comment]
@kbr- I'm super impressed with this PR! I've reviewed it locally, and everything looks great to me.
I agree with your choices to remove the Docker commands, which were incomplete and useless, and to consistently use the `service` command.

Future fixes (outside of the scope of this PR:
- I've opened [a new issue ](https://github.com/scylladb/scylladb/issues/11909)to add the rollback procedure for the image.
- Decide how to handle the link to the repositories (a generic link, per version links, etc.).
- Remove explicitly stated version names, such as "CentOS 7/8" in favor of "See OS Support by Platform and Version for information about supported versions."

**Comment by annastuchlik** [comment]
> @annastuchlik / @tzach: so how do we use the feature added in #11591?

We need to update the configuration on the AWS Amplify side. We're going to do it today. After that, the preview will be automatically added to documentation PRs - there will be an automatically added comment with relevant links.

**Review by annastuchlik — APPROVED** [review]
LGTM

**Comment by kbr-** [comment]
@scylladb/scylla-maint please take a look and merge

**Comment by tzach** [comment]
@kbr- cheers for one of the best refeactoring in docs history

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1

**Comment by denesb** [comment]
> @scylladb/scylla-maint Please backport to 5.1

Doesn't apply cleanly to 5.1, please prepare a PR with the backport. The way to do this is:
* `git checkout branc-5.1`
* `git checkout -b 11891-backport` - any branch name will do, this is just an example
* `git cherry-pick -x 0c7ff0d`
* solve conflicts
* push branch and open PR
* select `branch-5.1` as the target branch for the PR and also note that this is a backport in the PR comments

**Comment by denesb** [comment]
Actually we usually ask the original author of a patch to do the backport, which is @kbr- in this case.

**Comment by kbr-** [comment]
Done: https://github.com/scylladb/scylladb/pull/12034

**Pull request closed without merging**
