### PR TITLE
table_helper: move table_helper.{cc,hh} into tracing/

### PR DESCRIPTION
**Pull request by tchaikov**
it turns out tracing/trace_keyspace_helper.hh and table_helper.cc are the only two source files which include table_helper.hh, so tracing/trace_keyspace_helper.hh is the only consumer of the `table_helper` class.

in order to improve the modularity of the source structure, and to prepare for a better building system, let's move table_helper.{cc,hh} into tracing/ .

this change is inspired by following link failure

```
./build/./tracing/trace_keyspace_helper.cc:214: error: undefined reference to 'table_helper::setup_keyspace(cql3::query_processor&, service::migration_manager&, std::basic_string_view<char, std::char_traits<char> >, seastar::basic_sstring<char, unsigned int, 15u, true>, service::query_state&, std::vector<table_helper*, std::allocator<table_helper*> >)'
./build/./tracing/trace_keyspace_helper.cc:396: error: undefined reference to 'table_helper::cache_table_info(cql3::query_processor&, service::migration_manager&, service::query_state&)'
./table_helper.hh:92: error: undefined reference to 'table_helper::insert(cql3::query_processor&, service::migration_manager&, service::query_state&, seastar::noncopyable_function<cql3::query_options ()>)'
./table_helper.hh:92: error: undefined reference to 'table_helper::insert(cql3::query_processor&, service::migration_manager&, service::query_state&, seastar::noncopyable_function<cql3::query_options ()>)'
./table_helper.hh:92: error: undefined reference to 'table_helper::insert(cql3::query_processor&, service::migration_manager&, service::query_state&, seastar::noncopyable_function<cql3::query_options ()>)'
./table_helper.hh:92: error: undefined reference to 'table_helper::insert(cql3::query_processor&, service::migration_manager&, service::query_state&, seastar::noncopyable_function<cql3::query_options ()>)'
clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

the reason of the failure is that the CMake-based building system fails to link `scylla_tracing` against `scylla-main`.

- [x] cleanup. No need to backport.

### CODE REVIEW

**Comment by mykaul** [comment]
@tchaikov - the 'backport' checkbox is ticked - but it's not clear if we should or should not (I guess not) backport this.

**Comment by tchaikov** [comment]
> @tchaikov - the 'backport' checkbox is ticked - but it's not clear if we should or should not (I guess not) backport this.

@mykaul hi Yaniv, i take it as a claim that I explained why this change should be backported or not. In this very case, I added the label of code/cleanup, so I think I can tick it. Otherwise the workflow checking it would fail. @yaronkaikov could you please clarify this?

**Comment by yaronkaikov** [comment]
> > @tchaikov - the 'backport' checkbox is ticked - but it's not clear if we should or should not (I guess not) backport this.
> 
> @mykaul hi Yaniv, i take it as a claim that I explained why this change should be backported or not. In this very case, I added the label of code/cleanup, so I think I can tick it. Otherwise the workflow checking it would fail. @yaronkaikov could you please clarify this?

@tchaikov The idea is also to explain in the PR cover later if we need to backport or not and why.

**Comment by tchaikov** [comment]
> > > @tchaikov - the 'backport' checkbox is ticked - but it's not clear if we should or should not (I guess not) backport this.
> 
> > 
> 
> > @mykaul hi Yaniv, i take it as a claim that I explained why this change should be backported or not. In this very case, I added the label of code/cleanup, so I think I can tick it. Otherwise the workflow checking it would fail. @yaronkaikov could you please clarify this?
> 
> 
> 
> @tchaikov The idea is also to explain in the PR cover later if we need to backport or not and why. 

@yaronkaikov so in this case, since I already added the cleanup label, shall I tick the checkbox or just remove it from my cover letter, or leave it as it is?

**Comment by yaronkaikov** [comment]
> > > > @tchaikov - the 'backport' checkbox is ticked - but it's not clear if we should or should not (I guess not) backport this.
> > 
> > 
> > > 
> > 
> > 
> > > @mykaul hi Yaniv, i take it as a claim that I explained why this change should be backported or not. In this very case, I added the label of code/cleanup, so I think I can tick it. Otherwise the workflow checking it would fail. @yaronkaikov could you please clarify this?
> > 
> > 
> > @tchaikov The idea is also to explain in the PR cover later if we need to backport or not and why.
> 
> @yaronkaikov so in this case, since I already added the cleanup label, shall I tick the checkbox or just remove it from my cover letter, or leave it as it is?

We should tick the box and explain below why no backport is needed. you can leave the label. The explanation just need to be clear, even if it's a short one ;-)

**Comment by avikivity** [comment]
audit also uses table_helper. Please avoid unnecessary churn.

**Comment by tchaikov** [comment]
sorry, i didn't check the enterprise build. meant to also prepare for the modulization.

**Comment by tchaikov** [comment]
created #18455 instead.

**Pull request closed without merging**
