### PR TITLE
utils/cached_file: reduce latency (and increase overhead) of partially-cached reads

### PR DESCRIPTION
**Pull request by michoecho**
Currently, `cached_file::stream` (currently used only by index_reader, to read index pages), works as follows.

Assume that the caller requested a read of the range [pos, pos + size). Then:

- If the first page of the requested range is uncached, the entire [pos, pos + size) range is read from disk (even if some later pieces of it are cached), the resulting pages are added to the cache, and the read completes (most likely) from the cached pages.
- If the first page of the read is cached, then the rest of the read is handled page-by-page, in a sequential loop, serving each page either from cache (if present) or from disk.

For example, assume that pages 0, 1, 2, 3, 4 are requested.

If exactly pages 1, 2 are cached, then `stream` will read the entire [0, 4] range (in one I/O operation) from disk and insert the missing 0, 3, 4, and then it will continue serving the read from cache.

If exactly pages 0 and 3 are cached, then it will serve 0 from cache, then it will read 1 from disk and insert it into cache, then it will read 2 from disk and insert it into cache, then it will serve 3 from cache,
then it will read 4 from disk and insert it into cache.

If exactly the first page is cached, a 128 kiB read turns into 31 I/O sequential read ops.

This is weird, and doesn't look intended. In one case, we are reading even pages we already have, just to avoid fragmenting the read, and in the other case we are reading pages one-by-one (not in parallel!) even if they are neighbours.

I'm not sure if cached_file should minimize IOPS or byte throughput, but the current state is surely suboptimal. Even if its read strategy is somehow optimal, it should still at least coalesce contiguous reads and perform the non-contiguous reads in parallel.

This patch leans into minimizing IOPS. After the patch, we serve as many front pages from the cache as we can, but when we see an uncached page, we read the entire remainder of the read from disk. As if we trimmed the read request by the longest cached prefix, and then performed the rest using the logic from before the patch.

For example, if exactly pages 0 and 3 are cached, then we serve 0 from cache, then we read [1, 4] from disk and insert everything into cache.

For partially-cached files, this will result in more bytes read from disk, but less IOPS. This might be a bad thing. But if so, then we should lean the other way in a more explicit and efficient way than we currently do.

Not a bug, no backport considerations.

### CODE REVIEW

**Comment by michoecho** [comment]
This PR is more for discussion than for merging. I don't know if it does the right thing or the opposite of the right thing. But the current logic seems weird and unintended, and surprised me when I encountered it.

I encountered it when running perf_fast_forward, the case where we have a table of 1000000 partitions, and we alternate between reading 64 partitions and skipping 256 partitions. I wrote https://github.com/scylladb/scylladb/pull/20897, and I was surprised to see that in this test case, the number of IOPS performed by the index reader grew by ~16x.

What happened there is that before that without #20897, both cursors (lower bound, upper bound) of the index reader happen to start their scan of the index file at page 0, while with #20897, the upper bound cursor skips the first page (it's unneeded) and starts at page 1.
So before the PR, both streams perform reads [0, 128kiB), [128 kiB, 256 kiB), ..., but after the PR, the upper bound stream performs reads [4 kiB, 132 kiB), [132 kiB, 260 kiB), ...
And it so happens, that the reads of the first stream consistently have their first page cached. So, as described here, the 128 kiB reads of the first stream are fragmented into 31 sequential reads. And in total, we go from two 128 kiB reads to one 128 kiB reads and thirty one 4 kiB reads. Which is weird.

**Comment by mykaul** [comment]
My intuition (which is based on nothing other than intuition) is the other way around - fast disks today can handle more (random) IOPS than in the past (or slower disks). We want to minimize IOPS for EBS and slower disks. 
I wonder if we can quantify this in any way in the cloud - see how many times we saturate our IOPS vs. bandwidth limits (that the IO scheduler is configured with).

Also - if we have pages in cache, shouldn't we make more effort to (re)use them rather than read them again from disk?

**Review by tgrabiec — APPROVED** [review]

**Comment by tgrabiec** [comment]
Since this patch is an improvement, I think we can merge it. 

The handling of readahead is not optimal, but I'm not sure it's worth investing in it now. Cases where we have overlap of readahead with cached pages should be relatively uncommon, unless access has temporal relationship like in this case. There could be overlap of readahead with pages cached during binary search, if we re-read the whole index page after it was evicted from the partition index page cache. But in that case, I would expect the pages touched by binary search to be evicted earlier too.

**Comment by tgrabiec** [comment]
If we wanted to use the page cache for other purposes, like data file reads, this would have to be improved. @michoecho Worth to open a generic enhancement issue for the readahead.

**Pull request closed without merging**
