### PR TITLE
test: test_tablets.py: Enable verbose logging

### PR DESCRIPTION
**Pull request by tgrabiec**
This is in order to aid investigation of falkiness of the test, which fails due to a timeout during scan after cluster restart in debug mode.

See #14746.

I enable trace-level logging for some scylla-side loggers and inject logging of sent and received messages on the driver side.

### CODE REVIEW

**Comment by avikivity** [comment]
Doesn't it reproduce locally with --repeat $large_number?

**Comment by tgrabiec** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4185/

```
16:47:32,718 793     cql_group_functions_tests      DEBUG    cql_group_functions_tests.py:46   | test_dates_type_group: CREATE TABLE all_types (id int PRIMARY KEY, my_date date);
16:48:12,702 793     errors                         ERROR    conftest.py         :225  | test_dates_type_group: test failed: 
self = <cql_group_functions_tests.TestGroupFunctions object at 0x7fb205103b10>

    @pytest.mark.no_boot_speedups
    def test_dates_type_group(self):
        session = self.prepare()
        for single_type in self.dates_type_list:
>           self.create_tables_and_run_group_functions(session=session, table_name=self.table_name,
                                                       single_type=single_type)

cql_group_functions_tests.py:121: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cql_group_functions_tests.py:89: in create_tables_and_run_group_functions
    session.execute('DROP TABLE {}'.format(table_name))
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   cassandra.OperationTimedOut: errors={'127.0.95.3:9042': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=127.0.95.3:9042

```

Unrelated. @kbr-scylla Does it look like one of recent failures?

**Comment by tgrabiec** [comment]
> Doesn't it reproduce locally with --repeat $large_number?

No. I don't remember which $large_number I tried, but it was large.

**Comment by kbr-scylla** [comment]
> Unrelated. @kbr-scylla Does it look like one of recent failures?

These "Client request timeout"s seem to be quite common nowadays:
https://github.com/scylladb/scylladb/issues?q=is%3Aissue+is%3Aopen++%22Client+request+timeout.%22+

**Pull request closed without merging**
