### PR TITLE
Fix typo (patch -> batch)

### PR DESCRIPTION
**Pull request by mykaul**
See subject.

### CODE REVIEW

**Comment by mykaul** [comment]
@annastuchlik , please review.

**Comment by tzach** [comment]
LGTM
BTW, this issue is inhertaed from Apache Cassandra doc
https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#unlogged-batches

I sugget to open a corresponding issue (or send a PR)

**Comment by denesb** [comment]
Queued.
@mykaul in the future, please prepend to the subject the subsystem (or module) that is the target of the patch. In this case this would be `docs: Fix typo...`. I edited the patch to add it this time.

**Comment by denesb** [comment]
One more thing: please set `next` as the target branch of pull-requests (not `master`).

**Comment by annastuchlik** [comment]
@mykaul Thanks for opening this PR! The initial problems were caused by some temporary connectivity problems.

I've opened the same PR with Cassandra.

**Comment by annastuchlik** [comment]
@scylladb/scylla-maint Please backport to 5.1 if possible

**Pull request closed without merging**
