### PR TITLE
[branch-6.0] Update the tools/java submodule

### PR DESCRIPTION
**Pull request by denesb**
* tools/java 4ee15fd9...6dfc187a (1):
  > Update Scylla Java driver to 3.11.5.3.

[botond: regenerate frozen toolchain]

### CODE REVIEW

**Comment by denesb** [comment]
@yaronkaikov please generate the arm64 image.

**Comment by denesb** [comment]
> [test_tablet_split](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/31/testReport/junit/%28root%29/test_tablets/Tests___Unit_Tests___test_tablet_split) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablet_split)

https://github.com/scylladb/scylladb/issues/18896

**Comment by yaronkaikov** [comment]
> @yaronkaikov please generate the arm64 image.

Done

image

**Comment by denesb** [comment]
Thanks @yaronkaikov, queued.

**Comment by denesb** [comment]
I already queued this and then I saw that this was added to the 6.0.1 milestone. Does this mean that I should have only queued this after 6.0 is released? @mykaul

**Comment by mykaul** [comment]
> I already queued this and then I saw that this was added to the 6.0.1 milestone. Does this mean that I should have only queued this after 6.0 is released? @mykaul

I think it's fine to include it as part of 6.0. I did not anticipate we'll be held with 6.0GA for so long :-(

**Comment by denesb** [comment]
Closed by https://github.com/scylladb/scylladb/commit/8a064daccfc38246e7797a54a4fa1af511229fe6.

**Pull request closed without merging**
