### PR TITLE
[Backport 5.2]: cleanup staging and uploaded sstables

### PR DESCRIPTION
**Pull request by bhalevy**
This series backports a few bug fixes (and re-fixes on top of them) to branch-5.2:
* https://github.com/scylladb/scylladb/issues/9559
* https://github.com/scylladb/scylladb/issues/11933
* https://github.com/scylladb/scylladb/issues/13631
* https://github.com/scylladb/scylladb/pull/13526
* https://github.com/scylladb/scylladb/issues/13634
* https://github.com/scylladb/scylladb/pull/14151
* https://github.com/scylladb/scylladb/issues/14001

The gist of this change is adding an optional `owned_ranges_ptr` to `compaction_descriptor`
that allows any compaction type (scrub compaction excluded) to perform cleanup compaction piggybacked on the compaction reader that filters out any tokens not included in this list of owned ranges.

SSTables that need cleanup are identified in 2 code paths:
1. cleanup compaction: in this case all sstables for which `needs_cleanup()` returns true are put on a `sstables_requiring_cleanup` set and cleanup waits until it becomes empty.  This may require retries as some of them may be in `staging` if they are required for view updates following streaming/repair.
2. upload sstables: in this case, foreign sstables are copied into the `upload` folder and the may contain tokens not owned by the node, e.g. if they were backed up when the cluster had different topology and they are restored with `nodetool refresh`.  Those sstables are not put onto `sstables_requiring_cleanup` (they used to but this was fixed), and are just added to sstables that need resharding and resharding compaction is taking case of both resharding and cleanup via the `compaction_descriptor.owned_ranges`.

### CODE REVIEW

**Comment by bhalevy** [comment]
rebased

**Comment by bhalevy** [comment]
> At one side, it's important to cleanup staging, at the other, we're bringing lots of fresh changes to a stable branch which can cause unknown issues. @bhalevy what if we extract the minimal part to guarantee that cleanup only proceeds after we're done with view building (the condition variable is signalled once the staging set is empty, meaning view building has completed all the work).

I'd consider it a different fix and it may make backporting of additional fixes on top of it problematic.

It's not to say I oppose it entirely but it makes me frown

**Comment by avikivity** [comment]
This is a huge series. Are these all regressions? How confident are we in those fixes?

**Comment by raphaelsc** [comment]
> > At one side, it's important to cleanup staging, at the other, we're bringing lots of fresh changes to a stable branch which can cause unknown issues. @bhalevy what if we extract the minimal part to guarantee that cleanup only proceeds after we're done with view building (the condition variable is signalled once the staging set is empty, meaning view building has completed all the work).
> 
> I'd consider it a different fix and it may make backporting of additional fixes on top of it problematic.
> 
> It's not to say I oppose it entirely but it makes me frown

The fixes come with a major refactor which is complex and the evidence are the amounts of fixes that came later and possibly even more fixes for issues we are still not aware of. Isn't it wiser to allow it to cooking a bit more, let it go through a OSS release and then consider it for backporting?

This series is fixing a preexisting issue, not a regression, so users have been living with lack of cleanup on staging for always. Not claiming that it's good to allow such a bug in the system, but I am worried about the risk of bringing in lots of fresh changes to stable branches.

**Comment by DoronArazii** [comment]
@bhalevy what's the next step here?

**Comment by bhalevy** [comment]
> @bhalevy what's the next step here?

This is a big and risky series.
And frankly, we found a number of issues with the patches that are fixed in master and included here
but I'm not 100% confident we covered all cases, so I'm a bit reluctant to push this backport prematurely.
I think that in this case we should incline towards being conservative and let the fixes brew some time in the latest oss and enterprise releases to gain confidence about them and only then reconsider their backport.

**Comment by bhalevy** [comment]
rebased

**Comment by denesb** [comment]
I think this shouldn't go into 5.2 but go into 2023.1 directly.

**Comment by bhalevy** [comment]
> I think this shouldn't go into 5.2 but go into 2023.1 directly.

Why create that discrepancy?
Wouldn't it make backporting to 5.2 and then merging into 2023.1 more complicated in the future?

**Comment by denesb** [comment]
> > I think this shouldn't go into 5.2 but go into 2023.1 directly.
> 
> Why create that discrepancy? Wouldn't it make backporting to 5.2 and then merging into 2023.1 more complicated in the future?

We keep backports to OSS releases minimal, and backport features and large and complex fixes only to enterprise.

**Comment by yaronkaikov** [comment]
@bhalevy Running https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/1/ , we should get an AMI at the end of this job
/cc @roydahan

**Comment by yaronkaikov** [comment]
@bhalevy `us-east-1-x86_64 = ami-05f67f78151e15af0`

**Comment by bhalevy** [comment]
@yarongilor let's build a new ami and retest it

**Comment by yarongilor** [comment]
> @yarongilor let's build a new ami and retest it

Building now in https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/3/

**Comment by bhalevy** [comment]
> > @yarongilor let's build a new ami and retest it
> 
> Building now in https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/3/

@yarongilor what's the testing status?

**Comment by yarongilor** [comment]
> > > @yarongilor let's build a new ami and retest it
> > 
> > 
> > Building now in https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/3/
> 
> @yarongilor what's the testing status?

@bhalevy , the newly created AMI is under tests. See progress in [task](https://github.com/scylladb/qa-tasks/issues/1502#issuecomment-1737527314)

**Comment by bhalevy** [comment]
> > > > @yarongilor let's build a new ami and retest it
> > > 
> > > 
> > > Building now in https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/3/
> > 
> > 
> > @yarongilor what's the testing status?
> 
> @bhalevy , the newly created AMI is under tests. See progress in [task](https://github.com/scylladb/qa-tasks/issues/1502#issuecomment-1737527314)

@yarongilor what's the status?

**Comment by yarongilor** [comment]
> > > > > @yarongilor let's build a new ami and retest it
> > > > 
> > > > 
> > > > Building now in https://jenkins.scylladb.com/job/scylla-5.2/job/byo/job/byo_build_tests_dtest/3/
> > > 
> > > 
> > > @yarongilor what's the testing status?
> > 
> > 
> > @bhalevy , the newly created AMI is under tests. See progress in [task](https://github.com/scylladb/qa-tasks/issues/1502#issuecomment-1737527314)
> 
> @yarongilor what's the status?

@bhalevy , the core dump is not reproduced but the nodetool cleanup issue [does](https://github.com/scylladb/scylladb/issues/15461#issuecomment-1752021545).

**Comment by bhalevy** [comment]
[a344c65](https://github.com/scylladb/scylladb/commit/a344c658bc46f6f69d301d992f83040ad9563ba4):
- rebased + retested
- added: compaction_manager: perform_cleanup: ignore condition_variable_timed_out

**Comment by bhalevy** [comment]
@avikivity @mykaul CI passed and since this branch is susceptible to bit rot due to its sheer size.
Let's make a decision if we want to merge or not before it needs rebasing yet again.
(Well if we wait long enough 5.2 will end its life :))

**Comment by mykaul** [comment]
I'm in favor of merging.

**Comment by mykaul** [comment]
@avikivity , @bhalevy - decision?

**Comment by bhalevy** [comment]
> @avikivity , @bhalevy - decision?

I'm also in favor of merging.
It's up to @avikivity

**Comment by raphaelsc** [comment]
> > @avikivity , @bhalevy - decision?
> 
> I'm also in favor of merging. It's up to @avikivity

FWIW, went through the series to double check we're not missing any fix that came later.

**Comment by raphaelsc** [comment]
@bhalevy by the way, it's very important that we prevent cleanup in parallel to decommission, as if a replica regains ownership of a token being cleaned up, we can have data loss. preexisting problem anyway, just thought about it while going through the series and thinking about implications of owned ranges becoming a state in manager, but it's fine as long as we keep the state for the lifetime of cleanup.

**Comment by bhalevy** [comment]
> @bhalevy by the way, it's very important that we prevent cleanup in parallel to decommission, as if a replica regains ownership of a token being cleaned up, we can have data loss. preexisting problem anyway, just thought about it while going through the series and thinking about implications of owned ranges becoming a state in manager, but it's fine as long as we keep the state for the lifetime of cleanup.

@gleb-cloudius is working on automating cleanup as part of raft-based consistent topology changes, so this should be tackled as part of that effort.
Later, with tablet, cleanup is also made simpler by the tablet replica state machine that the tablets scheduler manages, that will make sure to delete stale tablet replicas after they've been migrated, again making today's cleanup unrequired.
All in all, we should not spend too much effort in improving today's cleanup mechanism, in future versions.

**Comment by denesb** [comment]
@bhalevy it's been a while since I reviewed this new cleanup, but won't this make it easier to accidentally have cleanup running during decommision? AFAIK, with the "old" `nodetool cleanup`, the command returned after cleanup was done. With the "new" cleanup" this is done partially/fully in the background and the command returns immediately, giving the impression that cleanup is now done, no?

**Comment by bhalevy** [comment]
> @bhalevy it's been a while since I reviewed this new cleanup, but won't this make it easier to accidentally have cleanup running during decommision? AFAIK, with the "old" `nodetool cleanup`, the command returned after cleanup was done. With the "new" cleanup" this is done partially/fully in the background and the command returns immediately, giving the impression that cleanup is now done, no?

No, on the contrary. `nodetool cleanup` used to return early before the staging sstables were cleaned up but now it waits for them after initiating offstrategy compaction and awaiting view updates generation.

**Comment by denesb** [comment]
@bhalevy this aged out, as 5.2 is EOL, do we want to backport it to 2023.1? A lot of time has passed since and we have not seen any issues related to cleanup since AFAIK.

**Comment by bhalevy** [comment]
> @bhalevy this aged out, as 5.2 is EOL, do we want to backport it to 2023.1? A lot of time has passed since and we have not seen any issues related to cleanup since AFAIK.

I think it's still too risky, and with the lack of reported issues from the field we can defer it.

**Comment by mykaul** [comment]
5.2 is End-of-life, closing.

**Pull request closed without merging**
