### PR TITLE
[Backport 6.0]: Rebuild bloom filters that have bad partition estimates

### LINKED ISSUE #19049: bloom filter: reduce size of over-estimated bloom filter
When sealing the sstable, check whether the filter (the original partition estimate really) was over-estimated. If it was, reduce its size to be as close to the size needed for the real partition count as possible.

### PR DESCRIPTION
**Pull request by lkshminarayanan**
The bloom filters are built with partition estimates because the actual partition count might not be available in all cases. If the estimate is inaccurate, the bloom filters might end up being too large or too small compared to their optimal sizes. This PR rebuilds bloom filters with inaccurate partition estimates using the actual partition count before the filter is written to disk. A bloom filter is considered to have an inaccurate estimate if its false positive rate based on the current bitmap size is either less than 75% or more than 125% of the configured false positive rate.

Fixes #19049

A manual test was run to check the impact of rebuild on compaction.

Table definition used : CREATE TABLE scylla_bench.simple_table (id int PRIMARY KEY);

Setup : 3 billion random rows with id in the range [0, 1e8) were inserted as batches of 5 rows into scylla_bench.simple_table via 80 threads.

Compaction statistics :

scylla_bench.simple_table :
(a) Total number of compactions : `1501`
(b) Total time spent in compaction : `9h58m47.269s` (c) Number of compactions which rebuilt bloom filters : `16` (d) Total time taken by these 16 compactions which rebuilt bloom filters : `2h55m11.89s` (e) Total time spent by these 16 compactions to rebuild bloom filters : `8m6.221s` which is
- `4.63%` of the total time taken by the compactions which rebuilt filters (d)
- `1.35%` of the total compaction time (b).

(f) Total bytes saved by rebuilding filters : `388 MB`

system.compaction_history :
(a) Total number of compactions : `77`
(b) Total time spent in compaction : `21.24s`
(c) Number of compactions which rebuilt bloom filters : `74` (d) Time taken by these 74 compactions which rebuilt bloom filters : `20.48s` (e) Time spent by these 74 compactions to rebuild bloom filters : `377ms` which is
- `1.84%` of the total time taken by the compactions which rebuilt filters (d)
- `1.77%` of the total compaction time (b).

(f) Total bytes saved by rebuilding filters : `20 kB`

The following tables also had compactions and the bloom filter was rebuilt in all those compactions. However, the time taken for every rebuild was observed as 0ms from the logs as it completed within a microsecond :

system.raft :
(a) Total number of compactions : `2`
(b) Total time spent in compaction : `106ms`
(c) Total bytes saved by rebuilding filters : `960 B`

system_schema.tables :
(a) Total number of compactions : `1`
(b) Total time spent in compaction : `25ms`
(c) Total bytes saved by rebuilding filter : `312 B`

system.topology :
(a) Total number of compactions : `1`
(b) Total time spent in compaction : `25ms`
(c) Total bytes saved by rebuilding filter : `320 B`

Closes scylladb/scylladb#19190

* github.com:scylladb/scylladb:
  bloom_filter_test: add testcase to verify filter rebuilds
  test/boost: move bloom filter tests from sstable_datafile_test into a new file
  sstables/mx/writer: rebuild bloom filters with bad partition estimates
  sstables/mx/writer: add variable to track number of partitions consumed
  sstable: introduce sstable::maybe_rebuild_filter_from_index()
  sstable: add method to return filter format for the given sstable version
  utils/i_filter: introduce get_filter_size()

(cherry picked from commit 371e37924fd8a9734edc2445d20c40a0472daaa1)

Backported from #19190 to 6.0.

Also included in this PR is a backport of #19601 to 6.0 :

Log the sstable origin when its bloom filter is being rebuilt. The
origin has to be passed to the method by the caller as it is not
available in the sstable object when the filter is rebuilt.

(cherry picked from commit https://github.com/scylladb/scylladb/commit/c80df8504c460436065fc8c006fa934ac6c41d22)

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
> #### Failed Tests (1/30771):
> * [test_change_node_ip](https://jenkins.scylladb.com//job/scylla-6.0/job/scylla-ci/107/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest_with_topology_changes___test_change_node_ip) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_change_node_ip)

https://github.com/scylladb/scylladb/issues/18693

**Comment by avikivity** [comment]
Why is this being backported?

**Comment by lkshminarayanan** [comment]
> Why is this being backported?

Mainly for the cloud? I'm not sure if the reclaim/reload is still disabled in cloud deployments but either way, this fix could benefit the existing clusters. It could potentially reduce the number of filters that are reclaimed and reloaded.

**Comment by denesb** [comment]
> Why is this being backported?

I though the BF eviction backport was the "quick fix" until the real fix (this PR) comes along and we want to backport both.

**Comment by avikivity** [comment]
> > Why is this being backported?
> 
> Mainly for the cloud?

I don't understand. What's special about the cloud? In any case it doesn't run 6.0.

> I'm not sure if the reclaim/reload is still disabled in cloud deployments but either way, this fix could benefit the existing clusters. It could potentially reduce the number of filters that are reclaimed and reloaded.


"benefit" isn't a reason to backport. Everything we do is for some benefit. The backport rules are: we backport fixes for regressions or critical bugs. Is this fixing a regression or critical bug?

If we just backport anything, we greatly increase the risk for introducing regressions to stable releases (as has happened with the bloom filter dropping vs snapshot bug).

**Comment by lkshminarayanan** [comment]
> > > Why is this being backported?
> > 
> > 
> > Mainly for the cloud?
> 
> I don't understand. What's special about the cloud? In any case it doesn't run 6.0.
> 
> > I'm not sure if the reclaim/reload is still disabled in cloud deployments but either way, this fix could benefit the existing clusters. It could potentially reduce the number of filters that are reclaimed and reloaded.
> 
> "benefit" isn't a reason to backport. Everything we do is for some benefit. The backport rules are: we backport fixes for regressions or critical bugs. Is this fixing a regression or critical bug?
> 
> If we just backport anything, we greatly increase the risk for introducing regressions to stable releases (as has happened with the bloom filter dropping vs snapshot bug).

I understand. I'll close the backports.

**Pull request closed without merging**
