### PR TITLE
service levels: update `client_state` when granted roles changes

### PR DESCRIPTION
**Pull request by Jadw1**
Introduces subscriber mechanism in role manager to notify about changes in roles configurations. This allows client state to subscribe to it and update service level params when roles are granted/revoked and if service levels are assigned to them.

NOTE: This PR is continuation of #13441 and should be merged after it. (currently this PR shows it has 6 commits but only last 2 are new changes)

NOTE 2: When merging to enterprise, others role managers (like `ldap_role_manager`) need to implement notification mechanism.

### CODE REVIEW

**Review by eliransin — APPROVED** [review]
LGTM,
I think we should make sure we have extensive testing for concurrent role changes,
or at least reason about why it is not a problem to have several of those client state updates running concurrently.

**Comment by Jadw1** [comment]
Changelog:
- rebased on top of latest https://github.com/scylladb/scylladb/pull/13441
- fixed an error (the error was happening when callback was called on client_state of already dropped role)

**Comment by Jadw1** [comment]
@eliransin ping (this should be merged after #13441)

**Comment by eliransin** [comment]
This is a good first step, I just want to mention that it will actually not really work until RBAC is managed with raft.
/cc @ptrsmrn 
The role manager uses a table to update the roles, the gran/revoke/set_attribute which are notifying the subscibers, are only called on the coordinator side, and the underlying operation they perform is writing to the `auth.roles` table.
Which means that on the coordinator side, things are going to be OK but on the replica sides (all other nodes if RF=ALL), nothing will happen.
This will only work when role managers will be actually notified which can happen (for the standard role manage) only when the table is raft based and we can hook into the 'apply' stage for the RBAC commands of group 0.
For other role managers, it is a good question what we are going to do, I couldn't find any CDC option build into LDAP,
so we will have no choice but to query the server for role changes, this is only relevant for LDAP authorizer (not LDAP authenticator). But the solution will probably be derived from product definitions (what is the max time expected from the system to adjust to new roles configurations after it has been changed on the LDAP/other remote server).

**Review by eliransin — APPROVED** [review]
LGTM

**Pull request closed without merging**
