### PR TITLE
test/alternator: fix flaky test test_item_latency

### LINKED ISSUE #18847: alternator: test_item_latency is flaky
```
test_table_s = dynamodb.Table(name='alternator_Test_1716375329548')
metrics = 'http://127.249.147.1:9180/metrics'

    def test_item_latency(test_table_s, metrics):
>       with check_sets_latency(metrics, ['DeleteItem', 'GetItem', 'PutItem', 'UpdateItem']):

test/alternator/test_metrics.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.11/contextlib.py:144: in __exit__
    next(self.gen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

metrics = 'http://127.249.147.1:9180/metrics'
operation_names = ['DeleteItem', 'GetItem', 'PutItem', 'UpdateItem']

    @contextmanager
    def check_sets_latency(metrics, operation_names):
        the_metrics = get_metrics(metrics)
        saved_latency_count = { x: get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': x}, the_metrics) for x in operation_names }
        saved_latency_sum = { x: get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': x}, the_metrics) for x in operation_names }
        # TODO: Also look at the latency_bucket.
        yield
        the_metrics = get_metrics(metrics)
        for op in operation_names:
            # The total "count" and "sum" on all shards should strictly increase
            assert saved_latency_count[op] < get_metric(metrics, 'scylla_alternator_op_latency_count', {'op': op}, the_metrics)
>           assert saved_latency_sum[op] < get_metric(metrics, 'scylla_alternator_op_latency_sum', {'op': op}, the_metrics)
E           assert 175340000.0 < 175340000.0
E            +  where 175340000.0 = get_metric('http://127.249.147.1:9180/metrics', 'scylla_alternator_op_latency_sum', {'op': 'UpdateItem'}, '# HELP scylla_alien_receive_batch_queue_length Current receive batch queue length\n# TYPE scylla_alien_receive_batch_..._sstables_to_move_count{shard="0"} 0.000000\nscylla_view_update_generator_sstables_to_move_count{shard="1"} 0.000000\n')

test/alternator/test_metrics.py:230: AssertionError
```

logs: 
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9060/testReport/junit/(root)/test_metrics/test_item_latency_208/
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9060/testReport/junit/(root)/non-boost%20tests/alternator_test_metrics_debug_3/

happened in PRs:
https://github.com/scylladb/scylladb/pull/17799
https://github.com/scylladb/scylladb/pull/18769

### PR DESCRIPTION
**Pull request by nyh**
The Alternator test test_metrics.py::test_item_latency confirms that for several operation types (PutItem, GetItem, DeleteItem, UpdateItem) we did not forget to measure their latencies.

The test checked that a latency was updated by checking that two metrics increases:
    scylla_alternator_op_latency_count
    scylla_alternator_op_latency_sum

However, it turns out that the "sum" is only an approximate sum of all latencies, and when the total sum grows large it sometimes does *not* increase when a short latency is added to the statistics. When this happens, this test fails on the assertion that the "sum" increases after an operation. We saw this happening sometimes in CI runs.

The simple fix is to stop checking _sum at all, and only verify that the _count increases - this is really an integer counter that unconditionally increases when a latency is added to the histogram.

Don't worry that the strength of this test is reduced - this test was never meant to check the accuracy or correctness of the histograms - we should have different (and better) tests for that, unrelated to Alternator. The purpose of *this* test is only to verify that for some specific operation like PutItem, Alternator didn't forget to measure its latency and update the histogram. We want to avoid a bug like we had in counters in the past (#9406).

Fixes #18847.

This patch un-flakes a recently introduced test, introduced in commit d207962e40cdf8fa977941e5a7afb5c7353d3138, so it should be backported to 6.0 but the faulty test does not exist in earlier branches.

### CODE REVIEW

**Review by amnonh — APPROVED** [review]
LGTM

**Comment by denesb** [comment]
Looks like CI is running for ~2days now....

**Comment by nyh** [comment]
> Looks like CI is running for ~2days now....

This can't be my patch's fault - all it does is to **remove** an assert from a test, to make it less flaky.
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/9441/ tells me:
```
jenkins pipeline failure: Error when executing always post condition:
at hudson.model.Computer.recordTermination(Computer.java:242)
```
I have no idea what this means.
I restarted that CI run. Let's see what happens.

**Comment by mykaul** [comment]
@scylladb/scylla-maint - please review and merge

**Comment by nyh** [comment]
By the way, I opened https://github.com/scylladb/scylladb/issues/19081 on the issue that the histogram "sum" is not accurate. But as I explained above, this test doesn't need to rely on the "sum" being accurate - all this tests wants to verify is that some latency histogram get updated, and for that it's enough to see that the "count" (which is accurate) increased, so this is the fix in this PR.

**Comment by nyh** [comment]
Hallelujah, the CI passed. Thanks @avikivity for merging.

**Comment by mykaul** [comment]
Now we need the backport.

**Pull request closed without merging**
