### PR TITLE
Introduce schema/ module

### PR DESCRIPTION
**Pull request by avikivity**
Schema related files are moved there. This excludes schema files that also interact with mutations, because the mutation module depends on the schema. Those files will have to go into a separate module.

### CODE REVIEW

**Comment by michoecho** [comment]
Are these "introduce module" changes moving towards some "physical" build system changes (e.g. C++ modules) to help the toolchain, or are only logical (/for readability)?

**Comment by denesb** [comment]
> Are these "introduce module" changes moving towards some "physical" build system changes (e.g. C++ modules) to help the toolchain, or are only logical (/for readability)?

Yes.

Both, but now that C++ module support is on the horizon, we have to motivation we lacked when readability was the only gain.

**Review by denesb — APPROVED** [review]

**Comment by avikivity** [comment]
We can try to create libraries ahead of the real module implementation. A test will only link with the libraries it uses.

**Review by nyh — APPROVED** [review]

**Comment by tchaikov** [comment]
> Are these "introduce module" changes moving towards some "physical" build system changes (e.g. C++ modules) to help the toolchain, or are only logical (/for readability)?

@michoecho hi, Michał, i think Avi's change paves the road to a C++20 modular world. as, in C++20 modular, all module units are well defined. and only public interfaces are exposed. so if we want to define different subsystems in scylla using modules, we will have to define a set of public interfaces for each of them. so they only talk to each other with the public interfaces exposed by each modules. also, we need to use a finer granularity interfaces instead of a single blob, i.e., modules to model the dependencies. as each module will have is own interface definition and precompiled module interface file (likely the AST etc.)

**Comment by nyh** [comment]
> > Are these "introduce module" changes moving towards some "physical" build system changes (e.g. C++ modules) to help the toolchain, or are only logical (/for readability)?
> 
> @michoecho hi, Michał, i think Avi's change paves the road to a C++20 modular world. 

I know that some developers _don't_ like them, but this is exactly why I created very-long-lived issues like issue https://github.com/scylladb/scylladb/issues/1 (compilation is slow) and https://github.com/scylladb/scylladb/issues/7871 (get rid of asserts and aborts). These long-lived issues allows someone to lay out a desired goal - even if this goal is several years away (or even if will never be fully achieved), and then allows developers to **dispute** the goal or ask for it to be changed even a long time after it was presented, it allows developers who send patches to Refs this issue to claim that their patch brings us one step closer to this goal - and it allows reviewers to verify that the patch is indeed relevant to the stated goal.

I think it would be nice if someone created such an issue about "modules", where he would also explain why moving stuff into subdirectories is important for this goal (to be honest, I don't understand this myself and the explanation above didn't completely satisfied me because it doesn't even mention subdirectories).

**Comment by tchaikov** [comment]
> > > Are these "introduce module" changes moving towards some "physical" build system changes (e.g. C++ modules) to help the toolchain, or are only logical (/for readability)?
> > 
> > 
> > @michoecho hi, Michał, i think Avi's change paves the road to a C++20 modular world.
> 
> I know that some developers _don't_ like them, but this is exactly why I created very-long-lived issues like issue #1 

what do you mean by "them?

> (compilation is slow) and #7871 (get rid of asserts and aborts). These long-lived issues allows someone to lay out a desired goal - even if this goal is several years away (or even if will never be fully achieved), and then allows developers to **dispute** the goal or ask for it to be changed even a long time after it was presented, it allows developers who send patches to Refs this issue to claim that their patch brings us one step closer to this goal - and it allows reviewers to verify that the patch is indeed relevant to the stated goal.
> 
> I think it would be nice if someone created such an issue about "modules", where he would also explain why moving stuff into subdirectories is important for this goal (to be honest, I don't understand this myself and the explanation above didn't completely satisfied me because it doesn't even mention subdirectories).

@nyh  i admit that i failed to connect C++ modules to subdirectories. not sure if https://github.com/tchaikov/seastar/blob/cxx-modules-impl/modules/CMakeLists.txt helps. one of the reasons why subdirectories help might be that it helps us to group the source files into modules. well, we can still group them without subdirectories. it just visually groups them into modules.

**Comment by nyh** [comment]
> > I know that some developers _don't_ like them, but this is exactly why I created very-long-lived issues like issue #1
> 
> what do you mean by "them"?

Yes, I wrote a slightly too-hard-to-parse sentence. The "them" in the first part of the sentence refers to the "long-lived-issues" which I only introduced in the second part of the sentence.

What I want to do was to recommend that when someone starts a long-term project to improve some aspect of the code, they should open an issue about it which explains why they are starting to work towards this direction. I also wanted to concede that some other developers **don't like** these long-term open-ended issues, and more then once in the past complained when I opened them. 

> > I think it would be nice if someone created such an issue about "modules", where he would also explain why moving stuff into subdirectories is important for this goal (to be honest, I don't understand this myself and the explanation above didn't completely satisfied me because it doesn't even mention subdirectories).
 
> @nyh i admit that i failed to connect C++ modules to subdirectories.

This patch and similar patches says the word "modules" in the title, but the patch itself has nothing to do with C++ modules and instead mostly moves files around - usually into a subdirectory. I would have liked to have an issue that explains why modules is a good goal, and why moving source files around the directory is an important part of this goal. And then I would have liked PRs that do this to refer to this issue - as a justification for this PR.

> not sure if https://github.com/tchaikov/seastar/blob/cxx-modules-impl/modules/CMakeLists.txt helps.

It doesn't because
1. When I reviewed this PR, I had no idea that I should look at this specific file inside the Seastar (!) project.
2. Even if I look at it now, I hstill ave no idea why you sent me this file... It doesn't include any comments. What does it explain?

> I one of the reasons why subdirectories help might be that it helps us to group the source files into modules. well, we can still group them without subdirectories. it just visually groups them into modules.

I can understand how visually grouping files into subdirectories is convenient and helpful for understanding. But since Avi and you are apparently on a campaign to move things into subdirectories, and have multiple patches on this topic, I think it's worth taking the time to write out the end goals and intermediate goals of this campaign, to better help reviewers be able to judge whether any specific patch really fits these goals. Otherwise, you can "excuse" virtually any code-reorgranization patch by saying "this will be better for C++ modules". Some code-reogranizations do indeed provide better readability, better organization, etc., but aren't really about "modules" so modules shouldn't be an excuse for every improvement.

**Comment by tchaikov** [comment]
created #12962 . it's far from perfect . i will fill the issue with more details.

**Comment by nyh** [comment]
Thanks. But this issue doesn't say much about the subdirectories and cmake changes which has been the topic of recent patches that claimed to be about "modules".

I have some doubts how much modules will improve build speed (issue #1), but probably it's just my own ignorance (I never did anything with modules). In my past experience without modules, compilation speed was **never** directly related to the header file size (making it beneficial to include less headers) and was always about the **amount of generated code**, mostly the amount of instantiated templates. We have source files (like I think messaging_service.cc) which takes minutes to compile because they have a lot of statements that require template instantiation - completely unrelated to the amount of header files they include.

**Comment by tchaikov** [comment]
i will add more details tomorrow. it's related to how CMake models the C++ modules.

**Comment by tchaikov** [comment]
> Thanks. But this issue doesn't say much about the subdirectories and cmake changes which has been the topic of recent patches that claimed to be about "modules".
> 
> I have some doubts how much modules will improve build speed (issue #1), but probably it's just my own ignorance (I never did anything with modules). In my past experience without modules, compilation speed was **never** directly related to the header file size (making it beneficial to include less headers) and was always about the **amount of generated code**, mostly the amount of instantiated templates. We have source files (like I think messaging_service.cc) which takes minutes to compile because they have a lot of statements that require template instantiation - completely unrelated to the amount of header files they include.

i think the precompiled AST should help to speed up the compilation, no? but if templates resides right in the source file being compiled, then yeah, even C++ modules cannot help in this case.

**Comment by avikivity** [comment]
clang can output information about how long it takes to parse vs. generate code.

**Comment by avikivity** [comment]
Switching from -O2 to -O0 cuts storage_proxy.o compilation time from 38 seconds to 20 seconds (dev mode).

**Comment by avikivity** [comment]
-O1 -> 30 seconds

**Comment by michoecho** [comment]
> clang can output information about how long it takes to parse vs. generate code.

messaging_service.cc (release mode):
image

storage_proxy.cc (release mode):
image

storagy_proxy.cc (dev mode):
image

**Comment by michoecho** [comment]
(I'm not making any point, just throwing random illustrations to things mentioned earlier, because illustrations are cool.)

**Comment by avikivity** [comment]
We're more interested in dev mode compile times, since those happen more often when a human is waiting for them.

**Comment by nyh** [comment]
> We're more interested in dev mode compile times, since those happen more often when a human is waiting for them.

Right. A very promising direction you began to look at in the past is to un-templatize (and use stuff like std::function) various pieces of code in dev build mode because the performance penalty is minimal but the compilation-time improvement can be huge (because, again, I claim that the build time is proportional to the generated code, not amount of parsing of header files). For this, we also need to use traditional header files, not "modules".

**Comment by tchaikov** [comment]
> In [#1 (comment)](https://github.com/scylladb/scylladb/issues/1#issuecomment-1005191229) I mentioned that improving build time is actually two separate goals. One is improving the build time of everything from scratch. I'm not optimistic that modules will help much there.

please note, both seastar and C++ standard library can be modularized. and we can benefit from this even when building the tree from scratch.

**Comment by avikivity** [comment]
> > We're more interested in dev mode compile times, since those happen more often when a human is waiting for them.
> 
> Right. A very promising direction you began to look at in the past is to un-templatize (and use stuff like std::function) various pieces of code in dev build mode because the performance penalty is minimal but the compilation-time improvement can be huge (because, again, I claim that the build time is proportional to the generated code, not amount of parsing of header files). For this, we also need to use traditional header files, not "modules".

Modules are orthogonal to type erasure. They don't conflict with it.

**Comment by avikivity** [comment]
wallclock times:

-O2:

build	8m7.887s
test 	3m33.237s

-O0:
build	6m34.344s
test 	9m0.871s

So -O2 still looks better.

**Comment by nyh** [comment]
Let's not forge that the goal of dev build mode was to do whatever we can while only slowing down tests "a bit" - we can argue what "a bit" means, but definitely not 3-fold and not even 2-fold.
I don't think the arithmetic sum of the build and test is what matters. This only matters for Jenkins, but us human developers the two things are almost unrelated:
1. When you use non-C++ test framework (we have a lot of those now), you often run Scylla many times for one build
2. On the other hand, when you develop you often build many times without running a test even once.

**Comment by nyh** [comment]
See explanation of why -O2 was chosen over -O1 (in clang) in commit 4fd5ef92ae61e234090779ced46f0dae8346eb28

**Comment by avikivity** [comment]
Yes, I was trying to measure whether it's still the case.

IIRC @michoecho said that with clang 15 -O1 and -O2 are similar.

**Comment by michoecho** [comment]
> IIRC @michoecho said that with clang 15 -O1 and -O2 are similar.

I only spoke about the optimization passes they execute. There are very few passes which are in O2 and not O1, and these passes didn't look to my untrained eye like ones that are supposed to be very time-consuming, but I didn't actually measure the times. You just said that you measured storage_proxy.cc at 38s with O2 and 30s with O1. That's quite a large difference — perhaps my intuition about the cost of the additional passes was wrong.

**Comment by avikivity** [comment]
Ah I forgot that. I guess I should also do a full build/run cycle with -O1.

**Comment by avikivity** [comment]
-O1:

build	7m57.869s
tes t	3m33.788s

**Comment by avikivity** [comment]
It looks like wall time dominates testing. 

user time for O1/O2 testing:

O1: 22m3s
O2: 20m53s

**Comment by nyh** [comment]
@avikivity when you measure wall time for an entire test run, you need to watch out for stragglers, which hide the real run time. I care about a single test, usually, not the entire test suite which I almost never run (I let the CI do this for me). 

Personally, I mostly care about Scylla boot time (which you can see in the beginning of a test/alternator/run output, for example). I want to see my test starting in 0.4 seconds (the current -O2 boot time), not in 10 seconds. But also try to run the entire test/alternator/run as an example - it's all sequential (no parallelization so no stragglers to hide slowness).

**Pull request closed without merging**
