### PR TITLE
Update cloud-instance-recommendations.rst

### PR DESCRIPTION
**Pull request by nopzdk**
updated storage size for n2-highmem-32 to 9000GB as this is default in SC

### CODE REVIEW

**Comment by tzach** [comment]
Fix https://github.com/scylladb/scylladb/issues/20121

**Comment by tzach** [comment]
The fix makes sense for *max* storage, but I guess it can also work for *recommended*.
LGTM

**Comment by avikivity** [comment]
Please use your work address, not gmail, so we can trace our contributors.

**Comment by tchaikov** [comment]
closing in favor of #21537, which sets the Author information with the mail address suggested by Avi.

**Comment by tchaikov** [comment]
@annastuchlik @nopzdk hi Anna and Michael, i took the liberty to create the pull request at #21537, could you please help review it?

**Pull request closed without merging**
