### PR TITLE
github: sync_labels: use ${{}} expression syntax in "if" condition

### PR DESCRIPTION
**Pull request by tchaikov**
to ensure that the expression is evaluated properly. see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsif

### CODE REVIEW

**Review by yaronkaikov — APPROVED** [review]

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint  please merge

**Comment by tchaikov** [comment]
tested at https://github.com/tchaikov/scylladb/actions/runs/8505621434/job/23294418516?pr=4

**Comment by yaronkaikov** [comment]
> tested at https://github.com/tchaikov/scylladb/actions/runs/8505621434/job/23294418516?pr=4

It failed ;-(

**Comment by tchaikov** [comment]
failed. because it didn't include #18125 and because this step was triggered. that's a proof that this change addresses the problem.

**Pull request closed without merging**
