### PR TITLE
Branch 5.1 backport scylla prepare fixes

### PR DESCRIPTION
**Pull request by vladzcloudius**
This PR:
* Switches scylla_prepare to a new perftune.py semantics.
* Fixes a regression introduced during an attempt to make scylla_cpuset_setup idempotent (#11385).
* Makes scylla_cpuset_setup idempotent.

### CODE REVIEW

**Comment by vladzcloudius** [comment]
@avikivity I intentionally didn't squash patch 1 and patch 3 in order to preserve the cherry-pick trail. Let me know if you want me to squash them (since 3 fixes a regression introduced by 1).

**Comment by avikivity** [comment]
I prefer to keep the patches separated.

I see all patches have Fixes #..., so don't need a new one for the series.

But, what about 5.2 and 5.3? Do they have everything?

**Comment by vladzcloudius** [comment]
> I prefer to keep the patches separated.
> 
> I see all patches have Fixes #..., so don't need a new one for the series.
> 
> But, what about 5.2 and 5.3? Do they have everything?

Didn't check. Let me check and send separate PRs if needed.

**Comment by vladzcloudius** [comment]
Both branch-5.2 and branch-5.3 have these 3 patches, @avikivity

**Comment by DoronArazii** [comment]
@avikivity ping

**Comment by avikivity** [comment]
Queued as 0d5751b4b6976279bdbb49b9f4ed3bad2c6a9a0c

**Comment by DoronArazii** [comment]
Already part of 5.1
Closing PR.

**Pull request closed without merging**
