### PR TITLE
Storage Proxy: Maintain metrics in response handler classes

### LINKED ISSUE #5797: some background_read counters are underflow
*Installation details*
Scylla version (or git commit hash): a8a4e584ec3332067b6b9e1756ba1bf2392e1424
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

`scylla_storage_proxy_coordinator_background_reads{scheduling_group_name="main",shard="0",type="queue_length"} 18446744073709551616.000000`

caused by 971711a5461c09421f1c9b1b3b2d9f6209a425da

### PR DESCRIPTION
**Pull request by eliransin**
There is a known problem introduced by 971711a, the problem
is that when some callbacks for a created response handler
are called from another scheduling groups an imbalance is
introduced to statistics which are now instantiated per
scheduling group. This can be easily solved by "remembering"
the stats of the scheduling group where the response handler
was created. This will mask out another problem where certain
operations are done outside of the "native" scheduling group.
This is a complex issue that needs to be addressed in separate
commit (see 971711a commit message).

Fixes #5797

### CODE REVIEW

**Comment by eliransin** [comment]
An older version of the patch have already been reviewed by @gleb-cloudius and @psarna , the patch title in the mailing list is:
`[PATCH] Storage Proxy: Maintain metrics in response handler classes`
The main change since the older patch is the introduction of paxos_executor and paxos stats to the structure.

**Comment by slivne** [comment]
@eliransin / @psarna / @gleb-cloudius is this till relevant if so lets review / merge

**Comment by eliransin** [comment]
We will need this fix.
@gleb-cloudius can you review?

**Review by gleb-cloudius — COMMENTED** [review]
That unfortunately enlarges each response handler by 8 bytes. Can we do better? For instance remembering scheduling group id instead of the reference? Also can a scheduling group disappear?

**Comment by eliransin** [comment]
This was done already

**Pull request closed without merging**
