### PR TITLE
[Backport 6.0] cql: improve validating RF's change in ALTER tablets KS

### PR DESCRIPTION
**Pull request by ptrsmrn**
This patch series fixes a couple of bugs around validating if RF is not changed by too much when performing ALTER tablets KS.
RF cannot change by more than 1 in total, because tablets load balancer cannot handle more work at once.

Fixes: https://github.com/scylladb/scylladb/issues/20039

Should be backported to 6.0 & 6.1 (wherever tablets feature is present), as this bug may break the cluster.

(cherry picked from commit https://github.com/scylladb/scylladb/commit/042825247f838203c14a770b753ff26a23e6836b)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/adf453af3f391dbd10f787eb16aa8c8ea61f32d5)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/9c5950533fb92ca7e44152dda761fa3a212da526)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/47acdc1f9847a89fcf5a4336d8e79b3d1fdeb671)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/93d61d7031b59a4338599a798ebc20febb2633d2)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/6676e473711161333ec4686fef4167d8eda89b3f)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/2aabe7f09cad0639532b8b98c65539e64cfb6140)

(cherry picked from commit https://github.com/scylladb/scylladb/commit/ee56bbfe6136a4f49be92705bca8c5df8e96bcc8)

Refs https://github.com/scylladb/scylladb/pull/20208

Closes: #21011

### CODE REVIEW

**Comment by ptrsmrn** [comment]
Blocked until https://github.com/scylladb/scylladb/issues/21034#issuecomment-2405660620 is resolved

**Comment by kbr-scylla** [comment]
Probably a better way would've been to include https://github.com/scylladb/scylladb/pull/21056  in the backport PRs, but OK.

**Comment by kbr-scylla** [comment]
What were the merge conflicts? How were they resolved? Was there anything substantial?

**Comment by ptrsmrn** [comment]
> What were the merge conflicts? How were they resolved? Was there anything substantial?

The conflicts were due to missing refactor. After resolving merge conflicts, the code still didn't compile, because some some functions' signatures have changed, which I fixed as well. All this was minor.
You can see for yourself if you compare the diffs:
1. 6.0 backport - https://patch-diff.githubusercontent.com/raw/scylladb/scylladb/pull/21047.diff
2. the original PR - https://github.com/scylladb/scylladb/pull/20208.diff

**Comment by kbr-scylla** [comment]
> The conflicts were due to missing refactor.

Would've been easier if you were more specific.

`git range-diff 042825247f^..ee56bbfe61 9810fb3efd^..2557991f92` (042825247f^..ee56bbfe61 are from `master`, 9810fb3efd^..2557991f92 are from this PR):
```diff
1:  042825247f ! 1:  9810fb3efd cql: remove unused helper function from test_tablets
    @@ Commit message
         `replication_factor` tag, which is forbidden in ALTER tablets KS
         statement.
     
    +    (cherry picked from commit 042825247f838203c14a770b753ff26a23e6836b)
    +
      ## test/cql-pytest/test_tablets.py ##
     @@ test/cql-pytest/test_tablets.py: def test_alter_tablet_keyspace(cql, this_dc):
                  cql.execute(f"ALTER KEYSPACE {keyspace} WITH REPLICATION = {{ 'class' : 'NetworkTopologyStrategy', '{rf_opt}' : {new_rf} }}")
2:  adf453af3f ! 2:  b3fcd9fc5b cql: refactor test_tablets::test_alter_tablet_keyspace
    @@ Commit message
         in general.
         2. Fixed whitespaces according to PEP8
     
    +    (cherry picked from commit adf453af3f391dbd10f787eb16aa8c8ea61f32d5)
    +
      ## test/cql-pytest/test_tablets.py ##
     @@ test/cql-pytest/test_tablets.py: def test_lwt_support_with_tablets(cql, test_keyspace, skip_without_tablets):
      # We want to ensure that we can only change the RF of any DC by at most 1 at a time
3:  9c5950533f ! 3:  4172d34c5c cql: extend test_alter_tablet_keyspace_rf
    @@ Commit message
         Added cases to also test decreasing RF and setting the same RF.
         Also added extra explanatory comments.
     
    +    (cherry picked from commit 9c5950533fb92ca7e44152dda761fa3a212da526)
    +
      ## test/cql-pytest/test_tablets.py ##
     @@ test/cql-pytest/test_tablets.py: def test_alter_tablet_keyspace_rf(cql, this_dc):
              def change_dc_rf(new_rf):
4:  47acdc1f98 ! 4:  e03cc8aa6c cql: validate RF change for new DCs in ALTER tablets KS
    @@ Commit message
         change constraints.
     
         Refs: #20039
    +    (cherry picked from commit 47acdc1f9847a89fcf5a4336d8e79b3d1fdeb671)
     
      ## cql3/statements/alter_keyspace_statement.cc ##
     @@ cql3/statements/alter_keyspace_statement.cc: void cql3::statements::alter_keyspace_statement::validate(query_processor& qp, c
    @@ test/topology_custom/test_tablets.py
     +from cassandra.protocol import ConfigurationException, InvalidRequest
      from cassandra.query import SimpleStatement, ConsistencyLevel
      from test.pylib.manager_client import ManagerClient
    - from test.pylib.rest_client import HTTPError, read_barrier
    + from test.pylib.rest_client import HTTPError
     @@ test/topology_custom/test_tablets.py: async def test_tablet_mutation_fragments_unowned_partition(manager: ManagerClien
                  await cql.run_async(f"SELECT partition_region FROM MUTATION_FRAGMENTS(test.test) WHERE pk={k}", host=host[0])
      
5:  93d61d7031 ! 5:  0913a15dc1 cql: harden `alter_keyspace_statement.cc::validate_rf_difference`
    @@ Commit message
         into an `int` type and somehow the code was still running fine, but only
         extra testing added later discovered a bug in here.
     
    +    (cherry picked from commit 93d61d7031b59a4338599a798ebc20febb2633d2)
    +
      ## cql3/statements/alter_keyspace_statement.cc ##
     @@
      #include <boost/range/algorithm.hpp>
6:  6676e47371 ! 6:  7aceb8a763 cql: fix validation of ALTERing RFs in tablets KS
    @@ Commit message
         2. Removing `REPLICATION_STRATEGY_CLASS_KEY` key from a map of RFs that
            needs their RFs to be validated.
     
    +    (cherry picked from commit 6676e473711161333ec4686fef4167d8eda89b3f)
    +
      ## cql3/statements/alter_keyspace_statement.cc ##
     @@ cql3/statements/alter_keyspace_statement.cc: void cql3::statements::alter_keyspace_statement::validate(query_processor& qp, c
                  auto new_ks = _attrs->as_ks_metadata_update(ks.metadata(), *qp.proxy().get_token_metadata_ptr(), qp.proxy().features());
7:  2aabe7f09c ! 7:  f05b9adba6 cql: join new and old KS options in ALTER tablets KS
    @@ Commit message
         test's body has been modified to wait for ALTER to complete before
         performing validation.
     
    +    (cherry picked from commit 2aabe7f09cad0639532b8b98c65539e64cfb6140)
    +
      ## cql3/statements/alter_keyspace_statement.cc ##
    -@@ cql3/statements/alter_keyspace_statement.cc: bool cql3::statements::alter_keyspace_statement::changes_tablets(query_processor
    -     return ks.get_replication_strategy().uses_tablets() && !_attrs->get_replication_options().empty();
    +@@ cql3/statements/alter_keyspace_statement.cc: void cql3::statements::alter_keyspace_statement::validate(query_processor& qp, c
    + #endif
      }
      
    ++bool cql3::statements::alter_keyspace_statement::changes_tablets(query_processor& qp) const {
    ++    auto ks = qp.db().find_keyspace(_name);
    ++    return ks.get_replication_strategy().uses_tablets() && !_attrs->get_replication_options().empty();
    ++}
    ++
     +namespace {
     +// These functions are used to flatten all the options in the keyspace definition into a single-level map<string, string>.
     +// (Currently options are stored in a nested structure that looks more like a map<string, map<string, string>>).
    @@ cql3/statements/alter_keyspace_statement.cc: bool cql3::statements::alter_keyspa
     +}
     +} // <anonymous> namespace
     +
    - future<std::tuple<::shared_ptr<cql_transport::event::schema_change>, cql3::cql_warnings_vec>>
    - cql3::statements::alter_keyspace_statement::prepare_schema_mutations(query_processor& qp, service::query_state& state, const query_options& options, service::group0_batch& mc) const {
    + future<std::tuple<::shared_ptr<cql_transport::event::schema_change>, std::vector<mutation>, cql3::cql_warnings_vec>>
    + cql3::statements::alter_keyspace_statement::prepare_schema_mutations(query_processor& qp, const query_options&, api::timestamp_type ts) const {
          using namespace cql_transport;
     @@ cql3/statements/alter_keyspace_statement.cc: cql3::statements::alter_keyspace_statement::prepare_schema_mutations(query_proce
              auto ks_md_update = _attrs->as_ks_metadata_update(ks_md, tm, feat);
    @@ cql3/statements/alter_keyspace_statement.cc: cql3::statements::alter_keyspace_st
     +        auto old_ks_options = get_old_options_flattened(ks, include_tablet_options);
     +        auto ks_options = get_current_options_flattened(_attrs, include_tablet_options, feat);
     +        ks_options.merge(old_ks_options);
    -+
    -         auto ts = mc.write_timestamp();
    -         auto global_request_id = mc.new_group0_state_id();
      
              // we only want to run the tablets path if there are actually any tablets changes, not only schema changes
    +-        if (ks.get_replication_strategy().uses_tablets() && !_attrs->get_replication_options().empty()) {
     +        // TODO: the current `if (changes_tablets(qp))` is insufficient: someone may set the same RFs as before,
     +        //       and we'll unnecessarily trigger the processing path for ALTER tablets KS,
     +        //       when in reality nothing or only schema is being changed
    -         if (changes_tablets(qp)) {
    ++        if (changes_tablets(qp)) {
                  if (!qp.topology_global_queue_empty()) {
    -                 return make_exception_future<std::tuple<::shared_ptr<::cql_transport::event::schema_change>, cql3::cql_warnings_vec>>(
    +                 return make_exception_future<std::tuple<::shared_ptr<::cql_transport::event::schema_change>, std::vector<mutation>, cql3::cql_warnings_vec>>(
    +                         exceptions::invalid_request_exception("Another global topology request is ongoing, please retry."));
    +
    + ## cql3/statements/alter_keyspace_statement.hh ##
    +@@ cql3/statements/alter_keyspace_statement.hh: class ks_prop_defs;
    + class alter_keyspace_statement : public schema_altering_statement {
    +     sstring _name;
    +     ::shared_ptr<ks_prop_defs> _attrs;
    ++    bool changes_tablets(query_processor& qp) const;
    + 
    + public:
    +     alter_keyspace_statement(sstring name, ::shared_ptr<ks_prop_defs> attrs);
     
      ## cql3/statements/ks_prop_defs.cc ##
     @@ cql3/statements/ks_prop_defs.cc: bool ks_prop_defs::get_durable_writes() const {
8:  ee56bbfe61 ! 8:  2557991f92 cql: sum of abs RFs diffs cannot exceed 1 in ALTER tablets KS
    @@ Commit message
         if the sum of absoulte differences of RFs specified in the statement is
         not greter than 1.
     
    +    (cherry picked from commit ee56bbfe6136a4f49be92705bca8c5df8e96bcc8)
    +
      ## cql3/statements/alter_keyspace_statement.cc ##
     @@ cql3/statements/alter_keyspace_statement.cc: future<> cql3::statements::alter_keyspace_statement::check_access(query_processo
          return state.has_keyspace_access(_name, auth::permission::ALTER);
```

The only interesting part is `7:  2aabe7f09c ! 7:  f05b9adba6`. You added `changes_tablets`.


It looks like you included 9ddfc2ce4ba6afdf24fe0f2cfe615809a636dc17 -- but why not cherry-pick this commit separately? Instead you included the diff inside f05b9adba6. Making it harder to review and harder to track what's backported and what's not backported.

Alternatively -- and I would prefer this -- do not include this refactor at all. I see nothing wrong with using the `if (ks.get_replication_strategy().uses_tablets() && !_attrs->get_replication_options().empty()) {` logic from before the refactor.

The `TODO` comment refers to `changes_tablets` but I think you can remove the `TODO` comment. If we fix the TODO we'll do it on `master` branch first anyway.

**Comment by kbr-scylla** [comment]
This is a minor problem, and we want to unblock 2024.2, so I'm merging.
But please take my comments into account for future backport

**Comment by ptrsmrn** [comment]
> This is a minor problem, and we want to unblock 2024.2, so I'm merging. But please take my comments into account for future backport

Sure, thanks. I wasn't aware how exactly backports are suppose to happen in case there's a conflict. I was also under the impression that, at least in case of 6.0 branch, we want to effortlessly get the code in and that's because other than the original PR, I have 3 backport PRs (so 4 PRs in total), so "lots" to handle, and 6.0, being the oldest release, will stop being supported soon, so "why bother with it".

**Pull request merged**
