### PR TITLE
bptree: Replace assert with static_assert

### PR DESCRIPTION
**Pull request by xemul**
The one runs under checked constexpr value anyway

### CODE REVIEW

**Review by avikivity — APPROVED** [review]

**Comment by xemul** [comment]
@benipeled , the "AWS Amplify Console Web Preview" failed, what does it mean?

**Comment by xemul** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2868/

#14944 , #14885 , #14011

**Comment by mykaul** [comment]
> @benipeled , the "AWS Amplify Console Web Preview" failed, what does it mean?

@DanielHe4rt I think knows.

**Comment by tchaikov** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2877/

known issue: #14944

**Review by denesb — APPROVED** [review]

**Pull request closed without merging**
