### PR TITLE
Update node exporter to v1.6.1

### PR DESCRIPTION
**Pull request by mykaul**
Fixes: https://github.com/scylladb/scylladb/issues/15044

### CODE REVIEW

**Comment by mykaul** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3053/

```
 [302/3077] tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.6.1.linux-amd64 build/node_exporter
 FAILED: build/node_exporter/node_exporter 
 tar -C build -xvpf /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz --no-same-owner && rm -rfv build/node_exporter && mv -v build/node_exporter-1.6.1.linux-amd64 build/node_exporter
 tar: /opt/scylladb/dependencies/node_exporter-1.6.1.linux-amd64.tar.gz: Cannot open: No such file or directory
 tar: Error is not recoverable: exiting now
```

Not very surprising, as it doesn't seem to run install-dependencies.sh with the new version...

**Comment by mykaul** [comment]
@avikivity - I assume this requires re-generating dbuild, so the dependency is downloaded to it? Is there a way to trigger this before standard build?

**Comment by mykaul** [comment]
> @avikivity - I assume this requires re-generating dbuild, so the dependency is downloaded to it? Is there a way to trigger this before standard build?

@yaronkaikov - is that something your team does, or just Avi?

**Comment by yaronkaikov** [comment]
> > @avikivity - I assume this requires re-generating dbuild, so the dependency is downloaded to it? Is there a way to trigger this before standard build?
> 
> @yaronkaikov - is that something your team does, or just Avi?

If it's to re-generate dbuild. normally it's @avikivity

**Comment by avikivity** [comment]
I'll merge this now, combining it with a clang update.

**Comment by mykaul** [comment]
We'll need to backport it to earlier releases, as the Go components the current node exporter version in those releases suffers from vulnerabilities, so vul scanners alert on them.

**Pull request closed without merging**
