### PR TITLE
tools/scylla-nodetool: implement info 

### PR DESCRIPTION
**Pull request by tchaikov**
Refs #15588

### CODE REVIEW

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6968/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6968/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8147/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/110/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6968/)
> 
> #### Failed Tests (18/23381):
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_5) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_6) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_7) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_8) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [test.nodetool.test_info](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/%28empty%29/test_nodetool_test_info_9) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test.nodetool.test_info)
> * [nodetool.test_info.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6968/testReport/junit/%28root%29/non-boost%20tests/nodetool_test_info_debug_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+nodetool.test_info.debug.1)
> 
> #### Build Details:
> * Duration: 1 hr 47 min
> * Builder: spider8.cloudius-systems.com

failures were caused the newly introduced change. let's blame the last minute change in my branch for upstreaming the subcommand.

**Comment by tchaikov** [comment]
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6973/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6973/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/118/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8154/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6973/)
> 
> #### Failed Tests (2/23390):
> * [test_change_two](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6973/testReport/junit/%28root%29/test_change_ip/test_change_two) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_change_two)
> * [topology.test_change_ip.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/6973/testReport/junit/%28root%29/non-boost%20tests/topology_test_change_ip_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology.test_change_ip.release.1)
> 
> #### Build Details:
> * Duration: 1 hr 47 min
> * Builder: spider3.cloudius-systems.com

#17444

**Review by denesb — APPROVED** [review]

**Comment by tchaikov** [comment]
@scylladb/scylla-maint hello maintainers, could you help queue this change?

**Comment by tchaikov** [comment]
> #### 🔴 CI State: ABORTED
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6974/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6974/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8155/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6974/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/119/)
> #### Build Details:
> 
>     * Duration: 2 hr 4 min
> 
>     * Builder: spider3.cloudius-systems.com

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/119/ the failure is gone. so i am not able to annotate it.

**Pull request closed without merging**
