### PR TITLE
Fix frozen mutation consume ordering

### PR DESCRIPTION
**Pull request by mikolajsieluzycki**

### CODE REVIEW

**Comment by denesb** [comment]
@bhalevy what's up with this PR? Will someone take over it?
I think the first 3 commits of this was already merged as part of #11129.

**Comment by bhalevy** [comment]
> @bhalevy what's up with this PR? Will someone take over it? I think the first 3 commits of this was already merged as part of #11129.

Yes, I planned to take it from here.
You can too of course.

**Comment by mykaul** [comment]
@bhalevy , @denesb - worth keeping this open?

**Comment by bhalevy** [comment]
Sorry, this PR can be closed.
It was reworked in #11269

**Pull request closed without merging**
