### PR TITLE
adding top banner to the Docs website with a link to the ScyllaDB Uni…

### PR DESCRIPTION
**Pull request by guy9**
…versity fall LIVE event
@annastuchlik please review

### CODE REVIEW

**Review by tzach — APPROVED** [review]
LGTM

**Review by annastuchlik — APPROVED** [review]
LGTM

**Comment by avikivity** [comment]
I don't think the source tree is the right place for advertisements. There should be a different way to add transient notifications to the documentation site.

**Comment by annastuchlik** [comment]
@avikivity The documentation look and feel is implemented via the Sphinx theme, including notifications. Apart from the banner, there are also user messages, such as a notification when a user is viewing the docs for a deprecated/unstable ScyllaDB version.

Enabling/disabling/updating the banner via the conf.py file is a very quick and easy way to let users know about ScyllaDB events. What would be the reason for finding a different way?

**Comment by tzach** [comment]
@avikivity have a point. It would be better to define a Banner in the theme which can be update externally with out PR per project.

**Comment by avikivity** [comment]
Let's say we create a branch. The branch will live as long as the version it supports, the advertisements it carries will get outdated.

In general it's not good to mix marketing with documentation.

**Comment by annastuchlik** [comment]
> In general it's not good to mix marketing with documentation.

As a rule, I agree.

> It would be better to define a Banner in the theme which can be update externally with out PR per project.

In theory, that could work. In practice, if you update the banner in the theme, you have to immediately release a new version of the theme - otherwise the banner will not be updated on the page. Merging a PR in the scylladb repo is less complicated and less time-consuming than releasing a new theme version. But yes, that would be an option.

> Let's say we create a branch. The branch will live as long as the version it supports, the advertisements it carries will get outdated.

In fact, this is not an issue because the banner does not change depending on the branch - it's visible regardless of which branch you choose from the drop-down (now there's only "master" and "5.1"). Sphinx only uses the conf.py file from the master branch, so the banner, versioning, etc. are only configured on master, but are visible across all versions.

@tzach @dgarcia360 
Let's discuss if there are other options to enable the banner in the docs.

**Pull request closed without merging**
