### PR TITLE
db/view/view.cc: rate limit view update error messages

### PR DESCRIPTION
**Pull request by cvybhu**
When propagating a view update to a paired view replica fails, there is an error message.
This message is printed for every mutation, which causes log spam when some node goes down.

This isn't a fatal error - it's normal that a remote view replica goes down, it'll hopefully receive the updates later through hints.

I'm unsure if the error message should be printed at all, but for now we can just rate limit it and that will improve the situation with log spamming.

Refs: #12711, #12321

### CODE REVIEW

**Comment by cvybhu** [comment]
I'm not marking it as a fix for #12711 yet, because there's still two things to be done:
1) Decide if the error message should be printed at all
2) See if hints are propagated correctly. Maybe this is an indication of incorrect hint behavior (also mentioned in #12711)

In the meantime we can merge this and improve the log spam situation.

**Comment by cvybhu** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4951/

```
19:00:55  + docker system prune -a -f --filter until=72h
19:00:55  Error response from daemon: a prune operation is already running
19:00:56  [Pipeline] }
19:00:56  [Pipeline] // script
19:00:56  Error when executing cleanup post condition:
19:00:56  hudson.AbortException: script returned exit code 1
19:00:56  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:667)
19:00:56  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:613)
19:00:56  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:557)
19:00:56  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
19:00:56  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
19:00:56  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
19:00:56  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
19:00:56  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
19:00:56  	at java.base/java.lang.Thread.run(Thread.java:829)
19:00:56  
```
Looks like an issue with the CI runner, I will restart the CI

cc @benipeled  (?)

**Comment by cvybhu** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4952/

Same thing, it fails at the "checkout" step :c

**Comment by benipeled** [comment]
@cvybhu a runner issue - I opened https://github.com/scylladb/scylla-pkg/issues/3343 and retrigger the CI for this change

**Comment by mykaul** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4956/

@cvybhu - are the above failures relevant for this one?

**Comment by cvybhu** [comment]
It's relevant, but it's really weird.
It looks like some test started failing because it detected the error messages that I rate limited.
Rate limiting error messages shouldn't influence this at all - the errors were there anyway, there was just more of them.
But now it's saying "Unexpected error". Were there no error messages before? What happened?

TBH I think we could just completely remove this error message. It's an internal error, but an expected one. It's normal that it happens when a node temporarily goes down. I will open a PR that removes the message altogether.

**Comment by denesb** [comment]
Rate limiting adds a message under the rate limited one, something like: `Rate limiting dropped XXX similar messages`. Maybe this confuses some error log filter which now fails to detect this error message as expected.

**Comment by fruch** [comment]
> Rate limiting adds a message under the rate limited one, something like: `Rate limiting dropped XXX similar messages`. Maybe this confuses some error log filter which now fails to detect this error message as expected.

Seems exactly that:
https://github.com/scylladb/scylla-dtest/blob/fd511485577edb9d4a3380c5263ed2835fd10735/materialized_views_test.py#L250

**Comment by cvybhu** [comment]
Let's just remove the message, it's expected that a remote view update fails sometimes. Nodes can go up and down.
Opened #13190, which removes the message

**Comment by mykaul** [comment]
> Let's just remove the message, it's expected that a remote view update fails sometimes. Nodes can go up and down. Opened #13190, which removes the message

I was actually in favor of this approach, for the time being. At least until we have more confidence in removing it altogether.

**Comment by cvybhu** [comment]
> I was actually in favor of this approach, for the time being. At least until we have more confidence in removing it altogether.

Ok, reopened for consideration.

> > Rate limiting adds a message under the rate limited one, something like: `Rate limiting dropped XXX similar messages`. Maybe this confuses some error log filter which now fails to detect this error message as expected.
> 
> Seems exactly that: https://github.com/scylladb/scylla-dtest/blob/fd511485577edb9d4a3380c5263ed2835fd10735/materialized_views_test.py#L250

Hmm so if I wanted the CI to pass I have to first open a PR to `scylla-dtest` to make it tolerate those messages, and then once it reaches the CI I can proceed with this PR for `scylladb`. I will do it.

**Comment by roydahan** [comment]
dtest PR was merged and passed next.

**Comment by cvybhu** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/150/

Looks like the CI failed on something unrelated:
```
>               raise HTTPError(uri, resp.status, params, json, text)
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/before-test/test_snapshot, params: None, json: None, body:
E               Exception when starting cluster ScyllaCluster(name: e70db53a-c714-11ed-a685-16657470b22d, running: ScyllaServer(58, 127.54.165.22, 77486b46-0152-4f27-9d7f-d20d4bd3c5d2), 
```

**Review by denesb — APPROVED** [review]

**Pull request closed without merging**
