### PR TITLE
Subscribe repair_info::abort on node_ops_meta_data::abort_source

### PR DESCRIPTION
**Pull request by xemul**
The storage_service::stop() calls repair_service::abort_repair_node_ops() but at that time the sharded<repair_service> is already stopped and call .local() on it just crashes.

The suggested fix is to remove explicit storage_service -> repair_service kick. Instead, the repair_infos generated for the sake of node-ops are subscribed on the node_ops_meta_data's abort source and abort themselves automatically.

fixes: #10284

### CODE REVIEW

**Comment by xemul** [comment]
Cc @Deexie

**Comment by xemul** [comment]
v2: dropped the patch that moved `node_ops_meta_data` to .cc file.
Older clang wanted to have it when compiling `std::unordered_map<utils::UUID, node_ops_metadata> _node_ops` field

**Comment by asias** [comment]
Looks good to me. Thanks.

**Review by asias — APPROVED** [review]

**Comment by xemul** [comment]
cql_session_test.py::TestCqlSession::test_cluster_exclusive_cql_cluster_session_after_node_restart times-out, seems unrelated, re-kicked CI

**Review by denesb — APPROVED** [review]

**Comment by fruch** [comment]
still happens on 5.0:

https://jenkins.scylladb.com/job/scylla-5.0/job/next/232/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/dtest___test_simple_kill_node_while_decommissioning/

@xemul, do we want to backport this one ?

**Pull request merged**
