### PR TITLE
compaction/commitlog_replayer: Make sstable replay positions usable as replay threshold

### LINKED ISSUE #14870: Writes in commitlog segments, that are pinned by another table, can be resurrected
Commitlog segments are only discarded when all tables have released their respective replay handles, that point to said segment. It is possible that one table, that receives very little writes, have very long lived memtables, that pin commitlog segments, containing writes to other tables. It is possible that these writes are covered with a tombstone, written in a later write. This tombstone can get to disk, be compacted and purged, while the commitlog segment containing the earlier (covered) writes is still pinned. A later unclean restart, can cause these segments to be replayed, resurrecting the data.

### PR DESCRIPTION
**Pull request by elcallio**
Fixes #14870

Changes compaction replay position propagation to ensure we only care about destination shard RP:s (and thus maintain proper ordering) + use sstable RP:s at CL replay to figure out replay threshold below which we can skip mutations in log.

This was ignored before because resharding would make older sstable RP:s potentially broken/wrong for this purpose, but since resharding can only happen on restart, and compaction can only happen after a complete CL replay, we can make it work by filtering out any RP:s for older, resharded sstables being compacted. They are by definition already obsolete for both CL replay thresholds and truncation purposes (assuming we don't allow backdated truncation, which we don't). In fact, since RP:s are wallclock based, the only really care about them in sstables created during the last run (for CL replay) - either newly flushed or compacted, and then only about positions generated during current session (since memtable flush is RP ordered).

This is the third option to solve the above issue, and probably the least intrusive one. Credit goes to @raphaelsc for thinking about the sstable positions. This solution has the added benefit of not generating any extra flushes/segments or anything, and also passing all existing dtests for compaction and truncation.

### CODE REVIEW

**Comment by avikivity** [comment]
I notice there are no tests.

I'm worried about using replay_position:s. Since memtable flush can write into more than one sstable, how do we account for this? What if a memtable flush manages to seal one sstable and not another?  What's the arithmetic for replay_position when compacting sstables? What happens when an sstable disappears if it's all expired tombstones?

**Comment by elcallio** [comment]
Tests are botonds dtest (for resurrection issue) and existing CL/compaction tests (for not breaking existing behaviour/assumptions. 

You are right, if memtable flush happens to retry and reorder two flushes and fail the former but not the latter there will be a problem. Flush needs to enforce strict ordering of sstable seals in RP order. 

Compaction should be fine, since we only care (assuming ordered flushes) about preserving the highest RP for this shard and this node uptime period to ensure replay threshold. Any RP:s belonging to different/old/expired shards are by definition already replayed/handled. 

Not sure what you mean by the last question? Disappears as in is lost? In general, CL does not exist to handle that. If an sstable is removed by compaction, and we maintain high RP as defined by the PR we should be fine, in that compaction should ensure data is consistent, and CL will not resurrect things to make it not.

**Comment by elcallio** [comment]
@raphaelsc - what would be the simplest way to ensure we serialize ordering of sstable sealing for MT flushes?

**Comment by raphaelsc** [comment]
> Tests are botonds dtest (for resurrection issue) and existing CL/compaction tests (for not breaking existing behaviour/assumptions.
> 
> You are right, if memtable flush happens to retry and reorder two flushes and fail the former but not the latter there will be a problem. Flush needs to enforce strict ordering of sstable seals in RP order.
> 

the problem is that we reuse the same RP, coming from the same memtable, across all sstables generated from a single memtable flush. memtables are flushed in token order, and token order is not the same as RP one. 

we'd need to guarantee that all sstables are sealed or none, with something like:

1) write all sstables without sealing
2) seal all of them on completion
    we'd probably need to reuse the intent log we currently use for deletion, so a failure in between won't cause any to be loaded on restart. all the data lives in commitlog anyway as we only reap it once the flush completes successfully.
3) if any fail, we unlink all of them (again using the intent log for atomic deletion).

> 
> Not sure what you mean by the last question? Disappears as in is lost? In general, CL does not exist to handle that. If an sstable is removed by compaction, and we maintain high RP as defined by the PR we should be fine, in that compaction should ensure data is consistent, and CL will not resurrect things to make it not.

but then we'd need to persist it like in truncation table for the info to survive restarts, no? IIRC, that was more or less your first idea.

if the tombstone is GCed, and compaction output nothing, it means we can no longer find the rp anywhere but in volatile memory, right? so data in commitlog could still be resurrected.

**Comment by elcallio** [comment]
So, two things: We both have one memtable generating more than one sstable. That requires us to guarantee all or none of the tables are sealed. 
But we also potentially flush more than one memtable at one, if we have latency/IO bw issues. Here we need to ensure that sstable for MT1 (lower RP) seal before MT2 (higher RP) is sealed.

Ok, now I get the second part. If GC manages to completely eliminate tombstones before CL is gone, yes, we still have a problem. This could be solved by detecting this and writing a truncation-like record, yes. Or do version two, ensure no CL segments exist <= rp for which we GC. But then we are back on the solution 2 pitfalls (or solution 1 pitfalls).

In either case, great we managed to shoot a hole in this as well...

**Comment by elcallio** [comment]
Maybe we should return to solution 1, but instead implement it as a commit log commit log of flushes, i.e. write a separate tabulation of table+RP:s actually flushed by the system. This would still have the potential to break if we crash while updating this, but it should be rare and not very likely to collide with actual compaction (assuming it is done on flush). 
Glö.

**Pull request closed without merging**
