### PR TITLE
utils: spell "barrett" correctly

### PR DESCRIPTION
**Pull request by avikivity**
As P. T. Barnoom famously said, "write what you like but spell my name correctly". Following that, we correct the spelling of Barrett's name in the source tree.

### CODE REVIEW

**Review by denesb — APPROVED** [review]

**Comment by nyh** [comment]
Build error:
```
08:18:45  utils/gz/crc_combine.cc:149:14: error: use of undeclared identifier 'crc32_fold_barertt_u64'; did you mean 'crc32_fold_barrett_u64'?
08:18:45      u32 z1 = crc32_fold_barertt_u64(y1);
08:18:45               ^~~~~~~~~~~~~~~~~~~~~~
08:18:45               crc32_fold_barrett_u64
08:18:45  utils/gz/barrett.hh:153:10: note: 'crc32_fold_barrett_u64' declared here
08:18:45  uint32_t crc32_fold_barrett_u64(uint64_t p) {
08:18:45           ^
```

**Comment by nyh** [comment]
> As P. T. Barnoom famously said, "write what you like but spell my name correctly". Following that, we correct the spelling of Barrett's name in the source tree.

Ironically, you mispelled Barnum's name :-)

**Comment by avikivity** [comment]
> > As P. T. Barnoom famously said, "write what you like but spell my name correctly". Following that, we correct the spelling of Barrett's name in the source tree.
> 
> Ironically, you misspelled Barnum's name :-)

What a twist!

**Comment by avikivity** [comment]
v2: correct an unintentional newly-introduced misspelling of Barrett's name.

**Pull request closed without merging**
