### PR TITLE
test.py: cleanups in topology test suites

### PR DESCRIPTION
**Pull request by kbr-**
Fix the type of `create_server`, rename `topology_for_class` to `get_cluster_factory`, simplify the suite definitions and parameters passed to `get_cluster_factory`

### CODE REVIEW

**Review by michoecho — APPROVED** [review]
Nitpick

**Review by alecco — APPROVED** [review]
LGTM

**Comment by nyh** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2326/

Many test fails, but I don't understand how it's related to your patch :-( Anybody has any ideas?

**Comment by kbr-** [comment]
Well, that looks nice. Someone who understands what these tests do should probably investigate them.

**Comment by denesb** [comment]
Test failures are completely bonkers. As if an old version of scylla was built, which doesn't have the fixes/features tested by the tests.

**Comment by nyh** [comment]
> Test failures are completely bonkers. As if an old version of scylla was built, which doesn't have the fixes/features tested by the tests.

I agree. I don't know what to make of these failures and I don't even know where to start understanding what happened. So I just restarted the CI now and let's see what happens.

**Comment by kbr-** [comment]
The same failures! Nice.

**Comment by denesb** [comment]
Try rebasing.

**Comment by kbr-** [comment]
I will probably do that... although I don't feel comfortable with just ignoring these errors.

**Comment by kbr-** [comment]
What the hell! The same failures, even after rebasing :D
Something fishy's going on.

**Comment by kbr-** [comment]
Ugh, I think I know...
This `PythonTestSuite` class is not only used for Topology suites, it's also used for the cql-pytest suite.
The default cluster size was `1` before my change:
```python3
        topology = self.cfg.get("topology", {"class": "simple", "replication_factor": 1})
```
(the cluster size was set to `replication_factor`)

after my change it became 3!
And that's what causes these failures - the tests are now running on a 3 node cluster!

**Comment by kbr-** [comment]
BTW. the tests are using NTS with RF=1:
```python3
@pytest.fixture(scope="session")
def test_keyspace(cql, this_dc):
    name = unique_name()
    cql.execute("CREATE KEYSPACE " + name + " WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', '" + this_dc + "' : 1 }")
    yield name
    cql.execute("DROP KEYSPACE " + name)
```

**Comment by kbr-** [comment]
v2:
- set default cluster size to 1, put spaces around `=`

diff: https://github.com/scylladb/scylladb/compare/b211dd0ffa79f5d442fdc99a7fa3b851ecd71d81..696bdb2de71eb0c64163f609002e06361e57da38

**Comment by nyh** [comment]
> BTW. the tests are using NTS with RF=1:
> ```python3
> @pytest.fixture(scope="session")
> def test_keyspace(cql, this_dc):
>     name = unique_name()
>     cql.execute("CREATE KEYSPACE " + name + " WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', '" + this_dc + "' : 1 }")
>     yield name
>     cql.execute("DROP KEYSPACE " + name)
> ```

This is deliberate. We recommend to users to use NTS even with rf=1 to make it possible to upgrade later, so I wanted to test the same code paths that users would use.

**Comment by kbr-** [comment]
Yes that's good, but it makes the failures even more suspicious - since we're using RF=1 (and not RF=number-of-nodes-in-the-cluster), the number of replicas has not changed even when we changed cluster size. So what caused these failures to start appearing... maybe the fact that we introduce a network? Or maybe that there are some range scans which now have to fetch partitions from different nodes?

I opened a separate issue: https://github.com/scylladb/scylladb/issues/11645

**Comment by kbr-** [comment]
@nyh please review

**Comment by kbr-** [comment]
@nyh ping

**Review by nyh — APPROVED** [review]

**Pull request merged**
