### PR TITLE
transport: Dont bypass seastar API when making syscalls

### PR DESCRIPTION
**Pull request by muthu90tech**
Please see issue: https://github.com/scylladb/scylladb/issues/17443

This PR helps in avoid using syscalls directly in transport/controller.cc .
The seastar APIs were missing a couple of syscalls needed to be used in controller.cc, so I created a PR for those syscalls to be added in seastar namespace here: https://github.com/scylladb/seastar/pull/2314

### CODE REVIEW

**Comment by kbr-scylla** [comment]
@tchaikov I see you're reviewing https://github.com/scylladb/seastar/pull/2314, could you please also review this PR which uses those APIs? (Might potentially affect your review of https://github.com/scylladb/seastar/pull/2314)

**Comment by tchaikov** [comment]
> @tchaikov I see you're reviewing [scylladb/seastar#2314](https://github.com/scylladb/seastar/pull/2314), could you please also review this PR which uses those APIs? (Might potentially affect your review of [scylladb/seastar#2314](https://github.com/scylladb/seastar/pull/2314))

ack. will take a look.

**Comment by muthu90tech** [comment]
> > @tchaikov I see you're reviewing [scylladb/seastar#2314](https://github.com/scylladb/seastar/pull/2314), could you please also review this PR which uses those APIs? (Might potentially affect your review of [scylladb/seastar#2314](https://github.com/scylladb/seastar/pull/2314))
> 
> ack. will take a look.

Hi, I have made updates to seastar, here: https://github.com/scylladb/seastar/pull/2314/files, if this looks good, I can use the new APIs here. Thank you

**Comment by mykaul** [comment]
> @scylladb/scylla-maint please review and trigger CI for this pull request **CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=19565

Triggered.

**Comment by mykaul** [comment]
2621/3237] CXX build/debug/transport/controller.o
 FAILED: build/debug/transport/controller.o 
 clang++ -MD -MT build/debug/transport/controller.o -MF build/debug/transport/controller.o.d -std=c++23 -I/jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include -I/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/gen/include -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_API_LEVEL=7 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEBUG_PROMISE -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DFMT_SHARED -I/usr/include/p11-kit-1 -DWITH_GZFILEOP -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -march=westmere -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -Og -DSCYLLA_BUILD_MODE=debug -g -gz -Xclang -fexperimental-assignment-tracking=disabled -iquote. -iquote build/debug/gen -std=gnu++23  -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -march=westmere -DBOOST_ALL_DYN_LINK    -fvisibility=hidden -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-psabi -Wno-enum-constexpr-conversion -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/debug/transport/controller.o transport/controller.cc
 transport/controller.cc:183:25: error: no struct named 'group_details' in namespace 'seastar'
   183 |         struct seastar::group_details grp = co_await seastar::grp_detail(group_name.c_str());
       |                ~~~~~~~~~^
 transport/controller.cc:183:63: error: no member named 'grp_detail' in namespace 'seastar'
   183 |         struct seastar::group_details grp = co_await seastar::grp_detail(group_name.c_str());
       |                                                      ~~~~~~~~~^
 transport/controller.cc:188:27: error: no member named 'change_ownership_of_file' in namespace 'seastar'
   188 |         co_await seastar::change_ownership_of_file(socket.c_str(), grp.group_gid);
       |                  ~~~~~~~~~^

**Comment by mykaul** [comment]
> @scylladb/scylla-maint please review and trigger CI for this pull request **CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=19565

Triggered.

**Review by denesb — CHANGES_REQUESTED** [review]
Thanks for this PR @muthu90tech.

Please drop the seastar submodule update from the PR, we will update seastar in scylladb.git and then merge this PR.

Have you signed our CLA?

Please prefix the patch title with: transport:, so it will look like this:
"transport: don't bypass seastar API when making syscalls"

**Comment by muthu90tech** [comment]
> Thanks for this PR @muthu90tech.
> 
> Please drop the seastar submodule update from the PR, we will update seastar in scylladb.git and then merge this PR.
> 
> Have you signed our CLA?
> 
> Please prefix the patch title with: transport:, so it will look like this: "transport: don't bypass seastar API when making syscalls"

Thanks @denesb , I have signed the CLA, will update description.

**Comment by avikivity** [comment]
> @scylladb/scylla-maint please review and trigger CI for this pull request **CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=19565

Triggered

**Comment by muthu90tech** [comment]
> Thanks for this PR @muthu90tech.
> 
> Please drop the seastar submodule update from the PR, we will update seastar in scylladb.git and then merge this PR.
> 
> Have you signed our CLA?
> 
> Please prefix the patch title with: transport:, so it will look like this: "transport: don't bypass seastar API when making syscalls"

Thanks I have also dropped the seastar submodule update from the PR, not sure if the build will pass without it, as this PR relies on few new APIs introduced in seastar commit : cd7f3b8e8850cd80a4f6899cedc726e576c51abe
Thanks @denesb

**Comment by denesb** [comment]
@muthu90tech latest master should have the required commit, please rebase this PR on latest master.

**Comment by denesb** [comment]
Actually, I saw you rebased 1 h ago, let me try CI.

**Comment by denesb** [comment]
Queued, thanks @muthu90tech!

**Pull request closed without merging**
