### PR TITLE
docs: fix name of roles table keyspace from system to system_auth

### PR DESCRIPTION
**Pull request by tarzanek**
**Please replace this line with justification for the backport/\* labels added to this PR**

### CODE REVIEW

**Comment by tarzanek** [comment]
@annastuchlik can you have a look? 
thnx
L

**Comment by dawmd** [comment]
If I remember correctly, `system_auth` is a legacy keyspace and we use `system` for everything nowadays. CC @nuivall

**Comment by nuivall** [comment]
@tarzanek for what version is this a fix for? Is it really on master the case that auth tables are in system_auth? The keyspace will exist because it's a workaround for poorly written cqlsh but it should be empty on new versions.

**Comment by tarzanek** [comment]
ah, ok, I am looking at wrong docs <sigh>

sorry, closing

https://enterprise.docs.scylladb.com/branch-2024.1/alternator/compatibility.html#authorization

looks OK

**Pull request closed without merging**
