### PR TITLE
s3/client: Tag pieces of jumbo uploader

### PR DESCRIPTION
**Pull request by xemul**
The jumbo sink is there to upload files that can be potentially larger than 50Gb (10000*5Mb). For that the sink uploads a set of so called "pieces" -- files up to 50Gb each -- then uses the copy-upload APi call to squash the pieces together. After copying the piece is removed. In case of a crash while uploading pieces remain in the bucket forever which is not great.

This patch tags pieces with 'kind=piece' tag in order to tell pieces from regular objects. This can be used, for example, by setting up the lifecycle tag-based policy and collect dangling pieces eventually.

fixes: #13670

### CODE REVIEW

**Comment by xemul** [comment]
upd:
- rebased

**Comment by tchaikov** [comment]
this change alone does not address #13670. so probably we cannot close it with the `fixes` tag in the commit message.

also, if we have one or more follow-up changes to address this issue, would be better to outline the working items in #13670.

also, is it possible to have a tiny test for testing this newly added tag for categorizing the uploaded object?

**Comment by xemul** [comment]
> this change alone does not address #13670. so probably we cannot close it with the `fixes` tag in the commit message.

There's #15518 that I plan to rename when this one gets merged to track the lifecycle policies

> also, if we have one or more follow-up changes to address this issue, would be better to outline the working items in #13670.
> 
> also, is it possible to have a tiny test for testing this newly added tag for categorizing the uploaded object?

Pieces are very fast-living, this PR had several commits on top that validated this worked, but it was too heavy. I think I'll get back to it as a followup, maybe as a part of a larger error paths checking tests. In the end of the day -- this is going to be a test for x-amz-tagging header to work :shrug: not sure it worth the effort now

**Comment by tchaikov** [comment]
the title of #13670 reads 

> Garbage collect dangling pieces

without your explanation, one can hardly tell that there is another issue with a similar title tracking this issue. how can i tell the scope of issue by reading the description of #13670 ?

**Comment by xemul** [comment]
> the title of #13670 reads
> 
> > Garbage collect dangling pieces

Yes. I back then noticed that pieces can be left as uploaded objects and wrote it down not to forget. From my perspective the issues's description text clearly explains what the problem is.

> without your explanation, one can hardly tell that there is another issue with a similar title tracking this issue. how can i tell the scope of issue by reading the description of #13670 ?

I don't get what you're having problems with. There's an ongoing suggestion to tag pieces and setup lifecycle management to gc it eventually. If this proposal is accepted (I so far haven't seen neither acceptance no rejection) then I'll go ahead and update the #15518 to be more generic -- provide lifecycle management for both pieces and incomplete uploads.

**Comment by tchaikov** [comment]
@xemul this is a part of the implementation, i can deduce the general design from this puzzle. but i cannot find the "proposal". if you are seeking a yah or nay on the proposal, i don't see why we cannot go this way. i was asking for clarifications on the issue and its connection to this PR, not the change itself.

in this very context, i was under the impression that i was requested for a review. so, i think the PR fixing an issue is supposed to address it. probably i am missing something obvious?

**Comment by xemul** [comment]
> @xemul this is a part of the implementation, i can deduce the general design from this puzzle.

My bad, I wasn't clear enough assuming that the issue itself is pretty simple :( Let me describe it in more details

So, there a problem with jumbo uploading sink described in #13670, namely -- pieces are real S3 objects and in case something goes wrong while uploading a jumbo object, one or more pieces can be left untracked. This PR suggests a fix for the issue (thus the "closes" tag) -- to tag pieces with 'kind=piece' so that the bucket admin could tell pieces from other objects and gc them they way it wants _for_ _example_ by setting up lifecycle policy on the bucket. (I say "for example" just because I always assume there are more than one ways of doing pretty much anything even if I'm unaware of them all.)  This bucket configuration is definitely _not_ what Scylla binary should do, it's the thing that has to be resolved somewhere else, and once pieces tagging PR (this one) is merged, we can assume the issue to be solved on scylla side (again, thus the "closes" tag).

Next, related to the aforementioned "somewhere else" thing. There's a related issue #15518 which describes similar, but not identical, problem with incomplete parts -- they also need to be gc-ed. And unlike pieces we don't need to explicitly tag incomplete uploads, because S3 lifecycle policy allows gc-ing them even without tags.

I hope this makes the current plan clear.

> but i cannot find the "proposal".

Hopefully it was in the patch description:

> This patch tags pieces with 'kind=piece' tag in order to tell pieces from regular objects. This can be used, for example, by setting up the lifecycle tag-based policy and collect dangling pieces eventually.

And, as I mentioned above, tagging a piece really _closes_ the issue on the scylla side. Setting up lifecycle management is to be done "somewhere else" and is to be discussed.

> if you are seeking a yah or nay on the proposal, i don't see why we cannot go this way. i was asking for clarifications on the issue and its connection to this PR, not the change itself.

Also hopefully, the connection of #13670 and this PR was in the PR description as well -- if we tag pieces we can gc them later. Now I think that this "later" part required clarification.

> in this very context, i was under the impression that i was requested for a review. so, i think the PR fixing an issue is supposed to address it. probably i am missing something obvious?

**Review by tchaikov — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
> This bucket configuration is definitely _not_ what Scylla binary should do, it's the thing that has to be resolved somewhere else, and once pieces tagging PR (this one) is merged, we can assume the issue to be solved on scylla side

this is surprising to me actually. as i assumed that we should have a github issue tracking this work and its following-up action items if scylla binary should take care of the lifecycle of "piece" objects. if some other entitiy/components are involved to cleanup the "pieces", i think it's better a reason why we need another ticket for filling the developers with more context, instead of asking him/her to read the code or asking Pavel, well, if he/she is aware that there is a following-up work. the "work" could be a change in document or an improvement in a tool ..

but we don't have it. so it might be hard for us to track the follow-up work.

**Comment by xemul** [comment]
> this is surprising to me actually. as i assumed that we should have a github issue tracking this work and its following-up action items if scylla binary should take care of the lifecycle of "piece" objects.

Normally Scylla tracks piece lifecycle on its own. The piece lifecycle is like this

1. multipart upload piece object
2. complete uploading
3. copy-upload piece to component file
4. remove the piece object

In case scylla/instance crashes between steps 2 and 4 there may be a piece object hanging around and scylla has no options to re-pick it up without extra help. This PR suggests tagging pieces to locate them, next step is to pick them up.

> if some other entitiy/components are involved to cleanup the "pieces", i think it's better a reason why we need another ticket for filling the developers with more context, instead of asking him/her to read the code or asking Pavel, well, if he/she is aware that there is a following-up work. the "work" could be a change in document or an improvement in a tool ..

I'll do the necessary "paper work" around this matter after tagging approach is accepted and merged :)

**Comment by tchaikov** [comment]
probably a little bit off-topic, i think scylla *can* do the cleanup, if we attach some tag which marks the ownership of pieces, so that a scylla instance is started it will be able to consume it's predecessor's legacy including the already completed uploads or the pieces.

**Comment by avikivity** [comment]
> The jumbo sink is there to upload files that can be potentially larger than 50Gb (10000*5Mb). For that the sink uploads a set of so called "pieces" -- files up to 50Gb each -- then uses the copy-upload APi call to squash the pieces together. After copying the piece is removed. In case of a crash while uploading pieces remain in the bucket forever which is not great.
> 
> This patch tags pieces with 'kind=piece' tag in order to tell pieces from regular objects. This can be used, for example, by setting up the lifecycle tag-based policy and collect dangling pieces eventually.

Is this for the error case? In the normal path they can be deleted directly, no?


> 
> fixes: #13670

Ah, the issue says so, but the cover letter should as well.

**Comment by tchaikov** [comment]
> > The jumbo sink is there to upload files that can be potentially larger than 50Gb (10000*5Mb). For that the sink uploads a set of so called "pieces" -- files up to 50Gb each -- then uses the copy-upload APi call to squash the pieces together. After copying the piece is removed. In case of a crash while uploading pieces remain in the bucket forever which is not great.
> > This patch tags pieces with 'kind=piece' tag in order to tell pieces from regular objects. This can be used, for example, by setting up the lifecycle tag-based policy and collect dangling pieces eventually.
> 
> Is this for the error case? In the normal path they can be deleted directly, no?

yes, it is designed for the error path.

> 
> > fixes: #13670
> 
> Ah, the issue says so, but the cover letter should as well.

**Pull request closed without merging**
