### PR TITLE
Treewide use-after-move bug fixes

### PR DESCRIPTION
**Pull request by raphaelsc**
That's courtersy of https://github.com/raphaelsc/seastar/commit/153813d3b88f284fe135c8ac3c00d6777faad276, which annotates Seastar smart pointer classes with Clang's consumed attributes, to help Clang to statically spot use-after-move bugs.

### CODE REVIEW

**Comment by raphaelsc** [comment]
Do I need to open a github issue for each one of those? :-)

**Review by denesb — APPROVED** [review]

**Comment by denesb** [comment]
> Do I need to open a github issue for each one of those? :-)

I was going to say, please open an issue for all that is non-benign. But a use-after-move is never benign, and even if it is, it can become very much not benign very quickly.

**Comment by raphaelsc** [comment]
v2:
opened gh issue and added Fixes tag to each patch

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint ping

**Pull request merged**
