### PR TITLE
compaction: Delete atomically off-strategy input sstables

### PR DESCRIPTION
**Pull request by raphaelsc**
After commit a57724e7118, off-strategy no longer races with view building, therefore deletion code can be simplified and piggyback on mechanism for deleting all sstables atomically, meaning a crash midway won't result in some of the files coming back to life, which leads to unnecessary work on restart.

Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>

### CODE REVIEW

**Comment by raphaelsc** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3421/

Looks like the failure is unrelated.

**Comment by bhalevy** [comment]
> After commit [a57724e](https://github.com/scylladb/scylladb/commit/a57724e711849f472a57d968fe07520ba6fac06e), off-strategy no longer races with view building, therefore deletion code can be simplified and piggyback on mechanism for deleting all sstables atomically, meaning a crash midway won't result in some of the files coming back to life, which leads to unnecessary work on restart.

Csn't it also lead to data resurrection?
If compaction happens to delete data and tombstone that deleted it in the same go, and they are stored in differentc sstables, and the tombstone is deleted first snd then scylla crashes.

**Review by bhalevy — APPROVED** [review]

**Comment by raphaelsc** [comment]
> > After commit [a57724e](https://github.com/scylladb/scylladb/commit/a57724e711849f472a57d968fe07520ba6fac06e), off-strategy no longer races with view building, therefore deletion code can be simplified and piggyback on mechanism for deleting all sstables atomically, meaning a crash midway won't result in some of the files coming back to life, which leads to unnecessary work on restart.
> 
> Csn't it also lead to data resurrection? If compaction happens to delete data and tombstone that deleted it in the same go, and they are stored in differentc sstables, and the tombstone is deleted first snd then scylla crashes.

you're completely right about that. probably the most important reason for atomic deletion.

**Comment by raphaelsc** [comment]
> > > After commit [a57724e](https://github.com/scylladb/scylladb/commit/a57724e711849f472a57d968fe07520ba6fac06e), off-strategy no longer races with view building, therefore deletion code can be simplified and piggyback on mechanism for deleting all sstables atomically, meaning a crash midway won't result in some of the files coming back to life, which leads to unnecessary work on restart.
> > 
> > 
> > Csn't it also lead to data resurrection? If compaction happens to delete data and tombstone that deleted it in the same go, and they are stored in differentc sstables, and the tombstone is deleted first snd then scylla crashes.
> 
> you're completely right about that. probably the most important reason for atomic deletion.

although it's less likely to happen with off-strategy input as we expect files to be disjoint with each other.

**Comment by bhalevy** [comment]
> > > > After commit [a57724e](https://github.com/scylladb/scylladb/commit/a57724e711849f472a57d968fe07520ba6fac06e), off-strategy no longer races with view building, therefore deletion code can be simplified and piggyback on mechanism for deleting all sstables atomically, meaning a crash midway won't result in some of the files coming back to life, which leads to unnecessary work on restart.
> > > 
> > > 
> > > Csn't it also lead to data resurrection? If compaction happens to delete data and tombstone that deleted it in the same go, and they are stored in differentc sstables, and the tombstone is deleted first snd then scylla crashes.
> > 
> > 
> > you're completely right about that. probably the most important reason for atomic deletion.
> 
> although it's less likely to happen with off-strategy input as we expect files to be disjoint with each other.

true

**Comment by raphaelsc** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3431/

Another unrelated failure. We must fix the reliability of the tests. 

/CC @scylladb/scylla-maint

**Comment by mykaul** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3431/
> 
> Another unrelated failure. We must fix the reliability of the tests.

Do we have open issues on each failure? 

> 
> /CC @scylladb/scylla-maint

**Comment by raphaelsc** [comment]
@scylladb/scylla-maint ping merge.

**Pull request closed without merging**
