### PR TITLE
test/pylib: scylla_cluster: release IPs when cluster is no longer needed

### PR DESCRIPTION
**Pull request by kbr-scylla**
With sufficiently many test cases we would eventually run out of IP addresses, because IPs (which are leased from a global host registry) would only be released at the end of an entire test suite.

In fact we already hit this during next promotions, causing much pain indeed.

Release IPs when a cluster, after being marked dirty, is stopped and thrown away.

### CODE REVIEW

**Comment by kbr-scylla** [comment]
@scylladb/scylla-maint this will fix our recent problems in next promotion. The framework was hanging trying to lease new IPs from the IP pool. Eventually tests timed out.

**Comment by avikivity** [comment]
> With sufficiently many test cases we would eventually run out of IP addresses, because IPs (which are leased from a global host registry) would only be released at the end of an entire test suite.
> 
> In fact we already hit this during next promotions, causing much pain indeed.
> 
> Release IPs when a cluster, after being marked dirty, is stopped and thrown away.

Nice detective work.

**Review by avikivity — APPROVED** [review]

**Review by denesb — APPROVED** [review]

**Review by alecco — APPROVED** [review]
LGTM

**Comment by alecco** [comment]
> This patch is good (and I see it was already committed), but maybe it's an opportunity to raise some doubts on the IP-address allocation:
> 
> 1. Even if we never release addresses, why did we ever run out of IP addresses? As I calculated in test/cql-pytest/run.py, we have `253*255*255` to choose from. Maybe test/pylib uses too small a range?

The current sub-range per test is "class C" subnet, so max 253 IPs/hosts at a time for each test and ~16M parallel tests. Perhaps we can change it to be "class B"? (65534 IPs/test, ~64k tests) @kostja ?

Note: at the moment each topology test _case_ uses a cluster of 3 to 6 servers.

**Comment by kbr-scylla** [comment]
> Maybe test/pylib uses too small a range?

The host registry has only 254 IPs, so it is indeed quite small.

> Why did running out of IP addresses cause some hard-to-debug pain and not some immediately-obvious error message?

Logs that are hard to correlate with the corresponding tests, and not enough logs. Hence https://github.com/scylladb/scylladb/pull/12483 to avoid this in the future.

**Comment by avikivity** [comment]
We can use `unshare -rn` to get a new network namespace, if we want.

**Pull request closed without merging**
