### PR TITLE
test/pylib: handle ScyllaCluster start failure

### PR DESCRIPTION
**Pull request by alecco**
If ScyllaCluster fails to initialize don't try to get its logs and don't try to stop it.

### CODE REVIEW

**Comment by alecco** [comment]
This fix was included in https://github.com/scylladb/scylladb/pull/12685 but it can be a standalone pull request.

**Comment by kbr-scylla** [comment]
> If ScyllaCluster fails to initialize don't try to get its logs and don't try to stop it.

Why not? If a cluster fails to initialize because e.g. a server fails to start, we do want to get its logs and we do want to stop all servers which managed to start before that failed one.

Please provide an example scenario where this PR makes a difference, with how the user experience looks "before" and "after". How would I simulate the scenario locally?

**Comment by alecco** [comment]
> > If ScyllaCluster fails to initialize don't try to get its logs and don't try to stop it.
> 
> Why not? If a cluster fails to initialize because e.g. a server fails to start, we do want to get its logs and we do want to stop all servers which managed to start before that failed one.
> 
> Please provide an example scenario where this PR makes a difference, with how the user experience looks "before" and "after". How would I simulate the scenario locally?

A trivial way to break it is passing it a wrong parameter to scylla exe.

**Review by nyh — COMMENTED** [review]
What does "ScyllaCluster fails to initialize" include? Could this be Scylla failing to boot? If this is the case, why **not** get the logs? Aren't the logs important to understand why Scylla failed to boot?

**Comment by alecco** [comment]
> What does "ScyllaCluster fails to initialize" include? Could this be Scylla failing to boot? If this is the case, why **not** get the logs? Aren't the logs important to understand why Scylla failed to boot?

This is for the case where there are no logs. Like wrong exe params.

**Review by kostja — APPROVED** [review]

**Pull request closed without merging**
