### PR TITLE
Update tools/cqlsh submodule

### PR DESCRIPTION
**Pull request by fruch**
* tools/cqlsh 426fa0ea...b4233d47 (4):
  > Draft: explicit build-time packge dependencies
  > stop retruning status_code=2 on schema disagreement
  > Fix minor typos in the code
  > Dockerfile: apt-get update and apt-get upgrade to get latest OS packages

Fixes: https://github.com/scylladb/scylladb/issues/16552

### CODE REVIEW

**Comment by mykaul** [comment]
We usually add an issue and then label it with the 'backport' labels (not sure it matters that much, as GH search works for both issues and PRs...)

**Comment by avikivity** [comment]
The backport candidate label only applies to issues, not pull requests. We don't backport patches, we backport fixes to problems.

**Comment by nyh** [comment]
Moreover, please note that we don't backport a "update XXX submodule" patch per se. Instead, what we do in this case is:
1. The issue describes why we needed the update (e.g., perhaps in this case what we really needed was the "stop retruning status_code=2 on schema disagreement" patch, not the "Fix minor typos in the code" patch ;-))
2. Each submodoule has version branches (e.g., "master-5.4") and we cherry-pick only the specific submodule change chosen in the previous step into that version branch. We don't update the submodule to contain all the newest stuff.

This is all very manual and error-prone, which makes working with submodules a real pain, unfortunately.  Recently I spent a few hours (!) backporting a simple fix which involved Scylla, scylla-tools-java, scylla-jmx and scylla-dtest. I don't have a magic solution except reducing our use of submodules (e.g., like we added in-tree tests whereas in the past we had out-of-tree dtest).

**Comment by fruch** [comment]
> @fruch - please use #16552

use where ?

**Comment by mykaul** [comment]
> > @fruch - please use #16552
> 
> use where ?

In the cover for this PR

**Comment by mykaul** [comment]
@fruch - please resolve conflicts.

**Comment by fruch** [comment]
> @fruch - please resolve conflicts.

if someone else already pushed an update to the submodule, it already have those, and this PR isn't needed

**Comment by fruch** [comment]
those changes we introduced already by cc039498c6eb1972fc48c75dbbbc709eeed9632b

**Comment by mykaul** [comment]
@fruch - will you be backporting this to 5.4.x? (is it needed?)

**Comment by fruch** [comment]
> @fruch - will you be backporting this to 5.4.x? (is it needed?)

no, it's not that critical

**Pull request closed without merging**
