### PR TITLE
db/config.cc: increment components_memory_reclaim_threshold config default

### LINKED ISSUE #18607: bloom-filter: default value for components_memory_reclaim_threshold is too strict
`components_memory_reclaim_threshold` controls when we start evicting bloom filters from memory. It defaults to 0.1, which comes down to 10% of the shard's memory. It looks like this is too strict and causes unnecessary bloom filter eviction in otherwise healthy clusters. One cluster which was impacted by this, had a BF/memory ratio of 0.6. The eviction mechanism was introduced to avert OOM disasters, not to enforce lean bloom filters and so the default should be adjusted accordingly and increased to as high as 0.8 or even maybe 0.9. The idea is that by default it should only kick in when OOM is iminent, it should not intervene on clusters which have high BF memory consumption but are otherwise fine.

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Incremented the components_memory_reclaim_threshold config's default value to 0.8 as the previous value was too strict and caused unnecessary eviction in otherwise healthy clusters.

Fixes #18607

### CODE REVIEW

**Review by denesb — APPROVED** [review]

**Review by michoecho — CHANGES_REQUESTED** [review]
@denesb No, what are you doing. 0.8 effectively disables the entire mechanism.

The system gradually adjusts memtable flushing speed to keep memtable memory usage under 0.5 (and stops accepting writes at the extreme), and doesn't even start flushing until it reaches ~0.25~ 0.15.

Bloom filter memory usage isn't going to reach 0.8 because the system is all but guaranteed to OOM at ~0.75~ 0.85, and that's even without counting all the non-cache, non-memtable memory usage.

If you want to prevent OOM crashes with this feature, the threshold must be way under ~0.85~ (with enough margin to cover all non-LSA, non-bloom memory usage). If you want to guarantee that, then it must be somewhere under (0.5 - margin).

For example, take the last case of bloom explosion from a few days ago (https://github.com/scylladb/scylla-enterprise/issues/4156). The affected node started choking on bad_allocs at bloom fraction of 0.6, and crashed (due to bad_alloc-induced flush failure) at 0.65.

Edit: I misremembered the defaults — we start flushing at 0.15, not at 0.25. Which means that 0.8 might be enough to prevent some OOMs, but that's cutting it very close.

**Comment by denesb** [comment]
> If you want to prevent OOM crashes with this feature, the threshold must be way under 0.75 (with enough margin to cover all non-LSA, non-bloom memory usage). If you want to guarantee that, then it must be somewhere under (0.5 - margin).
> 
> For example, take the last case of bloom explosion from a few days ago ([scylladb/scylla-enterprise#4156](https://github.com/scylladb/scylla-enterprise/issues/4156)). The affected node started choking on bad_allocs at bloom fraction of 0.6, and crashed (due to bad_alloc-induced flush failure) at 0.65.

0.6 is way too strict. In another customer case, the cluster is healthy and steady at 0.6 BF memory usage ratio and forcing below makes IO and latencies jump and results in escalation. So we have to use the max() of all use-cases as the default and lower on deployments where the default is already problematic.

**Comment by michoecho** [comment]
> 0.6 is way too strict. In another customer case, the cluster is healthy and steady at 0.6 BF memory usage ratio

Steady at 0.6? Which customer case was that?

**Comment by denesb** [comment]
> > 0.6 is way too strict. In another customer case, the cluster is healthy and steady at 0.6 BF memory usage ratio
> 
> Steady at 0.6? Which customer case was that?

https://github.com/scylladb/scylla-enterprise/issues/4183
And let's stop discussing customer issues here, before we accidentally name-drop one of them. Although I suppose these cases are very much relevant here, still customer issues should not be discussed in the OSS repository.

**Comment by mykaul** [comment]
@avikivity - per our discussion on Sunday - please review.

**Comment by avikivity** [comment]
The goal of the feature was to prevent OOM. If we use the max() of all clusters, it will never prevent OOM since different clusters have other non-LSA components (prepared statements, cached queriers, running ops, background writes, repair with its large buffers, group 0 holding all the tablets metadata).

We can increase it to 0.2, but not beyond.

**Comment by denesb** [comment]
> The goal of the feature was to prevent OOM. If we use the max() of all clusters, it will never prevent OOM since different clusters have other non-LSA components (prepared statements, cached queriers, running ops, background writes, repair with its large buffers, group 0 holding all the tablets metadata).
> 
> We can increase it to 0.2, but not beyond.

If we make the default too conservative, field is just going to disable it on all clusters and then we also aren't preventing OOMs.
I have sent an email to rnd-int to discuss this in its wider context, let's continue the discussion there.

**Comment by mykaul** [comment]
@avikivity  - please help move this forward.

**Comment by mykaul** [comment]
@avikivity  - please look at this.

**Comment by avikivity** [comment]
0.8 makes the protection meaningless.

**Comment by denesb** [comment]
Alright, so let's make it 0.2.
The current default is 0.1 and I know of a single cluster where this caused problems. That said, I think field disabled it on every cluster they manage, after the aforementioned incident.

**Comment by mykaul** [comment]
> Alright, so let's make it 0.2. The current default is 0.1 and I know of a single cluster where this caused problems. That said, I think field disabled it on every cluster they manage, after the aforementioned incident.

@Lakshmipathi - are you making the change?

**Comment by denesb** [comment]
> > Alright, so let's make it 0.2. The current default is 0.1 and I know of a single cluster where this caused problems. That said, I think field disabled it on every cluster they manage, after the aforementioned incident.
> 
> @Lakshmipathi - are you making the change?

That is the wrong Lakshhi :). @lkshminarayanan is on PTO, yes he will make the change once he gets back.

**Comment by denesb** [comment]
I opened a PR with the updated value: https://github.com/scylladb/scylladb/pull/18964.

**Pull request closed without merging**
