### PR TITLE
locator: retry HTTP request to GCE/Azure metadata service

### LINKED ISSUE #19817: locator: missing retry logic on gce_snitch and azure_snitch
I had implemented retry logic on the metadata server access on ec2_snitch, https://github.com/scylladb/scylladb/commit/6b246dc119099629f13f1b02479eb752507ae283 and https://github.com/scylladb/scylladb/commit/0b894a7cace5ae33f0950cbd9a005404c7a03b9c (implemented simple retry logic first, and then supported exponential backoff).
Why we fixed it on ec2_snitch was, because we saw connection error on ec2_snitch https://github.com/scylladb/scylladb/issues/10250, I think we have seen same error on GCE and Azure, but it's safer to have same logic on them, too.
And scylla-machine-image already has retry logic for all cloud.

### PR DESCRIPTION
**Pull request by syuu1228**
Like we already do on EC2, implement retrying request to the metadata service on GCE and Azure.

Closes #19817

### CODE REVIEW

**Comment by syuu1228** [comment]
The implementation is basically same as ec2_snitch.cc and ec2_snitch.hh.

**Comment by yaronkaikov** [comment]
@syuu1228 let's use this branch with Byo, build GC/Azure images, and then run the artifact tests. make sure we don't break anything

**Comment by syuu1228** [comment]
@yaronkaikov 

Built with byo:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/byo/job/byo_build_tests_dtest/68/

And artifact tests for EC2/GCE/Azure images are passed:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ami-test/64/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-gce-image-test/37/
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-azure-image-test/40/

**Review by yaronkaikov — APPROVED** [review]
LGTM

**Comment by yaronkaikov** [comment]
@scylladb/scylla-maint can you please merge this?

**Comment by xemul** [comment]
https://github.com/scylladb/scylladb/issues/12306

**Comment by syuu1228** [comment]
@scylladb/scylla-maint ping

**Comment by kbr-scylla** [comment]
New code should be written using coroutines.

**Pull request closed without merging**
