### PR TITLE
compact and remove expired range tombstones from cache on read

### LINKED ISSUE #6033: Expired tombstones are kept in cache indefinitely
*Installation details*
HEAD: 0cb718276
Cluster size: 1

*Description*
Tombstones seems to be kept in the cache even after 'nodetool flush'.

How to reproduce:
1) Create a 1 node ccm cluster:
```
ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=<scylla repo>
```
2) Start it:
```
ccm start --jvm_arg="--memory" --jvm_arg="1G"  --jvm_arg="--smp" --jvm_arg="1"
```
3) From cqlsh create the table with `gc_grace_seconds=0`:
```
CREATE KEYSPACE ks2 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks2.test (
    a int PRIMARY KEY,
    b text,
    vladz1 int,
    vladz2 int
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```
4) Run the test where we create and entry, delete it with the tombstone in the future, then call `flush` and `compact` and still unable to read the re-inserted entry until we restart scylla:
```
fred@cqlsh> INSERT INTO ks2.test (a, vladz1) VALUES (1, 3);                                                                                                                                                                                                                                                                   
fred@cqlsh> INSERT INTO ks2.test (a, vladz1) VALUES (2, 4);                                                                                                                                                                                                                                                                   
fred@cqlsh> SELECT * FROM ks2.test;

 a | b    | vladz1 | vladz2
---+------+--------+--------
 1 | null |      3 |   null
 2 | null |      4 |   null

(2 rows)
fred@cqlsh> DELETE FROM ks2.test USING timestamp 9984457162684266 where a=1;                                                                                                                                                                                                                                                  
fred@cqlsh> SELECT * FROM ks2.test;                                                                                                                                                                                                                                                                                           

 a | b    | vladz1 | vladz2
---+------+--------+--------
 2 | null |      4 |   null

(1 rows)
fred@cqlsh> INSERT INTO ks2.test (a, vladz1) VALUES (1, 3);
fred@cqlsh> SELECT * FROM ks2.test;

 a | b    | vladz1 | vladz2
---+------+--------+--------
 2 | null |      4 |   null

(1 rows)
fred@cqlsh> exit
$ ../scylla-tools-java/bin/nodetool -p 7100 flush
$ ../scylla-tools-java/bin/nodetool -p 7100 compact
$ ~/.ccm/scylla-1/node1/data/ks2/test-83c06e70686a11ea8c6f000000000000/
total 40K
drwxrwxr-x 5 vladz vladz  303 Mar 17 12:16 .
drwxrwxr-x 3 vladz vladz   51 Mar 17 12:15 ..
-rw-rw-r-- 1 vladz vladz   66 Mar 17 12:16 mc-2-big-CompressionInfo.db
-rw-rw-r-- 1 vladz vladz   35 Mar 17 12:16 mc-2-big-Data.db
-rw-rw-r-- 1 vladz vladz   10 Mar 17 12:16 mc-2-big-Digest.crc32
-rw-rw-r-- 1 vladz vladz  176 Mar 17 12:16 mc-2-big-Filter.db
-rw-rw-r-- 1 vladz vladz    8 Mar 17 12:16 mc-2-big-Index.db
-rw-rw-r-- 1 vladz vladz   78 Mar 17 12:16 mc-2-big-Scylla.db
-rw-rw-r-- 1 vladz vladz 4.6K Mar 17 12:16 mc-2-big-Statistics.db
-rw-rw-r-- 1 vladz vladz   56 Mar 17 12:16 mc-2-big-Summary.db
-rw-rw-r-- 1 vladz vladz  102 Mar 17 12:16 mc-2-big-TOC.txt
drwxrwxr-x 2 vladz vladz    6 Mar 17 12:16 pending_delete
drwxrwxr-x 2 vladz vladz    6 Mar 17 12:15 staging
drwxrwxr-x 2 vladz vladz    6 Mar 17 12:15 upload
$ ~/work/scylla-tools-java/bin/cqlsh
Connected to scylla-1 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
fred@cqlsh> INSERT INTO ks2.test (a, vladz1) VALUES (1, 3);
fred@cqlsh> SELECT * FROM ks2.test;

 a | b    | vladz1 | vladz2
---+------+--------+--------
 2 | null |      4 |   null

(1 rows)
fred@cqlsh> exit

<Here we restart scylla and log into cqlsh again>

$ ~/work/scylla-tools-java/bin/cqlsh 
Connected to scylla-1 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
fred@cqlsh> SELECT * FROM ks2.test;

 a | b    | vladz1 | vladz2
---+------+--------+--------
 1 | null |      3 |   null
 2 | null |      4 |   null

(2 rows)
```

## Current status
### Tombstones covered so far:

- [x] Range tombstones: https://github.com/scylladb/scylladb/commit/87fa7d0381943ef3404a1d630baf00803b2800f5
- [ ] Partition tombstones
- [x] Row tombstones: https://github.com/scylladb/scylladb/issues/6033#issuecomment-1703398546
- [ ] Cell tombstones

### PR DESCRIPTION
**Pull request by alezzqz**
during read from cache compact and expire range tombstones remove expired empty rows from cache

Refs #2252
Fixes #6033

### CODE REVIEW

**Comment by alezzqz** [comment]
It works but there's a little issue exists:

for instance
we have four records for single partition with ck's 0, 1, 2, 3
and range tombstone ck >= 1 and ck <= 2
before tombstone expired we have the following rows in the cache:
```
row - ck{000400000000}
dummy - ck{000400000001}
row - ck{000400000001}
row - ck{000400000002}
dummy - ck{000400000002}
row - ck{000400000003}
last entry dummy
```
after the range tombstone expired we read partition from cache,
expired rows were compacted and now the cache contains:
```
row - ck{000400000000}
dummy - ck{000400000001}
dummy - ck{000400000002}
row - ck{000400000003}
last entry dummy
```
we see that dummy range tombstone rows are still in the cache.
Let's perform reading again:
```
row - ck{000400000000}
row - ck{000400000003}
last entry dummy
```
now we see that unnecessary dummy rows were compacted as we wanted.
The question is: maybe we could compact these dummy range tombstone rows on first read, together with expired rows? If such a simple way exists...

**Comment by bhalevy** [comment]
@tgrabiec @michoecho please review and provide your insight

**Comment by alezzqz** [comment]
just rebased on master

**Comment by bhalevy** [comment]
@tgrabiec / @michoecho please review

**Review by michoecho — APPROVED** [review]
Looks good to me, except that row tombstone expiration also deserves to be performed on dummy entries. So maybe that part should be hoisted out to a separate `if`, which doesn't have the `&& !_next_row.dummy()`.

> The question is: maybe we could compact these dummy range tombstone rows on first read, together with expired rows? If such a simple way exists...

I think it's fine to have temporary leftovers. I see no harm in that.

**Comment by mykaul** [comment]
@tgrabiec - please review as well.

**Comment by mykaul** [comment]
@tgrabiec - ping

**Comment by alezzqz** [comment]
just rebased on latest master

**Comment by nyh** [comment]
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3294/

One failure is a known flaky tests https://github.com/scylladb/scylladb/issues/14227
The other one I don't recognize, I suspect it's also a flaky test, I'll open and issue and restart the CI.

**Comment by nyh** [comment]
> > CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3294/
> 
> One failure is a known flaky tests #14227 The other one I don't recognize, I suspect it's also a flaky test, I'll open and issue and restart the CI.

Opened https://github.com/scylladb/scylladb/issues/15200 for the second flaky test. If I understand correctly, it's a test only recently added to "gating" so it might have been flaky all along.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider merging

**Comment by denesb** [comment]
> @scylladb/scylla-maint please consider merging

We need a review from @tgrabiec.

**Review by tgrabiec — APPROVED** [review]

**Comment by bhalevy** [comment]
@tgrabiec @raphaelsc With this mered, can we get rid of the cache invalidate after compaction?
For example, in https://github.com/scylladb/scylladb/blob/008bde54611bda98bde95ef3958332c3cc6b6709/replica/table.cc#L1347

Cc @michoecho

**Comment by tgrabiec** [comment]
This invalidation happens on a special type of compaction (cleanup). Regular compaction shouldn't invalidate cache. We still need this invalidation, because it's not done to force expired data to go away, it's done to remove all data for ranges which go away. Non-expired data may be no longer valid as well.

**Pull request closed without merging**
