### PR TITLE
docs: trigger the docs-pages workflow on release branches

### PR DESCRIPTION
**Pull request by benipeled**
Currently, the github docs-pages workflow is triggered only when changes are merged to the master/enterprise branches, which means that in the case of changes to a release branch, for example, a fix to branch-5.4, or a branch-5.4>branch-2024.1 merge, the docs-pages is not triggering and therefore the documentation is not updated with the new change,

In this change, I added the `branch-**` pattern, so changes to release branches will trigger the workflow

### CODE REVIEW

**Review by tzach — APPROVED** [review]

**Comment by tzach** [comment]
Looks good.
A future optimization can deploy *only* the branch pages when a branch changes. Not sure it's feasible or worth the effort.

**Comment by benipeled** [comment]
@dgarcia360 ^

**Comment by dgarcia360** [comment]
It won't work. When a `branch-` related branch receives a new commit, it will take the versions defined in the `conf.py` of that branch instead of the ones defined in the default branch. We have a couple of issues opened to trigger the publication of release branches:

- https://github.com/scylladb/sphinx-scylladb-theme/issues/886
- https://github.com/scylladb/sphinx-scylladb-theme/issues/124

**Comment by benipeled** [comment]
> > When a`branch-`related branch receives a new commit, it will take the versions defined in the `conf.py` of that branch instead of the ones defined in the default branch.
> 
> @benipeled To sum up, we specify which branches we want to publish in `conf.py` on `master`/`enterprise`, so the workflow must run on `master`/`enterprise`. If we ran it on a different branch, it would take `conf.py` from that branch - but that `conf.py` would not be up to date.

If we have one `conf.py` for all versions - the one in the default branch - we can adjust the checkout to use the default branch, something like (we need to add another environment variable similar to the FLAG):
```
- name: Checkout
  uses: actions/checkout@v3
  with:
    ref: ${{ env.DEFAULT_BRANCH }}
    persist-credentials: false
    fetch-depth: 0
```
This way the pages will always be built from the default branch even when they'll trigger from another branch

**Comment by dgarcia360** [comment]
> - name: Checkout
  uses: actions/checkout@v3
  with:
    ref: ${{ env.DEFAULT_BRANCH }}
    persist-credentials: false
    fetch-depth: 0

@benipeled looks good. I'm testing the proposed solution in https://github.com/scylladb/sphinx-scylladb-theme/pull/1023

If it works, could you please update this PR?

**Comment by benipeled** [comment]
> > * name: Checkout
> >   uses: actions/checkout@v3
> >   with:
> >   ref: ${{ env.DEFAULT_BRANCH }}
> >   persist-credentials: false
> >   fetch-depth: 0
> 
> @benipeled looks good. I'm testing the proposed solution in [scylladb/sphinx-scylladb-theme#1023](https://github.com/scylladb/sphinx-scylladb-theme/pull/1023)
> 
> If it works, could you please update this PR?

Done

PS> I like the `${{ github.event.repository.default_branch }}` you use on the other PR. In this case, I want to explicitly specify the required branch and not rely on an external variable that might change.

**Comment by dgarcia360** [comment]
@benipeled LGTM, we can merge.

We tested the solution in 
[sphinx-scylladb-theme](https://github.com/scylladb/sphinx-scylladb-theme) and triggered a build from a branch: https://github.com/scylladb/sphinx-scylladb-theme/actions/runs/8154359635

**Comment by benipeled** [comment]
@scylladb/scylla-maint please merge

**Comment by denesb** [comment]
@benipeled in the future, please use `master` as the target branch, not `next`.

**Comment by benipeled** [comment]
> @benipeled in the future, please use `master` as the target branch, not `next`.

Why? is it effect somehow the merge script?
I always change the target to next to avoid a case when someone will use the merge button on the PR page and merge it directly to the master

**Pull request merged**
